const cienciaData = [
    { q: "H2O É A FÓRMULA DE QUÊ?", options: ["AR", "SAL", "ÁGUA", "FOGO"], correct: 2 },
    { q: "QUAL O SÍMBOLO DO OURO?", options: ["AG", "AU", "FE", "OR"], correct: 1 },
    { q: "GÁS QUE RESPIRAMOS?", options: ["OXIGÊNIO", "HIDROGÊNIO", "HÉLIO", "CO2"], correct: 0 },
    { q: "QUAL O METAL LÍQUIDO?", options: ["FERRO", "MERCÚRIO", "PRATA", "COBRE"], correct: 1 },
    { q: "O QUE É O NACL?", options: ["AÇÚCAR", "SAL DE COZINHA", "VINAGRE", "ÁGUA"], correct: 1 },
    { q: "ESTADO DA ÁGUA NO GELO?", options: ["LÍQUIDO", "SÓLIDO", "GASOSO", "VAPOR"], correct: 1 },
    { q: "GÁS USADO EM BALÕES QUE SOBEM?", options: ["OXIGÊNIO", "HÉLIO", "NITROGÊNIO", "CO2"], correct: 1 },
    { q: "QUAL O PH DA ÁGUA PURA?", options: ["0", "5", "7", "14"], correct: 2 },
    { q: "SUBSTÂNCIA QUE CONDUZ ELETRICIDADE?", options: ["MADEIRA", "COBRE", "PLÁSTICO", "BORRACHA"], correct: 1 },
    { q: "O QUE É O CO2?", options: ["OXIGÊNIO", "DIÓXIDO DE CARBONO", "OZÔNIO", "AR"], correct: 1 },
    { q: "QUAL ELEMENTO TEM O SÍMBOLO 'FE'?", options: ["FÓSFORO", "FERRO", "FLÚOR", "FÉRNIO"], correct: 1 },
    { q: "PARTE MAIS PEQUENA DA MATÉRIA?", options: ["CÉLULA", "ÁTOMO", "MOLÉCULA", "GRÃO"], correct: 1 },
    { q: "O QUE É UMA MISTURA DE ÁGUA E ÓLEO?", options: ["HOMOGÊNEA", "HETEROGÊNEA", "SOLUÇÃO", "LIGA"], correct: 1 },
    { q: "QUAL METAL É ATRAÍDO POR ÍMÃS?", options: ["ALUMÍNIO", "OURO", "FERRO", "COBRE"], correct: 2 },
    { q: "O QUE O FOGO PRECISA PARA QUEIMAR?", options: ["ÁGUA", "OXIGÊNIO", "TERRA", "ARGÔNIO"], correct: 1 },
    { q: "QUAL O SÍMBOLO DA PRATA?", options: ["PR", "PT", "AG", "SI"], correct: 2 },
    { q: "O QUE É O DIAMANTE?", options: ["FERRO", "CARBONO PURO", "VIDRO", "ROCHA"], correct: 1 },
    { q: "QUAL GÁS É USADO EM REFRIGERANTES?", options: ["OXIGÊNIO", "CO2", "HÉLIO", "METANO"], correct: 1 },
    { q: "O QUE É O VINAGRE?", options: ["ÁCIDO ACÉTICO", "BASE", "SAL", "ÁLCOOL"], correct: 0 },
    { q: "QUAL O SÍMBOLO DO OXIGÊNIO?", options: ["OX", "O", "O2", "OG"], correct: 1 },
    { q: "QUAL O MAIOR ÓRGÃO?", options: ["CÉREBRO", "PELE", "FÍGADO", "CORAÇÃO"], correct: 1 },
    { q: "ÓRGÃO QUE FILTRA O SANGUE?", options: ["ESTÔMAGO", "RINS", "PULMÃO", "BAÇO"], correct: 1 },
    { q: "QUANTOS OSSOS TEM UM ADULTO?", options: ["150", "206", "300", "250"], correct: 1 },
    { q: "ONDE FICA O FÊMUR?", options: ["BRAÇO", "PERNA", "COSTELA", "CABEÇA"], correct: 1 },
    { q: "QUAL A COR DOS GLÓBULOS VERMELHOS?", options: ["AZUL", "VERDE", "VERMELHO", "BRANCO"], correct: 2 },
    { q: "O QUE O CORAÇÃO BOMBEIA?", options: ["ÁGUA", "SANGUE", "AR", "LINFA"], correct: 1 },
    { q: "QUANTOS SENTIDOS TEMOS?", options: ["4", "5", "6", "7"], correct: 1 },
    { q: "QUAL ÓRGÃO É USADO PARA OUVIR?", options: ["NARIZ", "ORELHA", "OLHO", "BOCA"], correct: 1 },
    { q: "ONDE SE PRODUZ A SALIVA?", options: ["BOCA", "ESTÔMAGO", "FÍGADO", "NARIZ"], correct: 0 },
    { q: "RESPONSÁVEL PELA CONEXÃO DOS OSSOS?", options: ["NERVO", "ARTICULAÇÃO", "MÚSCULO", "PELE"], correct: 1 },
    { q: "QUANTOS DENTES TEM UM ADULTO?", options: ["28", "32", "30", "36"], correct: 1 },
    { q: "O QUE OS PULMÕES FAZEM?", options: ["DIGEREM", "RESPIRAM", "PENSAM", "CORREM"], correct: 1 },
    { q: "QUAL O MOTOR DO CORPO?", options: ["CÉREBRO", "CORAÇÃO", "ESTÔMAGO", "RINS"], correct: 1 },
    { q: "ONDE FICA O CRÂNIO?", options: ["MÃO", "CABEÇA", "PÉ", "TRONCO"], correct: 1 },
    { q: "QUAL A FUNÇÃO DAS PÁLPEBRAS?", options: ["VER", "PROTEGE O OLHO", "OUVIR", "CHEIRAR"], correct: 1 },
    { q: "O QUE É O CÉREBRO?", options: ["MÚSCULO", "ÓRGÃO DO PENSAMENTO", "OSSO", "GLÂNDULA"], correct: 1 },
    { q: "PARA QUE SERVE O ESTÔMAGO?", options: ["RESPIRAR", "DIGERIR COMIDA", "ANDAR", "FALAR"], correct: 1 },
    { q: "QUANTOS DEDOS TEMOS NAS MÃOS?", options: ["8", "10", "12", "5"], correct: 1 },
    { q: "O QUE É A ÍRIS?", options: ["PARTE DO OUVIDO", "PARTE DO OLHO", "OSSO", "PELE"], correct: 1 },
    { q: "QUAL A FUNÇÃO DOS NERVOS?", options: ["DAR COR", "LEVAR SINAIS", "BOMBEAR", "FILTRAR"], correct: 1 },
    { q: "O QUE ATRAI O FERRO?", options: ["ÁGUA", "ÍMÃ", "MADEIRA", "LUZ"], correct: 1 },
    { q: "O QUE CAUSA O TROVÃO?", options: ["VENTO", "RAIO", "CHUVA", "NUVEM"], correct: 1 },
    { q: "QUAL A VELOCIDADE MAIS RÁPIDA?", options: ["SOM", "LUZ", "VENTO", "CARRO"], correct: 1 },
    { q: "O QUE É A GRAVIDADE?", options: ["FORÇA QUE NOS PUXA", "VENTO", "CALOR", "LUZ"], correct: 0 },
    { q: "QUEM CAI MAIS RÁPIDO NO VÁCUO?", options: ["PENA", "PEDRA", "AMBOS IGUAIS", "CHUMBO"], correct: 2 },
    { q: "O QUE É A ENERGIA SOLAR?", options: ["VEM DO VENTO", "VEM DO SOL", "VEM DA ÁGUA", "VEM DA TERRA"], correct: 1 },
    { q: "QUAL A UNIDADE DE TEMPERATURA?", options: ["METRO", "CELSIUS", "LITRO", "QUILO"], correct: 1 },
    { q: "O QUE É O ECO?", options: ["LUZ VOLTANDO", "SOM VOLTANDO", "VENTO", "CHUVA"], correct: 1 },
    { q: "PARA QUE SERVE A LUPA?", options: ["DIMINUIR", "AUMENTAR", "COLORIR", "APAGAR"], correct: 1 },
    { q: "O QUE É O VÁCUO?", options: ["AR GELADO", "ESPAÇO SEM MATÉRIA", "NUVEM", "FOGO"], correct: 1 },
    { q: "QUAL COR ABSORVE MAIS CALOR?", options: ["BRANCO", "PRETO", "AZUL", "AMARELO"], correct: 1 },
    { q: "O QUE É O VENTO?", options: ["AR PARADO", "AR EM MOVIMENTO", "ÁGUA", "LUZ"], correct: 1 },
    { q: "O QUE FAZ A LUZ REFLETIR?", options: ["ESPELHO", "PAPEL", "TERRA", "MADEIRA"], correct: 0 },
    { q: "QUAL A FONTE DA ENERGIA EÓLICA?", options: ["SOL", "VENTO", "ÁGUA", "URÂNIO"], correct: 1 },
    { q: "O QUE É A LUZ BRANCA?", options: ["SÓ BRANCO", "SOMA DE TODAS AS CORES", "SÓ AZUL", "AUSÊNCIA DE COR"], correct: 1 },
    { q: "PARA QUE SERVE O TERMÔMETRO?", options: ["MEDIR PESO", "MEDIR TEMPERATURA", "MEDIR ALTURA", "MEDIR TEMPO"], correct: 1 },
    { q: "O QUE ACONTECE SE A ÁGUA FERVE?", options: ["CONGELA", "VIRA VAPOR", "VIRA SAL", "SUMA"], correct: 1 },
    { q: "QUAL A UNIDADE DE MASSA?", options: ["METRO", "QUILOGRAMA", "LITRO", "GRAU"], correct: 1 },
    { q: "O QUE É A ELETRICIDADE?", options: ["FLUXO DE ELÉTRONS", "VENTO", "ÁGUA", "LUZ"], correct: 0 },
    { q: "O QUE É UM CONDUTOR?", options: ["BLOQUEIA ENERGIA", "PASSA ENERGIA", "É DE MADEIRA", "NÃO EXISTE"], correct: 1 },
    { q: "QUAL O CENTRO DO SISTEMA SOLAR?", options: ["TERRA", "SOL", "LUA", "JÚPITER"], correct: 1 },
    { q: "A LUA É O QUÊ DA TERRA?", options: ["PLANETA", "ESTRELA", "SATÉLITE NATURAL", "COMETA"], correct: 2 },
    { q: "QUAL PLANETA TEM ANÉIS FAMOSOS?", options: ["MARTE", "SATURNO", "VÊNUS", "MERCÚRIO"], correct: 1 },
    { q: "QUAL O PLANETA MAIS PRÓXIMO DO SOL?", options: ["TERRA", "MARTE", "MERCÚRIO", "JÚPITER"], correct: 2 },
    { q: "QUANTOS PLANETAS TEM O SISTEMA SOLAR?", options: ["7", "8", "9", "10"], correct: 1 },
    { q: "O QUE É O SOL?", options: ["PLANETA", "ESTRELA", "LUA", "GALÁXIA"], correct: 1 },
    { q: "QUAL O PLANETA CONHECIDO COMO AZUL?", options: ["MARTE", "TERRA", "SATURNO", "NEPTUNO"], correct: 1 },
    { q: "O QUE CAUSA O DIA E A NOITE?", options: ["ROTAÇÃO DA TERRA", "TRANSLAÇÃO", "VENTO", "LUA"], correct: 0 },
    { q: "QUAL PLANETA É O MAIOR?", options: ["TERRA", "JÚPITER", "SATURNO", "MARTE"], correct: 1 },
    { q: "O QUE É UMA GALÁXIA?", options: ["UMA ESTRELA", "CONJUNTO DE ESTRELAS", "UM PLANETA", "UMA NUVEM"], correct: 1 },
    { q: "QUAL O NOME DA NOSSA GALÁXIA?", options: ["ANDRÔMEDA", "VIA LÁCTEA", "SOLAR", "ÓRBITA"], correct: 1 },
    { q: "A LUA TEM LUZ PRÓPRIA?", options: ["SIM", "NÃO", "ÀS VEZES", "SÓ NO VERÃO"], correct: 1 },
    { q: "O QUE É UM ECLIPSE?", options: ["ALINHAMENTO DE ASTROS", "EXPLOSÃO", "VENTO FORTE", "FOGO"], correct: 0 },
    { q: "QUAL PLANETA É CHAMADO DE VERMELHO?", options: ["VÊNUS", "MARTE", "JÚPITER", "MERCÚRIO"], correct: 1 },
    { q: "O QUE É UM TELESCÓPIO?", options: ["MEDE PESO", "PARA VER LONGE", "PARA OUVIR", "MEDE CALOR"], correct: 1 },
    { q: "O QUE É O VÁCUO ESPACIAL?", options: ["AR GELADO", "AUSÊNCIA DE MATÉRIA", "FOGO", "NUVEM DE GÁS"], correct: 1 },
    { q: "QUANTO TEMPO A TERRA LEVA PARA DAR A VOLTA NO SOL?", options: ["24 HORAS", "365 DIAS", "30 DIAS", "12 HORAS"], correct: 1 },
    { q: "O QUE É UM ASTEROIDE?", options: ["PEQUENO PLANETA", "ROCHA ESPACIAL", "ESTRELA", "GÁS"], correct: 1 },
    { q: "QUAL O ÚLTIMO PLANETA DO SISTEMA?", options: ["PLUTÃO", "NEPTUNO", "URANO", "SATURNO"], correct: 1 },
    { q: "O QUE É UMA CONSTELAÇÃO?", options: ["DESENHO DE ESTRELAS", "PLANETA", "LUA NOVA", "SOL"], correct: 0 },
    { q: "O QUE ACONTECE NO PONTO DE EBULIÇÃO?", options: ["CONGELA", "VIRA VAPOR", "DERRETE", "SOME"], correct: 1 },
    { q: "O QUE É A CONDENSAÇÃO?", options: ["VAPOR VIRA LÍQUIDO", "LÍQUIDO VIRA GELO", "FOGO", "VENTO"], correct: 0 },
    { q: "QUAL O ESTADO DA LAVA VULCÂNICA?", options: ["SÓLIDO", "LÍQUIDO/PASTOSO", "GASOSO", "VAPOR"], correct: 1 },
    { q: "O QUE É UM ÁTOMO?", options: ["CÉLULA", "UNIDADE DA MATÉRIA", "ÓRGÃO", "PLANETA"], correct: 1 },
    { q: "O QUE É A FUSÃO?", options: ["CONGELAR", "DERRETER", "QUEIMAR", "SUBIR"], correct: 1 },
    { q: "QUAL O GÁS QUE AS PLANTAS LIBERAM?", options: ["CO2", "OXIGÊNIO", "HIDROGÊNIO", "NITROGÊNIO"], correct: 1 },
    { q: "O QUE É A MATÉRIA?", options: ["SÓ O QUE VEMOS", "TUDO QUE TEM MASSA E LUGAR", "SÓ PEDRAS", "SÓ ÁGUA"], correct: 1 },
    { q: "QUAL A PARTE DA CÉLULA QUE TEM O DNA?", options: ["PAREDE", "NÚCLEO", "MEMBRANA", "CITOPLASMA"], correct: 1 },
    { q: "O QUE É UM MICROSCÓPIO?", options: ["PARA VER O CÉU", "PARA VER COISAS MINÚSCULAS", "PARA OUVIR", "PARA MEDIR"], correct: 1 },
    { q: "QUAL A UNIDADE DE MEDIDA DA CORRENTE ELÉTRICA?", options: ["VOLT", "AMPERE", "WATT", "OHM"], correct: 1 },
    { q: "O QUE É A FOTOSSÍNTESE?", options: ["RESPIRAÇÃO ANIMAL", "ENERGIA DAS PLANTAS", "CHUVA", "VENTO"], correct: 1 },
    { q: "QUAL A MENOR UNIDADE DOS SERES VIVOS?", options: ["ÁTOMO", "CÉLULA", "ÓRGÃO", "TECIDO"], correct: 1 },
    { q: "O QUE OS GLÓBULOS BRANCOS FAZEM?", options: ["TRANSPORTAM AR", "DEFENDEM O CORPO", "DÃO COR", "DIGEREM"], correct: 1 },
    { q: "QUANTOS CROMOSSOMOS TEM O HUMANO?", options: ["23", "46", "50", "12"], correct: 1 },
    { q: "QUAL O NOME DO PIGMENTO DA PELE?", options: ["CLOROFILA", "MELANINA", "SANGUE", "QUERATINA"], correct: 1 },
    { q: "O QUE É UM SER UNICELULAR?", options: ["TEM UMA CÉLULA", "TEM MUITAS", "NÃO TEM", "É UMA PLANTA"], correct: 0 },
    { q: "QUAL ÓRGÃO PRODUZ A INSULINA?", options: ["FÍGADO", "PÂNCREAS", "RINS", "ESTÔMAGO"], correct: 1 },
    { q: "QUEM FORMULOU A TEORIA DA EVOLUÇÃO?", options: ["NEWTON", "DARWIN", "EINSTEIN", "TESLA"], correct: 1 },
    { q: "QUAL A FUNÇÃO DAS PLAQUETAS?", options: ["RESPIRAR", "COAGULAR O SANGUE", "CORRER", "PENSAR"], correct: 1 },
    { q: "O QUE É O METABOLISMO?", options: ["SONO", "REÇÕES QUÍMICAS DO CORPO", "FOME", "SEDE"], correct: 1 },
    { q: "ONDE OCORRE A DIGESTÃO?", options: ["PULMÃO", "TUBO DIGESTIVO", "CÉREBRO", "CORAÇÃO"], correct: 1 },
    { q: "QUAL O NOME DA DIVISÃO CELULAR?", options: ["MITOSE", "CORTE", "UNIÃO", "FUSÃO"], correct: 0 },
    { q: "O QUE É A ADRENALINA?", options: ["COMIDA", "HORMÔNIO", "OSSO", "GÁS"], correct: 1 },
    { q: "O QUE É UM VÍRUS?", options: ["PLANTA", "AGENTE INFECCIOSO", "ANIMAL", "PEDRA"], correct: 1 },
    { q: "PARA QUE SERVE A AUDIÇÃO?", options: ["VER", "OUVIR", "SENTIR", "CHEIRAR"], correct: 1 },
    { q: "O QUE É A GENÉTICA?", options: ["ESTUDO DOS OSSOS", "ESTUDO DA HEREDITARIEDADE", "ESTUDO DO MAR", "ESTUDO DO AR"], correct: 1 },
    { q: "QUAL O NOME DA PROTEÍNA DO CABELO?", options: ["MELANINA", "QUERATINA", "INSULINA", "BILE"], correct: 1 },
    { q: "O QUE É A BIOLOGIA?", options: ["ESTUDO DA TERRA", "ESTUDO DA VIDA", "ESTUDO DOS NÚMEROS", "ESTUDO DAS MÁQUINAS"], correct: 1 },
    { q: "QUAL O ELEMENTO MAIS LEVE?", options: ["OXIGÊNIO", "HIDROGÊNIO", "HÉLIO", "FERRO"], correct: 1 },
    { q: "O QUE É O OZÔNIO?", options: ["O2", "O3", "CO2", "H2O"], correct: 1 },
    { q: "QUAL O SÍMBOLO DO CARBONO?", options: ["CA", "C", "CB", "CR"], correct: 1 },
    { q: "O QUE É UM ÁCIDO?", options: ["PH MENOR QUE 7", "PH 7", "PH MAIOR QUE 7", "PH 14"], correct: 0 },
    { q: "QUAL O SÍMBOLO DO SÓDIO?", options: ["S", "SO", "NA", "SD"], correct: 2 },
    { q: "O QUE É UMA LIGA METÁLICA?", options: ["METAL PURO", "MISTURA DE METAIS", "PEDRA", "GÁS"], correct: 1 },
    { q: "QUAL O SÍMBOLO DO NITROGÊNIO?", options: ["NI", "N", "NT", "NG"], correct: 1 },
    { q: "O QUE É A OXIDAÇÃO?", options: ["GANHAR ÁGUA", "REAGIR COM OXIGÊNIO", "CONGELAR", "DERRETER"], correct: 1 },
    { q: "QUAL O SÍMBOLO DO POTÁSSIO?", options: ["P", "PO", "K", "PT"], correct: 2 },
    { q: "O QUE É O COBRE?", options: ["UM GÁS", "UM METAL", "UM LÍQUIDO", "UM SAL"], correct: 1 },
    { q: "QUAL O SÍMBOLO DO CÁLCIO?", options: ["C", "CA", "CL", "CU"], correct: 1 },
    { q: "O QUE É A DESTILAÇÃO?", options: ["CONGELAR", "SEPARAR LÍQUIDOS", "QUEIMAR", "MISTURAR"], correct: 1 },
    { q: "QUAL O SÍMBOLO DO CLORO?", options: ["C", "CH", "CL", "CO"], correct: 2 },
    { q: "O QUE É O HÉLIO?", options: ["UM METAL", "UM GÁS NOBRE", "UM LÍQUIDO", "UM SÓLIDO"], correct: 1 },
    { q: "QUAL O SÍMBOLO DO MAGNÉSIO?", options: ["M", "MA", "MG", "MS"], correct: 2 },
    { q: "O QUE É O CHUMBO?", options: ["METAL PESADO", "GÁS LEVE", "ÁGUA", "SAL"], correct: 0 },
    { q: "QUAL O SÍMBOLO DO FÓSFORO?", options: ["F", "FO", "P", "PH"], correct: 2 },
    { q: "O QUE É A QUÍMICA?", options: ["ESTUDO DOS ASTROS", "ESTUDO DA MATÉRIA", "ESTUDO DOS ANIMAIS", "ESTUDO DO PASSADO"], correct: 1 },
    { q: "QUAL O SÍMBOLO DO ENXOFRE?", options: ["E", "EN", "S", "EX"], correct: 2 },
    { q: "O QUE É O NEÔNIO?", options: ["UM METAL", "UM GÁS", "UM LÍQUIDO", "UM SAL"], correct: 1 },
    { q: "QUEM DESCOBRIU A GRAVIDADE?", options: ["DARWIN", "NEWTON", "EINSTEIN", "PASTEUR"], correct: 1 },
    { q: "O QUE É A VELOCIDADE?", options: ["PESO", "ESPAÇO PELO TEMPO", "CALOR", "LUZ"], correct: 1 },
    { q: "QUAL A UNIDADE DE FORÇA?", options: ["METRO", "NEWTON", "LITRO", "GRAU"], correct: 1 },
    { q: "O QUE É A INÉRCIA?", options: ["MOVIMENTO", "RESISTÊNCIA AO MOVIMENTO", "CALOR", "SOM"], correct: 1 },
    { q: "PARA QUE SERVE A BÚSSOLA?", options: ["VER O TEMPO", "ORIENTAÇÃO", "MEDIR PESO", "CALCULAR"], correct: 1 },
    { q: "O QUE É A ENERGIA CINÉTICA?", options: ["ENERGIA DO CALOR", "ENERGIA DO MOVIMENTO", "ENERGIA DA LUZ", "ENERGIA DO SOM"], correct: 1 },
    { q: "QUAL A UNIDADE DE FREQUÊNCIA?", options: ["WATT", "HERTZ", "VOLT", "METRO"], correct: 1 },
    { q: "O QUE É O CALOR?", options: ["TEMPERATURA", "TRANSFERÊNCIA DE ENERGIA", "VENTO", "LUZ"], correct: 1 },
    { q: "QUAL O NOME DA MUDANÇA DE DIREÇÃO DA LUZ?", options: ["REFLEXÃO", "REFRAÇÃO", "DIFRAÇÃO", "ABSORÇÃO"], correct: 1 },
    { q: "O QUE É O SOM?", options: ["LUZ", "ONDA MECÂNICA", "VAPOR", "VÁCUO"], correct: 1 },
    { q: "QUAL A UNIDADE DE POTÊNCIA?", options: ["JOULE", "WATT", "VOLT", "AMPÉRE"], correct: 1 },
    { q: "O QUE É A PRESSÃO?", options: ["FORÇA POR ÁREA", "PESO", "CALOR", "VENTO"], correct: 0 },
    { q: "QUAL O NOME DA CIÊNCIA DAS MÁQUINAS?", options: ["BIOLOGIA", "MECÂNICA", "QUÍMICA", "GEOLOGIA"], correct: 1 },
    { q: "PARA QUE SERVE O BARÔMETRO?", options: ["MEDIR UMIDADE", "MEDIR PRESSÃO DO AR", "MEDIR ALTURA", "MEDIR VELOCIDADE"], correct: 1 },
    { q: "O QUE O DINAMÔMETRO MEDE?", options: ["MASSA", "FORÇA", "TEMPERATURA", "VOLUME"], correct: 1 },
    { q: "INSTRUMENTO PARA VER ESTRELAS?", options: ["MICROSCÓPIO", "TELESCÓPIO", "PERISCÓPIO", "LUPA"], correct: 1 },
    { q: "O QUE O ANEMÔMETRO MEDE?", options: ["CHUVA", "VELOCIDADE DO VENTO", "LUZ", "CALOR"], correct: 1 },
    { q: "PARA QUE SERVE O HIDRÔMETRO?", options: ["MEDIR ÁGUA", "MEDIR AR", "MEDIR LUZ", "MEDIR SOM"], correct: 0 },
    { q: "O QUE O ESTETOSCÓPIO OUVE?", options: ["SONS DO CORPO", "SONS DO ESPAÇO", "VENTO", "MAR"], correct: 0 },
    { q: "INSTRUMENTO PARA VER SUBMARINOS?", options: ["TELESCÓPIO", "PERISCÓPIO", "MICROSCÓPIO", "BÚSSOLA"], correct: 1 },
    { q: "O QUE O HIGRÔMETRO MEDE?", options: ["PRESSÃO", "UMIDADE DO AR", "CALOR", "SOM"], correct: 1 },
    { q: "PARA QUE SERVE O RADAR?", options: ["VER BACTÉRIAS", "LOCALIZAR OBJETOS", "MEDIR FEBRE", "VER O DNA"], correct: 1 },
    { q: "O QUE O SISMÓGRAFO DETECTA?", options: ["VENTO", "TERREMOTOS", "CHUVA", "LUZ"], correct: 1 },
    { q: "QUAL A UNIDADE DE VOLUME LÍQUIDO?", options: ["METRO", "LITRO", "QUILO", "GRAU"], correct: 1 },
    { q: "O QUE O ODÔMETRO MEDE?", options: ["TEMPO", "DISTÂNCIA PERCORRIDA", "VELOCIDADE", "PESO"], correct: 1 },
    { q: "PARA QUE SERVE O CRONÔMETRO?", options: ["MEDIR PRESSÃO", "MEDIR TEMPO EXATO", "MEDIR CALOR", "MEDIR ALTURA"], correct: 1 },
    { q: "O QUE O VOLTÍMETRO MEDE?", options: ["CORRENTE", "TENSÃO ELÉTRICA", "RESISTÊNCIA", "SOM"], correct: 1 },
    { q: "O QUE É UMA BALANÇA?", options: ["MEDE COMPRIMENTO", "MEDE MASSA/PESO", "MEDE TEMPO", "MEDE LUZ"], correct: 1 },
    { q: "PARA QUE SERVE O SONAR?", options: ["VER NO ESCURO", "LOCALIZAR SOB A ÁGUA", "MEDIR VENTO", "VER O SOL"], correct: 1 },
    { q: "O QUE O TRANSFERIDOR MEDE?", options: ["PESO", "ÂNGULOS", "CALOR", "DISTÂNCIA"], correct: 1 },
    { q: "INSTRUMENTO PARA MEDIR FEBRE?", options: ["BARÔMETRO", "TERMÔMETRO", "RADAR", "BÚSSOLA"], correct: 1 },
    { q: "O QUE O ESCALÍMETRO MEDE?", options: ["PESO", "ESCALAS EM DESENHO", "TEMPO", "SOM"], correct: 1 },
    { q: "PARA QUE SERVE O ALTÍMETRO?", options: ["MEDIR PROFUNDIDADE", "MEDIR ALTITUDE", "MEDIR PESO", "MEDIR LUZ"], correct: 1 },
    { q: "ONDE FICA O MATERIAL GENÉTICO?", options: ["MEMBRANA", "NÚCLEO", "PAREDE", "CITOPLASMA"], correct: 1 },
    { q: "O QUE É A MITOCÔNDRIA?", options: ["FAZ A DIGESTÃO", "RESPIRAÇÃO CELULAR", "PROTEGE", "NADA"], correct: 1 },
    { q: "QUAL A USINA DE ENERGIA DA CÉLULA?", options: ["NÚCLEO", "MITOCÔNDRIA", "RIBOSSOMO", "LISOSSOMO"], correct: 1 },
    { q: "O QUE OS RIBOSSOMOS FAZEM?", options: ["PRODUZEM GORDURA", "PRODUZEM PROTEÍNAS", "PRODUZEM ÁGUA", "PRODUZEM AR"], correct: 1 },
    { q: "O QUE É O CITOPLASMA?", options: ["CASCA DA CÉLULA", "GEL QUE PREENCHE A CÉLULA", "O CENTRO", "O DNA"], correct: 1 },
    { q: "QUAL A FUNÇÃO DA MEMBRANA?", options: ["PENSAR", "CONTROLAR O QUE ENTRA/SAI", "PRODUZIR LUZ", "RESPIRAR"], correct: 1 },
    { q: "O QUE É UMA CÉLULA EUCARIONTE?", options: ["NÃO TEM NÚCLEO", "TEM NÚCLEO DEFINIDO", "É UMA BACTÉRIA", "É UM VÍRUS"], correct: 1 },
    { q: "O QUE É UMA CÉLULA PROCARIONTE?", options: ["TEM NÚCLEO", "NÃO TEM NÚCLEO DEFINIDO", "É UMA PLANTA", "É UM ANIMAL"], correct: 1 },
    { q: "QUAL CÉLULA TEM CLOROPLASTOS?", options: ["ANIMAL", "VEGETAL", "HUMANA", "BACTERIANA"], correct: 1 },
    { q: "O QUE É A PAREDE CELULAR?", options: ["CAPA MOLE", "PROTEÇÃO RÍGIDA (PLANTAS)", "GORDURA", "ÁGUA"], correct: 1 },
    { q: "O QUE SÃO ORGANELAS?", options: ["PEQUENOS ÓRGÃOS DA CÉLULA", "OSSOS", "ESTRELAS", "PLANETAS"], correct: 0 },
    { q: "O QUE É A DIVISÃO CELULAR?", options: ["MORTE", "REPRODUÇÃO DA CÉLULA", "FOME", "SEDE"], correct: 1 },
    { q: "QUAL O NOME DA DUPLICAÇÃO DO DNA?", options: ["TRADUÇÃO", "REPLICAÇÃO", "TRANSCRIÇÃO", "FUSÃO"], correct: 1 },
    { q: "O QUE É UM GENE?", options: ["UM ÓRGÃO", "SEGMENTO DE DNA", "UMA CÉLULA", "UM OSSO"], correct: 1 },
    { q: "QUAL A FORMA DO DNA?", options: ["CÍRCULO", "DUPLA HÉLICE", "QUADRADO", "LINHA RETA"], correct: 1 },
    { q: "QUANTOS PARES DE CROMOSSOMOS TEMOS?", options: ["12", "23", "46", "10"], correct: 1 },
    { q: "O QUE DETERMINA O SEXO BIOLÓGICO?", options: ["CROMOSSOMOS X/Y", "SANGUE", "IDADE", "ALTURA"], correct: 0 },
    { q: "O QUE É UMA MUTAÇÃO?", options: ["CRESCIMENTO", "ALTERAÇÃO NO DNA", "MORTE", "REPRODUÇÃO"], correct: 1 },
    { q: "QUAL O NOME DA UNIDADE DO DNA?", options: ["PROTEÍNA", "NUCLEOTÍDEO", "ÁTOMO", "CÉLULA"], correct: 1 },
    { q: "O QUE É A BIOTECNOLOGIA?", options: ["ESTUDO DOS OSSOS", "USO DE SERES VIVOS NA TECH", "ESTUDO DOS ASTROS", "QUÍMICA"], correct: 1 },
    { q: "O QUE É UMA VACINA?", options: ["REMÉDIO CURATIVO", "PREVENÇÃO DE DOENÇAS", "VENENO", "VITAMINA"], correct: 1 },
    { q: "O QUE O ANTIBIÓTICO COMBATE?", options: ["VÍRUS", "BACTÉRIAS", "FUNGOS", "VERMES"], correct: 1 },
    { q: "QUAL A FUNÇÃO DA VITAMINA C?", options: ["DAR FOME", "FORTALECER IMUNIDADE", "DAR SONO", "NADA"], correct: 1 },
    { q: "O QUE CAUSA A CÁRIE?", options: ["ÁGUA", "BACTÉRIAS E AÇÚCAR", "SAL", "FRUTAS"], correct: 1 },
    { q: "QUAL O SANGUE DOADOR UNIVERSAL?", options: ["A+", "O-", "AB+", "B-"], correct: 1 },
    { q: "O QUE É A ANEMIA?", options: ["FALTA DE ÁGUA", "FALTA DE FERRO NO SANGUE", "FALTA DE SONO", "FALTA DE AR"], correct: 1 },
    { q: "O QUE É A HIPERTENSÃO?", options: ["PRESSÃO BAIXA", "PRESSÃO ALTA", "FALTA DE SANGUE", "FEBRE"], correct: 1 },
    { q: "QUAL O NOME DO AÇÚCAR NO SANGUE?", options: ["SAL", "GLICOSE", "PROTEÍNA", "GORDURA"], correct: 1 },
    { q: "PARA QUE SERVE O CÁLCIO?", options: ["BOM PARA OS OSSOS", "BOM PARA O CABELO", "BOM PARA A PELE", "BOM PARA O OLHO"], correct: 0 },
    { q: "O QUE É O COLESTEROL?", options: ["TIPO DE GORDURA", "TIPO DE AÇÚCAR", "PROTEÍNA", "VITAMINA"], correct: 0 },
    { q: "O QUE CAUSA A DIABETES?", options: ["FALTA DE FERRO", "PROBLEMA COM INSULINA", "FALTA DE ÁGUA", "SAL"], correct: 1 },
    { q: "QUAL ÓRGÃO É AFETADO PELA HEPATITE?", options: ["CORAÇÃO", "FÍGADO", "RINS", "PULMÃO"], correct: 1 },
    { q: "O QUE É A INSOLAÇÃO?", options: ["FRIO EXCESSO", "CALOR EXCESSO/SOL", "FALTA DE AR", "CHUVA"], correct: 1 },
    { q: "QUAL A FUNÇÃO DO SUOR?", options: ["ESQUENTAR", "RESFRIAR O CORPO", "DAR CHEIRO", "LIMPAR O SANGUE"], correct: 1 },
    { q: "O QUE É O SISTEMA IMUNITÁRIO?", options: ["RESPIRAÇÃO", "DEFESA DO CORPO", "DIGESTÃO", "MOVIMENTO"], correct: 1 },
    { q: "PARA QUE SERVE A FIBRA ALIMENTAR?", options: ["DAR ENERGIA", "AJUDAR O INTESTINO", "FORTALECER OSSOS", "VER MELHOR"], correct: 1 },
    { q: "O QUE É UM HORMÔNIO?", options: ["MENSAGEIRO QUÍMICO", "OSSO", "CÉLULA", "GÁS"], correct: 0 },
    { q: "QUAL A TEMPERATURA MÉDIA DO CORPO?", options: ["30°C", "36-37°C", "40°C", "25°C"], correct: 1 },
    { q: "O QUE É A OBESIDADE?", options: ["FALTA DE PESO", "EXCESSO DE GORDURA", "ALTURA EXCESSO", "FALTA DE ÁGUA"], correct: 1 },
    { q: "PARA QUE SERVE O SONO?", options: ["CANSAÇO", "RECUPERAÇÃO DO CORPO", "FOME", "SEDE"], correct: 1 },
    { q: "O QUE É A SUBLIMAÇÃO?", options: ["SÓLIDO PARA LÍQUIDO", "SÓLIDO PARA GASOSO", "GELO", "FUSÃO"], correct: 1 },
    { q: "O QUE É A SOLIDIFICAÇÃO?", options: ["GASOSO PARA SÓLIDO", "LÍQUIDO PARA SÓLIDO", "FOGO", "DERRETER"], correct: 1 },
    { q: "QUAL O NOME DA ÁGUA GASOSA?", options: ["GELO", "VAPOR", "ORVALHO", "NEBLINA"], correct: 1 },
    { q: "O QUE É UMA REAÇÃO QUÍMICA?", options: ["SÓ MUDAR DE LUGAR", "FORMAÇÃO DE NOVA SUBSTÂNCIA", "QUEBRAR", "PINTAR"], correct: 1 },
    { q: "O QUE É UMA MISTURA HOMOGÊNEA?", options: ["DÁ PARA VER AS PARTES", "NÃO DÁ PARA VER AS PARTES", "ÁGUA E AREIA", "PEDRAS"], correct: 1 },
    { q: "O QUE É UMA MISTURA HETEROGÊNEA?", options: ["SÓ UMA COR", "DÁ PARA VER AS PARTES", "SAL NA ÁGUA", "AR"], correct: 1 },
    { q: "QUAL O COMPONENTE DO AR EM MAIOR QUANTIDADE?", options: ["OXIGÊNIO", "NITROGÊNIO", "CO2", "HIDROGÊNIO"], correct: 1 },
    { q: "O QUE É A EVAPORAÇÃO?", options: ["LENTA", "RÁPIDA", "INSTANTÂNEA", "CONGELAMENTO"], correct: 0 },
    { q: "O QUE É A EBULIÇÃO?", options: ["LENTA", "RÁPIDA (FERVURA)", "GELO", "VAPOR"], correct: 1 },
    { q: "QUAL A DENSIDADE DA ÁGUA PURA?", options: ["0", "1 G/CM³", "10", "100"], correct: 1 },
    { q: "O QUE FLUTUA NA ÁGUA?", options: ["OBJETO MAIS DENSO", "OBJETO MENOS DENSO", "FERRO", "PEDRA"], correct: 1 },
    { q: "O QUE É UM SOLVENTE?", options: ["O QUE É DISSOLVIDO", "O QUE DISSOLVE (EX: ÁGUA)", "SAL", "AÇÚCAR"], correct: 1 },
    { q: "O QUE É UM SOLUTO?", options: ["O LÍQUIDO", "A SUBSTÂNCIA DISSOLVIDA", "ÁGUA", "ÁLCOOL"], correct: 1 },
    { q: "QUAL O SOLVENTE UNIVERSAL?", options: ["ÁLCOOL", "ÁGUA", "ACETONA", "GASOLINA"], correct: 1 },
    { q: "O QUE É A DESTILAÇÃO SIMPLES?", options: ["SEPARA SÓLIDO DE LÍQUIDO", "CONGELA TUDO", "QUEIMA", "MISTURA"], correct: 0 },
    { q: "QUAL O NOME DO PROCESSO DE FILTRAR?", options: ["FILTRAÇÃO", "DECANTAÇÃO", "FUSÃO", "EBULIÇÃO"], correct: 0 },
    { q: "O QUE É A DECANTAÇÃO?", options: ["ESPERAR O SÓLIDO DESCER", "FERVER", "CONGELAR", "VENTAR"], correct: 0 },
    { q: "O QUE É UMA LIGA DE BRONZE?", options: ["OURO E PRATA", "COBRE E ESTANHO", "FERRO", "ALUMÍNIO"], correct: 1 },
    { q: "O QUE É O AÇO?", options: ["FERRO E CARBONO", "OURO", "COBRE", "PLÁSTICO"], correct: 0 },
    { q: "O QUE É A MALEABILIDADE?", options: ["QUEBRAR FÁCIL", "CAPACIDADE DE VIRAR FOLHAS", "COR", "PESO"], correct: 1 },
    { q: "COMO A LUZ VIAJA?", options: ["EM CURVAS", "EM LINHA RETA", "SÓ NO MAR", "NÃO VIAJA"], correct: 1 },
    { q: "O QUE É A OPACIDADE?", options: ["PASSA TODA A LUZ", "NÃO PASSA LUZ", "PASSA POUCA LUZ", "BRILHA"], correct: 1 },
    { q: "O QUE É UM CORPO TRANSLÚCIDO?", options: ["PASSA TODA A LUZ", "PASSA PARTE DA LUZ", "NÃO PASSA NADA", "É ESPELHO"], correct: 1 },
    { q: "O QUE É UM CORPO TRANSPARENTE?", options: ["PASSA TODA A LUZ", "NÃO PASSA LUZ", "É PRETO", "É FOSCO"], correct: 0 },
    { q: "QUAL A COR QUE SURGE DA MISTURA DE TODAS AS OUTRAS CORES?", options: ["PRETO", "BRANCO", "VERDE", "CINZA"], correct: 1 },
    { q: "O QUE É A AUSÊNCIA DE LUZ?", options: ["BRANCO", "PRETO", "AMARELO", "AZUL"], correct: 1 },
    { q: "O QUE É UMA ONDA SONORA?", options: ["VAPOR", "VIBRAÇÃO DA MATÉRIA", "LUZ", "VÁCUO"], correct: 1 },
    { q: "O SOM VIAJA NO VÁCUO?", options: ["SIM", "NÃO", "ÀS VEZES", "SÓ NO ESPAÇO"], correct: 1 },
    { q: "ONDE O SOM VIAJA MAIS RÁPIDO?", options: ["AR", "LÍQUIDOS", "SÓLIDOS", "VÁCUO"], correct: 2 },
    { q: "O QUE É A FREQUÊNCIA DO SOM?", options: ["ALTURA (GRAVE/AGUDO)", "VOLUME", "COR", "PESO"], correct: 0 },
    { q: "O QUE É UM SOM AGUDO?", options: ["FREQUÊNCIA BAIXA", "FREQUÊNCIA ALTA", "SOM FORTE", "SOM FRACO"], correct: 1 },
    { q: "O QUE É UM SOM GRAVE?", options: ["FREQUÊNCIA BAIXA", "FREQUÊNCIA ALTA", "BARULHO", "MÚSICA"], correct: 0 },
    { q: "O QUE É O TIMBRE?", options: ["VOLUME", "QUALIDADE/IDENTIDADE DO SOM", "ALTURA", "VELOCIDADE"], correct: 1 },
    { q: "O QUE É O INFRAVERMELHO?", options: ["LUZ VISÍVEL", "RADIAÇÃO DE CALOR", "SOM", "GELO"], correct: 1 },
    { q: "O QUE É O ULTRAVIOLETA?", options: ["RADIAÇÃO DO SOL", "SOM ALTO", "LUZ VERDE", "FOGO"], correct: 0 },
    { q: "PARA QUE SERVE O PRISMA?", options: ["CONGELAR", "DECOMPOR A LUZ", "BOMBEAR", "FILTRAR"], correct: 1 },
    { q: "O QUE É A LENTE CONVEXA?", options: ["LUPA/AUMENTA", "DIMINUI", "ESCURA", "PLANA"], correct: 0 },
    { q: "O QUE É O LASER?", options: ["SOM FORTE", "LUZ CONCENTRADA", "GÁS", "PÓ"], correct: 1 },
    { q: "O QUE É A FIBRA ÓPTICA?", options: ["FIO DE FERRO", "FIO QUE LEVA LUZ", "CORDA", "TUBO DE ÁGUA"], correct: 1 },
    { q: "QUAL A FUNÇÃO DA ALAVANCA?", options: ["DIMINUIR O PESO", "FACILITAR O ESFORÇO", "QUEBRAR", "NADA"], correct: 1 },
    { q: "O QUE É UMA ROLDANA (POLIA)?", options: ["UM PREGO", "RODA QUE LEVANTA PESO", "UM PARAFUSO", "UM MOTOR"], correct: 1 },
    { q: "QUAL A FUNÇÃO DO PLANO INCLINADO?", options: ["SUBIR COM MENOS FORÇA", "CAIR", "CORRER", "PULAR"], correct: 0 },
    { q: "O QUE É O ATRITO?", options: ["FORÇA QUE AJUDA", "FORÇA QUE SE OPÕE AO MOVIMENTO", "LUZ", "SOM"], correct: 1 },
    { q: "O QUE REDUZ O ATRITO?", options: ["AREIA", "LUBRIFICANTE/ÓLEO", "PEDRA", "BORRACHA"], correct: 1 },
    { q: "O QUE É UM MOTOR A COMBUSTÃO?", options: ["USA ÁGUA", "USA EXPLOSÃO DE COMBUSTÍVEL", "USA VENTO", "USA ÍMÃ"], correct: 1 },
    { q: "QUAL A FUNÇÃO DOS ENGRENAGENS?", options: ["TRANSMITIR MOVIMENTO", "PARAR", "ESQUENTAR", "LIMPAR"], correct: 0 },
    { q: "O QUE É A PRESSÃO ATMOSFÉRICA?", options: ["PESO DO AR", "PESO DA ÁGUA", "CALOR", "VENTO"], correct: 0 },
    { q: "O QUE É O EMPUXO?", options: ["FORÇA DA ÁGUA PARA CIMA", "FORÇA PARA BAIXO", "VENTO", "LUZ"], correct: 0 },
    { q: "QUAL A UNIDADE DE POTÊNCIA DE CARROS?", options: ["METROS", "CAVALOS (CV/HP)", "LITROS", "QUILOS"], correct: 1 },
    { q: "O QUE É A AERODINÂMICA?", options: ["ESTUDO DA ÁGUA", "ESTUDO DO AR EM MOVIMENTO", "ESTUDO DO FOGO", "ESTUDO DO DNA"], correct: 1 },
    { q: "PARA QUE SERVE O PARAFUSO?", options: ["CORTAR", "FIXAR E TRANSFORMAR MOVIMENTO", "QUEIMAR", "VER"], correct: 1 },
    { q: "O QUE É UMA MÁQUINA SIMPLES?", options: ["COMPUTADOR", "RAMPA/ALAVANCA", "CARRO", "AVIÃO"], correct: 1 },
    { q: "O QUE É A ENERGIA POTENCIAL?", options: ["ENERGIA ARMAZENADA", "MOVIMENTO", "LUZ", "SOM"], correct: 0 },
    { q: "O QUE É A ENERGIA TÉRMICA?", options: ["SOM", "CALOR", "VENTO", "LUA"], correct: 1 },
    { q: "QUAL A LEI DA CONSERVAÇÃO DA ENERGIA?", options: ["PODE SER CRIADA", "NÃO SE CRIA, SE TRANSFORMA", "PODE SER DESTRUÍDA", "NADA"], correct: 1 },
    { q: "O QUE É O TRABALHO NA FÍSICA?", options: ["PROFISSÃO", "FORÇA VEZES DESLOCAMENTO", "ESTUDO", "DORMIR"], correct: 1 },
    { q: "QUAL A UNIDADE DE RESISTÊNCIA ELÉTRICA?", options: ["VOLT", "OHM", "WATT", "AMPÉRE"], correct: 1 },
    { q: "O QUE É UM CURTO-CIRCUITO?", options: ["CAMINHO LONGO", "CONTATO DIRETO SEM RESISTÊNCIA", "PILHA NOVA", "LUZ ACESA"], correct: 1 },
    { q: "PARA QUE SERVE O FUSÍVEL?", options: ["DAR MAIS LUZ", "PROTEGER O CIRCUITO", "LIGAR O MOTOR", "MEDIR CALOR"], correct: 1 },
    { q: "QUAL O SISTEMA DA RESPIRAÇÃO?", options: ["DIGESTIVO", "RESPIRATÓRIO", "NERVOSO", "ÓSSEO"], correct: 1 },
    { q: "QUAL O SISTEMA QUE MOVE O CORPO?", options: ["RESPIRATÓRIO", "MUSCULAR", "URINÁRIO", "IMUNE"], correct: 1 },
    { q: "QUAL O SISTEMA QUE PROCESSA COMIDA?", options: ["CIRCULATÓRIO", "DIGESTÓRIO", "NERVOSO", "SENSORIAL"], correct: 1 },
    { q: "QUAL O SISTEMA QUE LEVA SANGUE PELO CORPO?", options: ["CARDIOVASCULAR", "ÓSSEO", "EXCRETOR", "LINFÁTICO"], correct: 0 },
    { q: "O QUE O SISTEMA EXCRETOR FAZ?", options: ["RESPIRA", "ELIMINA RESÍDUOS", "PENSAR", "CORRE"], correct: 1 },
    { q: "QUAL O NOME DO SISTEMA DE DEFESA DO CORPO HUMANO?", options: ["IMUNOLÓGICO", "ÓSSEO", "NERVOSO", "RESPIRATÓRIO"], correct: 0 },
    { q: "O QUE O SISTEMA ENDÓCRINO PRODUZ?", options: ["SANGUE", "HORMÔNIOS", "SUOR", "SALIVA"], correct: 1 },
    { q: "QUAL O NOME DA PARTE CENTRAL DO NERVO?", options: ["AXÔNIO", "NEURÔNIO", "CÉLULA", "TECIDO"], correct: 1 },
    { q: "O QUE OS ALVÉOLOS FAZEM?", options: ["DIGEREM", "TROCA DE GASES", "BOMBEIAM", "FILTRAM"], correct: 1 },
    { q: "ONDE SÃO PRODUZIDAS AS CÉLULAS DO SANGUE?", options: ["CORAÇÃO", "MEDULA ÓSSEA", "FÍGADO", "RINS"], correct: 1 },
    { q: "QUAL A FUNÇÃO DO INTESTINO DELGADO?", options: ["MASTIGAR", "ABSORVER NUTRIENTES", "SÓ GUARDAR", "RESPIRAR"], correct: 1 },
    { q: "QUAL A FUNÇÃO DO INTESTINO GROSSO?", options: ["ABSORVER ÁGUA", "PENSAR", "VER", "OUVIR"], correct: 0 },
    { q: "O QUE A BEXIGA ARMAZENA?", options: ["SANGUE", "URINA", "BILE", "SALIVA"], correct: 1 },
    { q: "QUAL O NOME DA CAPA DO NEURÔNIO?", options: ["PELE", "BAINHA DE MIELINA", "OSSO", "GORDURA"], correct: 1 },
    { q: "QUAL ÓRGÃO LIMPA AS TOXINAS?", options: ["CORAÇÃO", "FÍGADO", "PULMÃO", "OSSOS"], correct: 1 },
    { q: "QUAL A FUNÇÃO DOS TENDÕES?", options: ["LIGAR OSSO A MÚSCULO", "LIGAR OSSO A OSSO", "DIGERIR", "PENSAR"], correct: 0 },
    { q: "O QUE SÃO LIGAMENTOS?", options: ["LIGAM OSSO A OSSO", "PRODUZEM SANGUE", "SÃO NERVOS", "SÃO VEIAS"], correct: 0 },
    { q: "O QUE CAUSA O RESFRIADO?", options: ["BACTÉRIA", "VÍRUS", "FRIO", "FOME"], correct: 1 },
    { q: "QUAL DOENÇA É FALTA DE INSULINA?", options: ["ANEMIA", "DIABETES", "GRIPE", "CANCRO"], correct: 1 },
    { q: "O QUE É A HIPERTENSÃO?", options: ["PRESSÃO ALTA", "FALTA DE AR", "DOR DE CABEÇA", "FEBRE"], correct: 0 },
    { q: "QUAL DOENÇA AFETA OS OSSOS?", options: ["OSTEOPOROSE", "GASTRITE", "RINITE", "OTITE"], correct: 0 },
    { q: "O QUE O MOSQUITO AEDES TRANSMITE?", options: ["GRIPE", "DENGUE", "MALÁRIA", "RAIVA"], correct: 1 },
    { q: "QUAL O NOME DA INFLAMAÇÃO NO OUVIDO?", options: ["SINUSITE", "OTITE", "AMIGDALITE", "GASTRITE"], correct: 1 },
    { q: "O QUE É A MIOPIA?", options: ["DIFICULDADE DE VER LONGE", "DIFICULDADE DE OUVIR", "DOR NO PÉ", "FEBRE"], correct: 0 },
    { q: "O QUE É O ASTIGMATISMO?", options: ["AUDIÇÃO RUIM", "VISÃO EMBAÇADA", "FALTA DE CHEIRO", "CANSAÇO"], correct: 1 },
    { q: "QUAL A FUNÇÃO DO ANTIGÊNIO?", options: ["RECONHECER INVASOR", "MATAR", "BOMBEAR", "NADA"], correct: 0 },
    { q: "O QUE É UMA EPIDEMIA?", options: ["DOENÇA NUMA REGIÃO", "DOENÇA NO MUNDO TODO", "UMA CURA", "UM REMÉDIO"], correct: 0 },
    { q: "O QUE É UMA PANDEMIA?", options: ["DOENÇA LOCAL", "DOENÇA ESPALHADA PELO MUNDO", "SÓ UMA PESSOA", "NÃO É DOENÇA"], correct: 1 },
    { q: "QUAL VITAMINA VEM DO SOL?", options: ["VITAMINA A", "VITAMINA D", "VITAMINA C", "VITAMINA K"], correct: 1 },
    { q: "O QUE A FALTA DE VITAMINA C CAUSA?", options: ["RAQUITISMO", "ESCORBUTO", "ANEMIA", "CEGUEIRA"], correct: 1 },
    { q: "QUAL O NOME DO MÉDICO DO CORAÇÃO?", options: ["NEURO", "CARDIOLOGISTA", "DERMATO", "PEDIATRA"], correct: 1 },
    { q: "QUAL O MÉDICO DA PELE?", options: ["CARDIOLOGISTA", "DERMATOLOGISTA", "OCULISTA", "DENTISTA"], correct: 1 },
    { q: "O QUE É A ALERGIA?", options: ["REAÇÃO EXAGERADA DO IMUNE", "FOME", "FALTA DE SONO", "CRESCIMENTO"], correct: 0 },
    { q: "PARA QUE SERVE O SORO?", options: ["DAR FOME", "REIDRATAR E NUTRIR", "DAR SONO", "NADA"], correct: 1 },
    { q: "QUAL O NOME DA INFLAMAÇÃO NA GARGANTA?", options: ["OTITE", "AMIGDALITE", "GASTRITE", "COLITE"], correct: 1 },
    { q: "O QUE É O CÂNCER?", options: ["CRESCIMENTO DESCONTROLADO DE CÉLULAS", "UMA BACTÉRIA", "UM VÍRUS", "FALTA DE ÁGUA"], correct: 0 },
    { q: "QUAL O NOME DA PARALISIA INFANTIL?", options: ["GRIPE", "POLIOMIELITE", "SARAMPO", "VARICELA"], correct: 1 },
    { q: "O QUE É UM ECOSSISTEMA?", options: ["SÓ ANIMAIS", "RELAÇÃO SERES E AMBIENTE", "SÓ PLANTAS", "SÓ PEDRAS"], correct: 1 },
    { q: "QUAL O NOME DO LUGAR ONDE O SER VIVE?", options: ["HABITAT", "CASA", "NINHO", "CIDADE"], correct: 0 },
    { q: "O QUE É UM PRODUTOR?", options: ["PLANTA (FAZ O PRÓPRIO ALIMENTO)", "ANIMAL QUE CAÇA", "FUNGO", "PEDRA"], correct: 0 },
    { q: "O QUE É UM CONSUMIDOR?", options: ["PLANTA", "SER QUE COME OUTRO", "SOL", "ÁGUA"], correct: 1 },
    { q: "O QUE É A DECOMPOSIÇÃO?", options: ["RECICLAGEM DE MATÉRIA", "NASCIMENTO", "VOO", "SALTO"], correct: 0 },
    { q: "O QUE É A BIOMASSA?", options: ["MATÉRIA ORGÂNICA", "PEDRAS", "LUA", "GÁS"], correct: 0 },
    { q: "QUAL O NOME DO 'PAPEL' DO SER NA NATUREZA?", options: ["HABITAT", "NICHO ECOLÓGICO", "TRABALHO", "NOME"], correct: 1 },
    { q: "O QUE É A SUCESSÃO ECOLÓGICA?", options: ["MORTE", "MUDANÇA DA COMUNIDADE NO TEMPO", "FOME", "VENTO"], correct: 1 },
    { q: "O QUE É A SIMBIOSE?", options: ["LUTA", "RELAÇÃO ENTRE ESPÉCIES", "MORTE", "NASCE"], correct: 1 },
    { q: "O QUE É O PARASITISMO?", options: ["UM SE BENEFICIA E PREJUDICA OUTRO", "AJUDA MÚTUA", "LUTA", "NADA"], correct: 0 },
    { q: "O QUE É O MUTUALISMO?", options: ["AMBOS SE AJUDAM", "LUTA", "MORTE", "ROUBO"], correct: 0 },
    { q: "QUAL O NOME DO 'GAS ESTUFA'?", options: ["OXIGÊNIO", "CO2", "HÉLIO", "ARGÔNIO"], correct: 1 },
    { q: "O QUE A CAMADA DE OZÔNIO FILTRA?", options: ["VENTO", "RAIOS ULTRAVIOLETA", "NUVENS", "CHUVA"], correct: 1 },
    { q: "O QUE É A CHUVA ÁCIDA?", options: ["ÁGUA DOCE", "POLUIÇÃO NA ÁGUA DA CHUVA", "GELO", "FOGO"], correct: 1 },
    { q: "QUAL O NOME DA ENERGIA DA TERRA (CALOR)?", options: ["SOLAR", "GEOTÉRMICA", "EÓLICA", "NUCLEAR"], correct: 1 },
    { q: "QUAL O MAIOR RESERVATÓRIO DE ÁGUA DOCE?", options: ["RIOS", "GELO/GLACIARES", "MARES", "NUVENS"], correct: 1 },
    { q: "O QUE É A BIODIVERSIDADE?", options: ["UMA ESPÉCIE", "VARIEDADE DE VIDA", "SÓ PLANTAS", "SÓ ANIMAIS"], correct: 1 },
    { q: "QUAL A FUNÇÃO DOS ESTÔMATOS?", options: ["OUVIR", "TROCAS GASOSAS NA PLANTA", "DIGERIR", "VER"], correct: 1 },
    { q: "O QUE É O FITOPLÂNCTON?", options: ["ANIMAL", "ALGAS MICROSCÓPICAS", "PEDRA", "LUA"], correct: 1 },
    { q: "QUEM INVENTOU O TELEFONE?", options: ["EDISON", "GRAHAM BELL", "TESLA", "NEWTON"], correct: 1 },
    { q: "QUEM INVENTOU A LÂMPADA?", options: ["EINSTEIN", "THOMAS EDISON", "MARCONI", "DA VINCI"], correct: 1 },
    { q: "O QUE O MOTOR A VAPOR USA?", options: ["VENTO", "CALOR DA ÁGUA", "ELETRICIDADE", "ÍMÃ"], correct: 1 },
    { q: "QUEM  INVENTOU O AVIÃO?", options: ["WRIGHT", "SANTOS DUMONT", "COLOMBO", "CABRAL"], correct: 1 },
    { q: "O QUE É O CÓDIGO BINÁRIO?", options: ["SÓ 1 E 2", "SÓ 0 E 1", "SÓ A E B", "NÚMEROS 0 A 9"], correct: 1 },
    { q: "QUAL A PEÇA CENTRAL DO COMPUTADOR?", options: ["TECLADO", "PROCESSADOR (CPU)", "MOUSE", "MONITOR"], correct: 1 },
    { q: "O QUE É O WI-FI?", options: ["CABO", "CONEXÃO SEM FIO", "UM DISCO", "UM TELA"], correct: 1 },
    { q: "PARA QUE SERVE O GPS?", options: ["OUVIR MÚSICA", "LOCALIZAÇÃO", "MEDIR FEBRE", "CONTAR PASSOS"], correct: 1 },
    { q: "O QUE É UM ROBÔ?", options: ["UM ANIMAL", "MÁQUINA PROGRAMÁVEL", "UMA PLANTA", "UM HUMANO"], correct: 1 },
    { q: "QUEM INVENTOU O RÁDIO?", options: ["MARCONI", "EDISON", "NEWTON", "DARWIN"], correct: 0 },
    { q: "O QUE É O SOFTWARE?", options: ["PARTE FÍSICA", "PROGRAMAS E SISTEMAS", "CABOS", "BATERIA"], correct: 1 },
    { q: "O QUE É O HARDWARE?", options: ["PROGRAMAS", "PARTE FÍSICA/PEÇAS", "INTERNET", "SINAL"], correct: 1 },
    { q: "PARA QUE SERVE O USB?", options: ["FALAR", "CONECTAR DISPOSITIVOS", "COMER", "DORMIR"], correct: 1 },
    { q: "O QUE É A INTERNET?", options: ["UM COMPUTADOR", "REDE MUNDIAL", "UM SITE", "UM CABO"], correct: 1 },
    { q: "O QUE É A INTELIGÊNCIA ARTIFICIAL?", options: ["HUMANO", "MÁQUINA QUE SIMULA COGNIÇÃO", "UM LIVRO", "UM TELEFONE"], correct: 1 },
    { q: "O QUE É UM SATÉLITE ARTIFICIAL?", options: ["LUA", "EQUIPAMENTO EM ÓRBITA", "ESTRELA", "PLANETA"], correct: 1 },
    { q: "QUAL O COMBUSTÍVEL DOS FOGUETES?", options: ["GASOLINA", "HIDROGÊNIO/OXIGÊNIO LÍQUIDO", "CARVÃO", "LENHA"], correct: 1 },
    { q: "O QUE É A NANOTECNOLOGIA?", options: ["TECNOLOGIA GIGANTE", "TECNOLOGIA EM ESCALA ATÔMICA", "MECÂNICA", "SOM"], correct: 1 },
    { q: "PARA QUE SERVE A IMPRESSORA 3D?", options: ["FOTOGRAFAR", "CRIAR OBJETOS FÍSICOS", "VER O CÉU", "OUVIR"], correct: 1 },
    { q: "O QUE É A REALIDADE VIRTUAL?", options: ["UM FILME", "AMBIENTE SIMULADO", "A VIDA REAL", "UM DESENHO"], correct: 1 },
    { q: "QUAL A CAMADA MAIS EXTERNA DA TERRA?", options: ["NÚCLEO", "CROSTA", "MANTO", "GELO"], correct: 1 },
    { q: "QUAL A CAMADA MAIS QUENTE DA TERRA?", options: ["CROSTA", "NÚCLEO", "MANTO", "OCEANO"], correct: 1 },
    { q: "O QUE É O MAGMA?", options: ["ÁGUA QUENTE", "ROCHA FUNDIDA", "GÁS", "PEDRA"], correct: 1 },
    { q: "O QUE SÃO PLACAS TECTÔNICAS?", options: ["ILHAS", "BLOCOS DA CROSTA", "NUVENS", "ESTRELAS"], correct: 1 },
    { q: "O QUE CAUSA OS TERREMOTOS?", options: ["VENTO", "MOVIMENTO DAS PLACAS", "SOL", "CHUVA"], correct: 1 },
    { q: "QUAL O NOME DO SUPERCONTINENTE ANTIGO?", options: ["BRASIL", "PANGEIA", "EUROPA", "ÁFRICA"], correct: 1 },
    { q: "O QUE SÃO ROCHAS SEDIMENTARES?", options: ["DE VULCÕES", "DE RESTOS ACUMULADOS", "DO ESPAÇO", "DE DIAMANTE"], correct: 1 },
    { q: "O QUE SÃO ROCHAS METAMÓRFICAS?", options: ["DO MAR", "TRANSFORMADAS POR CALOR/PRESSÃO", "DE AREIA", "DE GELO"], correct: 1 },
    { q: "O QUE SÃO ROCHAS ÍGNEAS?", options: ["DE AREIA", "DE RESFRIAMENTO DO MAGMA", "DE PLANTAS", "DE ÁGUA"], correct: 1 },
    { q: "QUAL O MINERAL MAIS DURO?", options: ["TALCO", "DIAMANTE", "QUARTZO", "OURO"], correct: 1 },
    { q: "O QUE É A ESCALA RICHTER?", options: ["MEDE CALOR", "MEDE TERREMOTOS", "MEDE CHUVA", "MEDE VENTO"], correct: 1 },
    { q: "ONDE SE LOCALIZA O MANTO?", options: ["FORA DA TERRA", "ENTRE CROSTA E NÚCLEO", "NO MAR", "NO AR"], correct: 1 },
    { q: "O QUE É A EROSÃO?", options: ["PLANTIO", "DESGASTE DO SOLO", "FOGO", "VENTO"], correct: 1 },
    { q: "O QUE SÃO FÓSSEIS?", options: ["PEDRAS NOVAS", "RESTOS DE VIDA ANTIGA", "PLANTAS VIVAS", "LUA"], correct: 1 },
    { q: "O QUE É O PETRÓLEO?", options: ["ÁGUA", "COMBUSTÍVEL FÓSSIL", "SUCO", "MINERAL"], correct: 1 },
    { q: "QUAL O NOME DA CIÊNCIA QUE ESTUDA AS ROCHAS?", options: ["BIOLOGIA", "GEOLOGIA", "QUÍMICA", "FÍSICA"], correct: 1 },
    { q: "O QUE É UM VULCÃO ATIVO?", options: ["MORTO", "EM ERUPÇÃO OU PODE ENTRAR", "UM RIO", "UMA ILHA"], correct: 1 },
    { q: "O QUE É O TSUNAMI?", options: ["VENTO", "ONDA GIGANTE POR TERREMOTO NO MAR", "CHUVA", "NEVE"], correct: 1 },
    { q: "O QUE É O RELEVO?", options: ["COR DA TERRA", "FORMAS DA SUPERFÍCIE", "CALOR", "AR"], correct: 1 },
    { q: "O QUE É UMA HIPÓTESE?", options: ["UMA VERDADE", "UMA IDEIA A SER TESTADA", "UM ERRO", "UM FATO"], correct: 1 },
    { q: "O QUE É UMA TEORIA CIENTÍFICA?", options: ["UM CHUTE", "EXPLICAÇÃO BASEADA EM FATOS", "UM DESENHO", "UM LIVRO"], correct: 1 },
    { q: "O QUE É O VÁCUO?", options: ["LUGAR COM AR", "LUGAR SEM MATÉRIA", "LUGAR COM ÁGUA", "LUGAR COM FOGO"], correct: 1 },
    { q: "O QUE É A MATÉRIA?", options: ["SÓ O QUE VEMOS", "TUDO QUE TEM MASSA E VOLUME", "SÓ PEDRAS", "SÓ ÁGUA"], correct: 1 },
    { q: "QUAL A UNIDADE BÁSICA DA MATÉRIA?", options: ["CÉLULA", "ÁTOMO", "MOLÉCULA", "GRÃO"], correct: 1 },
    { q: "O QUE É O ZERO ABSOLUTO?", options: ["0°C", "MENOR TEMPERATURA POSSÍVEL", "100°C", "-10°C"], correct: 1 },
    { q: "O QUE É A RADIOATIVIDADE?", options: ["LUZ", "EMISSÃO DE ENERGIA POR ÁTOMOS", "SOM", "VENTO"], correct: 1 },
    { q: "O QUE É O DNA?", options: ["COMIDA", "CÓDIGO DA VIDA", "UM OSSO", "UM ÓRGÃO"], correct: 1 },
    { q: "QUAL O GÁS MAIS LEVE?", options: ["OXIGÊNIO", "HIDROGÊNIO", "HÉLIO", "NITROGÊNIO"], correct: 1 },
    { q: "O QUE É A FISSÃO NUCLEAR?", options: ["UNIÃO", "QUEBRA DO NÚCLEO DO ÁTOMO", "CONGELAR", "QUEIMAR"], correct: 1 },
    { q: "O QUE É A FUSÃO NUCLEAR?", options: ["QUEBRA", "UNIÃO DE NÚCLEOS ATÔMICOS", "VENTO", "ÁGUA"], correct: 1 },
    { q: "QUEM DESCOBRIU O RÁDIO (ELEMENTO)?", options: ["NEWTON", "MARIE CURIE", "EINSTEIN", "DARWIN"], correct: 1 },
    { q: "O QUE É A TABELA PERIÓDICA?", options: ["LISTA DE NOMES", "ORGANIZAÇÃO DOS ELEMENTOS", "UM CALENDÁRIO", "UM MAPA"], correct: 1 },
    { q: "O QUE É A BIOLOGIA?", options: ["ESTUDO DA TERRA", "ESTUDO DA VIDA", "ESTUDO DO ESPAÇO", "ESTUDO DOS NÚMEROS"], correct: 1 },
    { q: "O QUE É A FÍSICA?", options: ["ESTUDO DA VIDA", "ESTUDO DA MATÉRIA E ENERGIA", "ESTUDO DO PASSADO", "ESTUDO DAS PLANTAS"], correct: 1 },
    { q: "POR QUE O CÉU É AZUL?", options: ["REFLEXO DO MAR", "DISPERSÃO DA LUZ", "COR DO AR", "GELO"], correct: 1 },
    { q: "O QUE FAZ O PÃO CRESCER?", options: ["ÁGUA", "FERMENTO (FUNGOS)", "SAL", "AÇÚCAR"], correct: 1 },
    { q: "O QUE É O GELO SECO?", options: ["ÁGUA CONGELADA", "CO2 SÓLIDO", "NITROGÊNIO", "OXIGÊNIO"], correct: 1 },
    { q: "COMO O MICRO-ONDAS AQUECE?", options: ["FOGO", "VIBRAÇÃO DAS MOLÉCULAS DE ÁGUA", "LUZ", "VENTO"], correct: 1 },
    { q: "O QUE É A MAIZENA?", options: ["TRIGO", "AMIDO DE MILHO", "ARROZ", "FEIJÃO"], correct: 1 },
    { q: "POR QUE A ÁGUA DO MAR É SALGADA?", options: ["PEIXES", "MINERAIS DAS ROCHAS", "CHUVAS", "SOL"], correct: 1 },
    { q: "O QUE É O TEFLON?", options: ["METAL", "POLÍMERO ANTIADERENTE", "VIDRO", "PEDRA"], correct: 1 },
    { q: "O QUE É A LIGA DE LATÃO?", options: ["OURO E PRATA", "COBRE E ZINCO", "FERRO", "ALUMÍNIO"], correct: 1 },
    { q: "POR QUE O FERRO ENFERRUJA?", options: ["FRIO", "REAÇÃO COM OXIGÊNIO/UMIDADE", "LUZ", "CALOR"], correct: 1 },
    { q: "O QUE É O ÁLCOOL EM GEL?", options: ["ÁGUA", "ETANOL COM ESPESSANTE", "GASOLINA", "SUCO"], correct: 1 },
    { q: "O QUE É A SODA CÁUSTICA?", options: ["ÁCIDO", "BASE FORTE", "SAL", "AÇÚCAR"], correct: 1 },
    { q: "POR QUE O SABÃO LIMPA GORDURA?", options: ["QUEBRA A MOLÉCULA", "MOLÉCULA COM PARTE QUE ATRAI ÁGUA/ÓLEO", "FOGO", "VENTO"], correct: 1 },
    { q: "O QUE É O LÁTEX?", options: ["PLÁSTICO", "SEIVA DA SERINGUEIRA", "METAL", "PEDRA"], correct: 1 },
    { q: "O QUE É O VIDRO?", options: ["AREIA FUNDIDA", "METAL", "PLÁSTICO", "MADEIRA"], correct: 0 },
    { q: "POR QUE O VAPOR SOBE?", options: ["MAIS PESADO QUE O AR", "MENOS DENSO QUE O AR", "PORQUE É QUENTE", "PORQUE É ÁGUA"], correct: 1 },
    { q: "QUAL O GÁS DO ISQUEIRO?", options: ["OXIGÊNIO", "BUTANO", "HÉLIO", "CO2"], correct: 1 },
    { q: "O QUE É O QUEROSENE?", options: ["ÁGUA", "DERIVADO DO PETRÓLEO", "ÁLCOOL", "VINAGRE"], correct: 1 },
    { q: "PARA QUE USAMOS SAL NO GELO?", options: ["PARA CONGELAR", "PARA BAIXAR O PONTO DE FUSÃO", "PARA DAR COR", "PARA COMER"], correct: 1 },
    { q: "DE QUE É FEITO O GRAFITE DO LÁPIS?", options: ["CHUMBO", "CARBONO", "FERRO", "PLÁSTICO"], correct: 1 },
    { q: "QUAL O 'SANGUE AZUL' NA NATUREZA?", options: ["HUMANO", "HERRADURA (CARANGUEJO)", "CÃO", "GATO"], correct: 1 },
    { q: "O QUE É A ADRENALINA?", options: ["COMIDA", "HORMÔNIO DE ALERTA", "VITAMINA", "GÁS"], correct: 1 },
    { q: "QUAL O NOME DA PROTEÍNA DO SANGUE?", options: ["QUERATINA", "HEMOGLOBINA", "INSULINA", "MELANINA"], correct: 1 },
    { q: "O QUE É A MIOCARDITE?", options: ["DOR NO PÉ", "INFLAMAÇÃO NO CORAÇÃO", "FEBRE", "GRIPE"], correct: 1 },
    { q: "QUAL A FUNÇÃO DA LÍNGUA?", options: ["OUVIR", "PALADAR E FALA", "VER", "CHEIRAR"], correct: 1 },
    { q: "O QUE É O SISTEMA LINFÁTICO?", options: ["DIGESTÃO", "DEFESA E DRENAGEM", "RESPIRAÇÃO", "OSSOS"], correct: 1 },
    { q: "O QUE É A EPIDERME?", options: ["OSSO", "CAMADA EXTERNA DA PELE", "MÚSCULO", "ÓRGÃO"], correct: 1 },
    { q: "QUAL O MENOR OSSO DO CORPO?", options: ["DEDO", "ESTRIBO", "NARIZ", "DENTE"], correct: 1 },
    { q: "O QUE É A SINAPSE?", options: ["DOR", "COMUNICAÇÃO ENTRE NEURÔNIOS", "SONO", "FOME"], correct: 1 },
    { q: "QUAL ÓRGÃO NÃO SENTE DOR?", options: ["PELE", "CÉREBRO", "CORAÇÃO", "FÍGADO"], correct: 1 },
    { q: "O QUE É A MELATONINA?", options: ["HORMÔNIO DO SONO", "HORMÔNIO DA FOME", "VITAMINA", "SAL"], correct: 0 },
    { q: "QUAL A FUNÇÃO DO FÍGADO?", options: ["RESPIRAR", "DESINTOXICAR O CORPO", "PENSAR", "CORRER"], correct: 1 },
    { q: "O QUE É A CÓRNEA?", options: ["PARTE DO OUVIDO", "PARTE DO OLHO", "OSSO", "UNHA"], correct: 1 },
    { q: "QUAL O NOME DO MÉDICO DOS RINS?", options: ["NEURO", "NEFROLOGISTA", "CARDIOLOGISTA", "PEDIATRA"], correct: 1 },
    { q: "O QUE É O SORO FISIOLÓGICO?", options: ["ÁGUA COM SAL", "SUCO", "ÁLCOOL", "ÁCIDO"], correct: 0 },
    { q: "QUAL A FUNÇÃO DA BILE?", options: ["PENSAR", "DIGERIR GORDURAS", "RESPIRAR", "CORRER"], correct: 1 },
    { q: "O QUE É A APENDICITE?", options: ["DOR DE CABEÇA", "INFLAMAÇÃO DO APÊNDICE", "FEBRE", "GRIPE"], correct: 1 },
    { q: "QUAL O MAIOR MÚSCULO DO CORPO?", options: ["BÍCEPS", "GLÚTEO MÁXIMO", "LÍNGUA", "CORAÇÃO"], correct: 1 },
    { q: "O QUE É A ENCEFALITE?", options: ["INFLAMAÇÃO NO CÉREBRO", "DOR NO PÉ", "GRIPE", "CÁRIE"], correct: 0 },
    { q: "O QUE É A AURORA BOREAL?", options: ["FOGO", "PARTÍCULAS SOLARES NA ATMOSFERA", "NUVEM", "LUZ DA CIDADE"], correct: 1 },
    { q: "O QUE É UM ARCO-ÍRIS?", options: ["PINTURA", "REFRAÇÃO DA LUZ NA ÁGUA", "VENTO", "FUMAÇA"], correct: 1 },
    { q: "POR QUE O GELO FLUTUA?", options: ["PORQUE NÃO É PESADO", "MENOS DENSO QUE A ÁGUA", "PORQUE É FRIO", "PORQUE É BRANCO"], correct: 1 },
    { q: "O QUE É O SOM MAIS RÁPIDO QUE A LUZ?", options: ["AVIÃO JATO", "NADA É MAIS RÁPIDO", "TROVÃO", "BALA"], correct: 1 },
    { q: "O QUE É A LUZ ULTRAVIOLETA?", options: ["LUZ VERMELHA", "ONDA DO SOL", "SOM ALTO", "FUMAÇA"], correct: 1 },
    { q: "O QUE É A FIBRA ÓPTICA?", options: ["CABO DE FERRO", "CABO QUE LEVA LUZ", "CORDA", "TUBO"], correct: 1 },
    { q: "PARA QUE SERVE O PRISMA?", options: ["CONGELAR", "DECOMPOR A LUZ", "BOMBEAR", "FILTRAR"], correct: 1 },
    { q: "O QUE É A REFLEXÃO?", options: ["LUZ PASSA DIRETO", "LUZ BATE E VOLTA", "SOM", "CALOR"], correct: 1 },
    { q: "O QUE É A REFRAÇÃO?", options: ["LUZ VOLTA", "LUZ MUDA DE MEIO/VELOCIDADE", "FOGO", "VENTO"], correct: 1 },
    { q: "O QUE É UM ESPELHO CÔNCAVO?", options: ["RETO", "CURVADO PARA DENTRO", "CURVADO PARA FORA", "ESCURO"], correct: 1 },
    { q: "O QUE É O RADAR?", options: ["USA LUZ", "USA ONDAS DE RÁDIO", "USA SOM", "USA ÁGUA"], correct: 1 },
    { q: "O QUE É O SONAR?", options: ["USA LUZ", "USA ONDAS SONORAS NA ÁGUA", "USA VENTO", "USA FOGO"], correct: 1 },
    { q: "O QUE É O VÁCUO?", options: ["AR MUITO FRIO", "AUSÊNCIA DE MATÉRIA", "NUVEM", "FOGO"], correct: 1 },
    { q: "QUAL A CIÊNCIA QUE ESTUDA OS ASTROS?", options: ["BIOLOGIA", "ASTRONOMIA", "GEOLOGIA", "QUÍMICA"], correct: 1 },
    { q: "QUAL A CIÊNCIA QUE ESTUDA A MATÉRIA?", options: ["FÍSICA", "QUÍMICA", "AMBOS", "NENHUM"], correct: 2 },
    { q: "QUEM FOI ALBERT EINSTEIN?", options: ["PINTOR", "FÍSICO", "MÚSICO", "ATLETA"], correct: 1 },
    { q: "COMO É CONHECIDA A FÓRMULA E=MC²?", options: ["FÓRMULA DA ÁGUA", "EQUAÇÃO DA ENERGIA", "RECEITA", "NOME DE CARRO"], correct: 1 },
    { q: "O QUE É O BIG BANG?", options: ["UMA MÚSICA", "TEORIA DA ORIGEM DO UNIVERSO", "UM FILME", "UM JOGO"], correct: 1 },
    { q: "QUAL A CIÊNCIA DOS FÓSSEIS?", options: ["ZOOLOGIA", "PALEONTOLOGIA", "BOTÂNICA", "QUÍMICA"], correct: 1 },
    { q: "O QUE É A GRAVIDADE ZERO?", options: ["MUITO PESO", "AUSÊNCIA DE PESO APARENTE", "VENTO FORTE", "FOGO"], correct: 1 },
    { q: "QUAL O NOME DA UNIDADE DE PRESSÃO?", options: ["METRO", "PASCAL", "LITRO", "QUILO"], correct: 1 },
    { q: "O QUE É A BIOLOGIA MARINHA?", options: ["ESTUDO DOS OSSOS", "ESTUDO DA VIDA NO MAR", "ESTUDO DO SOL", "ESTUDO DO VENTO"], correct: 1 },
    { q: "CIÊNCIA QUE ESTUDA O CLIMA?", options: ["GEOLOGIA", "METEOROLOGIA", "FÍSICA", "QUÍMICA"], correct: 1 },
    { q: "O QUE É O DNA?", options: ["ACIDO DESOXIRRIBONUCLEICO", "PROTEÍNA", "GORDURA", "AÇÚCAR"], correct: 0 },
    { q: "QUAL A FUNÇÃO DOS RIBOSSOMOS?", options: ["RESPIRAR", "SÍNTESE DE PROTEÍNAS", "DIGERIR", "LOCOMOÇÃO"], correct: 1 },
    { q: "O QUE É A ENTROPIA?", options: ["ORDEM", "DESORDEM/CAOS", "CALOR", "LUZ"], correct: 1 },
    { q: "O QUE É O ABSOLUTO?", options: ["-273,15°C", "0°C", "100°C", "1000°C"], correct: 0 },
    { q: "CIÊNCIA É IMPORTANTE?", options: ["NÃO", "SIM", "TALVEZ", "NUNCA"], correct: 1 },
    { q: "QUAL É O PLANETA MAIS FRIO DO SISTEMA SOLAR?", options: ["MARTE", "NEPTUNO", "TERRA", "VÊNUS"], correct: 1 },
    { q: "O QUE É O PONTO DE ORVALHO?", options: ["CHUVA", "TEMPERATURA QUE O VAPOR VIRA ÁGUA", "GELO", "SOL"], correct: 1 },
    { q: "QUAL O SÍMBOLO DO CHUMBO?", options: ["CH", "PB", "FE", "CU"], correct: 1 },
]