const esportesData = [
    { q: "QUANTAS COPAS DO MUNDO O BRASIL TEM", options: ["3", "4", "5", "6"], correct: 2 },
    { q: "QUEM É O REI DO FUTEBOL", options: ["ZICO", "PELÉ", "NEYMAR", "RONALDO"], correct: 1 },
    { q: "QUAL O NOME DO ESTÁDIO MAIS FAMOSO DO RIO DE JANEIRO", options: ["MINEIRÃO", "MARACANÃ", "MORUMBI", "BEIRA-RIO"], correct: 1 },
    { q: "DE QUANTOS EM QUANTOS ANOS OCORRE A COPA DO MUNDO", options: ["2 ANOS", "4 ANOS", "5 ANOS", "6 ANOS"], correct: 1 },
    { q: "QUAL O NOME DO JOGADOR CHAMADO 'FENÔMENO'", options: ["RONALDINHO GAÚCHO", "RONALDO NAZÁRIO", "CRISTIANO RONALDO", "ROBINHO"], correct: 1 },
    { q: "QUAL TIME O PELÉ JOGOU A MAIOR PARTE DA CARREIRA", options: ["FLAMENGO", "SANTOS", "CORINTHIANS", "PALMEIRAS"], correct: 1 },
    { q: "QUEM FOI O CAPITÃO DO TETRA EM 1994", options: ["DUNGA", "CAFÚ", "ROMÁRIO", "BEBETO"], correct: 0 },
    { q: "QUAL O NOME DO JOGADOR CONHECIDO PELO 'DRIBRE DA VACA'", options: ["PELÉ", "NEYMAR", "GARRINCHA", "DENÍLSON"], correct: 2 },
    { q: "QUEM VENCEU A COPA DO MUNDO DE 2002", options: ["ALEMANHA", "FRANÇA", "BRASIL", "ARGENTINA"], correct: 2 },
    { q: "QUAL O NOME DO CLÁSSICO ENTRE FLAMENGO E FLUMINENSE", options: ["GRE-NAL", "FLA-FLU", "DERBY", "CLÁSSICO DAS MULTIDÕES"], correct: 1 },
    { q: "QUANTOS JOGADORES CADA TIME TEM EM CAMPO NO FUTEBOL", options: ["10", "11", "12", "7"], correct: 1 },
    { q: "QUEM É O MAIOR ARTILHEIRO DA SELEÇÃO FEMININA", options: ["FORMIGA", "MARTA", "CRISTIANE", "ANDRESSA"], correct: 1 },
    { q: "QUAL O NOME DA PENALIDADE MÁXIMA NO FUTEBOL", options: ["ESCANTEIO", "PÊNALTI", "FALTA", "IMPEDIMENTO"], correct: 1 },
    { q: "QUEM FOI O TREINADOR DO PENTA EM 2002", options: ["TELÊ SANTANA", "FELIPÃO", "TITE", "PARREIRA"], correct: 1 },
    { q: "QUAL TIME É CONHECIDO COMO 'VERDÃO'", options: ["SÃO PAULO", "PALMEIRAS", "CORITIBA", "GOIÁS"], correct: 1 },
    { q: "QUAL O NOME DO JOGO ENTRE GRÊMIO E INTERNACIONAL", options: ["FLA-FLU", "GRE-NAL", "DERBY", "BA-VI"], correct: 1 },
    { q: "QUEM É O JOGADOR QUE MAIS VEZES FOI CAPITÃO DA SELEÇÃO", options: ["CAFÚ", "DUNGA", "THIAGO SILVA", "LUCIO"], correct: 0 },
    { q: "QUAL O NOME DA TAÇA DA COPA DO MUNDO (ANTIGA)", options: ["LIBERTADORES", "JULES RIMET", "CHAMPIONS", "BRASIL"], correct: 1 },
    { q: "EM QUE ANO O BRASIL SEDIOU A SUA PRIMEIRA COPA", options: ["1950", "1970", "2014", "1962"], correct: 0 },
    { q: "QUAL O NOME DO ESTÁDIO DO CORINTHIANS", options: ["ALIANZ PARQUE", "NEO QUÍMICA ARENA", "MORUMBI", "VILA BELMIRO"], correct: 1 },
    { q: "QUEM É CONSIDERADO O MAIOR JOGADOR DE BASQUETE", options: ["LEBRON JAMES", "MICHAEL JORDAN", "KOBE BRYANT", "STEPHEN CURRY"], correct: 1 },
    { q: "QUAL O NOME DA LIGA DE BASQUETE DOS EUA", options: ["NFL", "NBA", "MLB", "NHL"], correct: 1 },
    { q: "QUANTOS PONTOS VALE UMA CESTA DE LONGE NO BASQUETE", options: ["1", "2", "3", "4"], correct: 2 },
    { q: "QUAL O NOME DA LIGA DE FUTEBOL AMERICANO", options: ["NBA", "NFL", "MLS", "UFC"], correct: 1 },
    { q: "COMO SE CHAMA A PONTUAÇÃO MÁXIMA NO FUTEBOL AMERICANO", options: ["HOME RUN", "TOUCHDOWN", "BASKET", "GOL"], correct: 1 },
    { q: "QUAL O NOME DO EVENTO FINAL DA NFL", options: ["WORLD SERIES", "SUPER BOWL", "FINALS", "PLAYOFFS"], correct: 1 },
    { q: "QUEM É O JOGADOR MAIS FAMOSO DO FUTEBOL AMERICANO (EX-MARIDO DA GISELE)", options: ["PATRICK MAHOMES", "TOM BRADY", "AARON RODGERS", "PEYTON MANNING"], correct: 1 },
    { q: "QUAL ESPORTE USA UM TACO E UMA BOLA PEQUENA", options: ["BASQUETE", "BEISEBOL", "FUTEBOL", "VÔLEI"], correct: 1 },
    { q: "QUANDO UM JOGADOR DE BEISEBOL RECORRE TODAS AS BASES", options: ["TOUCHDOWN", "HOME RUN", "STRIKE", "GOUT"], correct: 1 },
    { q: "QUAL O NOME DO BASQUETEBOLISTA BRASILEIRO 'MÃO SANTA'", options: ["NENÊ", "OSCAR SCHMIDT", "ANDERSON VAREJÃO", "HUERTAS"], correct: 1 },
    { q: "QUANTOS JOGADORES CADA TIME TEM EM QUADRA NO BASQUETE", options: ["4", "5", "6", "11"], correct: 1 },
    { q: "QUAL O NOME DO TIME DE BASQUETE DE CHICAGO", options: ["LAKERS", "BULLS", "WARRIORS", "CELTICS"], correct: 1 },
    { q: "EM QUAL ESPORTE SE USA UM DISCO (PUCK) NO GELO", options: ["CURLING", "HÓQUEI NO GELO", "PATINAÇÃO", "ESQUI"], correct: 1 },
    { q: "QUAL O NOME DO TIME DE BASQUETE DE LOS ANGELES", options: ["BULLS", "LAKERS", "NETS", "KNICKS"], correct: 1 },
    { q: "QUEM É O JOGADOR QUE MAIS FEZ CESTAS DE 3 NA NBA", options: ["RAY ALLEN", "STEPHEN CURRY", "RENNIE MILLER", "JAMES HARDEN"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE ONDE SE CHUTA UMA BOLA OVAL", options: ["SOCCER", "RUGBY / FUTEBOL AMERICANO", "TÊNIS", "GOLFE"], correct: 1 },
    { q: "QUAL O TEMPO DE UMA PARTIDA DE BASQUETE NBA (TOTAL)", options: ["40 MIN", "48 MIN", "60 MIN", "90 MIN"], correct: 1 },
    { q: "COMO SE CHAMA O ATO DE BLOQUEAR UM ARREMESSO NO BASQUETE", options: ["DRIBLE", "TOCO (BLOCK)", "ASSISTÊNCIA", "REBOTE"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE DE TIGER WOODS", options: ["TÊNIS", "GOLFE", "POLO", "NATAÇÃO"], correct: 1 },
    { q: "QUAL O NOME DO TROFÉU DA NBA", options: ["LARRY O'BRIEN", "VINCE LOMBARDI", "STANLEY CUP", "OSCAR"], correct: 0 },
    { q: "DE QUANTOS EM QUANTOS ANOS OCORREM OS JOGOS OLÍMPICOS", options: ["2 ANOS", "4 ANOS", "5 ANOS", "10 ANOS"], correct: 1 },
    { q: "QUAL O NOME DO HOMEM MAIS RÁPIDO DO MUNDO (100M)", options: ["CARL LEWIS", "USAIN BOLT", "TYSON GAY", "YOHAN BLAKE"], correct: 1 },
    { q: "QUANTAS MEDALHAS DE OURO TEM MICHAEL PHELPS (RECORDE)", options: ["15", "23", "28", "10"], correct: 1 },
    { q: "QUAL O NOME DA GINASTA BRASILEIRA 'PEQUENA NOTÁVEL'", options: ["REBECA ANDRADE", "DAIANE DOS SANTOS", "JADE BARBOSA", "DANIELLE HYPOLITO"], correct: 1 },
    { q: "QUAL ESPORTE USA UMA RAQUETE E UMA PETECA", options: ["TÊNIS", "BADMINTON", "SQUASH", "PING-PONG"], correct: 1 },
    { q: "COMO SE CHAMA O PONTO MÁXIMO NO JUDÔ", options: ["WAZA-ARI", "IPPON", "YUKO", "KOKA"], correct: 1 },
    { q: "QUEM É O MAIOR VENCEDOR DE GRAND SLAMS NO TÊNIS (MASC)", options: ["FEDERER", "NADAL", "DJOKOVIC", "AGASSI"], correct: 2 },
    { q: "QUAL O NOME DO ESPORTE DE REBECA ANDRADE", options: ["NATAÇÃO", "GINÁSTICA ARTÍSTICA", "ATLETISMO", "JUDÔ"], correct: 1 },
    { q: "QUANTOS ANÉIS TEM A BANDEIRA OLÍMPICA", options: ["3", "4", "5", "6"], correct: 2 },
    { q: "QUAL A DISTÂNCIA DE UMA MARATONA", options: ["21 KM", "42.195 KM", "10 KM", "50 KM"], correct: 1 },
    { q: "QUAL ESPORTE USA AS ARMAS FLORETE, ESPADA E SABRE", options: ["TIRO", "ESGRIMA", "ARCO E FLECHA", "BOXE"], correct: 1 },
    { q: "QUEM É A 'FADINHA' DO SKATE BRASILEIRO", options: ["LETICIA BUFONI", "RAYSSA LEAL", "SKY BROWN", "PÂMELA ROSA"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE QUE OCORRE EM UMA PISCINA COM GOLS", options: ["NADO SINCRONIZADO", "POLO AQUÁTICO", "SURF", "MERGULHO"], correct: 1 },
    { q: "ONDE FORAM OS PRIMEIROS JOGOS OLÍMPICOS DA ERA MODERNA (1896)", options: ["PARIS", "ATENAS", "LONDRES", "ROMA"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE DE GABRIEL MEDINA", options: ["SKATE", "SURF", "NATAÇÃO", "VELA"], correct: 1 },
    { q: "QUEM É O MAIOR BOXEADOR DE TODOS OS TEMPOS (PESO PESADO)", options: ["MIKE TYSON", "MUHAMMAD ALI", "EVANDER HOLYFIELD", "ROCKY"], correct: 1 },
    { q: "QUAL ESPORTE USA UMA BOLA PEQUENA E UMA MESA", options: ["SQUASH", "TÊNIS DE MESA", "SINUCA", "HÓQUEI"], correct: 1 },
    { q: "COMO SE CHAMA O NADADOR QUE FAZ O ESTILO 'BORBOLETA'", options: ["PHELPS", "CIELO", "THORPE", "TODOS"], correct: 3 },
    { q: "QUAL O NOME DO ESPORTE QUE ENVOLVE SALTO, TRAVE E SOLO", options: ["ATLETISMO", "GINÁSTICA ARTÍSTICA", "DANÇA", "CIRCO"], correct: 1 },
    { q: "QUEM FOI O PRIMEIRO BRASILEIRO A GANHAR OURO NO TÊNIS (DUPLAS/SIMPLES)", options: ["GUGA", "MARIA ESTHER BUENO", "MELIGENI", "BELLUCCI"], correct: 1 },
    { q: "QUEM É O MAIOR ÍDOLO BRASILEIRO DA FÓRMULA 1", options: ["NELSON PIQUET", "AYRTON SENNA", "EMERSON FITTIPALDI", "RUBENS BARRICHELLO"], correct: 1 },
    { q: "QUAL O NOME DA EQUIPE DE SENNA NO TRICAMPEONATO", options: ["FERRARI", "MCLAREN", "WILLIAMS", "REDBULL"], correct: 1 },
    { q: "QUEM TEM O RECORDE DE TÍTULOS NA F1 (7 - EMPATE)", options: ["SENNA E PROST", "SCHUMACHER E HAMILTON", "VETTEL E ALONSO", "VERSTAPPEN"], correct: 1 },
    { q: "QUAL A COR TRADICIONAL DOS CARROS DA FERRARI", options: ["AZUL", "AMARELO", "VERMELHO", "PRETO"], correct: 2 },
    { q: "QUAL O NOME DO ESPORTE DE ANDERSON SILVA", options: ["BOXE", "MMA (UFC)", "KARATÊ", "JIU-JITSU"], correct: 1 },
    { q: "QUEM É CONHECIDO COMO 'THE GOAT' NO MMA FEMININO", options: ["RONDA ROUSEY", "AMANDA NUNES", "CRIS CYBORG", "HOLLY HOLM"], correct: 1 },
    { q: "QUAL O NOME DA CATEGORIA DE CORRIDA DE CAMINHÕES", options: ["STOCK CAR", "FÓRMULA TRUCK", "INDY", "RALLY"], correct: 1 },
    { q: "ONDE OCORRE A FAMOSA CORRIDA DE '24 HORAS'", options: ["INTERLAGOS", "LE MANS", "MONACO", "DAYTONA"], correct: 1 },
    { q: "QUAL O NOME DO CIRCUITO DE F1 NO BRASIL", options: ["ESTORIL", "INTERLAGOS", "MONZA", "SPA"], correct: 1 },
    { q: "QUAL O NOME DA LUTA QUE É 'A ARTE SUAVE'", options: ["MUAY THAI", "JIU-JITSU", "KUNG FU", "CAPOEIRA"], correct: 1 },
    { q: "QUEM É O VILÃO (RIVAL) DE AYRTON SENNA", options: ["MANSELL", "ALAIN PROST", "PIQUET", "LAUDA"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE DE MIKE TYSON", options: ["MMA", "BOXE", "WRESTLING", "SUMÔ"], correct: 1 },
    { q: "QUANTOS LADOS TEM O RINGUE DO UFC (OCTÓGONO)", options: ["4", "6", "8", "10"], correct: 2 },
    { q: "QUAL O NOME DA LUTA BRASILEIRA COM MÚSICA", options: ["KARATÊ", "CAPOEIRA", "JUDÔ", "SUMÔ"], correct: 1 },
    { q: "QUAL PAÍS É FAMOSO PELO SUMÔ", options: ["CHINA", "JAPÃO", "COREIA", "TAILÂNDIA"], correct: 1 },
    { q: "COMO SE CHAMA A CORRIDA DE CARROS EM ESTRADAS DE TERRA", options: ["F1", "RALLY", "NASCAR", "INDY"], correct: 1 },
    { q: "QUEM É O PILOTO HOLANDÊS ATUAL DOMINANTE DA F1", options: ["HAMILTON", "MAX VERSTAPPEN", "LECLERC", "NORRIS"], correct: 1 },
    { q: "QUAL O NOME DA LUTA TAILANDESA QUE USA COTOVELOS", options: ["TAEKWONDO", "MUAY THAI", "BOXE", "HAPKIDO"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE DE VALENTINO ROSSI", options: ["F1", "MOTOGP", "RALLY", "MOTOCROSS"], correct: 1 },
    { q: "QUAL O NOME DA MANOBRA DE FINALIZAÇÃO NO JIU-JITSU", options: ["NOCAUTE", "FINALIZAÇÃO/ESTRANGULAMENTO", "GOLPE", "QUEDA"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE QUE USA UMA BOLA PESADA E PINOS", options: ["BOLICHE", "GOLFE", "SINUCA", "BÉLGICA"], correct: 0 },
    { q: "QUANTOS PINOS EXISTEM NO BOLICHE TRADICIONAL", options: ["8", "10", "12", "15"], correct: 1 },
    { q: "QUAL ESPORTE É JOGADO SOBRE UM CAVALO COM UM TACO", options: ["POLO", "HÍPICA", "RODEIO", "SURF"], correct: 0 },
    { q: "COMO SE CHAMA O ESPORTE DE DAR SALTOS EM CAVALOS", options: ["POLO", "HIPISMO", "ADESTRAMENTO", "CORRIDA"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE DE GUSTAVO KUERTEN", options: ["FUTEBOL", "TÊNIS", "VÔLEI", "NATAÇÃO"], correct: 1 },
    { q: "QUANTOS JOGADORES TEM UM TIME DE VÔLEI EM QUADRA", options: ["5", "6", "7", "11"], correct: 1 },
    { q: "QUAL O NOME DO JOGADOR DE VÔLEI QUE É O 'LÍBERO'", options: ["O QUE ATACA", "O ESPECIALISTA EM DEFESA", "O QUE LEVANTA", "O CAPITÃO"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE DE TIGER WOODS", options: ["TÊNIS", "GOLFE", "F1", "BOXE"], correct: 1 },
    { q: "COMO SE CHAMA O ESPORTE DE DESCER MONTANHAS NA NEVE", options: ["SKATE", "ESQUI / SNOWBOARD", "SURF", "PATINAÇÃO"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE QUE SE JOGA COM UMA BOLA E UMA REDE ALTA", options: ["FUTEBOL", "VÔLEI", "BASQUETE", "HANDEBOL"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE DE MESA COM TACOS E BOLAS COLORIDAS", options: ["BOLICHE", "SINUCA / BILHAR", "PING-PONG", "XADREZ"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE DE HORTÊNCIA E MAGIC PAULA", options: ["VÔLEI", "BASQUETE", "NATAÇÃO", "TÊNIS"], correct: 1 },
    { q: "QUAL A DISTÂNCIA DE UM TIRO LIVRE NO BASQUETE", options: ["3 METROS", "4.6 METROS", "6 METROS", "7 METROS"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE QUE USA UM ARCO E UMA FLECHA", options: ["TIRO AO ALVO", "TIRO COM ARCO", "ESGRIMA", "LANÇA"], correct: 1 },
    { q: "COMO SE CHAMA O 'GOL' NO FUTEBOL AMERICANO", options: ["CESTA", "TOUCHDOWN", "PONTO", "HOME RUN"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE DE SERENA WILLIAMS", options: ["VÔLEI", "TÊNIS", "GOLFE", "NATAÇÃO"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE QUE SE PRATICA EM UM VELÓDROMO", options: ["CORRIDA", "CICLISMO", "PATINAÇÃO", "SKATE"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE QUE USA UMA BOLA E AS MÃOS PARA FAZER GOL", options: ["FUTEBOL", "HANDEBOL", "BASQUETE", "VÔLEI"], correct: 1 },
    { q: "QUAL O NOME DA COMPETIÇÃO DE CICLISMO MAIS FAMOSA DO MUNDO", options: ["GIRO D'ITALIA", "TOUR DE FRANCE", "VUELTA", "COPA DO MUNDO"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE QUE USA UMA PRANCHA NO MAR", options: ["SKATE", "SURF", "VELA", "REMO"], correct: 1 },
    { q: "QUAL PAÍS VENCEU A PRIMEIRA COPA DO MUNDO (1930)", options: ["BRASIL", "URUGUAI", "ARGENTINA", "ITÁLIA"], correct: 1 },
    { q: "QUEM É O MAIOR ARTILHEIRO DA HISTÓRIA DAS COPAS (MASC)", options: ["PELÉ", "RONALDO", "MIROSLAV KLOSE", "MESSI"], correct: 2 },
    { q: "QUAL PAÍS SEDIOU A COPA DE 2014", options: ["ALEMANHA", "ÁFRICA DO SUL", "BRASIL", "RÚSSIA"], correct: 2 },
    { q: "QUEM GANHOU A COPA DO MUNDO DE 2010", options: ["HOLANDA", "ESPANHA", "ALEMANHA", "BRASIL"], correct: 1 },
    { q: "QUAL O NOME DO JOGADOR ARGENTINO DA 'MÃO DE DEUS'", options: ["MESSI", "MARADONA", "AGÜERO", "KEMPES"], correct: 1 },
    { q: "QUANTOS GOLS O BRASIL SOFREU DA ALEMANHA EM 2014", options: ["5", "6", "7", "8"], correct: 2 },
    { q: "QUAL O NOME DA BOLA DA COPA DE 1970", options: ["BRAZUCA", "TELSTAR", "JABULANI", "AL RIHLA"], correct: 1 },
    { q: "QUAL PAÍS TEM 4 TÍTULOS DA COPA (ALÉM DA ALEMANHA)", options: ["ARGENTINA", "ITÁLIA", "FRANÇA", "URUGUAI"], correct: 1 },
    { q: "QUEM FOI O ARTILHEIRO DA COPA DE 2002", options: ["RIVALDO", "RONALDO FENÔMENO", "KLOSE", "ZIDANE"], correct: 1 },
    { q: "QUAL JOGADOR DEU UMA CABEÇADA NA FINAL DE 2006", options: ["RONALDINHO", "ZIDANE", "MATERAZZI", "FIGO"], correct: 1 },
    { q: "QUAL O NOME DO TROFÉU ENTREGUE AO CAMPEÃO DA COPA", options: ["TAÇA JULES RIMET", "TAÇA FIFA", "COPA OURO", "CANECO"], correct: 1 },
    { q: "QUEM É O ÚNICO JOGADOR TRICAMPEÃO MUNDIAL", options: ["MARADONA", "PELÉ", "CAFÚ", "ZICO"], correct: 1 },
    { q: "QUAL PAÍS VENCEU A COPA DE 2018", options: ["CROÁCIA", "FRANÇA", "BÉLGICA", "INGLATERRA"], correct: 1 },
    { q: "QUAL O NOME DA BOLA DA COPA DE 2010 (QUE DESVIAVA)", options: ["BRAZUCA", "JABULANI", "TELSTAR", "TEAMGEIST"], correct: 1 },
    { q: "QUAL SELEÇÃO É CONHECIDA COMO 'A LARANJA MECÂNICA'", options: ["ALEMANHA", "HOLANDA", "BÉLGICA", "ÁFRICA DO SUL"], correct: 1 },
    { q: "QUAL O ÚNICO PAÍS QUE PARTICIPOU DE TODAS AS COPAS", options: ["ALEMANHA", "BRASIL", "ITÁLIA", "ARGENTINA"], correct: 1 },
    { q: "QUEM FOI O GOLEIRO DO BRASIL NO PENTA (2002)", options: ["TAFFAREL", "MARCOS", "DIDA", "ROGÉRIO CENI"], correct: 1 },
    { q: "QUAL PAÍS VENCEU A COPA DO MUNDO DE 2022", options: ["FRANÇA", "ARGENTINA", "CROÁCIA", "MARROCOS"], correct: 1 },
    { q: "QUAL O NOME DO ESTÁDIO DA FINAL DA COPA DE 1950", options: ["PACAEMBU", "MARACANÃ", "SÃO JANUÁRIO", "CENTENÁRIO"], correct: 1 },
    { q: "QUAL JOGADOR BRASILEIRO É CONHECIDO COMO 'O GALINHO DE QUINTINO'", options: ["PELÉ", "ZICO", "GARRINCHA", "SOCRATES"], correct: 1 },
    { q: "QUAL A COR DA MEDALHA DO 2º COLOCADO", options: ["OURO", "PRATA", "BRONZE", "LATÃO"], correct: 1 },
    { q: "QUANTOS METROS TEM UMA PISCINA OLÍMPICA", options: ["25M", "50M", "100M", "75M"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE DE CÉSAR CIELO", options: ["ATLETISMO", "NATAÇÃO", "JUDÔ", "VELA"], correct: 1 },
    { q: "QUANTOS JOGADORES TEM UM TIME DE HANDEBOL EM QUADRA", options: ["5", "6", "7", "11"], correct: 2 },
    { q: "QUAL O NOME DO ESPORTE QUE USA UM TRAMPOLIM", options: ["GINÁSTICA DE TRAMPOLIM", "SALTO ORNAMENTAL", "PARKOUR", "CIRCO"], correct: 0 },
    { q: "QUEM É O MAIOR MEDALHISTA OLÍMPICO DO BRASIL (VELA)", options: ["ROBERT SCHEIDT", "TORBEN GRAEL", "MARTINE GRAEL", "AMBOS A E B"], correct: 3 },
    { q: "QUAL ESPORTE TEM AS PROVAS DE ARREMESSO DE PESO", options: ["HALTEROFILISMO", "ATLETISMO", "GINÁSTICA", "LUTAS"], correct: 1 },
    { q: "QUAL O NOME DA PROVA QUE UNE NATAÇÃO, CICLISMO E CORRIDA", options: ["PENTATLO", "TRIATLO", "DECATLO", "BIATLO"], correct: 1 },
    { q: "QUEM É A GINASTA COM MAIS MEDALHAS EM UMA ÚNICA EDIÇÃO (BRASIL)", options: ["DAIANE", "REBECA ANDRADE", "JADE", "FLÁVIA"], correct: 1 },
    { q: "QUAL A CIDADE QUE SEDIOU AS OLIMPÍADAS DE 2020 (EM 2021)", options: ["RIO", "TÓQUIO", "PARIS", "LONDRES"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE DE ÍTALO FERREIRA", options: ["SKATE", "SURF", "VELA", "NATAÇÃO"], correct: 1 },
    { q: "COMO SE CHAMA O LUGAR ONDE OCORREM AS LUTAS DE JUDÔ", options: ["RINGUE", "TATAME", "QUADRA", "ARENA"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE QUE USA UMA BOLA PEQUENA E UM TACO (GRAMA)", options: ["GOLFE", "HÓQUEI SOBRE GRAMA", "CRÍQUETE", "POLO"], correct: 1 },
    { q: "QUEM É O MAIOR VENCEDOR DE MEDALHAS NO ATLETISMO (BRASIL)", options: ["ADHEMAR FERREIRA DA SILVA", "JOAQUIM CRUZ", "VANDERLEI CORDEIRO", "THIAGO BRAZ"], correct: 0 },
    { q: "QUAL ESPORTE TEM A PROVA DE SALTO COM VARA", options: ["GINÁSTICA", "ATLETISMO", "SALTO ORNAMENTAL", "CIRCO"], correct: 1 },
    { q: "QUANTAS MEDALHAS TEM UM PÓDIO", options: ["1", "2", "3", "4"], correct: 2 },
    { q: "QUAL O NOME DO ESPORTE DE ARTHUR ZANETTI", options: ["NATAÇÃO", "GINÁSTICA (ARGOLAS)", "JUDÔ", "SALTO"], correct: 1 },
    { q: "ONDE SERÃO AS OLIMPÍADAS DE 2024", options: ["LONDRES", "PARIS", "LOS ANGELES", "BRISBANE"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE DE MARTA", options: ["BASQUETE", "FUTEBOL FEMININO", "VÔLEI", "TÊNIS"], correct: 1 },
    { q: "O QUE SIGNIFICA A SIGLA COI", options: ["COMITÊ OLÍMPICO INTERNACIONAL", "CENTRO OLÍMPICO INTEGRADO", "COMISSÃO DE OURO", "CLUB OLÍMPICO"], correct: 0 },
    { q: "QUAL O NOME DO ESPORTE DE ROGER FEDERER", options: ["GOLFE", "TÊNIS", "F1", "CRÍQUETE"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE DE LEWIS HAMILTON", options: ["MOTOGP", "FÓRMULA 1", "RALLY", "INDY"], correct: 1 },
    { q: "QUAL O NOME DA PONTUAÇÃO ZERO NO TÊNIS", options: ["ZERO", "LOVE", "NADA", "MISS"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE DE TIGER WOODS", options: ["TÊNIS", "GOLFE", "POLO", "BEISEBOL"], correct: 1 },
    { q: "QUAL O NOME DO JOGADOR QUE FAZ O 'LEVANTAMENTO' NO VÔLEI", options: ["ATACANTE", "LEVANTADOR", "LÍBERO", "PONTA"], correct: 1 },
    { q: "QUANTOS SETS TEM UMA PARTIDA DE VÔLEI (MÁXIMO)", options: ["3", "4", "5", "6"], correct: 2 },
    { q: "QUAL O NOME DO ESPORTE DE TONY HAWK", options: ["SURF", "SKATE", "SNOWBOARD", "MOTOCROSS"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE DE SHAQUILLE O'NEAL", options: ["FUTEBOL AMERICANO", "BASQUETE", "LUTA LIVRE", "VÔLEI"], correct: 1 },
    { q: "COMO SE CHAMA O 'GOL' NO BASQUETE", options: ["PONTO", "CESTA", "TOUCHDOWN", "HOME RUN"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE QUE SE JOGA COM UMA RAQUETE NA PAREDE", options: ["TÊNIS", "SQUASH", "PADEL", "PING-PONG"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE DE MICHAEL SCHUMACHER", options: ["F1", "MOTOGP", "INDY", "STOCK CAR"], correct: 0 },
    { q: "QUAL O NOME DO ESPORTE DE MIKE TYSON", options: ["BOXE", "MMA", "KARATÊ", "JUDÔ"], correct: 0 },
    { q: "QUAL O NOME DO ESPORTE DE GABRIEL MEDINA", options: ["SKATE", "SURF", "NATAÇÃO", "BODYBOARD"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE DE REBECA ANDRADE", options: ["BALÉ", "GINÁSTICA ARTÍSTICA", "ATLETISMO", "SALTOS"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE DE CRISTIANO RONALDO", options: ["BASQUETE", "FUTEBOL", "TÊNIS", "GOLFE"], correct: 1 },
    { q: "COMO SE CHAMA O EMPATE NO XADREZ", options: ["XEQUE", "AFOGAMENTO / TABAS", "MATE", "ROCK"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE DE RAFAEL NADAL", options: ["FUTEBOL", "TÊNIS", "NATAÇÃO", "RUGBY"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE DE TOM BRADY", options: ["BASQUETE", "FUTEBOL AMERICANO", "BEISEBOL", "HÓQUEI"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE DE USAIN BOLT", options: ["MARATONA", "ATLETISMO (VELOCIDADE)", "SALTOS", "REVEZAMENTO"], correct: 1 },
    { q: "COMO SE CHAMA A CORRIDA DE CAVALOS", options: ["HÍPICA", "TURFE", "POLO", "RODEIO"], correct: 1 },
    { q: "QUANTOS PONTOS VALE UM LANCE LIVRE NO BASQUETE", options: ["1", "2", "3", "NENHUM"], correct: 0 },
    { q: "QUAL O TIME DE BASQUETE DE STEPHEN CURRY", options: ["LAKERS", "WARRIORS", "BULLS", "CELTICS"], correct: 1 },
    { q: "QUAL O NOME DA POSIÇÃO QUE LANÇA A BOLA NO BEISEBOL", options: ["PITCHER (ARREMESSO)", "BATTER", "CATCHER", "SHORTSTOP"], correct: 0 },
    { q: "QUAL O TEMPO DE CADA QUARTO NA NBA", options: ["10 MINUTOS", "12 MINUTOS", "15 MINUTOS", "20 MINUTOS"], correct: 1 },
    { q: "COMO SE CHAMA O ATO DE ENTERRAR A BOLA NO BASQUETE", options: ["LAYOUT", "DUNK (ENTERRADA)", "ASSISTÊNCIA", "TOCO"], correct: 1 },
    { q: "QUAL O TIME COM MAIS TÍTULOS NA HISTÓRIA DA NBA", options: ["BULLS", "LAKERS/CELTICS", "WARRIORS", "SPURS"], correct: 1 },
    { q: "QUAL O NOME DO JOGADOR DE BASQUETE CHAMADO 'KING'", options: ["JORDAN", "LEBRON JAMES", "KOBE", "SHAQ"], correct: 1 },
    { q: "QUAL ESPORTE TEM A POSIÇÃO DE 'QUARTERBACK'", options: ["RUGBY", "FUTEBOL AMERICANO", "BEISEBOL", "CRÍQUETE"], correct: 1 },
    { q: "QUANTAS BASES EXISTEM NO CAMPO DE BEISEBOL", options: ["2", "3", "4", "5"], correct: 2 },
    { q: "QUAL O NOME DO ESPORTE QUE USA UM 'STICK' E UMA BOLA NO GELO", options: ["CURLING", "HÓQUEI NO GELO", "PATINAÇÃO", "SLEDGE"], correct: 1 },
    { q: "QUAL O NOME DO TROFÉU DO CAMPEÃO DA NFL", options: ["OSCAR", "VINCE LOMBARDI", "STANLEY CUP", "WORLD CUP"], correct: 1 },
    { q: "COMO SE CHAMA O EMPATE NO BEISEBOL", options: ["NÃO EXISTE (EXTRA INNINGS)", "DRAW", "TIE", "ZERO"], correct: 0 },
    { q: "QUAL O NOME DO ESPORTE DE SHAUN WHITE", options: ["SKATE", "SNOWBOARD", "SURF", "BMX"], correct: 1 },
    { q: "QUAL O NOME DO TIME DE BASQUETE DE MIAMI", options: ["LAKERS", "HEAT", "MAGIC", "SUNS"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE QUE USA UM DISCO DE BORRACHA", options: ["DISCO", "HÓQUEI", "FRISBEE", "GOLFE"], correct: 1 },
    { q: "QUAL A PONTUAÇÃO DE UM 'FIELD GOAL' NO FUTEBOL AMERICANO", options: ["1", "3", "6", "2"], correct: 1 },
    { q: "QUEM É O JOGADOR DE BASQUETE CHAMADO 'BLACK MAMBA'", options: ["JORDAN", "KOBE BRYANT", "LEBRON", "CURRY"], correct: 1 },
    { q: "QUAL O NOME DA LIGA DE BEISEBOL DOS EUA", options: ["NFL", "MLB", "NBA", "NHL"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE QUE SE JOGA COM UMA BOLA OVAL E SEM PROTEÇÃO", options: ["FUTEBOL AMERICANO", "RUGBY", "HANDEBOL", "POLO"], correct: 1 },
    { q: "COMO SE CHAMA O 'BOLA AO ALTO' NO INÍCIO DO BASQUETE", options: ["KICKOFF", "JUMP BALL", "START", "TIP-OFF"], correct: 1 },
    { q: "QUAL O TORNEIO DE TÊNIS MAIS ANTIGO DO MUNDO", options: ["ROLAND GARROS", "WIMBLEDON", "US OPEN", "AUSTRALIAN OPEN"], correct: 1 },
    { q: "QUAL O PISO DO TORNEIO DE ROLAND GARROS", options: ["GRAMA", "SAIBRO (TERRA BATIDA)", "DURO", "CARPETE"], correct: 1 },
    { q: "QUEM É O 'REI DO SAIBRO' NO TÊNIS", options: ["FEDERER", "RAFAEL NADAL", "DJOKOVIC", "MURRAY"], correct: 1 },
    { q: "QUANTOS SETS SÃO NECESSÁRIOS PARA VENCER NO TÊNIS MASCULINO (GRAND SLAM)", options: ["2", "3", "4", "5"], correct: 1 },
    { q: "QUAL O NOME DO PONTO QUE VENCE A PARTIDA NO TÊNIS", options: ["SET POINT", "MATCH POINT", "GAME POINT", "BREAK POINT"], correct: 1 },
    { q: "QUAL O NOME DA MANOBRA DE SAQUE NO TÊNIS", options: ["KICK", "SERVIÇO", "THROW", "LOB"], correct: 1 },
    { q: "QUEM FOI A MAIOR TENISTA BRASILEIRA (19 GRAND SLAMS)", options: ["MARIA ESTHER BUENO", "BEATRIZ HADDAD", "TELIANA PEREIRA", "PAULA GONÇALVES"], correct: 0 },
    { q: "COMO SE CHAMA O PONTO MARCADO DIRETAMENTE NO SAQUE", options: ["LOB", "ACE", "SMASH", "SLICE"], correct: 1 },
    { q: "QUAL O NOME DA RAQUETE MENOR USADA EM MESAS", options: ["RAQUETE DE TÊNIS", "RAQUETE DE PING-PONG", "TACO", "PALETA"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE QUE USA UMA PETECA", options: ["SQUASH", "BADMINTON", "TENIS DE MESA", "VÔLEI"], correct: 1 },
    { q: "QUAL O NOME DO 'EMPATE' EM 40-40 NO TÊNIS", options: ["TIE", "DEUCE (IGUAIS)", "ADVANTAGE", "ALL"], correct: 1 },
    { q: "QUAL O NOME DO GOLPE DE CIMA PARA BAIXO NO TÊNIS", options: ["LOB", "SMASH", "SLICE", "DRIVE"], correct: 1 },
    { q: "QUAL O NOME DO TORNEIO DE TÊNIS QUE OCORRE NA AUSTRÁLIA", options: ["US OPEN", "AUSTRALIAN OPEN", "ROLAND GARROS", "WIMBLEDON"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE DE MESA QUE VIROU OLÍMPICO", options: ["PEBOLIM", "TÊNIS DE MESA", "SINUCA", "BOTÃO"], correct: 1 },
    { q: "QUAL O NOME DO GOLPE COM A PARTE DE TRÁS DA MÃO NO TÊNIS", options: ["FOREHAND", "BACKHAND", "SLICE", "TOP SPIN"], correct: 1 },
    { q: "QUAL O NOME DA REDE NO TÊNIS DE MESA", options: ["DIVISÓRIA", "REDE", "GRADE", "FILTRO"], correct: 1 },
    { q: "COMO SE CHAMA O ERRO NO SAQUE NO TÊNIS", options: ["MISS", "FALTA", "OUT", "FAULT"], correct: 3 },
    { q: "QUAL O NOME DO ESPORTE DE 'GUGA'", options: ["FUTEBOL", "TÊNIS", "VÔLEI", "SURF"], correct: 1 },
    { q: "QUAL O NOME DO TORNEIO QUE REÚNE OS MELHORES DO ANO NO TÊNIS", options: ["GRAND SLAM", "ATP FINALS", "MASTERS 1000", "COPA DAVIS"], correct: 1 },
    { q: "QUANTOS GRAND SLAMS EXISTEM POR ANO", options: ["2", "3", "4", "5"], correct: 2 },
    { q: "QUAL O LUGAR ONDE OCORRE O BOXE", options: ["CAMPO", "RINGUE", "TATAME", "OCTÓGONO"], correct: 1 },
    { q: "QUAL A LUTA QUE USA APENAS OS PUNHOS", options: ["KARATÊ", "BOXE", "JUDÔ", "MUAY THAI"], correct: 1 },
    { q: "COMO SE CHAMA A VITÓRIA POR DESMAIO NA LUTA", options: ["PONTO", "NOCAUTE (KO)", "QUEDA", "FALTA"], correct: 1 },
    { q: "QUAL O NOME DA VESTIMENTA DAS LUTAS ORIENTAIS", options: ["UNIFORME", "QUIMONO", "TOGA", "CAPA"], correct: 1 },
    { q: "QUAL A COR DA FAIXA DO MESTRE NO JUDÔ", options: ["BRANCA", "PRETA (OU CORAL/VERMELHA)", "VERDE", "AMARELA"], correct: 1 },
    { q: "QUAL A LUTA QUE SIGNIFICA 'CAMINHO DA SUAVIDADE'", options: ["AIKIDO", "JUDÔ", "KARATÊ", "SUMÔ"], correct: 1 },
    { q: "QUAL A LUTA QUE SE PRATICA EM UM CÍRCULO", options: ["BOXE", "SUMÔ", "JIU-JITSU", "MMA"], correct: 1 },
    { q: "COMO SE CHAMA O ÁRBITRO NO BOXE", options: ["JUIZ", "ÁRBITRO", "MESTRE", "CAPITÃO"], correct: 1 },
    { q: "QUAL A LUTA QUE USA CHUTES E SOCOS (COREANA)", options: ["JUDÔ", "TAEKWONDO", "SUMÔ", "JIU-JITSU"], correct: 1 },
    { q: "QUAL O NOME DA LUTA QUE ENVOLVE 'GRAPPLING'", options: ["BOXE", "WRESTLING (LUTA LIVRE)", "KUNG FU", "KARATÊ"], correct: 1 },
    { q: "QUAL O NOME DO LUGAR ONDE OCORRE O MMA", options: ["RINGUE", "OCTÓGONO", "TATAME", "QUADRA"], correct: 1 },
    { q: "QUEM É O FUNDADOR DO JIU-JITSU BRASILEIRO (FAMÍLIA)", options: ["SILVA", "GRACIE", "MACHADO", "NOGUEIRA"], correct: 1 },
    { q: "QUAL O NOME DO GOLPE DE PERNA NO KARATÊ", options: ["SOCO", "CHUTE", "QUEDA", "PEGADA"], correct: 1 },
    { q: "QUAL LUTA TEM O GOLPE 'MATA-LEÃO'", options: ["BOXE", "JIU-JITSU", "KARATÊ", "SUMÔ"], correct: 1 },
    { q: "QUAL A LUTA NACIONAL DO JAPÃO", options: ["KUNG FU", "SUMÔ", "TAEKWONDO", "MUAY THAI"], correct: 1 },
    { q: "QUAL LUTA USA LUVAS GRANDES E PROTETOR BUCAL", options: ["JUDÔ", "BOXE", "CAPOEIRA", "SUMÔ"], correct: 1 },
    { q: "QUAL A LUTA QUE NÃO PODE USAR AS MÃOS", options: ["BOXE", "TAEKWONDO (FOCO CHUTES)", "KICKBOXING", "NENHUMA"], correct: 1 },
    { q: "COMO SE CHAMA O 'GRITO' NAS ARTES MARCIAIS", options: ["KIAI", "GOLPE", "SOM", "START"], correct: 0 },
    { q: "QUAL A LUTA QUE USA O 'TRIDENTE' SAI", options: ["BOXE", "KARATÊ (ARMAS)", "JUDÔ", "SUMÔ"], correct: 1 },
    { q: "QUAL LUTA TEM 'ROUND' DE 3 OU 5 MINUTOS", options: ["FUTEBOL", "BOXE/MMA", "TÊNIS", "GOLFE"], correct: 1 },
    { q: "QUAL O TIME COM MAIS TÍTULOS DA CHAMPIONS LEAGUE", options: ["BARCELONA", "REAL MADRID", "MILAN", "LIVERPOOL"], correct: 1 },
    { q: "EM QUAL PAÍS FICA O TIME DO BAYERN DE MUNIQUE", options: ["ÁUSTRIA", "ALEMANHA", "SUÍÇA", "BÉLGICA"], correct: 1 },
    { q: "QUAL O NOME DO ESTÁDIO DO BARCELONA", options: ["SANTIAGO BERNABÉU", "CAMP NOU", "ANFIELD", "ESTÁDIO DA LUZ"], correct: 1 },
    { q: "QUEM É O JOGADOR COM MAIS BOLAS DE OURO (RECORDE)", options: ["CRISTIANO RONALDO", "MESSI", "RONALDINHO", "ZIDANE"], correct: 1 },
    { q: "QUAL TIME INGLÊS É CONHECIDO COMO 'THE REDS'", options: ["MANCHESTER UNITED", "LIVERPOOL", "ARSENAL", "CHELSEA"], correct: 1 },
    { q: "QUAL O NOME DA LIGA DE FUTEBOL DA ESPANHA", options: ["PREMIER LEAGUE", "LA LIGA", "SERIE A", "BUNDESLIGA"], correct: 1 },
    { q: "EM QUAL TIME CRISTIANO RONALDO SE TORNOU ÍDOLO NA INGLATERRA", options: ["CHELSEA", "MANCHESTER UNITED", "CITY", "TOTTENHAM"], correct: 1 },
    { q: "QUAL O NOME DO ESTÁDIO DO REAL MADRID", options: ["CAMP NOU", "SANTIAGO BERNABÉU", "MESTALLA", "SAN MAMÉS"], correct: 1 },
    { q: "QUAL TIME BRASILEIRO É CONHECIDO COMO 'O CLUBE DA FÉ'", options: ["SANTOS", "SÃO PAULO", "PALMEIRAS", "CORINTHIANS"], correct: 1 },
    { q: "QUEM É O MAIOR ARTILHEIRO DA HISTÓRIA DO FLAMENGO", options: ["NEYMAR", "ZICO", "GABIGOL", "ROMÁRIO"], correct: 1 },
    { q: "QUAL TIME VENCEU A LIBERTADORES DE 2019", options: ["RIVER PLATE", "FLAMENGO", "PALMEIRAS", "GREMIO"], correct: 1 },
    { q: "COMO SE CHAMA O CLÁSSICO ENTRE REAL MADRID E BARCELONA", options: ["DERBY", "EL CLÁSICO", "SUPERCLÁSICO", "THE GAME"], correct: 1 },
    { q: "QUAL O NOME DA LIGA DE FUTEBOL DA ITÁLIA", options: ["LIGUE 1", "SERIE A", "PREMIER", "EREDIVISIE"], correct: 1 },
    { q: "QUEM É O 'DONO' DO TIME DO INTER MIAMI", options: ["RONALDO", "DAVID BECKHAM", "MESSI", "ZIDANE"], correct: 1 },
    { q: "QUAL O TIME DE CORAÇÃO DO JOGADOR NEYMAR (REVELADO)", options: ["FLAMENGO", "SANTOS", "SÃO PAULO", "PALMEIRAS"], correct: 1 },
    { q: "QUAL TIME É O 'MAIOR CAMPEÃO' DA PREMIER LEAGUE", options: ["LIVERPOOL", "MANCHESTER UNITED", "CHELSEA", "CITY"], correct: 1 },
    { q: "QUAL O NOME DA LIGA DE FUTEBOL DOS ESTADOS UNIDOS", options: ["NFL", "MLS", "NBA", "NHL"], correct: 1 },
    { q: "QUAL TIME PORTUGUÊS TEM UM DRAGÃO NO ESCUDO", options: ["BENFICA", "PORTO", "SPORTING", "BRAGA"], correct: 1 },
    { q: "QUEM É O TREINADOR MAIOR VENCEDOR DA PREMIER LEAGUE", options: ["GUARDIOLA", "SIR ALEX FERGUSON", "MOURINHO", "KLOPP"], correct: 1 },
    { q: "QUAL O NOME DO TROFÉU DA CHAMPIONS LEAGUE", options: ["TAÇA FIFA", "ORELHUDA", "CANECO", "TAÇA OURO"], correct: 1 },
    { q: "QUAL O NOME DA MANOBRA DE DEFESA COM OS BRAÇOS JUNTOS", options: ["ATAQUE", "MANCHETE", "TOQUE", "SAQUE"], correct: 1 },
    { q: "QUANTOS TOQUES UM TIME PODE DAR NA BOLA NO VÔLEI", options: ["1", "2", "3", "4"], correct: 2 },
    { q: "COMO SE CHAMA O PONTO MARCADO NO CHÃO DO ADVERSÁRIO", options: ["GOL", "PONTO", "CESTA", "ACERTO"], correct: 1 },
    { q: "QUAL O NOME DO TREINADOR MAIS VITORIOSO DO VÔLEI BRASILEIRO", options: ["ZÉ ROBERTO", "BERNARDINHO", "RENAN", "DORIVAL"], correct: 1 },
    { q: "QUAL A POSIÇÃO DO JOGADOR QUE FICA NO MEIO DA REDE", options: ["LEVANTADOR", "CENTRAL", "LÍBERO", "PONTA"], correct: 1 },
    { q: "NO HANDEBOL, QUANTOS PASSOS O JOGADOR PODE DAR SEM QUICAR", options: ["1", "2", "3", "4"], correct: 2 },
    { q: "QUAL O NOME DO SAQUE QUE A BOLA CAI RÁPIDO NO VÔLEI", options: ["VIAGEM", "JORNADA NAS ESTRELAS", "POR CIMA", "BALANCEADO"], correct: 0 },
    { q: "COMO SE CHAMA O BLOQUEIO DE DOIS JOGADORES NO VÔLEI", options: ["SIMPLES", "DUPLO", "TRIPLO", "MURALHA"], correct: 1 },
    { q: "QUAL A DURAÇÃO DE UM SET NO VÔLEI (ATÉ QUANTOS PONTOS)", options: ["15", "21", "25", "30"], correct: 2 },
    { q: "NO HANDEBOL, QUAL JOGADOR PODE ENTRAR NA ÁREA", options: ["TODOS", "SÓ O GOLEIRO", "O PIVÔ", "O ARMADOR"], correct: 1 },
    { q: "QUAL O NOME DA JOGADA ONDE O LEVANTADOR JOGA A BOLA BAIXA", options: ["TEMPO", "CHINA", "EXPLORAÇÃO", "PIPE"], correct: 1 },
    { q: "QUEM É A MAIOR JOGADORA DE VÔLEI DO BRASIL (LANCE)", options: ["SHEILLA", "FABIANA", "FÊ GARAY", "SERGINHO (MASC)"], correct: 0 },
    { q: "QUAL O NOME DO CARTÃO QUE EXPULSA NO VÔLEI", options: ["AMARELO", "VERMELHO", "AZUL", "PRETO"], correct: 1 },
    { q: "NO VÔLEI, A BOLA QUE BATE NA LINHA É...", options: ["DENTRO", "FORA", "VOLTA", "FALTA"], correct: 0 },
    { q: "QUAL O NOME DA POSIÇÃO QUE ATACA PELO FUNDO NO VÔLEI", options: ["OPOSTO", "LÍBERO", "CENTRAL", "SAQUE"], correct: 0 },
    { q: "COMO SE CHAMA O ATO DE IMPEDIR O ATAQUE NA REDE", options: ["ATAQUE", "BLOQUEIO", "MANCHETE", "DEFESA"], correct: 1 },
    { q: "QUAL A COR DA CAMISA DO LÍBERO", options: ["IGUAL AO TIME", "DIFERENTE DO TIME", "BRANCA", "VERMELHA"], correct: 1 },
    { q: "QUANTOS SEGUNDOS O JOGADOR DE HANDEBOL PODE SEGURAR A BOLA", options: ["3 SEG", "5 SEG", "10 SEG", "ILIMITADO"], correct: 0 },
    { q: "QUAL O NOME DO JOGO DE VÔLEI NA AREIA", options: ["VÔLEI DE QUADRA", "VÔLEI DE PRAIA", "FUTEVÔLEI", "BIRIBOL"], correct: 1 },
    { q: "COMO SE CHAMA O 'TIE-BREAK' NO VÔLEI (PONTOS)", options: ["10 PONTOS", "15 PONTOS", "25 PONTOS", "5 PONTOS"], correct: 1 },
    { q: "QUAL O ESTILO DE NATAÇÃO MAIS RÁPIDO", options: ["PEITO", "COSTAS", "BORBOLETA", "CRAWL (LIVRE)"], correct: 3 },
    { q: "QUANTOS ESTILOS DE NATAÇÃO EXISTEM OFICIALMENTE", options: ["2", "3", "4", "5"], correct: 2 },
    { q: "COMO SE CHAMA A VIRADA NA PAREDE DA PISCINA", options: ["PULO", "VIRADA OLÍMPICA", "SALTO", "RETORNO"], correct: 1 },
    { q: "QUAL O NOME DO NADADOR BRASILEIRO QUE GANHOU OURO EM PEQUIM", options: ["XUXA", "CESAR CIELO", "GUSTAVO BORGES", "THIAGO PEREIRA"], correct: 1 },
    { q: "QUAL O ESTILO ONDE O NADADOR FICA DE BARRIGA PARA CIMA", options: ["CRAWL", "COSTAS", "PEITO", "MEDLEY"], correct: 1 },
    { q: "COMO SE CHAMA A PROVA QUE REÚNE OS 4 ESTILOS", options: ["REVEZAMENTO", "MEDLEY", "MARATONA", "SÉRIE"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE DE SALTAR DE PLATAFORMAS NA ÁGUA", options: ["POLO AQUÁTICO", "SALTOS ORNAMENTAIS", "NADO", "SURF"], correct: 1 },
    { q: "QUANTOS METROS TEM UMA PISCINA SEMI-OLÍMPICA", options: ["25M", "50M", "10M", "100M"], correct: 0 },
    { q: "COMO SE CHAMA O ÓCULOS USADO NA NATAÇÃO", options: ["MÁSCARA", "GOGGLES", "LENTES", "PROTETOR"], correct: 1 },
    { q: "QUAL O ESTILO CONHECIDO POR PARECER UM SAPO", options: ["CRAWL", "PEITO", "BORBOLETA", "COSTAS"], correct: 1 },
    { q: "QUANTOS NADADORES TEM UM REVEZAMENTO", options: ["2", "3", "4", "5"], correct: 2 },
    { q: "QUAL O NOME DA TOUCA USADA PARA NADAR", options: ["CHAPÉU", "TOUCA DE NATAÇÃO", "CAPA", "PROTETOR"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE QUE É O 'BALÉ NA ÁGUA'", options: ["SALTOS", "NADO ARTÍSTICO (SINCRONIZADO)", "POLO", "HIDRO"], correct: 1 },
    { q: "COMO SE CHAMA A PRANCHA USADA PARA TREINAR PERNAS", options: ["BÓIA", "PRANCHETA", "FLUTUADOR", "NADADEIRA"], correct: 1 },
    { q: "QUEM É A MAIOR NADADORA BRASILEIRA (MARATONA AQUÁTICA)", options: ["ETIENE MEDEIROS", "ANA MARCELA CUNHA", "JOANNA MARANHÃO", "POLIANA OKIMOTO"], correct: 1 },
    { q: "QUAL O NOME DO APARELHO QUE MARCA O TEMPO NA NATAÇÃO", options: ["RELÓGIO", "PLACAR ELETRÔNICO", "CRONÔMETRO DE MÃO", "START"], correct: 1 },
    { q: "QUAL O NOME DA DISTÂNCIA MAIS LONGA NA PISCINA (OLÍMPICA)", options: ["400M", "800M", "1500M", "5000M"], correct: 2 },
    { q: "COMO SE CHAMA O BLOCO ONDE O NADADOR COMEÇA", options: ["CAIXA", "BLOCO DE PARTIDA", "PRANCHA", "BASE"], correct: 1 },
    { q: "QUAL O ESTILO MAIS DIFÍCIL E CANSATIVO", options: ["CRAWL", "BORBOLETA", "PEITO", "COSTAS"], correct: 1 },
    { q: "O QUE SIGNIFICA 'ÁGUAS ABERTAS'", options: ["PISCINA", "MAR, LAGOS OU RIOS", "HIDRO", "SALTO"], correct: 1 },
    { q: "QUAL A LUTA QUE SIGNIFICA 'CAMINHO DAS MÃOS VAZIAS'", options: ["JUDÔ", "KARATÊ", "KUNG FU", "TAEKWONDO"], correct: 1 },
    { q: "QUAL A LUTA QUE USA CHUTES, SOCOS, COTOVELOS E JOELHOS", options: ["BOXE", "MUAY THAI", "KARATÊ", "JIU-JITSU"], correct: 1 },
    { q: "QUEM É CONSIDERADO O PAI DO JIU-JITSU BRASILEIRO", options: ["HÉLIO GRACIE", "ANDERSON SILVA", "VITOR BELFORT", "JOSÉ ALDO"], correct: 0 },
    { q: "COMO SE CHAMA O LUGAR ONDE OCORRE O MMA (UFC)", options: ["RINGUE", "OCTÓGONO", "QUADRA", "ARENA"], correct: 1 },
    { q: "QUAL A LUTA QUE USA UMA GRADE PARA CERCAR OS LUTADORES", options: ["BOXE", "MMA", "SUMÔ", "WRESTLING"], correct: 1 },
    { q: "QUAL A LUTA QUE É O ESPORTE NACIONAL DO JAPÃO", options: ["JUDÔ", "SUMÔ", "KARATÊ", "AIKIDO"], correct: 1 },
    { q: "COMO SE CHAMA O GRITO DADO NO IMPACTO DO GOLPE", options: ["KIAI", "SHOUT", "YELL", "Kiai-do"], correct: 0 },
    { q: "QUAL A LUTA QUE FOI CRIADA POR BRUCE LEE", options: ["KUNG FU", "JEET KUNE DO", "KARATÊ", "WING CHUN"], correct: 1 },
    { q: "QUAL A COR DA FAIXA MAIS ALTA NO KARATÊ (MESTRE)", options: ["BRANCA", "PRETA", "VERMELHA", "AZUL"], correct: 1 },
    { q: "QUAL A LUTA QUE USA LUVAS DE 10 OU 12 ONÇAS", options: ["MMA", "BOXE", "JUDÔ", "KARATÊ"], correct: 1 },
    { q: "COMO SE CHAMA A VITÓRIA QUANDO O ADVERSÁRIO DESISTE", options: ["NOCAUTE", "FINALIZAÇÃO (SUBMISSÃO)", "PONTOS", "EMPATE"], correct: 1 },
    { q: "QUAL A LUTA QUE SE ORIGINOU NA CHINA", options: ["KARATÊ", "KUNG FU", "JUDÔ", "TAEKWONDO"], correct: 1 },
    { q: "QUAL A LUTA QUE USA O 'DOJO' COMO LOCAL DE TREINO", options: ["BOXE", "ARTES MARCIAIS JAPONESAS", "WRESTLING", "FENCING"], correct: 1 },
    { q: "QUAL A LUTA QUE É CONHECIDA COMO 'A ARTE DAS 8 ARMAS'", options: ["BOXE", "MUAY THAI", "CAPOEIRA", "KRAV MAGA"], correct: 1 },
    { q: "COMO SE CHAMA A LUTA QUE SIMULA UMA DANÇA COM MÚSICA", options: ["BALÉ", "CAPOEIRA", "SAMBA", "JUDÔ"], correct: 1 },
    { q: "QUAL A LUTA QUE USA O 'IPPON' COMO PONTO MÁXIMO", options: ["BOXE", "JUDÔ", "MMA", "SUMÔ"], correct: 1 },
    { q: "QUEM É A MAIOR LENDA DO BOXE PESO PESADO (ANOS 70)", options: ["MIKE TYSON", "MUHAMMAD ALI", "ROCKY MARCIANO", "GEORGE FOREMAN"], correct: 1 },
    { q: "QUAL A LUTA QUE USA UM 'CINTURÃO' COMO PRÊMIO", options: ["FUTEBOL", "BOXE / MMA", "TÊNIS", "GOLFE"], correct: 1 },
    { q: "QUAL A LUTA QUE USA CHUTES MUITO ALTOS (OLÍMPICA)", options: ["JUDÔ", "TAEKWONDO", "BOXE", "JIU-JITSU"], correct: 1 },
    { q: "COMO SE CHAMA O INSTRUMENTO TOCADO NA CAPOEIRA", options: ["TAMBOR", "BERIMBAU", "VIOLÃO", "FLAUTA"], correct: 1 },
    { q: "QUAL ESPORTE USA UM ARCO E UMA FLECHA", options: ["TIRO AO ALVO", "TIRO COM ARCO", "ESGRIMA", "LANÇA"], correct: 1 },
    { q: "QUAL O NOME DO ALVO NO TIRO COM ARCO", options: ["PLACAR", "ESCUDO", "BULLSEYE (CENTRO)", "PONTO"], correct: 2 },
    { q: "QUAL ESPORTE USA AS ARMAS FLORETE E ESPADA", options: ["BOXE", "ESGRIMA", "LUTAS", "TIRO"], correct: 1 },
    { q: "COMO SE CHAMA O 'GOLPE' QUE MARCA PONTO NA ESGRIMA", options: ["TIRO", "TOQUE", "CORTE", "FURO"], correct: 1 },
    { q: "QUAL ESPORTE USA UM PRATO DE ARGILA COMO ALVO", options: ["TIRO COM ARCO", "TIRO ESPORTIVO (PRATO)", "DARDOS", "BOLA"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE DE DESCER RIOS EM BOTES", options: ["SURF", "RAFTING", "NATAÇÃO", "MERGULHO"], correct: 1 },
    { q: "QUAL ESPORTE USA UMA BOLA DE COURO E UM TACO (POLO)", options: ["HÍPICA", "POLO A CAVALO", "RODEIO", "SALTO"], correct: 1 },
    { q: "COMO SE CHAMA O ESPORTE DE ESCALAR MONTANHAS", options: ["TREKKING", "ALPINISMO / ESCALADA", "RAPEL", "SURF"], correct: 1 },
    { q: "QUAL ESPORTE USA UM CAVALO E OBSTÁCULOS", options: ["POLO", "HIPISMO (SALTOS)", "TURFE", "ADESTRAMENTO"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE QUE USA UM BARCO A VELA", options: ["REMO", "IATISMO (VELA)", "CANOAGEM", "SURF"], correct: 1 },
    { q: "QUAL ESPORTE USA UM PAR DE REMOS EM UM BARCO FINO", options: ["VELA", "REMO", "CANOAGEM", "RAFTING"], correct: 1 },
    { q: "QUAL O NOME DA COMPETIÇÃO DE CICLISMO DE ESTRADA", options: ["BMX", "CICLISMO DE ESTRADA", "MOUNTAIN BIKE", "DOWNHILL"], correct: 1 },
    { q: "QUAL ESPORTE USA UMA PRANCHA E UMA VELA PEQUENA", options: ["SURF", "WIND SURF", "SKATE", "VELA"], correct: 1 },
    { q: "COMO SE CHAMA O ESPORTE DE SALTAR DE PARAQUEDAS", options: ["ASA DELTA", "PARAQUEDISMO", "BUNGEE JUMP", "VOO LIVRE"], correct: 1 },
    { q: "QUAL ESPORTE USA UMA BOLA E UMA RAQUETE NA PAREDE", options: ["TÊNIS", "SQUASH", "PADEL", "PING-PONG"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE QUE USA UM DISCO PESADO", options: ["ARREMESSO DE PESO", "LANÇAMENTO DE DISCO", "DARDO", "MARTELO"], correct: 1 },
    { q: "QUAL ESPORTE USA UM CABO COMPRIDO COM UMA BOLA", options: ["DISCO", "MARTELO (ATLETISMO)", "PESO", "DARDO"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE DE SALTAR EM UMA CAIXA DE AREIA", options: ["SALTO EM ALTURA", "SALTO EM DISTÂNCIA", "SALTO COM VARA", "TRIPLO"], correct: 1 },
    { q: "QUAL ESPORTE USA UMA VARA PARA SALTAR ALTO", options: ["SALTO TRIPLO", "SALTO COM VARA", "SALTO EM DISTÂNCIA", "GINÁSTICA"], correct: 1 },
    { q: "COMO SE CHAMA A PROVA DE 10 MODALIDADES NO ATLETISMO", options: ["PENTATLO", "DECATLO", "TRIATLO", "MARATONA"], correct: 1 },
    { q: "O QUE SIGNIFICA 'ACE' NO TÊNIS OU VÔLEI", options: ["FALTA", "PONTO DIRETO NO SAQUE", "ERRO", "BLOQUEIO"], correct: 1 },
    { q: "O QUE É UM 'HAT-TRICK' NO FUTEBOL", options: ["3 FALTAS", "3 GOLS NO MESMO JOGO", "3 CARTÕES", "3 SUBSTITUIÇÕES"], correct: 1 },
    { q: "O QUE É O 'DOPING' NO ESPORTE", options: ["TREINAMENTO", "USO DE SUBSTÂNCIAS PROIBIDAS", "DIETA", "DESCANSO"], correct: 1 },
    { q: "O QUE É UM 'DOUBLE-DOUBLE' NO BASQUETE", options: ["DOIS GOLS", "DOIS DÍGITOS EM DUAS ESTATÍSTICAS", "DOIS TURNOS", "DUAS FALTAS"], correct: 1 },
    { q: "O QUE SIGNIFICA 'W.O.'", options: ["VITÓRIA POR DESISTÊNCIA/AUSÊNCIA", "EMPATE", "DERROTA", "REPETIÇÃO"], correct: 0 },
    { q: "O QUE É UM 'HOME RUN' NO BEISEBOL", options: ["CORRER TODAS AS BASES", "SAIR DO CAMPO", "PERDER A BOLA", "FALTA"], correct: 0 },
    { q: "O QUE É O 'VAR' NO FUTEBOL", options: ["ÁRBITRO DE VÍDEO", "TÉCNICO", "BOLA", "ESTÁDIO"], correct: 0 },
    { q: "O QUE É UM 'BIRDIE' NO GOLFE", options: ["UM PONTO RUIM", "UM ABAIXO DO PAR", "UMA FALTA", "UM PÁSSARO"], correct: 1 },
    { q: "O QUE SIGNIFICA 'KO' NAS LUTAS", options: ["KEEP OUT", "KNOCKOUT (NOCAUTE)", "KICK OUT", "KNOCKDOWN"], correct: 1 },
    { q: "O QUE É O 'PÓDIO'", options: ["LUGAR DO JUIZ", "LUGAR DOS VENCEDORES", "ENTRADA", "VESTIÁRIO"], correct: 1 },
    { q: "O QUE É UMA 'ZEBRA' NO ESPORTE", options: ["UM ANIMAL", "UM RESULTADO INESPERADO", "UM UNIFORME", "UM JUIZ"], correct: 1 },
    { q: "O QUE SIGNIFICA 'RECORDE MUNDIAL'", options: ["MELHOR MARCA DA HISTÓRIA", "UMA MARCA ANTIGA", "UM PRÊMIO", "UM TREINO"], correct: 0 },
    { q: "O QUE É UM 'PLAYOFF'", options: ["JOGO DE TREINO", "FASE ELIMINATÓRIA (MATA-MATA)", "FINAL", "INÍCIO"], correct: 1 },
    { q: "O QUE É O 'DRAFT' NOS ESPORTES AMERICANOS", options: ["SISTEMA DE ESCOLHA DE NOVOS JOGADORES", "UM JOGO", "UM TREINO", "UM CONTRATO"], correct: 0 },
    { q: "O QUE É O 'QUARTERBACK'", options: ["UM JUIZ", "O LANÇADOR NO FUTEBOL AMERICANO", "UM DEFENSOR", "UM GOLEIRO"], correct: 1 },
    { q: "O QUE É O 'LÍBERO' NO VÔLEI", options: ["O ATACANTE", "O ESPECIALISTA EM DEFESA", "O CAPITÃO", "O RESERVA"], correct: 1 },
    { q: "O QUE É O 'GRIP' NO TÊNIS OU F1", options: ["SAPATO", "ADERÊNCIA", "FORÇA", "VELOCIDADE"], correct: 1 },
    { q: "O QUE É UM 'GRAND SLAM' NO TÊNIS", options: ["UM JOGO", "OS 4 MAIORES TORNEIOS DO ANO", "UM GOLPE", "UM TREINO"], correct: 1 },
    { q: "O QUE É O 'CHECKMATE' NO XADREZ", options: ["FIM DO JOGO (VITÓRIA)", "AVISO", "PERDA", "EMPATE"], correct: 0 },
    { q: "O QUE É O 'GRID' NA FÓRMULA 1", options: ["O CARRO", "A POSIÇÃO DE LARGADA", "O PNEU", "O MOTOR"], correct: 1 },
    { q: "QUEM É O MAIOR VENCEDOR DE TOUR DE FRANCE (7 TÍTULOS - CASSADOS)", options: ["LANCE ARMSTRONG", "EDDY MERCKX", "CHRIS FROOME", "POGACAR"], correct: 0 },
    { q: "QUAL O NOME DO JOGADOR DE GOLFE MAIS RICO DO MUNDO", options: ["PHIL MICKELSON", "TIGER WOODS", "RORY MCILROY", "JON RAHM"], correct: 1 },
    { q: "QUANTOS TÍTULOS MUNDIAIS TEM O SURFISTA KELLY SLATER", options: ["5", "8", "11", "13"], correct: 2 },
    { q: "QUEM É A MAIOR MEDALHISTA DA GINÁSTICA ARTÍSTICA (EUA)", options: ["NADIA COMANECI", "SIMONE BILES", "GABBY DOUGLAS", "SHANNON MILLER"], correct: 1 },
    { q: "QUAL O NOME DO JOGADOR DE BASQUETE CHAMADO 'THE GREEK FREAK'", options: ["LUKA DONCIC", "GIANNIS ANTETOKOUNMPO", "NIKOLA JOKIC", "PAU GASOL"], correct: 1 },
    { q: "QUEM FOI O PRIMEIRO HOMEM A CORRER 100M ABAIXO DE 10S", options: ["USAIN BOLT", "JIM HINES", "CARL LEWIS", "JESSE OWENS"], correct: 1 },
    { q: "QUAL O NOME DO GOLEIRO RUSSO CHAMADO 'ARANHA NEGRA'", options: ["YASHIN", "BUFFON", "NEUER", "CASILLAS"], correct: 0 },
    { q: "QUEM É O MAIOR VENCEDOR DE TÍTULOS DA NBA COMO JOGADOR (11)", options: ["JORDAN", "BILL RUSSELL", "KAREEM", "WILT"], correct: 1 },
    { q: "QUAL O NOME DA TENISTA COM MAIS TÍTULOS DE GRAND SLAM (GERAL)", options: ["SERENA WILLIAMS", "MARGARET COURT", "STEFFI GRAF", "MARTINA"], correct: 1 },
    { q: "QUEM É O MAIOR ARTILHEIRO DA HISTÓRIA DA CHAMPIONS LEAGUE", options: ["MESSI", "CRISTIANO RONALDO", "LEWANDOWSKI", "BENZEMA"], correct: 1 },
    { q: "QUAL O NOME DO ATLETA QUE GANHOU 4 OUROS NA ALEMANHA NAZISTA", options: ["CARL LEWIS", "JESSE OWENS", "JIM THORPE", "PAAVO NURMI"], correct: 1 },
    { q: "QUEM É O JOGADOR DE FUTEBOL COM MAIS JOGOS PELA SELEÇÃO BRASILEIRA", options: ["PELÉ", "CAFÚ", "ROBERTO CARLOS", "NEYMAR"], correct: 1 },
    { q: "QUAL O NOME DO PILOTO DE F1 CHAMADO 'O PROFESSOR'", options: ["SENNA", "ALAIN PROST", "LAUDA", "STEWART"], correct: 1 },
    { q: "QUEM É O ÚNICO PILOTO TRICAMPEÃO MUNDIAL BRASILEIRO (ALÉM DE SENNA)", options: ["FITTIPALDI", "NELSON PIQUET", "MASSA", "BARRICHELLO"], correct: 1 },
    { q: "QUAL O NOME DO JOGADOR DE BASQUETE QUE FEZ 100 PONTOS NUM JOGO", options: ["JORDAN", "WILT CHAMBERLAIN", "KOBE", "LEBRON"], correct: 1 },
    { q: "QUEM É A MAIOR JOGADORA DE FUTEBOL DE TODOS OS TEMPOS", options: ["MARTA", "MIA HAMM", "ALEX MORGAN", "BIRGIT PRINZ"], correct: 0 },
    { q: "QUAL O NOME DO NADADOR QUE GANHOU 8 OUROS EM PEQUIM 2008", options: ["CIELO", "MICHAEL PHELPS", "IAN THORPE", "MARK SPITZ"], correct: 1 },
    { q: "QUEM É O JOGADOR DE TÊNIS CHAMADO 'BABY FEDERER'", options: ["ALCARAZ", "GRIGOR DIMITROV", "ZVEREV", "TSITSIPAS"], correct: 1 },
    { q: "QUAL O NOME DO CICLISTA CHAMADO 'O CANIBAL'", options: ["LANCE", "EDDY MERCKX", "INDURAIN", "PANTANI"], correct: 1 },
    { q: "QUEM É O MAIOR VENCEDOR DE SUPER BOWLS (JOGADOR)", options: ["PATRICK MAHOMES", "TOM BRADY", "JOE MONTANA", "ELI MANNING"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE DE DESCER UM TUBO DE GELO EM UM TRENÓ", options: ["ESQUI", "BOBSLEIGH", "CURLING", "PATINAÇÃO"], correct: 1 },
    { q: "QUAL ESPORTE USA UMA VASSOURA PARA LIMPAR O GELO", options: ["HÓQUEI", "CURLING", "PATINAÇÃO", "SLEDGE"], correct: 1 },
    { q: "COMO SE CHAMA O DISCO USADO NO HÓQUEI NO GELO", options: ["BALL", "PUCK", "DISK", "RING"], correct: 1 },
    { q: "QUAL O PAÍS QUE MAIS GANHA MEDALHAS EM OLIMPÍADAS DE INVERNO", options: ["EUA", "NORUEGA", "CANADÁ", "RÚSSIA"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE DE SALTAR DE UMA RAMPA GIGANTE COM ESQUIS", options: ["SLALOM", "SALTO DE ESQUI", "DOWNHILL", "FREESTYLE"], correct: 1 },
    { q: "COMO SE CHAMA A DANÇA NO GELO COM PATINS", options: ["HÓQUEI", "PATINAÇÃO ARTÍSTICA", "CURLING", "VELOCIDADE"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE QUE UNE ESQUI E TIRO AO ALVO", options: ["TRIATLO", "BIATLO", "COMBINADO", "CROSS-COUNTRY"], correct: 1 },
    { q: "QUAL O NOME DA CORRIDA DE PATINS NO GELO (VELOCIDADE)", options: ["SHORT TRACK", "ICE RACING", "FAST SKATE", "SLIDE"], correct: 0 },
    { q: "COMO SE CHAMA O TRENÓ ONDE O ATLETA DESCE DE BRUÇOS", options: ["BOBSLEIGH", "SKELETON", "LUGE", "SLED"], correct: 1 },
    { q: "COMO SE CHAMA O TRENÓ ONDE O ATLETA DESCE DE COSTAS", options: ["SKELETON", "LUGE", "BOBSLEIGH", "SLED"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE DE DESCER MONTANHAS EM ZIGUE-ZAGUE", options: ["DOWNHILL", "SLALOM", "CROSS", "JUMP"], correct: 1 },
    { q: "QUAL O NOME DA PEDRA USADA NO CURLING", options: ["ROCK", "STONE", "DISC", "BALL"], correct: 1 },
    { q: "QUAL O NOME DO ESQUI FEITO EM TERRENO PLANO", options: ["ALPINE", "CROSS-COUNTRY", "FREESTYLE", "MOGULS"], correct: 1 },
    { q: "ONDE FORAM AS OLIMPÍADAS DE INVERNO DE 2022", options: ["PONTRESINA", "PEQUIM", "SOCHI", "VANCOUVER"], correct: 1 },
    { q: "COMO SE CHAMA O LOCAL ONDE SE PRATICA PATINAÇÃO", options: ["QUADRA", "RINK (PISTA DE GELO)", "ARENA", "CAMPO"], correct: 1 },
    { q: "QUAL O NOME DO FILME SOBRE A EQUIPE DE BOBSLEIGH DA JAMAICA", options: ["JAMAICA ABAIXO DE ZERO", "CORRIDA NO GELO", "TRENÓ FANTASMA", "VELOZES NO GELO"], correct: 0 },
    { q: "QUAL O NOME DO ESPORTE DE FAZER ACROBACIAS NO ESQUI", options: ["MOGULS", "FREESTYLE", "SLALOM", "ALPINE"], correct: 1 },
    { q: "O QUE SIGNIFICA 'OFF-PISTE' NO ESQUI", options: ["DENTRO DA PISTA", "FORA DA PISTA (NEVE FOFA)", "FIM DA PISTA", "INÍCIO"], correct: 1 },
    { q: "QUAL O NOME DA PRANCHA ÚNICA PARA A NEVE", options: ["ESQUI", "SNOWBOARD", "SKATE", "SURF"], correct: 1 },
    { q: "QUAL A DURAÇÃO DE UM JOGO DE HÓQUEI (3 TEMPOS DE...)", options: ["15 MIN", "20 MIN", "30 MIN", "45 MIN"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE DE LANÇAR UM DARDO DISTANTE", options: ["TIRO", "LANÇAMENTO DE DARDO", "ARREMESSO", "FLECHA"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE DE LEVANTAR PESOS GIGANTES", options: ["HALTEROFILISMO", "GINÁSTICA", "LUTAS", "FISICULTURISMO"], correct: 0 },
    { q: "QUAL O NOME DO ESPORTE DE SALTAR EM CIMA DE UM CAVALO (GINÁSTICA)", options: ["HIPISMO", "VOLTEIO", "ADESTRAMENTO", "SALTO"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE QUE USA UMA BOLA PEQUENA E UM BURACO", options: ["SINUCA", "GOLFE", "BOLICHE", "CROQUET"], correct: 1 },
    { q: "COMO SE CHAMA O ESPORTE DE CORRER COM OBSTÁCULOS", options: ["MARATONA", "STEEPLECHASE", "REVEZAMENTO", "SPRINT"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE DE 'REBOLAR' O DISCO NO AR", options: ["FRISBEE", "DISCO", "BOLA", "PRATO"], correct: 0 },
    { q: "QUAL ESPORTE USA UMA BOLA E UM BASTÃO COM REDE NA PONTA", options: ["HÓQUEI", "LACROSSE", "CRÍQUETE", "POLO"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE DE REMAR EM PÉ EM UMA PRANCHA", options: ["SURF", "STAND UP PADDLE", "CAIAQUE", "CANOA"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE QUE USA UM VOLANTE (PETECA)", options: ["TÊNIS", "BADMINTON", "SQUASH", "PING-PONG"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE DE ESCALADA EM PAREDES PEQUENAS", options: ["RAPEL", "BOULDER", "ALPINISMO", "TREKKING"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE DE PULAR DE LUGARES ALTOS COM ELÁSTICO", options: ["PARAQUEDISMO", "BUNGEE JUMP", "VOO LIVRE", "SALTO"], correct: 1 },
    { q: "COMO SE CHAMA O ESPORTE DE FAZER MANOBRAS COM BICICLETA PEQUENA", options: ["CICLISMO", "BMX", "MTB", "SPEED"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE DE EQUILÍBRIO EM UMA FITA", options: ["CORDA BAMBA", "SLACKLINE", "PARKOUR", "MALABARES"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE DE SALTAR ENTRE PRÉDIOS E MUROS", options: ["SKATE", "PARKOUR", "CORRIDA", "SALTO"], correct: 1 },
    { q: "QUAL ESPORTE USA UM TACO CHATO E UMA BOLA (POPULAR NA ÍNDIA)", options: ["BEISEBOL", "CRÍQUETE", "POLO", "GOLFE"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE DE MESA COM JOGADORES PRESOS EM BARRAS", options: ["BOTÃO", "PEBOLIM (TOTÓ)", "AIR HOCKEY", "PING-PONG"], correct: 1 },
    { q: "COMO SE CHAMA O ESPORTE DE LANÇAR BOLAS DE METAL NO CHÃO", options: ["BOLICHE", "BOCHA / PETANCA", "SINUCA", "MALHA"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE DE MERGULHO SEM CILINDRO", options: ["SNORKEL", "APNEIA (MERGULHO LIVRE)", "SCUBA", "PESCA"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE DE LUTAR COM ESPADAS DE BAMBU", options: ["ESGRIMA", "KENDO", "SAMURAI", "NINJA"], correct: 1 },
    { q: "QUAL O NOME DA COMPETIÇÃO QUE REÚNE TODOS OS ESPORTES DA AMÉRICA", options: ["OLIMPÍADAS", "PAN-AMERICANO", "COPA AMÉRICA", "LIBERTADORES"], correct: 1 },
    { q: "QUAL O NOME DO JOGADOR DE TÊNIS QUE GANHOU 14 VEZES ROLAND GARROS", options: ["FEDERER", "RAFAEL NADAL", "DJOKOVIC", "MURRAY"], correct: 1 },
    { q: "QUAL A DISTÂNCIA OFICIAL DE UMA MARATONA", options: ["42.195 KM", "21 KM", "10 KM", "50 KM"], correct: 0 },
    { q: "QUAL O ÚNICO JOGADOR DE BASQUETE A MARCAR 100 PONTOS EM UM JOGO", options: ["JORDAN", "WILT CHAMBERLAIN", "KOBE BRYANT", "LEBRON"], correct: 1 },
    { q: "QUAL O NOME DO NADADOR QUE GANHOU 23 MEDALHAS DE OURO OLÍMPICAS", options: ["CESAR CIELO", "MICHAEL PHELPS", "IAN THORPE", "MARK SPITZ"], correct: 1 },
    { q: "QUEM É O MAIOR ARTILHEIRO DA HISTÓRIA DA SELEÇÃO BRASILEIRA (MASC/FIFA)", options: ["PELÉ", "NEYMAR", "RONALDO", "ZICO"], correct: 1 },
    { q: "QUAL O NOME DA PRIMEIRA MULHER BRASILEIRA A GANHAR UM OURO NO JUDÔ", options: ["MAYRA AGUIAR", "SARAH MENEZES", "RAFAELA SILVA", "KETLEYN QUADROS"], correct: 1 },
    { q: "EM QUAL CIDADE OCORRERAM AS PRIMEIRAS OLIMPÍADAS MODERNAS", options: ["PARIS", "ATENAS", "ROMA", "LONDRES"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE QUE USA UMA PETECA CHAMADA 'VOLANTE'", options: ["TÊNIS", "BADMINTON", "SQUASH", "PING-PONG"], correct: 1 },
    { q: "QUANTOS PONTOS VALE UM TOUCHDOWN NO FUTEBOL AMERICANO", options: ["3", "6", "7", "2"], correct: 1 },
    { q: "QUAL O NOME DA CORRIDA DE CICLISMO MAIS FAMOSA DA ITÁLIA", options: ["TOUR DE FRANCE", "GIRO D'ITALIA", "VUELTA", "MILÃO-ROMA"], correct: 1 },
    { q: "QUEM É O PILOTO COM MAIOR NÚMERO DE VITÓRIAS NA F1", options: ["SENNA", "MICHAEL SCHUMACHER", "LEWIS HAMILTON", "VETTEL"], correct: 2 },
    { q: "QUAL O NOME DO ESPORTE QUE SE PRATICA EM UM VELÓDROMO", options: ["ATLETISMO", "CICLISMO DE PISTA", "PATINAÇÃO", "SKATE"], correct: 1 },
    { q: "COMO SE CHAMA O EMPATE NO XADREZ", options: ["XEQUE", "TÁBUAS (REMETE A EMPATE)", "MATE", "ROCK"], correct: 1 },
    { q: "QUAL O NOME DO JOGADOR QUE MAIS VEZES VENCEU A NBA (11 TÍTULOS)", options: ["JORDAN", "BILL RUSSELL", "KAREEM", "MAGIC"], correct: 1 },
    { q: "QUAL A DURAÇÃO DE UM ROUND NO BOXE PROFISSIONAL", options: ["2 MIN", "3 MIN", "5 MIN", "10 MIN"], correct: 1 },
    { q: "QUEM É A MAIOR TENISTA DA HISTÓRIA DO BRASIL", options: ["BEATRIZ HADDAD", "MARIA ESTHER BUENO", "TELIANA PEREIRA", "PAULA GONÇALVES"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE DE DAR SALTO EM CIMA DE UM CAVALO", options: ["HIPISMO", "VOLTEIO", "ADESTRAMENTO", "TURFE"], correct: 1 },
    { q: "QUAL O NOME DA LUTA QUE USA O OCTÓGONO", options: ["BOXE", "MMA (UFC)", "KARATÊ", "JUDÔ"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE QUE USA UM 'PUCK'", options: ["HÓQUEI NO GELO", "CURLING", "PATINAÇÃO", "SKELETON"], correct: 0 },
    { q: "QUANTOS JOGADORES TEM UM TIME DE POLO AQUÁTICO EM CAMPO", options: ["5", "6", "7", "11"], correct: 2 },
    { q: "QUAL O NOME DA REGRA QUE IMPEDE O ATACANTE DE FICAR NA FRENTE", options: ["FALTA", "IMPEDIMENTO", "ESCANTEIO", "TIRO LIVRE"], correct: 1 },
    { q: "QUAL O NOME DO CARTÃO QUE EXPULSA O JOGADOR", options: ["AMARELO", "VERMELHO", "AZUL", "VERDE"], correct: 1 },
    { q: "QUANTOS MINUTOS TEM UM TEMPO DE FUTEBOL", options: ["30", "45", "60", "90"], correct: 1 },
    { q: "QUAL O NOME DA ÁREA ONDE O GOLEIRO PODE USAR AS MÃOS", options: ["PEQUENA ÁREA", "GRANDE ÁREA", "CAMPO TODO", "MEIO CAMPO"], correct: 1 },
    { q: "QUANTAS SUBSTITUIÇÕES SÃO PERMITIDAS HOJE (REGRA GERAL)", options: ["3", "5", "6", "11"], correct: 1 },
    { q: "COMO SE CHAMA O GOL MARCADO COM A MÃO (FAMOSO MARADONA)", options: ["GOL DE PLACA", "LA MANO DE DIOS", "GOL CONTRA", "PENALTI"], correct: 1 },
    { q: "QUEM É O MAIOR VENCEDOR DA CHAMPIONS LEAGUE (CLUBES)", options: ["BARCELONA", "REAL MADRID", "MILAN", "BAYERN"], correct: 1 },
    { q: "QUAL TIME É CONHECIDO COMO 'O CLUBE MAIS RICO DO MUNDO'", options: ["REAL MADRID", "NEWCASTLE / CITY", "FLAMENGO", "SANTOS"], correct: 1 },
    { q: "QUAL O NOME DO TROFÉU DA COPA LIBERTADORES", options: ["ORELHUDA", "TAÇA LIBERTADORES", "COPA OURO", "CANECO"], correct: 1 },
    { q: "QUAL O NOME DO JOGADOR QUE FAZ O 'GOL DE BICICLETA'", options: ["PELÉ", "LEÔNIDAS DA SILVA", "NEYMAR", "RONALDO"], correct: 1 },
    { q: "QUAL O NOME DO TIME QUE JOGA NO ESTÁDIO ANFIELD", options: ["MANCHESTER", "LIVERPOOL", "CHELSEA", "ARSENAL"], correct: 1 },
    { q: "QUAL O NOME DO ÁRBITRO DE VÍDEO NO FUTEBOL", options: ["JUIZ", "VAR", "BANDEIRINHA", "QUARTO ÁRBITRO"], correct: 1 },
    { q: "QUAL O TIME QUE TEM O APELIDO DE 'VELHA SENHORA'", options: ["MILAN", "JUVENTUS", "INTER", "ROMA"], correct: 1 },
    { q: "QUAL O NOME DO JOGADOR QUE MARCOU 5 GOLS EM 9 MINUTOS", options: ["MESSI", "LEWANDOWSKI", "RONALDO", "HAALAND"], correct: 1 },
    { q: "QUAL O NOME DO TIME DE PELÉ NOS EUA", options: ["GALAXY", "NEW YORK COSMOS", "MIAMI", "ORLANDO"], correct: 1 },
    { q: "QUAL O NOME DO PRIMEIRO TIME DE FUTEBOL DO MUNDO", options: ["REAL MADRID", "SHEFFIELD FC", "LIVERPOOL", "MILAN"], correct: 1 },
    { q: "QUAL O TIME QUE NUNCA CAIU NO BRASIL (SÉRIE A - 2024)", options: ["FLAMENGO/SÃO PAULO", "CORINTHIANS", "PALMEIRAS", "VASCO"], correct: 0 },
    { q: "QUEM É O JOGADOR CHAMADO 'EL BASTO' OU 'CR7'", options: ["RONALDO", "CRISTIANO RONALDO", "RONALDINHO", "ROMÁRIO"], correct: 1 },
    { q: "QUAL O NOME DA LIGA DE FUTEBOL DA ALEMANHA", options: ["LALIGA", "BUNDESLIGA", "PREMIER", "SERIE A"], correct: 1 },
    { q: "QUAL O NOME DO ESTÁDIO DO FLAMENGO (EM PROJETO/NOME)", options: ["MARACANÃ", "GASÔMETRO", "MINEIRÃO", "ENGENHÃO"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE QUE USA AS ARMAS FLORETE E SABRE", options: ["TIRO", "ESGRIMA", "JUDÔ", "LUTAS"], correct: 1 },
    { q: "QUAL A COR DA BANDEIRA QUE ENCERRA UMA CORRIDA DE F1", options: ["VERMELHA", "QUADRICULADA", "AMARELA", "AZUL"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE DE GABRIEL MEDINA", options: ["SKATE", "SURF", "NATAÇÃO", "VELA"], correct: 1 },
    { q: "QUEM É A 'FADINHA' DO SKATE", options: ["LETICIA BUFONI", "RAYSSA LEAL", "SKY BROWN", "PÂMELA ROSA"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE QUE SE JOGA COM UMA BOLA E UMA VASSOURA (GELO)", options: ["HÓQUEI", "CURLING", "BOBSLEIGH", "SLED"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE DE MARTA", options: ["BASQUETE", "FUTEBOL", "VÔLEI", "TÊNIS"], correct: 1 },
    { q: "QUANTOS JOGADORES TEM UM TIME DE VÔLEI EM QUADRA", options: ["5", "6", "7", "11"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE DE ANDERSON SILVA", options: ["BOXE", "MMA (UFC)", "JUDÔ", "JIU-JITSU"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE QUE USA UM BARCO A VELA", options: ["REMO", "IATISMO (VELA)", "CANOAGEM", "SURF"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE DE MICHAEL JORDAN", options: ["FUTEBOL", "BASQUETE", "BEISEBOL", "TÊNIS"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE QUE SE JOGA COM AS MÃOS E FAZ GOL", options: ["FUTEBOL", "HANDEBOL", "BASQUETE", "VÔLEI"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE DE TIGER WOODS", options: ["TÊNIS", "GOLFE", "F1", "POLO"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE QUE USA UM TACO E UMA BOLA PEQUENA (GRAMA)", options: ["BEISEBOL", "CRÍQUETE", "GOLFE", "HÓQUEI"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE DE REBECA ANDRADE", options: ["NATAÇÃO", "GINÁSTICA ARTÍSTICA", "ATLETISMO", "JUDÔ"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE QUE USA UM DISCO NO GELO", options: ["CURLING", "HÓQUEI NO GELO", "PATINAÇÃO", "SKELETON"], correct: 0 },
    { q: "QUAL O NOME DA COMPETIÇÃO DE CICLISMO NA FRANÇA", options: ["GIRO", "TOUR DE FRANCE", "VUELTA", "CORRIDA"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE QUE SE JOGA COM UMA RAQUETE E UMA PETECA", options: ["TÊNIS", "BADMINTON", "SQUASH", "PING-PONG"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE DE USAIN BOLT", options: ["NATAÇÃO", "ATLETISMO", "MARATONA", "SALTOS"], correct: 1 },
    { q: "QUAL O NOME DO ESPORTE QUE USA UMA BOLA E UM BURACO", options: ["SINUCA", "GOLFE", "BOLICHE", "CROQUET"], correct: 1 },
];