const geekData = [
    { q: "QUAL FILME TEM A FRASE 'EU SOU SEU PAI'?", options: ["STAR TREK", "O IMPÉRIO CONTRA-ATACA", "HARRY POTTER", "VINGADORES"], correct: 1 },
    { q: "QUAL É O NOME DO PROTAGONISTA DE THE LEGEND OF ZELDA?", options: ["ZELDA", "GANON", "LINK", "EΡΟΝΑ"], correct: 2 },
    { q: "QUAL É A COR DA ROUPA DO MARIO?", options: ["VERDE", "AZUL", "AMARELO", "VERMELHO"], correct: 3 },
    { q: "QUEM É O IRMÃO DO THOR NA MARVEL?", options: ["LOKI", "ODIN", "HELA", "THANOS"], correct: 0 },
    { q: "QUAL É O POKÉMON INICIAL DE TIPO FOGO NA PRIMEIRA GERAÇÃO?", options: ["PIKACHU", "CHARMANDER", "SQUIRTLE", "BULBASAUR"], correct: 1 },
    { q: "QUAL O NOME DO ROBÔ COMPANHEIRO DE LUKE SKYWALKER?", options: ["C-3PO", "BB-8", "R2-D2", "WALL-E"], correct: 2 },
    { q: "QUAL É A IDENTIDADE SECRETA DO HOMEM-ARANHA?", options: ["BRUCE WAYNE", "TONY STARK", "CLARK KENT", "PETER PARKER"], correct: 3 },
    { q: "QUAL É O NOME DO REINO DE SIMBA EM O REI LEÃO?", options: ["TERRA DO NUNCA", "TERRA DO REINO", "WAKANDA", "ASGARD"], correct: 1 },
    { q: "QUAL É O PRINCIPAL OBJETIVO EM MINECRAFT?", options: ["CORRER", "SOBREVIVER E CONSTRUIR", "FUTEBOL", "LUTAR BOXE"], correct: 1 },
    { q: "QUAL PERSONAGEM DA DC É CONHECIDO COMO O HOMEM DE AÇO?", options: ["BATMAN", "FLASH", "SUPERMAN", "AQUAMAN"], correct: 2 },
    { q: "QUAL É A ARMA USADA POR KATNISS EM JOGOS VORAZES?", options: ["ESPADA", "ARCO E FLECHA", "LANÇA", "ESCUDO"], correct: 1 },
    { q: "COMO É CHAMADO O MESTRE DE NARUTO?", options: ["KAKASHI", "JIRAIYA", "OROCHEEMARU", "ITACHI"], correct: 1 },
    { q: "QUAL É O NOME DA I.A. DE TONY STARK EM HOMEM DE FERRO?", options: ["SIRI", "ALEXA", "JARVIS", "CORTANA"], correct: 2 },
    { q: "QUAL É A CIDADE ONDE VIVE O BATMAN?", options: ["METROPOLIS", "GOTHAM CITY", "CENTRAL CITY", "STAR CITY"], correct: 1 },
    { q: "QUAL É A PRINCIPAL TRANSFORMAÇÃO DOS SAIYAJINS?", options: ["BANKAI", "SUPER SAIYAJIN", "MODO SÁBIO", "GEAR FOURTH"], correct: 1 },
    { q: "QUAL É O NOME DA ESPADA DO REI ARTHUR?", options: ["DURANDAL", "EXCALIBUR", "MURAMASA", "MITHRIL"], correct: 1 },
    { q: "QUAL É A COR DO PAC-MAN?", options: ["AZUL", "VERMELHO", "AMARELO", "VERDE"], correct: 2 },
    { q: "QUEM É O CRIADOR DA MARVEL?", options: ["JACK KIRBY", "BOB KANE", "STAN LEE", "STEVE DITKO"], correct: 2 },
    { q: "QUAL É O NOME DO VILÃO DE HARRY POTTER?", options: ["DUMBLEDORE", "VOLDEMORT", "SNAPE", "HAGRID"], correct: 1 },
    { q: "QUAL É O JOGO DE LUTA DA NINTENDO COM VÁRIOS PERSONAGENS?", options: ["STREET FIGHTER", "TEKKEN", "SMASH BROS", "MORTAL KOMBAT"], correct: 2 },
    { q: "EM QUAL FILME OCORRE O 'ESTALO DE THANOS'?", options: ["GUERRA INFINITA", "ULTIMATO", "ERA DE ULTRON", "GUERRA CIVIL"], correct: 0 },
    { q: "QUAL É A RAÇA DO PERSONAGEM CHEWBACCA?", options: ["EWOK", "WOOKIEE", "JAWA", "HUTT"], correct: 1 },
    { q: "QUAL É O NOME DO MELHOR AMIGO DO BOB ESPONJA?", options: ["LULA MOLUSCO", "PATRICK", "SANDY", "SR. SIRI"], correct: 1 },
    { q: "QUAL É O NOME DO DRAGÃO DE GAME OF THRONES?", options: ["DROGON", "SMAUG", "SHENLONG", "FALCOR"], correct: 0 },
    { q: "QUAL O NOME DA PRINCESA QUE O MARIO RESGATA?", options: ["DAISY", "PEACH", "ZELDA", "ROSALINA"], correct: 1 },
    { q: "QUAL O NOME DO PAI DO SIMBA?", options: ["SCAR", "MUFASA", "PUMBA", "ZAZU"], correct: 1 },
    { q: "QUEM É O DEUS DA GUERRA EM GOD OF WAR?", options: ["ZEUS", "ARES", "KRATOS", "HERCULES"], correct: 2 },
    { q: "QUAL O NOME DA ESCOLA DE HARRY POTTER?", options: ["HOGWARTS", "NARNIA", "WAKANDA", "XAVIER"], correct: 0 },
    { q: "QUAL É O VERDADEIRO NOME DO HOMEM DE FERRO?", options: ["BRUCE BANNER", "STEVE ROGERS", "TONY STARK", "NATASHA ROMANOFF"], correct: 2 },
    { q: "QUAL É O NOME DO PARCEIRO DO SHERLOCK HOLMES?", options: ["WATSON", "MORIARTY", "LESTRADE", "MYCROFT"], correct: 0 },
    { q: "QUAL O NOME DO VILÃO AZUL DE SMURFS?", options: ["GARGAMEL", "PAPA SMURF", "CASCÃO", "CEBOLINHA"], correct: 0 },
    { q: "QUAL É O NOME DO UNICÓRNIO DO FILME MEU MALVADO FAVORITO?", options: ["FOFO", "FLUFFY", "AGNES", "GRYFFIN"], correct: 1 },
    { q: "QUAL É O TIME DE QUIDITCH DE HARRY POTTER?", options: ["GRIFINÓRIA", "SONSERINA", "CORVINAL", "LUFA-LUFA"], correct: 0 },
    { q: "QUAL É O NOME DO CAPITÃO DE PIRATAS DO CARIBE?", options: ["JACK SPARROW", "BARBOSSA", "DAVY JONES", "SALAZAR"], correct: 0 },
    { q: "QUAL É A COR DO HULK?", options: ["CINZA", "VERDE", "AZUL", "AMARELO"], correct: 1 },
    { q: "QUAL É O NOME DA BONECA POSSUÍDA DO CINEMA?", options: ["BARBIE", "ANNABELLE", "CHUCKY", "TIFFANY"], correct: 1 },
    { q: "QUEM É O HERÓI QUE USA UM ESCUDO CIRCULAR?", options: ["IRON MAN", "THOR", "CAPITÃO AMÉRICA", "HULK"], correct: 2 },
    { q: "QUAL É O NOME DO FILHO DO GOKU?", options: ["VEGETA", "GOHAN", "PICCOLO", "TRUNKS"], correct: 1 },
    { q: "QUAL O NOME DO CACHORRO DO MICKEY MOUSE?", options: ["PLUTO", "PATETA", "BIDU", "SNOOPY"], correct: 0 },
    { q: "QUAL É A FAMOSA FRASE DO BUZZ LIGHTYEAR?", options: ["EU SOU O CARA", "AO INFINITO E ALÉM", "EU SOU O REI", "VIVA O HOJE"], correct: 1 },
    { q: "QUAL O NOME DO ALIENÍGENA QUE QUER VOLTAR PARA CASA?", options: ["ALF", "E.T.", "STITCH", "YODA"], correct: 1 },
    { q: "QUAL É O NOME DO MESTRE DO KUNG FU PANDA?", options: ["SHIFU", "OOGWAY", "TIGRESA", "TAI LUNG"], correct: 0 },
    { q: "QUAL O NOME DA ESPOSA DO SHREK?", options: ["FIONA", "CINDERELA", "BRANCA DE NEVE", "TIANA"], correct: 0 },
    { q: "QUAL É O MEIO DE TRANSPORTE DE MARTY MCFLY?", options: ["DELOREAN", "BAT-MÓVEL", "TARDIS", "IMPALA"], correct: 0 },
    { q: "QUAL O NOME DO MAPA DO HARRY POTTER?", options: ["MAPA MUNDI", "MAPA DO MAROTO", "MAPA DO TESOURO", "MAPA DA MINA"], correct: 1 },
    { q: "QUAL É O NOME DO ALMIRANTE DE STAR WARS?", options: ["ACKBAR", "THRAWN", "TARKIN", "HUX"], correct: 0 },
    { q: "QUAL O NOME DA CIDADE DO FLASH?", options: ["GOTHAM", "METROPOLIS", "CENTRAL CITY", "STAR CITY"], correct: 2 },
    { q: "QUAL É A FRASE DE VELOZES E FURIOSOS?", options: ["SOU RÁPIDO", "FAMÍLIA", "CORRA OU MORRA", "ESTRADA"], correct: 1 },
    { q: "QUAL É O NOME DA FILHA DO THANOS?", options: ["NEBULA", "GAMORA", "HELA", "MANTIS"], correct: 1 },
    { q: "QUAL É O NOME DO DRAGÃO DE MULAN?", options: ["MUSHU", "SHENLONG", "SYRAX", "DRACO"], correct: 0 },
    { q: "QUAL É O NOME DO VILÃO DE 'O REI LEÃO'?", options: ["MUFASA", "SCAR", "PUMBA", "ZAZU"], correct: 1 },
    { q: "QUAL É A COR DO SABRE DE LUZ DO MESTRE YODA?", options: ["AZUL", "VERMELHO", "VERDE", "ROXO"], correct: 2 },
    { q: "QUAL É O NOME DO PROTAGONISTA DE 'PIRATAS DO CARIBE'?", options: ["WILL TURNER", "JACK SPARROW", "BARBOSSA", "DAVY JONES"], correct: 1 },
    { q: "QUEM É O MELHOR AMIGO DE HARRY POTTER?", options: ["DRACO MALFOY", "NEVILLE", "RONY WEASLEY", "CEDRICO"], correct: 2 },
    { q: "QUAL É O NOME DO BONECO DE NEVE DE 'FROZEN'?", options: ["SVEN", "KRISTOFF", "OLAF", "HANS"], correct: 2 },
    { q: "QUAL É A IDENTIDADE DO HOMEM DE FERRO?", options: ["STEVE ROGERS", "BRUCE BANNER", "TONY STARK", "CLARK KENT"], correct: 2 },
    { q: "QUAL É O NOME DA CIDADE DO SUPERMAN?", options: ["GOTHAM", "METROPOLIS", "STAR CITY", "CENTRAL CITY"], correct: 1 },
    { q: "QUAL É O NOME DO POKÉMON QUE EVOLUI DO PIKACHU?", options: ["PICHU", "RAICHU", "LUCARIO", "EEVEE"], correct: 1 },
    { q: "QUAL É A ARMA PRINCIPAL DO CAPITÃO AMÉRICA?", options: ["MARTELO", "ESCUDO", "ESPADA", "ARCO"], correct: 1 },
    { q: "QUAL É O NOME DO VILÃO ROXO DA MARVEL?", options: ["THANOS", "LOKI", "ULTRON", "VENOM"], correct: 0 },
    { q: "EM 'TOY STORY', QUAL É O NOME DO DONO DOS BRINQUEDOS?", options: ["SID", "ANDY", "BUZZ", "WOODY"], correct: 1 },
    { q: "QUAL É O NOME DO MESTRE DE SKATE DOS TARTARUGAS NINJA?", options: ["SHREDDER", "SPLINTER", "APRIL", "CASEY"], correct: 1 },
    { q: "QUAL É O NOME DO FILME DO CORINGA COM JOAQUIN PHOENIX?", options: ["BATMAN", "CORINGA", "ESQUADRÃO SUICIDA", "CAVALEIRO DAS TREVAS"], correct: 1 },
    { q: "QUAL É O NOME DO CRIADOR DO FACEBOOK?", options: ["BILL GATES", "ELON MUSK", "MARK ZUCKERBERG", "STEVE JOBS"], correct: 2 },
    { q: "QUAL É O NOME DA MÃE DO SIMBA?", options: ["NALA", "SARABI", "SHENZI", "KIARA"], correct: 1 },
    { q: "QUAL É O NOME DO PERSONAGEM QUE USA UMA MÁSCARA DE HOCKEY?", options: ["CHUCKY", "FREDDY KRUEGER", "JASON VOORHEES", "MICHAEL MYERS"], correct: 2 },
    { q: "QUAL É O NOME DO DRAGÃO DE 'A ESTRANHA JORNADA DE CHIHIRO'?", options: ["HAKU", "FALCOR", "MUSHU", "DROGON"], correct: 0 },
    { q: "QUAL É A COR DO POWER RANGER LÍDER TRADICIONAL?", options: ["AZUL", "PRETO", "VERMELHO", "VERDE"], correct: 2 },
    { q: "QUAL É O NOME DO GATO QUE PERSEGUE O JERRY?", options: ["TOM", "GARFIELD", "FRAJOLA", "SILVESTRE"], correct: 0 },
    { q: "QUAL É O NOME DO OGRO VERDE DO CINEMA?", options: ["HULK", "SHREK", "GRINCH", "SULLY"], correct: 1 },
    { q: "QUAL É O NOME DO ROBÔ PEQUENO DE 'WALL-E'?", options: ["EVE", "MO", "WALL-E", "AUTO"], correct: 2 },
    { q: "QUAL É O NOME DO IRMÃO DO LUIGI?", options: ["WARIO", "MARIO", "WALUIGI", "BOWSER"], correct: 1 },
    { q: "QUAL É O NOME DA VILÃ DE '101 DÁLMATAS'?", options: ["MALEVOLA", "URSULA", "CRUELLA DE VIL", "MADRASTA"], correct: 2 },
    { q: "QUAL É O NOME DO LEÃO DE 'MADAGASCAR'?", options: ["ALEX", "MARTY", "MELMAN", "GLORIA"], correct: 0 },
    { q: "QUAL É A COR DA PEDRA DA MENTE NA MARVEL?", options: ["AMARELA", "AZUL", "VERDE", "ROXA"], correct: 0 },
    { q: "QUAL É O NOME DO PERSONAGEM QUE DIZ 'EU SOU O GROOT'?", options: ["ROCKET", "GROOT", "DRAX", "STAR-LORD"], correct: 1 },
    { q: "QUAL É O NOME DO PAI DE LUKE SKYWALKER?", options: ["OBI-WAN", "YODA", "DARTH VADER", "PALPATINE"], correct: 2 },
    { q: "QUAL É O NOME DA ESPOSA DO HOMEM DE FERRO?", options: ["NATASHA", "WANDA", "PEPPER POTTS", "PEGGY CARTER"], correct: 2 },
    { q: "QUAL É O NOME DO JOGO ONDE SE CAPTURA MONSTROS?", options: ["DIGIMON", "POKÉMON", "ZELDA", "SONIC"], correct: 1 },
    { q: "QUAL É O NOME DO URSO QUE GOSTA DE MEL?", options: ["POOH", "PADDINGTON", "TED", "BALU"], correct: 0 },
    { q: "QUAL É O NOME DO PERSONAGEM QUE VIVE EM UMA FENDA NO BIQUÍNI?", options: ["PATRICK", "BOB ESPONJA", "LULA MOLUSCO", "SR. SIRI"], correct: 1 },
    { q: "QUAL É O NOME DO VILÃO DE 'OS INCRÍVEIS'?", options: ["SÍNDROME", "BOM VOYAGE", "ESCAVADOR", "GELADO"], correct: 0 },
    { q: "QUAL É A COR DO PERSONAGEM SONIC?", options: ["VERMELHO", "AMARELO", "AZUL", "VERDE"], correct: 2 },
    { q: "QUAL É O NOME DO HUMANO EM 'MONSTROS S.A.'?", options: ["BOO", "ANDY", "SID", "RILEY"], correct: 0 },
    { q: "QUAL É O NOME DA FILHA DE SIMBA?", options: ["NALA", "KIARA", "VITANI", "ZIRA"], correct: 1 },
    { q: "QUAL É O NOME DO MEIO DE TRANSPORTE DO HARRY POTTER?", options: ["VASSOURA", "CARRO", "TAPETE", "DRAGÃO"], correct: 0 },
    { q: "QUAL É O NOME DO VILÃO DE 'BATMAN: O CAVALEIRO DAS TREVAS'?", options: ["PINGUIM", "CHARADA", "CORINGA", "BANE"], correct: 2 },
    { q: "QUAL É O NOME DA PRINCESA DE 'ALADDIN'?", options: ["TIANA", "JASMINE", "BELA", "ARIEL"], correct: 1 },
    { q: "QUAL É O NOME DO PLANETA DO SUPERMAN?", options: ["MARTE", "KRIPTON", "TERRA", "ASGARD"], correct: 1 },
    { q: "QUAL É O NOME DO CACHORRO DO FILME 'UP'?", options: ["DUG", "RUSSELL", "KEVIN", "CARL"], correct: 0 },
    { q: "QUAL É O NOME DO PERSONAGEM QUE É UM ESPANTALHO EM 'BATMAN'?", options: ["CORINGA", "ESPANTALHO", "PINGUIM", "BANE"], correct: 1 },
    { q: "QUAL É O NOME DO VILÃO DE 'A PEQUENA SEREIA'?", options: ["URSULA", "MORGANNA", "MALEVOLA", "CRUELLA"], correct: 0 },
    { q: "QUAL É O NOME DO PARCEIRO DO BATMAN?", options: ["ROBIN", "FLASH", "CYBORG", "AQUAMAN"], correct: 0 },
    { q: "QUAL É O NOME DO DEUS DO TROVÃO?", options: ["ZEUS", "ODIN", "THOR", "LOKI"], correct: 2 },
    { q: "QUAL É O NOME DA CIDADE DO HOMEM-ARANHA?", options: ["CHICAGO", "LOS ANGELES", "NOVA YORK", "MIAMI"], correct: 2 },
    { q: "QUAL É O NOME DO FILME COM DINOSSAUROS REANIMADOS?", options: ["JURASSIC PARK", "KING KONG", "GODZILLA", "TRANSFORMERS"], correct: 0 },
    { q: "QUAL É O NOME DO LÍDER DOS AUTOBOTS?", options: ["MEGATRON", "BUMBLEBEE", "OPTIMUS PRIME", "IRONHIDE"], correct: 2 },
    { q: "QUAL É O NOME DA PROTAGONISTA DE 'JOGOS VORAZES'?", options: ["BELLA", "KATNISS EVERDEEN", "TRIS", "HERMIONE"], correct: 1 },
    { q: "QUAL É O NOME DO MESTRE DE 'KARATE KID'?", options: ["MIYAGI", "SATO", "KREESE", "DANIEL"], correct: 0 },
    { q: "QUAL É O NOME DO VILÃO DE 'MATRIX'?", options: ["NEO", "MORPHEUS", "AGENTE SMITH", "TRINITY"], correct: 2 },
    { q: "QUAL É O NOME DO NAVIO DE JACK SPARROW?", options: ["PÉROLA NEGRA", "HOLANDÊS VOADOR", "VINGANÇA DA RAINHA", "TITANIC"], correct: 0 },
    { q: "QUAL É O NOME DO VILÃO DE 'OS VINGADORES' DE 2012?", options: ["THANOS", "LOKI", "ULTRON", "HELA"], correct: 1 },
    { q: "QUAL O NOME DO PERSONAGEM PRINCIPAL DE 'GOD OF WAR'?", options: ["ZEUS", "ATREUS", "KRATOS", "BALDUR"], correct: 2 },
    { q: "QUAL É O NOME DA MÃE DE HARRY POTTER?", options: ["HERMIONE", "LILY", "PETUNIA", "NARCISA"], correct: 1 },
    { q: "QUAL É O NOME DO MELHOR AMIGO DE ASH KETCHUM?", options: ["BROOK", "MISTY", "PIKACHU", "GARY"], correct: 2 },
    { q: "QUAL É O NOME DA CIDADE DE 'OS SIMPSONS'?", options: ["SOUTH PARK", "QUAHOG", "SPRINGFIELD", "SHELBYVILLE"], correct: 2 },
    { q: "QUAL É A ARMA DE NARUTO NO INÍCIO DA SÉRIE?", options: ["KATANA", "SHURIKEN", "KUNAI", "PERGAMINHO"], correct: 2 },
    { q: "QUAL O NOME DO VILÃO PRINCIPAL DE 'O SENHOR DOS ANÉIS'?", options: ["GANDALF", "FRODO", "SAURON", "SARUMAN"], correct: 2 },
    { q: "QUAL É O NOME DO DRAGÃO DE 'SHREK'?", options: ["DRAGOA", "SMAUG", "MUSHU", "FALCOR"], correct: 0 },
    { q: "QUAL É O NOME DA INTELIGÊNCIA ARTIFICIAL DE 'HALO'?", options: ["SIRI", "CORTANA", "ALEXA", "GLADOS"], correct: 1 },
    { q: "QUAL É O NOME DO REI DE WAKANDA?", options: ["T'CHALLA", "ERIK KILLMONGER", "M'BAKU", "LUKE CAGE"], correct: 0 },
    { q: "QUAL É A COR DO FANTASMA MAIS RÁPIDO DO PAC-MAN?", options: ["AZUL", "ROSA", "LARANJA", "VERMELHO"], correct: 3 },
    { q: "QUAL É O NOME DO PAI DE SIMBA?", options: ["SCAR", "MUFASA", "PUMBA", "TIMÃO"], correct: 1 },
    { q: "QUAL É O NOME DO ESTÚDIO DE 'MEU AMIGO TOTORO'?", options: ["DISNEY", "PIXAR", "GHIBLI", "DREAMWORKS"], correct: 2 },
    { q: "QUAL É O NOME DO VILÃO DE 'MORTAL KOMBAT'?", options: ["SUB-ZERO", "SCORPION", "SHAO KAHN", "RAIDEN"], correct: 2 },
    { q: "QUAL É O NOME DO ROBÔ DE 'INTERSTELAR'?", options: ["TARS", "R2-D2", "HAL 9000", "BUMBLEBEE"], correct: 0 },
    { q: "QUAL É A FRASE DE 'TOY STORY'?", options: ["VIVA A VIDA", "AO INFINITO E ALÉM", "EU SOU O REI", "SOU UM BRINQUEDO"], correct: 1 },
    { q: "QUAL O NOME DO PROTAGONISTA DE 'ONE PIECE'?", options: ["ZORO", "SANJI", "LUFFY", "NAMI"], correct: 2 },
    { q: "QUAL É O NOME DA MÃE DO BAMBI?", options: ["FALINE", "ELA NÃO TEM NOME", "FLOWER", "THUMPER"], correct: 1 },
    { q: "QUAL É O NOME DA JORNALISTA DE 'SUPERMAN'?", options: ["LOIS LANE", "MARY JANE", "PEPPER POTTS", "IRIS WEST"], correct: 0 },
    { q: "QUAL É O NOME DO VILÃO DE 'TRANSFORMERS'?", options: ["OPTIMUS", "BUMBLEBEE", "MEGATRON", "STARSQUEAM"], correct: 2 },
    { q: "QUAL É O NOME DO JOGO COM O 'MASTER CHIEF'?", options: ["DOOM", "HALO", "GEARS OF WAR", "DESTINY"], correct: 1 },
    { q: "QUAL É A COR DO SABRE DE LUZ DE DARTH VADER?", options: ["VERDE", "AZUL", "VERMELHO", "ROXO"], correct: 2 },
    { q: "QUAL O NOME DO CACHORRO DE 'SCOOBY-DOO'?", options: ["SALSICHA", "SCOOBY-DOO", "FRED", "PLUTO"], correct: 1 },
    { q: "QUAL É O NOME DO LUGAR ONDE VIVE O SHREK?", options: ["CASTELO", "PÂNTANO", "FLORESTA", "CIDADE"], correct: 1 },
    { q: "QUAL O NOME DO CRIADOR DE 'STAR WARS'?", options: ["STEVEN SPIELBERG", "GEORGE LUCAS", "JAMES CAMERON", "RIDLEY SCOTT"], correct: 1 },
    { q: "QUAL É O NOME DO COMPANHEIRO DO HAN SOLO?", options: ["CHEWBACCA", "LUKE", "LANDO", "YODA"], correct: 0 },
    { q: "QUAL O NOME DA MENINA DE 'MONSTROS S.A.'?", options: ["BOO", "LILO", "VANELLOPE", "RILEY"], correct: 0 },
    { q: "QUAL O NOME DO JOGO DA ROCHSTAR COM CAWBOYS?", options: ["GTA", "RED DEAD REDEMPTION", "BULLY", "MAFIA"], correct: 1 },
    { q: "QUAL É O NOME DO PERSONAGEM QUE DIZ 'BAZINGA'?", options: ["SHELDON COOPER", "LEONARD", "HOWARD", "RAJ"], correct: 0 },
    { q: "QUAL É O NOME DA CASA DE JON SNOW?", options: ["LANNISTER", "STARK", "TARGARYEN", "BARATHEON"], correct: 1 },
    { q: "QUAL O NOME DO POKÉMON QUE DORME NO CAMINHO?", options: ["PIKACHU", "SNORLAX", "MEOWTH", "PSYDUCK"], correct: 1 },
    { q: "QUAL É O NOME DA ESPADA DE LINK EM ZELDA?", options: ["MASTER SWORD", "EXCALIBUR", "MURAMASA", "MITHRIL"], correct: 0 },
    { q: "QUAL É O NOME DO VILÃO DE 'O ESTRANHO MUNDO DE JACK'?", options: ["JACK", "OOGIE BOOGIE", "SALLY", "ZERO"], correct: 1 },
    { q: "QUAL O NOME DO AGENTE 007?", options: ["ETHAN HUNT", "JASON BOURNE", "JAMES BOND", "JACK REACHER"], correct: 2 },
    { q: "QUAL É O NOME DO FILHO DE GOKU?", options: ["VEGETA", "GOHAN", "PICCOLO", "FREEZA"], correct: 1 },
    { q: "QUAL É O NOME DO LUGAR ONDE MORA O POPEYE?", options: ["MAR", "NAVIO", "PIER", "DOCA"], correct: 3 },
    { q: "QUAL É A COR DO PERSONAGEM BARNEY?", options: ["VERDE", "ROXO", "AZUL", "AMARELO"], correct: 1 },
    { q: "QUAL O NOME DO PROTAGONISTA DE 'ASSASSIN'S CREED 2'?", options: ["ALTAIR", "EZIO AUDITORE", "CONNOR", "EDWARD"], correct: 1 },
    { q: "QUAL É O NOME DO DRAGÃO DE 'COMO TREINAR O SEU DRAGÃO'?", options: ["BANGUELA", "TEMPESTADE", "BATATÃO", "DROGON"], correct: 0 },
    { q: "QUAL É O NOME DA VILÃ DE 'BRANCA DE NEVE'?", options: ["MALEVOLA", "URSULA", "RAINHA MÁ", "CRUELLA"], correct: 2 },
    { q: "QUAL O NOME DO MACACO DO ALADDIN?", options: ["ABU", "IAGO", "RAJA", "GENIO"], correct: 0 },
    { q: "QUAL É O NOME DO VILÃO DE 'DETONA RALPH'?", options: ["FELIX", "VANELOPE", "REI DOCE", "RALPH"], correct: 2 },
    { q: "QUAL É O NOME DA CIDADE DO HOMEM-ARANHA?", options: ["GOTHAM", "METROPOLIS", "NOVA YORK", "STAR CITY"], correct: 2 },
    { q: "QUAL O NOME DO PROTAGONISTA DE 'FALLOUT'?", options: ["DOOM SLAYER", "VAULT DWELLER", "MASTER CHIEF", "SNAKE"], correct: 1 },
    { q: "QUAL O NOME DO PASSARINHO AMARELO DE 'LOONEY TUNES'?", options: ["FRAJOLA", "PIU-PIU", "PATOLINO", "PERNALONGA"], correct: 1 },
    { q: "QUAL É O NOME DO VILÃO DE 'REIDEN' EM METAL GEAR?", options: ["LIQUID SNAKE", "ARMSTRONG", "OCELOT", "VAMP"], correct: 1 },
    { q: "QUAL É O NOME DA BONECA DE 'TOY STORY 4'?", options: ["GABBY GABBY", "JESSIE", "BO PEEP", "BARBIE"], correct: 0 },
    { q: "QUAL O NOME DO MEIO DE TRANSPORTE DO DOUTOR ESTRANHO?", options: ["VASSOURA", "TAPETE", "CAPA DA LEVITAÇÃO", "PORTAL"], correct: 2 },
    { q: "QUAL É O NOME DO DRAGÃO DE 'MULAN'?", options: ["MUSHU", "DROGON", "SHENLONG", "SYRAX"], correct: 0 },
    { q: "QUAL É A COR DO FANTASMA QUE PERSEGUE O PAC-MAN?", options: ["AZUL", "VERMELHO", "ROSA", "TODAS AS ANTERIORES"], correct: 3 },
    { q: "QUAL É O NOME DO MARTELO DO THOR?", options: ["MJOLNIR", "STORM BREAKER", "EXCALIBUR", "MITHRIL"], correct: 0 },
    { q: "QUAL É A TRANSFORMAÇÃO MAIS FORTE DE GOKU NO Z?", options: ["SUPER SAIYAJIN 1", "SUPER SAIYAJIN 2", "SUPER SAIYAJIN 3", "SUPER SAIYAJIN 4"], correct: 2 },
    { q: "QUAL O NOME DO ROBÔ COMPANHEIRO DO HAN SOLO?", options: ["C-3PO", "R2-D2", "BB-8", "ELE NÃO TEM UM ROBÔ"], correct: 3 },
    { q: "QUAL É O NOME DO PROTAGONISTA DE 'THE WITCHER'?", options: ["VESEMIR", "ESKEL", "GERALT", "LAMBERT"], correct: 2 },
    { q: "QUAL O NOME DO VILÃO DE 'SHREK 2'?", options: ["ENCANTADO", "FADA MADRINHA", "RUMPELSTILTSKIN", "LORD FARQUAAD"], correct: 1 },
    { q: "QUAL É O NOME DO CRIADOR DE 'NARUTO'?", options: ["EIICHIRO ODA", "MASASHI KISHIMOTO", "AKIRA TORIYAMA", "TITE KUBO"], correct: 1 },
    { q: "QUAL É A COR DO POWER RANGER VERDE ORIGINAL?", options: ["VERDE", "BRANCO", "AMARELO", "PRETO"], correct: 0 },
    { q: "QUAL O NOME DO JOGO ONDE VOCÊ CAÇA DINOSSAUROS?", options: ["ARK", "MINECRAFT", "TERRARIA", "ROBLOX"], correct: 0 },
    { q: "QUAL É O NOME DA IA DO FILME 'IRON MAN'?", options: ["JARVIS", "FRIDAY", "SIRI", "ALEXA"], correct: 0 },
    { q: "QUAL O NOME DO LUGAR ONDE OS MORTOS VÃO NA MARVEL?", options: ["ASGARD", "VALHALLA", "HELL", "WAKANDA"], correct: 1 },
    { q: "QUAL É O NOME DA ARMA DO MICHELANGELO (TARTARUGAS NINJA)?", options: ["KATANA", "SAI", "BASTÃO", "NUNCHAKU"], correct: 3 },
    { q: "QUAL É O NOME DO VILÃO DE 'STAR WARS VII'?", options: ["DARTH VADER", "KYLO REN", "SNOKE", "PALPATINE"], correct: 1 },
    { q: "QUAL O NOME DO PROTAGONISTA DE 'POKÉMON'?", options: ["GARY", "RED", "ASH KETCHUM", "LEON"], correct: 2 },
    { q: "QUAL O NOME DO LUGAR ONDE VIVE O BATMAN?", options: ["MANSÃO WAYNE", "BAT-CAVERNA", "ASILO ARKHAM", "GOTHAM CITY"], correct: 0 },
    { q: "QUAL É O NOME DO DRAGÃO DE 'HARRY POTTER E O CÁLICE DE FOGO'?", options: ["RABO-CÓRNEO", "NORBERTO", "DROGON", "SMAUG"], correct: 0 },
    { q: "QUAL O NOME DO JOGO DA NINTENDO COM UM GORILA?", options: ["MARIO", "DONKEY KONG", "ZELDA", "KIRBY"], correct: 1 },
    { q: "QUAL É A COR DA CAPA DO SUPERMAN?", options: ["AZUL", "VERMELHA", "AMARELA", "PRETA"], correct: 1 },
    { q: "QUAL O NOME DA ESPADA QUE FRODO USA?", options: ["FERROADA", "ANDURIL", "GLAMDRING", "ORCRIST"], correct: 0 },
    { q: "QUAL É O NOME DO VILÃO DE 'MATRIX'?", options: ["MORPHEUS", "NEO", "AGENTE SMITH", "TRINITY"], correct: 2 },
    { q: "QUAL O NOME DO PERSONAGEM QUE TEM UM ESCUDO?", options: ["THOR", "HULK", "CAPITÃO AMÉRICA", "HOMEM DE FERRO"], correct: 2 },
    { q: "QUAL O NOME DO FILME QUE TEM O PERSONAGEM WOODY?", options: ["TOY STORY", "CARROS", "FROZEN", "SHREK"], correct: 0 },
    { q: "QUAL O NOME DO VILÃO DE 'ALADDIN'?", options: ["IAGO", "JAFAR", "ABU", "SULTÃO"], correct: 1 },
    { q: "QUAL O NOME DO JOGO COM O PERSONAGEM KRATOS?", options: ["HALO", "GOD OF WAR", "DOOM", "ZELDA"], correct: 1 },
    { q: "QUAL É A COR DA ROUPA DO LUIGI?", options: ["VERMELHO", "AMARELO", "AZUL", "VERDE"], correct: 3 },
    { q: "QUAL O NOME DO POKÉMON QUE TEM O NÚMERO 1?", options: ["BULBASAUR", "CHARMANDER", "SQUIRTLE", "PIKACHU"], correct: 0 },
    { q: "QUAL O NOME DO PERSONAGEM QUE USA UMA MÁSCARA DE MORCEGO?", options: ["BATMAN", "HOMEM-ARANHA", "SUPERMAN", "FLASH"], correct: 0 },
    { q: "QUAL O NOME DA CIDADE DO JOGO 'GTA SAN ANDREAS'?", options: ["VICE CITY", "LIBERTY CITY", "LOS SANTOS", "GOTHAM"], correct: 2 },
    { q: "QUAL O NOME DO LÍDER DOS X-MEN?", options: ["WOLVERINE", "CICLOPE", "PROFESSOR X", "MAGNETO"], correct: 2 },
    { q: "QUAL É O NOME DA FILHA DE TONY STARK?", options: ["NATASHA", "WANDA", "MORGAN", "PEPPER"], correct: 2 },
    { q: "QUAL O NOME DO VILÃO DE 'A BELA E A FERA'?", options: ["GASTON", "LUMIERE", "COGSWORTH", "FERA"], correct: 0 },
    { q: "QUAL O NOME DO PERSONAGEM QUE TEM UMA GARRA DE METAL?", options: ["BATMAN", "WOLVERINE", "HULK", "THOR"], correct: 1 },
    { q: "QUAL O NOME DO JOGO ONDE VOCÊ É UM ASSASSINO?", options: ["ASSASSIN'S CREED", "COD", "GTA", "MINECRAFT"], correct: 0 },
    { q: "QUAL É O NOME DA MÃE DO SIMBA?", options: ["SARABI", "NALA", "SHENZI", "ZIRA"], correct: 0 },
    { q: "QUAL O NOME DO PERSONAGEM QUE VIVE EM UM ABACAXI?", options: ["PATRICK", "LULA MOLUSCO", "BOB ESPONJA", "SR. SIRI"], correct: 2 },
    { q: "QUAL O NOME DO VILÃO DE 'MORTAL KOMBAT' QUE ROUBA ALMAS?", options: ["SUB-ZERO", "SCORPION", "SHANG TSUNG", "RAIDEN"], correct: 2 },
    { q: "QUAL O NOME DO PAI DO LUKE SKYWALKER?", options: ["OBI-WAN", "YODA", "DARTH VADER", "PALPATINE"], correct: 2 },
    { q: "QUAL O NOME DO FILME QUE TEM UM TUBARÃO?", options: ["JAWS", "TITANIC", "AVATAR", "SHREK"], correct: 0 },
    { q: "QUAL O NOME DO PERSONAGEM QUE CORRE MUITO RÁPIDO?", options: ["BATMAN", "FLASH", "SUPERMAN", "AQUAMAN"], correct: 1 },
    { q: "QUAL O NOME DO JOGO DA MOJANG?", options: ["ROBLOX", "MINECRAFT", "FORNITE", "GTA"], correct: 1 },
    { q: "QUAL É A COR DO SABRE DO OBI-WAN?", options: ["AZUL", "VERDE", "VERMELHO", "ROXO"], correct: 0 },
    { q: "QUAL O NOME DO VILÃO DE 'THOR: RAGNAROK'?", options: ["LOKI", "HELA", "THANOS", "ODIN"], correct: 1 },
    { q: "QUAL O NOME DO PERSONAGEM QUE USA UM ARCO E FLECHA?", options: ["GAVIÃO ARQUEIRO", "THOR", "HULK", "HOMEM DE FERRO"], correct: 0 },
    { q: "QUAL O NOME DO FILME QUE TEM UM ROBÔ CHAMADO BUMBLEBEE?", options: ["TRANSFORMERS", "CARROS", "WALL-E", "TOY STORY"], correct: 0 },
    { q: "QUAL O NOME DO LUGAR ONDE VIVEM OS HOBBITS?", options: ["GONDOR", "MORDOR", "CONDADO", "ROHAN"], correct: 2 },
    { q: "QUAL O NOME DO PERSONAGEM QUE TEM UM ESCUDO DE VIBRANIUM?", options: ["HOMEM DE FERRO", "THOR", "CAPITÃO AMÉRICA", "PANTERA NEGRA"], correct: 2 },
    { q: "QUAL O NOME DO JOGO ONDE VOCÊ ATIRA EM PORTAIS?", options: ["HALO", "PORTAL", "DOOM", "QUAKE"], correct: 1 },
    { q: "QUAL O NOME DO VILÃO DE 'CAPITÃO AMÉRICA: GUERRA CIVIL'?", options: ["ZEMO", "RED SKULL", "THANOS", "LOKI"], correct: 0 },
    { q: "QUAL O NOME DO PERSONAGEM QUE É UM DEUS TRAPACEIRO?", options: ["THOR", "ODIN", "LOKI", "BALDUR"], correct: 2 },
    { q: "QUAL O NOME DO FILME QUE TEM O PERSONAGEM ELSA?", options: ["FROZEN", "SHREK", "TOY STORY", "CARROS"], correct: 0 },
    { q: "QUAL É O NOME DO PARCEIRO DO SNOOPY?", options: ["LINUS", "CHARLIE BROWN", "WOODSTOCK", "SCHROEDER"], correct: 2 },
    { q: "QUAL É O NOME DO VILÃO DE 'PANTERA NEGRA'?", options: ["KLAW", "KILLMONGER", "M'BAKU", "ZEMO"], correct: 1 },
    { q: "QUAL É A FRASE DE ORDEM DE OPTIMUS PRIME?", options: ["AVANÇAR", "ROBOTS AVANTE", "AUTOBOTS, TRANSFORMAR E AVANÇAR", "LUTAR"], correct: 2 },
    { q: "QUAL É O NOME DO CÃO DO MICKEY?", options: ["PATETA", "PLUTO", "BIDU", "SNOOPY"], correct: 1 },
    { q: "QUAL O NOME DO JOGO ONDE VOCÊ CAÇA FANTASMAS?", options: ["LUIGI'S MANSION", "MARIO KART", "ZELDA", "METROID"], correct: 0 },
    { q: "QUAL O NOME DO VILÃO DE 'SHREK PARA SEMPRE'?", options: ["ENCANTADO", "FADA MADRINHA", "RUMPELSTILTSKIN", "DRAGÃO"], correct: 2 },
    { q: "QUAL É O NOME DA ESPADA DE BILBO BOLSEIRO?", options: ["ANDURIL", "FERROADA", "GLAMDRING", "ORCRIST"], correct: 1 },
    { q: "QUAL O NOME DO ROBÔ DO FILME 'BIG HERO 6'?", options: ["BAYMAX", "HIRO", "GOGO", "WASABI"], correct: 0 },
    { q: "QUAL É A COR DO POWER RANGER ROSA?", options: ["VERMELHO", "ROSA", "AZUL", "AMARELO"], correct: 1 },
    { q: "QUAL O NOME DO PROTAGONISTA DE 'DRAGON BALL'?", options: ["VEGETA", "GOHAN", "GOKU", "PICCOLO"], correct: 2 },
    { q: "QUAL É O NOME DO VILÃO DE 'WATCHMEN'?", options: ["OZIMANDIAS", "RORSCHACH", "DR. MANHATTAN", "COMEDIANTE"], correct: 0 },
    { q: "QUAL O NOME DO NAVIO DE 'ONE PIECE'?", options: ["GOING MERRY", "THOUSAND SUNNY", "BLACK PEARL", "TITANIC"], correct: 0 },
    { q: "QUAL É O NOME DA ARMA DO TARTARUGA NINJA DONATELLO?", options: ["KATANA", "SAI", "BASTÃO BO", "NUNCHAKU"], correct: 2 },
    { q: "QUAL O NOME DO VILÃO DE 'STAR WARS VIII'?", options: ["SNOKE", "KYLO REN", "HUX", "PHASMA"], correct: 1 },
    { q: "QUAL O NOME DO LUGAR ONDE MORA O SUPERMAN NA TERRA?", options: ["METROPOLIS", "SMALLVILLE", "GOTHAM", "CENTRAL CITY"], correct: 1 },
    { q: "QUAL É O NOME DO DRAGÃO DE 'A BELA ADORMECIDA'?", options: ["MALEVOLA", "URSULA", "FAUNA", "FLORA"], correct: 0 },
    { q: "QUAL O NOME DO JOGO DA SEGA COM UM OURIÇO?", options: ["MARIO", "SONIC", "ALEX KIDD", "SHINOBI"], correct: 1 },
    { q: "QUAL É A COR DO CABELO DO PERSONAGEM TRUNKS?", options: ["PRETO", "ROXO", "AMARELO", "AZUL"], correct: 1 },
    { q: "QUAL O NOME DA ESPADA QUE O REI ARTHUR TIROU DA PEDRA?", options: ["EXCALIBUR", "FERROADA", "DURANDAL", "MITHRIL"], correct: 0 },
    { q: "QUAL É O NOME DO VILÃO DE 'KINGSMAN'?", options: ["VALENTINE", "EGGSY", "HARRY", "MERLIN"], correct: 0 },
    { q: "QUAL O NOME DO PERSONAGEM QUE USA UM MARTELO?", options: ["IRON MAN", "THOR", "HULK", "ANT-MAN"], correct: 1 },
    { q: "QUAL O NOME DO FILME QUE TEM O PERSONAGEM LIGHTNING MCQUEEN?", options: ["CARROS", "TOY STORY", "FROZEN", "SHREK"], correct: 0 },
    { q: "QUAL O NOME DO VILÃO DE 'HERCULES' NO DESENHO DA DISNEY?", options: ["ZEUS", "HADES", "FIL", "PEGASUS"], correct: 1 },
    { q: "QUAL O NOME DO JOGO COM O PERSONAGEM MASTER CHIEF?", options: ["HALO", "DOOM", "DESTINY", "METROID"], correct: 0 },
    { q: "QUAL É A COR DO SABRE DE LUZ DO MACE WINDU?", options: ["AZUL", "VERDE", "ROXO", "VERMELHO"], correct: 2 },
    { q: "QUAL O NOME DO POKÉMON QUE TEM O NÚMERO 4?", options: ["BULBASAUR", "CHARMANDER", "SQUIRTLE", "PIKACHU"], correct: 1 },
    { q: "QUAL O NOME DO PERSONAGEM QUE USA UMA MÁSCARA DE FERRO?", options: ["BATMAN", "TONY STARK", "CLARK KENT", "PETER PARKER"], correct: 1 },
    { q: "QUAL O NOME DA CIDADE DO JOGO 'GTA VICE CITY'?", options: ["LOS SANTOS", "LIBERTY CITY", "VICE CITY", "GOTHAM"], correct: 2 },
    { q: "QUAL O NOME DO LÍDER DOS DECEPTICONS?", options: ["OPTIMUS", "BUMBLEBEE", "MEGATRON", "STARSQUEAM"], correct: 2 },
    { q: "QUAL É O NOME DA IRMÃ DA ELSA EM 'FROZEN'?", options: ["ANNA", "OLAF", "SVEN", "KRISTOFF"], correct: 0 },
    { q: "QUAL O NOME DO VILÃO DE 'MULAN'?", options: ["SHAN YU", "MUSHU", "IAGO", "JAFAR"], correct: 0 },
    { q: "QUAL O NOME DO PERSONAGEM QUE TEM GARRAS NAS MÃOS?", options: ["BATMAN", "WOLVERINE", "HULK", "THOR"], correct: 1 },
    { q: "QUAL O NOME DO JOGO ONDE VOCÊ SOBREVIVE A UM APOCALIPSE ZUMBI?", options: ["RESIDENT EVIL", "COD", "GTA", "MARIO"], correct: 0 },
    { q: "QUAL É O NOME DA MÃE DA BAMBI?", options: ["ELA NÃO TEM NOME", "NALA", "SARABI", "KIARA"], correct: 0 },
    { q: "QUAL O NOME DO PERSONAGEM QUE VIVE EM UM PÂNTANO?", options: ["SHREK", "FIONA", "BURRO", "DRAGÃO"], correct: 0 },
    { q: "QUAL O NOME DO VILÃO DE 'MORTAL KOMBAT' QUE É UM FEITICEIRO?", options: ["SUB-ZERO", "SCORPION", "QUAN CHI", "RAIDEN"], correct: 2 },
    { q: "QUAL O NOME DO MESTRE DO LUKE SKYWALKER?", options: ["OBI-WAN", "YODA", "AMBOS", "PALPATINE"], correct: 2 },
    { q: "QUAL O NOME DO FILME QUE TEM UM TÊNIS QUE AMARRA SOZINHO?", options: ["DE VOLTA PARA O FUTURO", "STAR WARS", "MATRIX", "ALIEN"], correct: 0 },
    { q: "QUAL O NOME DO PERSONAGEM QUE TEM UM LAÇO DA VERDADE?", options: ["WONDER WOMAN", "BATGIRL", "SUPERGIRL", "CATWOMAN"], correct: 0 },
    { q: "QUAL JOGO PERTENCE À EPIC GAMES?", options: ["FORTNITE", "MINECRAFT", "ROBLOX", "GTA"], correct: 0 },
    { q: "QUAL É A COR DO SABRE DO REY?", options: ["AZUL", "AMARELO", "AMBOS", "VERMELHO"], correct: 2 },
    { q: "QUAL O NOME DO VILÃO DE 'HOMEM-ARANHA 1' (2002)?", options: ["DOUTOR OCTOPUS", "DUENDE VERDE", "VENOM", "MISTÉRIO"], correct: 1 },
    { q: "QUAL O NOME DO PERSONAGEM QUE USA UM ESCUDO DE METAL?", options: ["GAVIÃO ARQUEIRO", "THOR", "CAPITÃO AMÉRICA", "IRON MAN"], correct: 2 },
    { q: "QUAL O NOME DO FILME QUE TEM UM PERSONAGEM CHAMADO OPTIMUS PRIME?", options: ["TRANSFORMERS", "CARROS", "WALL-E", "TOY STORY"], correct: 0 },
    { q: "QUAL O NOME DO LUGAR ONDE VIVE O REI ELFO EM O HOBBIT?", options: ["FLORESTA DAS TREVAS", "GONDOR", "MORDOR", "CONDADO"], correct: 0 },
    { q: "QUAL O NOME DO PERSONAGEM QUE TEM UM REATOR NO PEITO?", options: ["CAPITÃO AMÉRICA", "THOR", "HOMEM DE FERRO", "HULK"], correct: 2 },
    { q: "QUAL O NOME DO JOGO ONDE VOCÊ ESCALAVA PRÉDIOS EM PARIS?", options: ["ASSASSIN'S CREED UNITY", "HALO", "DOOM", "PORTAL"], correct: 0 },
    { q: "QUAL O NOME DO VILÃO DE 'VINGADORES: ERA DE ULTRON'?", options: ["THANOS", "LOKI", "ULTRON", "ZEMO"], correct: 2 },
    { q: "QUAL O NOME DO PERSONAGEM QUE É O DEUS DO TROVÃO?", options: ["THOR", "ODIN", "LOKI", "ZEUS"], correct: 0 },
    { q: "QUAL O NOME DO FILME QUE TEM A PERSONAGEM MOANA?", options: ["MOANA", "FROZEN", "SHREK", "TOY STORY"], correct: 0 },
    { q: "QUAL É O NOME DO VILÃO DE 'OS GOONIES'?", options: ["OS FRATELLI", "JASON", "FREDDY", "CHUCKY"], correct: 0 },
    { q: "QUAL É A COR DO SABRE DE LUZ DE LUKE EM 'O RETORNO DE JEDI'?", options: ["AZUL", "VERDE", "VERMELHO", "ROXO"], correct: 1 },
    { q: "QUAL É O NOME DO DRAGÃO DE 'A HISTÓRIA SEM FIM'?", options: ["FALCOR", "DROGON", "MUSHU", "SMAUG"], correct: 0 },
    { q: "QUEM É O CRIADOR DE 'STAR WARS'?", options: ["STEVEN SPIELBERG", "GEORGE LUCAS", "JAMES CAMERON", "JJ ABRAMS"], correct: 1 },
    { q: "QUAL É O NOME DO GATO DE 'ALICE NO PAÍS DAS MARAVILHAS'?", options: ["GATO DE BOTAS", "CHESHIRE", "TOM", "GARFIELD"], correct: 1 },
    { q: "QUAL É A IDENTIDADE SECRETA DA MULHER-MARAVILHA?", options: ["DIANA PRINCE", "CARA DANVERS", "NATASHA ROMANOFF", "WANDA MAXIMOFF"], correct: 0 },
    { q: "QUAL É O NOME DO CÃO DE 'TINTIM'?", options: ["MILU", "BIDU", "SNOOPY", "PLUTO"], correct: 0 },
    { q: "QUAL É O NOME DO VILÃO DE 'A BELA ADORMECIDA'?", options: ["URSULA", "MALEVOLA", "CRUELLA", "GOTHEL"], correct: 1 },
    { q: "EM 'THE LAST OF US', QUAL É O NOME DA MENINA?", options: ["ELLIE", "ABBY", "SARAH", "TESS"], correct: 0 },
    { q: "QUAL É O NOME DO PAI DE HARRY POTTER?", options: ["SIRIUS", "ALVO", "TIAGO", "SEVERO"], correct: 2 },
    { q: "QUAL É O NOME DO ROBÔ COMPANHEIRO DE WALL-E?", options: ["EVE", "ROSIE", "HAL", "R2"], correct: 0 },
    { q: "QUAL É O NOME DO JOGO ONDE VOCÊ ATIRA COM TINTA?", options: ["FORTNITE", "SPLATOON", "HALO", "OVERWATCH"], correct: 1 },
    { q: "QUAL É O NOME DO REINO DE THOR?", options: ["WAKANDA", "ASGARD", "MIDGARD", "XANDAR"], correct: 1 },
    { q: "QUAL É O NOME DO MESTRE DE 'KUNG FU PANDA'?", options: ["SHIFU", "PO", "TIGRESA", "TAI LUNG"], correct: 0 },
    { q: "QUAL É A COR DO POWER RANGER AZUL?", options: ["VERDE", "AZUL", "AMARELO", "PRETO"], correct: 1 },
    { q: "QUAL É O NOME DO VILÃO DE 'O ESTRANHO MUNDO DE JACK'?", options: ["OOGIE BOOGIE", "JACK", "SALLY", "ZERO"], correct: 0 },
    { q: "QUAL É O NOME DO PAI DO GOKU?", options: ["BARDOCK", "RADITZ", "VEGETA", "KING COLD"], correct: 0 },
    { q: "QUAL É O NOME DO JOGO DA NINTENDO COM LINGUAGEM DE SINAIS?", options: ["ZELDA", "METROID", "CELESTE", "SKYWARD SWORD"], correct: 0 },
    { q: "QUAL É O NOME DA VILÃ DE 'PEQUENA SEREIA'?", options: ["URSULA", "MALEVOLA", "MORGANNA", "HELGA"], correct: 0 },
    { q: "QUAL É O NOME DO FILHO DE NARUTO?", options: ["BORUTO", "HIMAWARI", "MINATO", "KAWAKI"], correct: 0 },
    { q: "QUAL É O NOME DO VILÃO DE 'KUNG FU PANDA 2'?", options: ["LORD SHEN", "TAI LUNG", "KAI", "SHIFU"], correct: 0 },
    { q: "QUAL É A COR DO SABRE DE LUZ DE DARTH MAUL?", options: ["AZUL", "VERDE", "ROXO", "VERMELHO"], correct: 3 },
    { q: "QUAL É O NOME DO CÃO DE 'DOCE LAR'?", options: ["BIDU", "MARLEY", "HATCHIKO", "BEETHOVEN"], correct: 1 },
    { q: "QUAL É O NOME DO JOGO DE CARTAS DE 'THE WITCHER'?", options: ["GWENT", "HEARTHSTONE", "POKER", "UNO"], correct: 0 },
    { q: "QUAL É O NOME DO VILÃO DE 'X-MEN' QUE CONTROLA METAL?", options: ["MAGNETO", "XAVIER", "LOGAN", "FERA"], correct: 0 },
    { q: "QUAL É O NOME DO ROBÔ DE 'PERDIDOS NO ESPAÇO'?", options: ["ROBÔ", "HAL", "R2", "TARS"], correct: 0 },
    { q: "QUAL É O NOME DA CIDADE DE 'SOUTH PARK'?", options: ["SPRINGFIELD", "SOUTH PARK", "QUAHOG", "GOTHAM"], correct: 1 },
    { q: "QUAL É O NOME DO VILÃO DE 'MEU MALVADO FAVORITO'?", options: ["VECTOR", "GRU", "EL MACHO", "BALTHAZAR"], correct: 0 },
    { q: "QUAL É A COR DA CAPA DO DOUTOR ESTRANHO?", options: ["AZUL", "VERMELHA", "AMARELA", "ROXA"], correct: 1 },
    { q: "QUAL É O NOME DO JOGO ONDE VOCÊ É UM GATO?", options: ["STRAY", "CAT QUEST", "ROBLOX", "MINECRAFT"], correct: 0 },
    { q: "QUAL É O NOME DO PAI DA ARIEL?", options: ["TRITÃO", "SEBASTIÃO", "LINGUADO", "ERIC"], correct: 0 },
    { q: "QUAL É O NOME DO VILÃO DE 'HULK'?", options: ["ABOMINAÇÃO", "LOKI", "THANOS", "VENOM"], correct: 0 },
    { q: "QUAL É O NOME DO JOGO COM O PERSONAGEM ALOY?", options: ["HORIZON", "ZELDA", "HALO", "UNARTED"], correct: 0 },
    { q: "QUAL É O NOME DO ROBÔ COMPANHEIRO DE MEGA MAN?", options: ["RUSH", "ROLL", "PROTOMAN", "BASS"], correct: 0 },
    { q: "QUAL É A COR DO PERSONAGEM YOSHI?", options: ["VERMELHO", "VERDE", "AZUL", "AMARELO"], correct: 1 },
    { q: "QUAL É O NOME DO VILÃO DE 'SEXTA-FEIRA 13'?", options: ["JASON", "FREDDY", "CHUCKY", "MICHAEL"], correct: 0 },
    { q: "QUAL É O NOME DO JOGO ONDE VOCÊ DANÇA?", options: ["JUST DANCE", "FORTNITE", "FIFA", "GTA"], correct: 0 },
    { q: "QUAL É O NOME DO PAI DO SIMBA?", options: ["MUFASA", "SCAR", "PUMBA", "TIMÃO"], correct: 0 },
    { q: "QUAL É O NOME DA VILÃ DE '101 DÁLMATAS'?", options: ["CRUELLA", "MALEVOLA", "URSULA", "GOTHEL"], correct: 0 },
    { q: "QUAL É O NOME DO JOGO DA CAPCOM COM ZUMBIS?", options: ["RESIDENT EVIL", "SILENT HILL", "DOOM", "HALO"], correct: 0 },
    { q: "QUAL É O NOME DO PERSONAGEM QUE DIZ 'EU SOU O HOMEM DE FERRO'?", options: ["TONY STARK", "STEVE ROGERS", "BRUCE BANNER", "THOR"], correct: 0 },
    { q: "QUAL É O NOME DO VILÃO DE 'A MÚMIA'?", options: ["IMHOTEP", "ANCK-SU-NAMUN", "SCORPION KING", "RICK"], correct: 0 },
    { q: "QUAL É A COR DO SABRE DE LUZ DO AHSOKA TANO?", options: ["BRANCO", "AZUL", "VERDE", "AMARELO"], correct: 0 },
    { q: "QUAL É O NOME DO JOGO COM O PERSONAGEM NATHAN DRAKE?", options: ["UNCHARTED", "TOMB RAIDER", "HALO", "DOOM"], correct: 0 },
    { q: "QUAL É O NOME DO PAI DO BAMBI?", options: ["O GRANDE PRÍNCIPE", "TAMBOR", "FLOR", "FALINE"], correct: 0 },
    { q: "QUAL É O NOME DO VILÃO DE 'GHOSTBUSTERS'?", options: ["GOZER", "STAY PUFT", "SLIMER", "VIGO"], correct: 0 },
    { q: "QUAL É O NOME DO JOGO ONDE VOCÊ CONSTRÓI CIDADES?", options: ["SIMCITY", "MINECRAFT", "ROBLOX", "GTA"], correct: 0 },
    { q: "QUAL É O NOME DO ROBÔ DE 'STAR WARS' DOURADO?", options: ["C-3PO", "R2-D2", "BB-8", "K-2SO"], correct: 0 },
    { q: "QUAL É A COR DO CABELO DA ARIEL?", options: ["LOIRO", "PRETO", "RUIVO", "AZUL"], correct: 2 },
    { q: "QUAL É O NOME DO JOGO ONDE VOCÊ ATIRA EM COGUMELOS?", options: ["MARIO", "ZELDA", "SONIC", "PAC-MAN"], correct: 0 },
    { q: "QUAL É O NOME DO VILÃO DE 'PETER PAN'?", options: ["CAPITÃO GANCHO", "SMEE", "TICK TOCK", "PAN"], correct: 0 },
    { q: "QUAL É A COR DO SABRE DE LUZ DO COUNT DOOKU?", options: ["AZUL", "VERDE", "ROXO", "VERMELHO"], correct: 3 },
    { q: "QUAL É O NOME DO DRAGÃO DE 'A BELA ADORMECIDA'?", options: ["MALEVOLA", "URSULA", "MUSHU", "DROGON"], correct: 0 },
    { q: "QUEM É O CRIADOR DE 'MINECRAFT'?", options: ["NOTCH", "JEB", "BILL GATES", "ELON MUSK"], correct: 0 },
    { q: "QUAL É O NOME DO PERSONAGEM QUE USA UMA MÁSCARA DE GÁS EM 'BATMAN'?", options: ["CORINGA", "ESPANTALHO", "BANE", "PINGUIM"], correct: 1 },
    { q: "QUAL É A IDENTIDADE SECRETA DO FLASH?", options: ["BARRY ALLEN", "WALLY WEST", "CLARK KENT", "BRUCE WAYNE"], correct: 0 },
    { q: "QUAL É O NOME DO CÃO DE 'FAMILY GUY'?", options: ["STEWIE", "BRIAN", "CHRIS", "PETER"], correct: 1 },
    { q: "QUAL É O NOME DO VILÃO DE 'FROZEN'?", options: ["HANS", "OLAF", "KRISTOFF", "SVEN"], correct: 0 },
    { q: "EM 'THE WITCHER', QUAL É O NOME DA FEITICEIRA AMADA POR GERALT?", options: ["YENNEFER", "TRISS", "CIRI", "KEIRA"], correct: 0 },
    { q: "QUAL É O NOME DO PADRINHO DE HARRY POTTER?", options: ["LUPIN", "SNAPE", "SIRIUS BLACK", "HAGRID"], correct: 2 },
    { q: "QUAL É O NOME DO ROBÔ COMPANHEIRO DE HIRO EM 'BIG HERO 6'?", options: ["BAYMAX", "WALL-E", "R2", "DATA"], correct: 0 },
    { q: "QUAL É O JOGO ONDE VOCÊ LUTA COM PERSONAGENS DA DISNEY?", options: ["KINGDOM HEARTS", "ZELDA", "HALO", "FINAL FANTASY"], correct: 0 },
    { q: "QUAL É O NOME DO PLANETA NATAL DE THOR?", options: ["TERRA", "ASGARD", "SAKAAR", "VORMIR"], correct: 1 },
    { q: "QUAL É O NOME DO MESTRE DE 'PO' EM KUNG FU PANDA?", options: ["SHIFU", "OOGWAY", "TIGRESA", "ZEN"], correct: 0 },
    { q: "QUAL É A COR DO POWER RANGER AMARELO?", options: ["ROSA", "AZUL", "AMARELO", "PRETO"], correct: 2 },
    { q: "QUAL É O NOME DO VILÃO DE 'OS CAÇA-FANTASMAS'?", options: ["GELEIA", "GOZER", "STAY PUFT", "VIGO"], correct: 1 },
    { q: "QUAL É O NOME DO PAI DO VEGETA?", options: ["REI VEGETA", "BARDOCK", "GOKU", "FREEZA"], correct: 0 },
    { q: "QUAL É O JOGO ONDE VOCÊ CONTROLA UM PÁSSARO CONTRA PORCOS?", options: ["ANGRY BIRDS", "FLAPPY BIRD", "SONIC", "MARIO"], correct: 0 },
    { q: "QUAL É O NOME DA VILÃ DE 'TANGLED' (ENROLADOS)?", options: ["MALEVOLA", "GOTHEL", "URSULA", "IZMA"], correct: 1 },
    { q: "QUAL É O NOME DO FILHO DE BORUTO?", options: ["ELE NÃO TEM FILHO", "NARUTO", "MINATO", "KAWAKI"], correct: 0 },
    { q: "QUAL É O NOME DO VILÃO DE 'SCOOBY-DOO 2'?", options: ["MASCARADO", "DRÁCULA", "LOBISOMEM", "FANTASMA"], correct: 0 },
    { q: "QUAL É A COR DO SABRE DE LUZ DO KYLO REN?", options: ["AZUL", "VERDE", "VERMELHO", "AMARELO"], correct: 2 },
    { q: "QUAL É O NOME DO CÃO DE 'TOY STORY'?", options: ["SLINKY", "BUSTER", "PLUTO", "BIDU"], correct: 0 },
    { q: "QUAL É O JOGO DE TIRO DA BLIZZARD?", options: ["OVERWATCH", "HALO", "DOOM", "VALORANT"], correct: 0 },
    { q: "QUAL É O NOME DO VILÃO DE 'X-MEN' QUE É AZUL E SE TELEPORTA?", options: ["NOTURNO (HERÓI)", "MÍSTICA", "FESTA", "FÊNIX"], correct: 0 },
    { q: "QUAL É O NOME DO ROBÔ DE 'LOST IN SPACE'?", options: ["ROBÔ B9", "TARS", "HAL", "WALL-E"], correct: 0 },
    { q: "QUAL É O NOME DA CIDADE DE 'SÉRIE DARK'?", options: ["WINDEN", "GOTHAM", "SPRINGFIELD", "DERRY"], correct: 0 },
    { q: "QUAL É O NOME DO VILÃO DE 'MEU MALVADO FAVORITO 2'?", options: ["EL MACHO", "VECTOR", "BALTHAZAR", "GRU"], correct: 0 },
    { q: "QUAL É A COR DO REATOR ARC NO PEITO DE TONY STARK?", options: ["VERDE", "VERMELHO", "AZUL", "AMARELO"], correct: 2 },
    { q: "QUAL É O JOGO ONDE VOCÊ É UM GANSO?", options: ["UNTITLED GOOSE GAME", "STRAY", "ROBLOX", "MINECRAFT"], correct: 0 },
    { q: "QUAL É O NOME DO PAI DA BELA EM 'A BELA E A FERA'?", options: ["MAURICE", "GASTON", "LUMIERE", "ADAM"], correct: 0 },
    { q: "QUAL É O NOME DO VILÃO DE 'AQUAMAN'?", options: ["ARRAIA NEGRA", "LOKI", "THANOS", "OCEAN MASTER"], correct: 3 },
    { q: "QUAL É O JOGO COM O PERSONAGEM ELLY?", options: ["THE LAST OF US", "ZELDA", "HORIZON", "HALO"], correct: 0 },
    { q: "QUAL É O NOME DO ROBÔ COMPANHEIRO DE SAMUS?", options: ["ELA NÃO TEM ROBÔ", "RUSH", "ROLL", "EVE"], correct: 0 },
    { q: "QUAL É A COR DO PERSONAGEM WARIO?", options: ["AMARELO", "ROXO", "VERMELHO", "VERDE"], correct: 0 },
    { q: "QUAL É O NOME DO VILÃO DE 'A HORA DO PESADELO'?", options: ["FREDDY KRUEGER", "JASON", "CHUCKY", "MICHAEL"], correct: 0 },
    { q: "QUAL É O JOGO ONDE VOCÊ DIRIGE CARROS COM FOGUETES?", options: ["ROCKET LEAGUE", "FIFA", "GTA", "NEED FOR SPEED"], correct: 0 },
    { q: "QUAL É O NOME DO PAI DO HERCULES?", options: ["ZEUS", "HADES", "ARES", "APOLO"], correct: 0 },
    { q: "QUAL É O NOME DA VILÃ DE 'ALICE NO PAÍS DAS MARAVILHAS'?", options: ["RAINHA DE COPAS", "MALEVOLA", "URSULA", "CRUELLA"], correct: 0 },
    { q: "QUAL É O JOGO DA VALVE ONDE VOCÊ LUTA CONTRA ZUMBIS?", options: ["LEFT 4 DEAD", "DOOM", "RESIDENT EVIL", "HALO"], correct: 0 },
    { q: "QUAL É O NOME DO PERSONAGEM QUE USA UM MARTELO E É UM SAPO?", options: ["THROG", "THOR", "HULK", "GROOT"], correct: 0 },
    { q: "QUAL É O NOME DO VILÃO DE 'SHARK TALE' (ESPANTALHÃO)?", options: ["DON LINO", "OSCAR", "LENNY", "SYKES"], correct: 0 },
    { q: "QUAL É A COR DO SABRE DE LUZ DO SAMUEL L. JACKSON?", options: ["ROXO", "AZUL", "VERDE", "VERMELHO"], correct: 0 },
    { q: "QUAL É O JOGO COM O PERSONAGEM JOEL?", options: ["THE LAST OF US", "UNCHARTED", "HALO", "DOOM"], correct: 0 },
    { q: "QUAL É O NOME DO PAI DA CINDERELA?", options: ["ELE MORRE NO INÍCIO", "REI", "GRÃO-DUQUE", "MENSAGEIRO"], correct: 0 },
    { q: "QUAL É O NOME DO VILÃO DE 'THE FLASH'?", options: ["REVERSO", "CORINGA", "LOKI", "BANE"], correct: 0 },
    { q: "QUAL É O JOGO ONDE VOCÊ É UM MÉDICO NO ESPAÇO?", options: ["DEAD SPACE", "HALO", "DOOM", "STARFIELD"], correct: 0 },
    { q: "QUAL É O NOME DO ROBÔ DE 'STAR WARS' BOLA?", options: ["BB-8", "R2-D2", "C-3PO", "K-2SO"], correct: 0 },
    { q: "QUAL É A COR DO CABELO DA RAPUNZEL?", options: ["LOIRO", "PRETO", "RUIVO", "AZUL"], correct: 0 },
    { q: "QUAL É O JOGO ONDE VOCÊ ENTRA EM SONHOS?", options: ["DREAMS", "MARIO", "ZELDA", "SONIC"], correct: 0 },
    { q: "QUAL É O NOME DO VILÃO DE 'A PRINCESA E O SAPO'?", options: ["DR. FACILIER", "JAFAR", "HADES", "GASTON"], correct: 0 },
    { q: "QUAL É A COR DO SABRE DE LUZ DO GENERAL GRIEVOUS?", options: ["AZUL E VERDE", "VERMELHO", "ROXO", "AMARELO"], correct: 0 },
    { q: "QUAL É O NOME DO DRAGÃO DE 'A BELA E A FERA'?", options: ["NÃO TEM DRAGÃO", "MUSHU", "DROGON", "SMAUG"], correct: 0 },
    { q: "QUEM É O CRIADOR DE 'ROBLOX'?", options: ["DAVID BASZUCKI", "NOTCH", "MARK ZUCKERBERG", "BILL GATES"], correct: 0 },
    { q: "QUAL O NOME DO PERSONAGEM QUE USA UMA SERRA ELÉTRICA NO LUGAR DA MÃO?", options: ["ASH WILLIAMS", "JASON", "FREDDY", "LEATHERFACE"], correct: 0 },
    { q: "QUAL É A IDENTIDADE SECRETA DO LANTERNA VERDE?", options: ["HAL JORDAN", "BARRY ALLEN", "CLARK KENT", "BRUCE WAYNE"], correct: 0 },
    { q: "QUAL É O NOME DO CÃO DE 'ADVENTURE TIME'?", options: ["JAKE", "FINN", "BIDU", "PLUTO"], correct: 0 },
    { q: "QUAL É O NOME DO VILÃO DE 'RATATOUILLE'?", options: ["SKINNER", "REMY", "LINGUINI", "EGO"], correct: 0 },
    { q: "EM 'CYBERPUNK 2077', QUAL É O NOME DO PERSONAGEM DE KEANU REEVES?", options: ["JOHNNY SILVERHAND", "V", "JACKIE", "DEX"], correct: 0 },
    { q: "QUAL É O NOME DO ELFO DOMÉSTICO DE HARRY POTTER?", options: ["DOBBY", "MONSTRO", "WINKY", "HOKEY"], correct: 0 },
    { q: "QUAL É O NOME DO ROBÔ COMPANHEIRO DE RATCHET?", options: ["CLANK", "JAK", "DAXTER", "BOT"], correct: 0 },
    { q: "QUAL O JOGO ONDE VOCÊ SOBREVIVE EM UMA ILHA COM DINOSSAUROS?", options: ["ARK: SURVIVAL", "MINECRAFT", "ZELDA", "HALO"], correct: 0 },
    { q: "QUAL É O NOME DO PLANETA NATAL DO THANOS?", options: ["TITÃ", "TERRA", "ZEN-WHOBERI", "VORMIR"], correct: 0 },
    { q: "QUAL É O NOME DO MESTRE DE 'PO' QUE É UMA TARTARUGA?", options: ["OOGWAY", "SHIFU", "ZEN", "KAI"], correct: 0 },
    { q: "QUAL É A COR DO POWER RANGER PRETO?", options: ["PRETO", "AZUL", "AMARELO", "VERDE"], correct: 0 },
    { q: "QUAL É O NOME DO VILÃO DE 'TERMINATOR'?", options: ["T-800", "SARAH CONNOR", "JOHN CONNOR", "SKYNET"], correct: 3 },
    { q: "QUAL É O NOME DO IRMÃO DO VEGETA?", options: ["TARBLE", "RADITZ", "GOKU", "NAPPA"], correct: 0 },
    { q: "QUAL O JOGO ONDE VOCÊ É UM PÁSSARO QUE PASSA POR CANOS?", options: ["FLAPPY BIRD", "ANGRY BIRDS", "SONIC", "MARIO"], correct: 0 },
    { q: "QUAL É O NOME DA VILÃ DE 'A NOVA ONDA DO IMPERADOR'?", options: ["YZMA", "MALEVOLA", "URSULA", "GOTHEL"], correct: 0 },
    { q: "QUAL É O NOME DO PAI DO NARUTO?", options: ["MINATO", "JIRAIYA", "KAKASHI", "HIRUZEN"], correct: 0 },
    { q: "QUAL É O NOME DO VILÃO DE 'MONSTROS S.A.'?", options: ["RANDALL", "SULLY", "MIKE", "BOO"], correct: 0 },
    { q: "QUAL É A COR DO SABRE DE LUZ DO QUI-GON JINN?", options: ["VERDE", "AZUL", "VERMELHO", "ROXO"], correct: 0 },
    { q: "QUAL É O NOME DO CÃO DE 'COCO' (A VIDA É UMA FESTA)?", options: ["DANTE", "MIGUEL", "HECTOR", "ERNESTO"], correct: 0 },
    { q: "QUAL O JOGO DE LUTA DA CAPCOM?", options: ["STREET FIGHTER", "TEKKEN", "MORTAL KOMBAT", "SMASH BROS"], correct: 0 },
    { q: "QUAL É O NOME DO VILÃO DE 'WATCHMEN' QUE É UM GÊNIO?", options: ["OZYMANDIAS", "RORSCHACH", "MANHATTAN", "CORUJA"], correct: 0 },
    { q: "QUAL É O NOME DO ROBÔ DE 'WALL-E' QUE LIMPA TUDO?", options: ["M-O", "EVE", "AUTO", "WALL-E"], correct: 0 },
    { q: "QUAL É O NOME DA CIDADE DE 'SÉRIE STRANGER THINGS'?", options: ["HAWKINS", "DERRY", "WINDEN", "GOTHAM"], correct: 0 },
    { q: "QUAL É O NOME DO VILÃO DE 'MEU MALVADO FAVORITO 3'?", options: ["BALTHAZAR BRATT", "VECTOR", "EL MACHO", "DR. NEFARIO"], correct: 0 },
    { q: "QUAL É A COR DA JOIA DA REALIDADE NA MARVEL?", options: ["VERMELHA", "AZUL", "VERDE", "AMARELA"], correct: 0 },
    { q: "QUAL O JOGO ONDE VOCÊ É UM TUBARÃO?", options: ["MANEATER", "STRAY", "ROBLOX", "MINECRAFT"], correct: 0 },
    { q: "QUAL É O NOME DO PAI DA TIARA EM 'A PRINCESA E O SAPO'?", options: ["JAMES", "FACILIER", "LAWRENCE", "NAVEEN"], correct: 0 },
    { q: "QUAL É O NOME DO VILÃO DE 'SHAZAM'?", options: ["DR. SIVANA", "ADÃO NEGRO", "LOKI", "THANOS"], correct: 0 },
    { q: "QUAL O JOGO COM O PERSONAGEM KRATOS NO ESPAÇO?", options: ["ELE NÃO ESTÁ NO ESPAÇO", "HALO", "DOOM", "STARFIELD"], correct: 0 },
    { q: "QUAL É O NOME DO ROBÔ COMPANHEIRO DE 'SNAKE'?", options: ["METAL GEAR", "RUSH", "ROLL", "EVE"], correct: 0 },
    { q: "QUAL É A COR DO PERSONAGEM WALUIGI?", options: ["ROXO", "AMARELO", "VERDE", "AZUL"], correct: 0 },
    { q: "QUAL É O NOME DO VILÃO DE 'PANICO'?", options: ["GHOSTFACE", "JASON", "FREDDY", "CHUCKY"], correct: 0 },
    { q: "QUAL O JOGO ONDE VOCÊ JOGA FUTEBOL COM CARROS?", options: ["ROCKET LEAGUE", "FIFA", "GTA", "ASPHALT"], correct: 0 },
    { q: "QUAL É O NOME DO PAI DA MULHER-MARAVILHA?", options: ["ZEUS", "ARES", "APOLO", "HADES"], correct: 0 },
    { q: "QUAL É O NOME DA VILÃ DE 'ROBIN HOOD' (DISNEY)?", options: ["PRÍNCIPE JOÃO", "MALEVOLA", "URSULA", "CRUELLA"], correct: 0 },
    { q: "QUAL O JOGO ONDE VOCÊ É UM GATO NO APOCALIPSE?", options: ["STRAY", "DOOM", "RESIDENT EVIL", "HALO"], correct: 0 },
    { q: "QUAL É O NOME DO PERSONAGEM QUE USA UM ESCUDO E É UM COELHO?", options: ["CAPITÃO CENOURA", "THOR", "HULK", "MARIO"], correct: 0 },
    { q: "QUAL É O NOME DO VILÃO DE 'MADAGASCAR 3'?", options: ["CAPITÃ DUBOIS", "MOTO MOTO", "ALEX", "MAURICE"], correct: 0 },
    { q: "QUAL É A COR DO SABRE DE LUZ DO PLO KOON?", options: ["AZUL", "VERDE", "AMARELO", "VERMELHO"], correct: 0 },
    { q: "QUAL O JOGO COM O PERSONAGEM ARTHUR MORGAN?", options: ["RED DEAD REDEMPTION 2", "UNCHARTED", "GTA", "DOOM"], correct: 0 },
    { q: "QUAL É O NOME DO PAI DA BELA ADORMECIDA?", options: ["REI ESTEVÃO", "REI HUBERT", "MAURICE", "REI TRITÃO"], correct: 0 },
    { q: "QUAL É O NOME DO VILÃO DE 'V DE VINGANÇA'?", options: ["ALTO CHANCELER", "V", "EVEY", "FINCH"], correct: 0 },
    { q: "QUAL O JOGO ONDE VOCÊ É UM CAÇADOR DE MONSTROS?", options: ["MONSTER HUNTER", "HALO", "DOOM", "ZELDA"], correct: 0 },
    { q: "QUAL É O NOME DO ROBÔ DE 'STAR WARS' ALTO E PRETO?", options: ["K-2SO", "R2-D2", "C-3PO", "BB-8"], correct: 0 },
    { q: "QUAL É A COR DO CABELO DA MERIDA?", options: ["RUIVO", "LOIRO", "PRETO", "AZUL"], correct: 0 },
    { q: "QUAL O JOGO ONDE VOCÊ É UM PÃO?", options: ["I AM BREAD", "MARIO", "ZELDA", "SONIC"], correct: 0 },
    { q: "QUAL É O NOME DO VILÃO DE 'ENCANTO'?", options: ["NÃO HÁ VILÃO REAL", "BRUNO", "ABUELA", "MARIANO"], correct: 0 },
    { q: "QUAL É A COR DO SABRE DE LUZ DO ASYLA VENTRESS?", options: ["VERMELHO", "AZUL", "VERDE", "AMARELO"], correct: 0 },
    { q: "QUAL É O NOME DO DRAGÃO DE 'A PRINCESA E O SAPO'?", options: ["NÃO TEM DRAGÃO", "MUSHU", "DROGON", "RAY"], correct: 0 },
    { q: "QUEM É O CRIADOR DE 'PAC-MAN'?", options: ["TORU IWATANI", "SHIGERU MIYAMOTO", "HIDEO KOJIMA", "NOTCH"], correct: 0 },
    { q: "QUAL PERSONAGEM USA UMA LUVA COM LÂMINAS NOS SONHOS?", options: ["FREDDY KRUEGER", "JASON", "CHUCKY", "PINHEAD"], correct: 0 },
    { q: "QUAL É A IDENTIDADE SECRETA DO ARQUEIRO VERDE?", options: ["OLIVER QUEEN", "BARRY ALLEN", "HAL JORDAN", "BRUCE WAYNE"], correct: 0 },
    { q: "QUAL É O NOME DO CÃO DE 'FAMILY GUY'?", options: ["BRIAN", "STEWIE", "CHRIS", "PETER"], correct: 0 },
    { q: "QUAL É O NOME DO VILÃO DE 'VIDA DE INSETO'?", options: ["HOPPER", "FLIK", "DOT", "MOLT"], correct: 0 },
    { q: "EM 'DETROIT: BECOME HUMAN', QUAL O NOME DO ANDROIDE POLICIAL?", options: ["CONNOR", "MARCUS", "KARA", "ALICE"], correct: 0 },
    { q: "QUAL É O NOME DO DONO DO BURRO EM 'SHREK'?", options: ["SHREK", "FIONA", "FARQUAAD", "ENCANTADO"], correct: 0 },
    { q: "QUAL É O NOME DO ROBÔ DE 'METRO 2033'?", options: ["NÃO TEM ROBÔS", "TARS", "DATA", "R2"], correct: 0 },
    { q: "EM QUE JOGO VOCÊ CONTROLA UM GRUPO DE SOBREVIVENTES NO MAR?", options: ["RAFT", "MINECRAFT", "ZELDA", "HALO"], correct: 0 },
    { q: "QUAL É O NOME DO PLANETA DE ORIGEM DA GAMORA?", options: ["ZEN-WHOBERI", "TITÃ", "TERRA", "XANDAR"], correct: 0 },
    { q: "QUAL É O NOME DO MESTRE DE 'PO' QUE É UM PAVÃO?", options: ["LORD SHEN", "SHIFU", "OOGWAY", "KAI"], correct: 0 },
    { q: "QUAL É A COR DO POWER RANGER BRANCO?", options: ["BRANCO", "PRETO", "AZUL", "VERDE"], correct: 0 },
    { q: "QUAL É O NOME DO VILÃO DE 'ROBOCOP'?", options: ["CLARENCE BODDICKER", "ALEX MURPHY", "LEWIS", "ED-209"], correct: 3 },
    { q: "QUAL É O NOME DO PAI DO TRUNKS?", options: ["VEGETA", "GOKU", "GOHAN", "PICCOLO"], correct: 0 },
    { q: "EM QUE JOGO VOCÊ É UM PÃO QUE QUER VIRAR TORRADA?", options: ["I AM BREAD", "MARIO", "ZELDA", "SONIC"], correct: 0 },
    { q: "QUAL É O NOME DA VILÃ DE 'A PEQUENA SEREIA'?", options: ["URSULA", "MALEVOLA", "YZMA", "GOTHEL"], correct: 0 },
    { q: "QUAL É O NOME DA MÃE DO NARUTO?", options: ["KUSHINA", "HINATA", "SAKURA", "TSUNADE"], correct: 0 },
    { q: "QUAL É O NOME DO VILÃO DE 'UP: ALTAS AVENTURAS'?", options: ["CHARLES MUNTZ", "DUG", "RUSSELL", "KEVIN"], correct: 0 },
    { q: "QUAL É A COR DO SABRE DE LUZ DO CAL KESTIS?", options: ["AZUL (INICIAL)", "VERMELHO", "ROXO", "BRANCO"], correct: 0 },
    { q: "QUAL É O NOME DO CÃO DE 'GRINCH'?", options: ["MAX", "BIDU", "PLUTO", "SNOOPY"], correct: 0 },
    { q: "QUAL JOGO DE LUTA TEM O PERSONAGEM SCORPION?", options: ["MORTAL KOMBAT", "STREET FIGHTER", "TEKKEN", "SMASH BROS"], correct: 0 },
    { q: "QUAL É O NOME DO VILÃO DE 'HOMEM-ARANHA: NO ARANHAVERSO'?", options: ["REI DO CRIME", "DUENDE", "VENOM", "MISTÉRIO"], correct: 0 },
    { q: "QUAL É O NOME DO ROBÔ DE 'PROMETHEUS'?", options: ["DAVID", "HAL", "TARS", "DATA"], correct: 0 },
    { q: "QUAL É O NOME DA CIDADE DE 'SÉRIE TWIN PEAKS'?", options: ["TWIN PEAKS", "HAWKINS", "DERRY", "WINDEN"], correct: 0 },
    { q: "QUAL É O NOME DO VILÃO DE 'PADDINGTON'?", options: ["MILLICENT CLYDE", "GRU", "VECTOR", "EL MACHO"], correct: 0 },
    { q: "QUAL É A COR DA JOIA DO PODER NA MARVEL?", options: ["ROXA", "AZUL", "VERDE", "VERMELHA"], correct: 0 },
    { q: "EM QUE JOGO VOCÊ É UM POMBO QUE CAUSA CAOS?", options: ["PIGEON SIMULATOR", "STRAY", "ROBLOX", "MINECRAFT"], correct: 0 },
    { q: "QUAL É O NOME DO PAI DA MOANA?", options: ["TUI", "MAUI", "TAMATOA", "HEIHEI"], correct: 0 },
    { q: "QUAL É O NOME DO VILÃO DE 'WONDER WOMAN 1984'?", options: ["MAXWELL LORD", "ARES", "LOKI", "THANOS"], correct: 0 },
    { q: "QUAL JOGO TEM O PERSONAGEM KRATOS NA MITOLOGIA NÓRDICA?", options: ["GOD OF WAR (2018)", "HALO", "DOOM", "ZELDA"], correct: 0 },
    { q: "QUAL É O NOME DO ROBÔ COMPANHEIRO DE 'SNAKE' EM MGS4?", options: ["METAL GEAR MK. II", "RUSH", "ROLL", "EVE"], correct: 0 },
    { q: "QUAL É A COR DO PERSONAGEM TOAD?", options: ["BRANCO E VERMELHO", "AZUL", "VERDE", "AMARELO"], correct: 0 },
    { q: "QUAL É O NOME DO VILÃO DE 'SCREAM'?", options: ["GHOSTFACE", "JASON", "FREDDY", "CHUCKY"], correct: 0 },
    { q: "EM QUE JOGO VOCÊ É UM CIRURGIÃO ATRAPALHADO?", options: ["SURGEON SIMULATOR", "FIFA", "GTA", "MINECRAFT"], correct: 0 },
    { q: "QUAL É O NOME DO PAI DO AQUAMAN?", options: ["TOM CURRY", "ZEUS", "ORM", "TRITÃO"], correct: 0 },
    { q: "QUAL É O NOME DO VILÃO DE 'MOGLI'?", options: ["SHERE KHAN", "BALU", "BAGUERA", "KAA"], correct: 0 },
    { q: "EM QUE JOGO VOCÊ É UM CABRITO QUE CAUSA CAOS?", options: ["GOAT SIMULATOR", "DOOM", "RESIDENT EVIL", "HALO"], correct: 0 },
    { q: "QUAL É O NOME DO PERSONAGEM QUE É UM PATO HERÓI?", options: ["DARKWING DUCK", "THOR", "HULK", "MARIO"], correct: 0 },
    { q: "QUAL É O NOME DO VILÃO DE 'KUNG FU PANDA 3'?", options: ["KAI", "TAI LUNG", "LORD SHEN", "SHIFU"], correct: 0 },
    { q: "QUAL É A COR DO SABRE DE LUZ DO LUMIYA?", options: ["CHICOTE DE LUZ VERMELHO", "AZUL", "VERDE", "AMARELO"], correct: 0 },
    { q: "QUAL JOGO TEM O PERSONAGEM JOHN MARSTON?", options: ["RED DEAD REDEMPTION", "UNCHARTED", "GTA", "DOOM"], correct: 0 },
    { q: "QUAL É O NOME DO PAI DA BRANCA DE NEVE?", options: ["REI", "CAÇADOR", "ANÃO", "PRÍNCIPE"], correct: 0 },
    { q: "QUAL É O NOME DO VILÃO DE 'INCEPTION'?", options: ["NÃO TEM UM VILÃO FÍSICO", "COBB", "MAL", "SAITO"], correct: 2 },
    { q: "EM QUE JOGO VOCÊ É UM GUERREIRO DE PAPEL?", options: ["PAPER MARIO", "HALO", "DOOM", "ZELDA"], correct: 0 },
    { q: "QUAL É O NOME DO ROBÔ DE 'STAR WARS' DE SUCATA?", options: ["CHOPPER", "R2-D2", "C-3PO", "BB-8"], correct: 0 },
    { q: "QUAL É A COR DO CABELO DA ELSA?", options: ["PLATINADO", "LOIRO", "PRETO", "RUIVO"], correct: 0 },
    { q: "EM QUE JOGO VOCÊ É UM GANSO EM UMA VILA?", options: ["UNTITLED GOOSE GAME", "MARIO", "ZELDA", "SONIC"], correct: 0 }
];