const geografiaData = [
    { q: "QUAL A CAPITAL DO BRASIL", options: ["RIO DE JANEIRO", "SÃO PAULO", "BRASÍLIA", "SALVADOR"], correct: 2 },
    { q: "QUAL A CAPITAL DA FRANÇA", options: ["LONDRES", "MADRI", "PARIS", "ROMA"], correct: 2 },
    { q: "TÓQUIO É A CAPITAL DE QUAL PAÍS", options: ["CHINA", "JAPÃO", "COREIA DO SUL", "TAIWAN"], correct: 1 },
    { q: "QUAL A CAPITAL DA ARGENTINA", options: ["SANTIAGO", "MONTEVIDÉU", "BUENOS AIRES", "LIMA"], correct: 2 },
    { q: "LONDRES É A CAPITAL DE ONDE", options: ["EUA", "INGLATERRA", "CANADÁ", "AUSTRÁLIA"], correct: 1 },
    { q: "QUAL A CAPITAL DOS wESTADOS UNIDOS", options: ["NEW YORK", "WASHINGTON D.C.", "MIAMI", "LOS ANGELES"], correct: 1 },
    { q: "LISBOA É A CAPITAL DE QUAL PAÍS", options: ["ESPANHA", "PORTUGAL", "ITÁLIA", "FRANÇA"], correct: 1 },
    { q: "QUAL A CAPITAL DA ITÁLIA", options: ["MILÃO", "VENEZA", "ROMA", "NÁPOLES"], correct: 2 },
    { q: "MOSCOU É A CAPITAL DE ONDE", options: ["UCRÂNIA", "RÚSSIA", "POLÔNIA", "ALEMANHA"], correct: 1 },
    { q: "QUAL A CAPITAL DA CHINA", options: ["XANGAI", "PEQUIM", "HONG KONG", "TAIPÉ"], correct: 1 },
    { q: "BERLIM É A CAPITAL DE QUAL PAÍS", options: ["ÁUSTRIA", "ALEMANHA", "SUIÇA", "BÉLGICA"], correct: 1 },
    { q: "QUAL A CAPITAL DO MÉXICO", options: ["CANCÚN", "CIDADE DO MÉXICO", "GUADALAJARA", "MONTERREY"], correct: 1 },
    { q: "QUAL A CAPITAL DO EGITO", options: ["CAIRO", "ALEXANDRIA", "GIZA", "LUXOR"], correct: 0 },
    { q: "MADRI É A CAPITAL DE QUAL PAÍS", options: ["FRANÇA", "PORTUGAL", "ESPANHA", "ITÁLIA"], correct: 2 },
    { q: "QUAL A CAPITAL DO CANADÁ", options: ["TORONTO", "VANCOUVER", "OTTAWA", "MONTREAL"], correct: 2 },
    { q: "CANBERRA É A CAPITAL DE ONDE", options: ["NOVA ZELÂNDIA", "AUSTRÁLIA", "ÁFRICA DO SUL", "ÍNDIA"], correct: 1 },
    { q: "QUAL A CAPITAL DA COLÔMBIA", options: ["CALI", "MEDELLÍN", "BOGOTÁ", "CARTAGENA"], correct: 2 },
    { q: "LIMA É A CAPITAL DE QUAL PAÍS", options: ["CHILE", "EQUADOR", "PERU", "BOLÍVIA"], correct: 2 },
    { q: "QUAL A CAPITAL DA COREIA DO SUL", options: ["PEQUIM", "SEUL", "TÓQUIO", "PYONGYANG"], correct: 1 },
    { q: "AMSTERDÃ É A CAPITAL DE ONDE", options: ["BÉLGICA", "HOLANDA", "DINAMARCA", "SUÉCIA"], correct: 1 },
    { q: "QUAL O MAIOR CONTINENTE DO MUNDO", options: ["ÁFRICA", "ÁSIA", "AMÉRICA", "EUROPA"], correct: 1 },
    { q: "QUAL O MAIOR OCEANO DA TERRA", options: ["ATLÂNTICO", "PACÍFICO", "ÍNDICO", "ÁRTICO"], correct: 1 },
    { q: "EM QUAL CONTINENTE FICA O EGITO", options: ["ÁSIA", "ÁFRICA", "EUROPA", "AMÉRICA"], correct: 1 },
    { q: "QUAL CONTINENTE É CONHECIDO COMO 'VELHO MUNDO'", options: ["ÁSIA", "ÁFRICA", "EUROPA", "AMÉRICA"], correct: 2 },
    { q: "QUAL O OCEANO QUE BANHA O BRASIL", options: ["PACÍFICO", "ATLÂNTICO", "ÍNDICO", "ANTÁRTICO"], correct: 1 },
    { q: "QUANTOS CONTINENTES EXISTEM", options: ["4", "5", "6", "7"], correct: 2 },
    { q: "QUAL O MENOR CONTINENTE DO MUNDO", options: ["EUROPA", "OCEANIA", "ANTÁRTIDA", "ÁSIA"], correct: 1 },
    { q: "ONDE FICA A ANTÁRTIDA", options: ["NORTE", "SUL", "LESTE", "OESTE"], correct: 1 },
    { q: "QUAL CONTINENTE TEM MAIS PAÍSES", options: ["ÁSIA", "ÁFRICA", "EUROPA", "AMÉRICA"], correct: 1 },
    { q: "EM QUAL CONTINENTE FICA A FRANÇA", options: ["AMÉRICA", "EUROPA", "ÁSIA", "OCEANIA"], correct: 1 },
    { q: "QUAL O MAIOR PAÍS DA AMÉRICA DO SUL", options: ["ARGENTINA", "BRASIL", "CHILE", "COLÔMBIA"], correct: 1 },
    { q: "O ALASKA FICA EM QUAL CONTINENTE", options: ["ÁSIA", "AMÉRICA DO NORTE", "EUROPA", "ÁFRICA"], correct: 1 },
    { q: "QUAL OCEANO FICA ENTRE A AMÉRICA E A ÁSIA", options: ["ATLÂNTICO", "PACÍFICO", "ÍNDICO", "ÁRTICO"], correct: 1 },
    { q: "EM QUAL CONTINENTE FICA A CHINA", options: ["ÁSIA", "EUROPA", "ÁFRICA", "OCEANIA"], correct: 0 },
    { q: "QUAL O CONTINENTE MAIS GELADO", options: ["EUROPA", "ÁSIA", "ANTÁRTIDA", "AMÉRICA"], correct: 2 },
    { q: "O MAR MORTO FICA EM QUAL CONTINENTE", options: ["ÁFRICA", "ÁSIA", "EUROPA", "AMÉRICA"], correct: 1 },
    { q: "QUAL CONTINENTE É UMA GRANDE ILHA", options: ["ÁFRICA", "OCEANIA", "EUROPA", "ÁSIA"], correct: 1 },
    { q: "EM QUAL CONTINENTE FICA O BRASIL", options: ["AMÉRICA DO NORTE", "AMÉRICA DO SUL", "EUROPA", "ÁFRICA"], correct: 1 },
    { q: "QUAL OCEANO BANHA A ÍNDIA", options: ["ATLÂNTICO", "PACÍFICO", "ÍNDICO", "ÁRTICO"], correct: 2 },
    { q: "O CANAL DO PANAMÁ LIGA QUAIS OCEANOS", options: ["ATLÂNTICO E ÍNDICO", "ATLÂNTICO E PACÍFICO", "PACÍFICO E ÍNDICO", "MAR MORTO"], correct: 1 },
    { q: "QUAL O MAIOR RIO DO MUNDO", options: ["NILO", "AMAZONAS", "MISSISSIPPI", "CONGO"], correct: 1 },
    { q: "QUAL A MONTANHA MAIS ALTA DO MUNDO", options: ["K2", "MONTE EVEREST", "MONTE BRANCO", "A CONCÁGUA"], correct: 1 },
    { q: "QUAL O MAIOR DESERTO DO MUNDO", options: ["SAARA", "ANTÁRTIDA", "GOBI", "ATACAMA"], correct: 1 },
    { q: "ONDE FICA A CORDILHEIRA DOS ANDES", options: ["EUROPA", "AMÉRICA DO SUL", "ÁSIA", "ÁFRICA"], correct: 1 },
    { q: "QUAL O MAIOR LAGO DO MUNDO", options: ["LAGO SUPERIOR", "MAR CÁSPIO", "LAGO VITÓRIA", "MAR MORTO"], correct: 1 },
    { q: "ONDE FICA O RIO NILO", options: ["ÁSIA", "ÁFRICA", "AMÉRICA", "EUROPA"], correct: 1 },
    { q: "QUAL O PONTO MAIS BAIXO DA TERRA", options: ["FOSSA DAS MARIANAS", "MAR MORTO", "VALE DA MORTE", "ABISMO"], correct: 1 },
    { q: "QUAL O NOME DA MAIOR FLORESTA TROPICAL", options: ["CONGO", "AMAZÔNIA", "MATA ATLÂNTICA", "TAIGA"], correct: 1 },
    { q: "QUAL O DESERTO MAIS SECO DO MUNDO", options: ["SAARA", "ATACAMA", "GOBI", "CALAHARI"], correct: 1 },
    { q: "ONDE FICAM OS ALPES", options: ["AMÉRICA", "EUROPA", "ÁSIA", "ÁFRICA"], correct: 1 },
    { q: "QUAL O RIO QUE PASSA POR LONDRES", options: ["SENA", "TÂMISA", "TIBRE", "RENO"], correct: 1 },
    { q: "QUAL O RIO QUE PASSA POR PARIS", options: ["TÂMISA", "SENA", "RENO", "DANÚBIO"], correct: 1 },
    { q: "COMO SE CHAMA UM GRUPO DE ILHAS", options: ["ARQUIPÉLAGO", "ATOL", "PENÍNSULA", "BAÍA"], correct: 0 },
    { q: "QUAL A MAIOR ILHA DO MUNDO", options: ["JAPÃO", "GROENLÂNDIA", "MADAGASCAR", "AUSTRÁLIA"], correct: 1 },
    { q: "QUAL O NOME DA PASSAGEM ENTRE DOIS MARES", options: ["CANAL", "ESTREITO", "BAÍA", "DELTA"], correct: 1 },
    { q: "ONDE FICA O RIO GANGES", options: ["CHINA", "ÍNDIA", "EGITO", "BRASIL"], correct: 1 },
    { q: "COMO SE CHAMA A TERRA CERCADA POR ÁGUA", options: ["ILHA", "PENÍNSULA", "DELTA", "VALE"], correct: 1 },
    { q: "QUAL O MAIOR CANAL ARTIFICIAL DO MUNDO", options: ["PANAMÁ", "SUEZ", "CORINTO", "GRANDE CANAL"], correct: 1 },
    { q: "QUAL O NOME DA MONTANHA MAIS ALTA DO BRASIL", options: ["PICO DA BANDEIRA", "PICO DA NEBLINA", "PEDRA DA GÁVEA", "PICO DAS AGULHAS"], correct: 1 },
    { q: "ONDE FICA O MONTE FUJI", options: ["CHINA", "JAPÃO", "COREIA", "TAIWAN"], correct: 1 },
    { q: "QUAL PAÍS TEM UMA FOLHA DE BORDO NA BANDEIRA", options: ["EUA", "CANADÁ", "JAPÃO", "LÍBANO"], correct: 1 },
    { q: "QUAL A COR DA BANDEIRA DA CHINA", options: ["AZUL", "VERMELHA", "VERDE", "AMARELA"], correct: 1 },
    { q: "QUAL PAÍS TEM UM SOL NO MEIO DA BANDEIRA", options: ["BRASIL", "ARGENTINA", "CHILE", "MÉXICO"], correct: 1 },
    { q: "QUAL BANDEIRA TEM AS CORES VERDE, BRANCO E VERMELHO", options: ["FRANÇA", "ITÁLIA", "RÚSSIA", "ALEMANHA"], correct: 1 },
    { q: "QUAL O PAÍS MAIS POPULOSO DO MUNDO", options: ["RÚSSIA", "ÍNDIA", "CHINA", "EUA"], correct: 1 },
    { q: "QUAL O MAIOR PAÍS DO MUNDO EM TERRITÓRIO", options: ["CHINA", "RÚSSIA", "CANADÁ", "BRASIL"], correct: 1 },
    { q: "EM QUAL PAÍS FICA A CIDADE DE VENEZA", options: ["FRANÇA", "ITÁLIA", "ESPANHA", "GRÉCIA"], correct: 1 },
    { q: "QUAL PAÍS É CONHECIDO PELA TERRA DO SOL NASCENTE", options: ["CHINA", "JAPÃO", "TAIWAN", "COREIA"], correct: 1 },
    { q: "QUAL PAÍS TEM O FORMATO DE UMA BOTA", options: ["GRÉCIA", "ITÁLIA", "MÉXICO", "NORUEGA"], correct: 1 },
    { q: "EM QUAL PAÍS FICA A TORRE EIFFEL", options: ["INGLATERRA", "FRANÇA", "ALEMANHA", "ITÁLIA"], correct: 1 },
    { q: "QUAL PAÍS É FAMOSO PELAS PIRÂMIDES", options: ["MÉXICO", "EGITO", "ÍNDIA", "PERU"], correct: 1 },
    { q: "A ESTÁTUA DA LIBERDADE FICA EM QUAL PAÍS", options: ["FRANÇA", "ESTADOS UNIDOS", "INGLATERRA", "BRASIL"], correct: 1 },
    { q: "QUAL PAÍS TEM A MAIOR ÁREA DE FLORESTA DO MUNDO", options: ["BRASIL", "RÚSSIA", "CANADÁ", "CHINA"], correct: 1 },
    { q: "ONDE FICA A SEDE DA ONU", options: ["LONDRES", "NEW YORK", "GENEBRA", "PARIS"], correct: 1 },
    { q: "QUAL PAÍS TEM A BANDEIRA QUADRADA", options: ["FRANÇA", "SUÍÇA", "BÉLGICA", "ÁUSTRIA"], correct: 1 },
    { q: "QUAL PAÍS É FAMOSO PELOS CANAIS DE AMSTERDÃ", options: ["ALEMANHA", "HOLANDA", "BÉLGICA", "SUÉCIA"], correct: 1 },
    { q: "QUAL O ÚNICO PAÍS QUE É TAMBÉM UM CONTINENTE", options: ["ÍNDIA", "AUSTRÁLIA", "RÚSSIA", "GROENLÂNDIA"], correct: 1 },
    { q: "EM QUAL PAÍS FICA O TAJ MAHAL", options: ["EGITO", "ÍNDIA", "CHINA", "TURQUIA"], correct: 1 },
    { q: "QUAL PAÍS TEM 3 CAPITAIS", options: ["EUA", "ÁFRICA DO SUL", "SUIÇA", "BRASIL"], correct: 1 },
    { q: "A EURO É A MOEDA DE QUAL REGIÃO", options: ["ÁSIA", "UNIÃO EUROPEIA", "AMÉRICA", "ÁFRICA"], correct: 1 },
    { q: "QUANTOS ESTADOS TEM O BRASIL", options: ["24", "26 + DF", "27", "25"], correct: 1 },
    { q: "QUAL O MAIOR ESTADO DO BRASIL EM ÁREA", options: ["MATO GROSSO", "AMAZONAS", "MINAS GERAIS", "PARÁ"], correct: 1 },
    { q: "QUAL O ESTADO MAIS POPULOSO DO BRASIL", options: ["RIO DE JANEIRO", "SÃO PAULO", "BAHIA", "MINAS GERAIS"], correct: 1 },
    { q: "QUAL A CAPITAL DO RIO DE JANEIRO", options: ["NITERÓI", "RIO DE JANEIRO", "PETRÓPOLIS", "CABO FRIO"], correct: 1 },
    { q: "EM QUAL REGIÃO FICA O ESTADO DA BAHIA", options: ["NORTE", "NORDESTE", "SUDESTE", "SUL"], correct: 1 },
    { q: "QUAL A CAPITAL DE MINAS GERAIS", options: ["VITÓRIA", "BELO HORIZONTE", "CURITIBA", "GOIÂNIA"], correct: 1 },
    { q: "O RIO GRANDE DO SUL FICA EM QUAL REGIÃO", options: ["SUDESTE", "SUL", "CENTRO-OESTE", "NORTE"], correct: 1 },
    { q: "QUAL A CAPITAL DO AMAZONAS", options: ["BELÉM", "MANAUS", "BOA VISTA", "PALMAS"], correct: 1 },
    { q: "EM QUAL REGIÃO FICA BRASÍLIA", options: ["SUDESTE", "CENTRO-OESTE", "SUL", "NORDESTE"], correct: 1 },
    { q: "QUAL O MENOR ESTADO DO BRASIL", options: ["ALAGOAS", "SERGIPE", "ESPÍRITO SANTO", "PIAUÍ"], correct: 1 },
    { q: "QUAL A CAPITAL DO PARANÁ", options: ["FLORIANÓPOLIS", "CURITIBA", "PORTO ALEGRE", "LONDRINA"], correct: 1 },
    { q: "QUAL ESTADO TEM A CAPITAL CUIABÁ", options: ["MATO GROSSO", "MATO GROSSO DO SUL", "GOIÁS", "TOCANTINS"], correct: 0 },
    { q: "ONDE FICA O ARQUIPÉLAGO DE FERNANDO DE NORONHA", options: ["BAHIA", "PERNAMBUCO", "CEARÁ", "RIO DE JANEIRO"], correct: 1 },
    { q: "QUAL A ÚNICA CAPITAL BRASILEIRA NO HEMISFÉRIO NORTE", options: ["MANAUS", "MACAPÁ", "BOA VISTA", "BELÉM"], correct: 2 },
    { q: "QUAL O PONTO MAIS ORIENTAL DO BRASIL", options: ["PONTA DO SEIXAS", "CABO ORANGE", "CHUÍ", "PONTA DO SINO"], correct: 0 },
    { q: "O RIO SÃO FRANCISCO É CONHECIDO COMO...", options: ["VELHO CHICO", "RIO DO SOL", "GRANDE RIO", "RIO DO OURO"], correct: 0 },
    { q: "QUAL ESTADO É O MAIOR PRODUTOR DE CAFÉ", options: ["SÃO PAULO", "MINAS GERAIS", "ESPÍRITO SANTO", "PARANÁ"], correct: 1 },
    { q: "QUAL CAPITAL É UMA ILHA", options: ["RECIFE", "FLORIANÓPOLIS", "SALVADOR", "FORTALEZA"], correct: 1 },
    { q: "QUAL O ESTADO MAIS NOVO DO BRASIL", options: ["ACRE", "TOCANTINS", "RORAIMA", "AMAPÁ"], correct: 1 },
    { q: "QUAL A REGIÃO COM O MAIOR NÚMERO DE ESTADOS", options: ["NORTE", "NORDESTE", "SUDESTE", "CENTRO-OESTE"], correct: 1 },
    { q: "QUAL A CAPITAL DA ÁUSTRIA", options: ["PRAGA", "VIENA", "ZURIQUE", "BUDAPESTE"], correct: 1 },
    { q: "QUAL A CAPITAL DA TURQUIA", options: ["ISTAMBUL", "ANCARA", "ANTALYA", "IZMIR"], correct: 1 },
    { q: "QUAL A CAPITAL DA ESCÓCIA", options: ["LONDRES", "EDIMBURGO", "GLASGOW", "DUBLIN"], correct: 1 },
    { q: "DUBLIN É A CAPITAL DE ONDE", options: ["IRLANDA", "ISLÂNDIA", "NORUEGA", "DINAMARCA"], correct: 0 },
    { q: "QUAL A CAPITAL DA GRÉCIA", options: ["ESPARTA", "ATENAS", "CRETA", "RODES"], correct: 1 },
    { q: "QUAL A CAPITAL DA SUÍÇA", options: ["GENEBRA", "BERNA", "ZURIQUE", "BASILEIA"], correct: 1 },
    { q: "BANGKOK É A CAPITAL DE QUAL PAÍS", options: ["VIETNÃ", "TAILÂNDIA", "MALÁSIA", "FILIPINAS"], correct: 1 },
    { q: "QUAL A CAPITAL DA ÁFRICA DO SUL", options: ["CIDADE DO CABO", "PRETÓRIA", "JOHANNESBURGO", "DURBAN"], correct: 1 },
    { q: "QUAL A CAPITAL DA NOVA ZELÂNDIA", options: ["AUCKLAND", "WELLINGTON", "CHRISTCHURCH", "SYDNEY"], correct: 1 },
    { q: "QUAL A CAPITAL DO EGITO", options: ["ALEXANDRIA", "CAIRO", "GIZA", "LUXOR"], correct: 1 },
    { q: "VARSOVIA É A CAPITAL DE QUAL PAÍS", options: ["HUNGRIA", "POLÔNIA", "REPÚBLICA TCHECA", "UCRÂNIA"], correct: 1 },
    { q: "QUAL A CAPITAL DA NORUEGA", options: ["ESTOCOLMO", "OSLO", "HELSINQUE", "COPENHAGUE"], correct: 1 },
    { q: "QUAL A CAPITAL DA SUÉCIA", options: ["OSLO", "ESTOCOLMO", "HELSINQUE", "COPENHAGUE"], correct: 1 },
    { q: "REIJKJAVIK É A CAPITAL DE QUAL PAÍS", options: ["FINLÂNDIA", "ISLÂNDIA", "GROENLÂNDIA", "DINAMARCA"], correct: 1 },
    { q: "QUAL A CAPITAL DA BÉLGICA", options: ["BRUXELAS", "AMSTERDÃ", "LUXEMBURGO", "ANTUÉRPIA"], correct: 0 },
    { q: "QUAL A CAPITAL DE ISRAEL", options: ["TEL AVIV", "JERUSALÉM", "HAIFA", "Gaza"], correct: 1 },
    { q: "QUAL A CAPITAL DA ARÁBIA SAUDITA", options: ["DUBAI", "RIADE", "MECA", "DOHA"], correct: 1 },
    { q: "QUAL A CAPITAL DO CHILE", options: ["VALPARAÍSO", "SANTIAGO", "CONCEPCIÓN", "LIMA"], correct: 1 },
    { q: "MONTEVIDÉU É A CAPITAL DE ONDE", options: ["PARAGUAI", "URUGUAI", "ARGENTINA", "CHILE"], correct: 1 },
    { q: "QUAL A CAPITAL DO EQUADOR", options: ["QUITO", "GUAYAQUIL", "CUENCA", "LIMA"], correct: 0 },
    { q: "QUAL O NOME DA CAMADA DE AR DA TERRA", options: ["LITOSFERA", "ATMOSFERA", "HIDROSFERA", "BIOSFERA"], correct: 1 },
    { q: "O QUE É O MAGMA QUANDO SAI DO VULCÃO", options: ["PEDRA", "LAVA", "FOGO", "CINZA"], correct: 1 },
    { q: "COMO SE CHAMA O ESTUDO DOS MAPAS", options: ["GEOGRAFIA", "CARTOGRAFIA", "GEOLOGIA", "HISTÓRIA"], correct: 1 },
    { q: "QUAL A LINHA QUE DIVIDE NORTE E SUL", options: ["MERIDIANO", "EQUADOR", "TRÓPICO", "CAPRICÓRNIO"], correct: 1 },
    { q: "QUAL O PONTO MAIS ALTO DA AMÉRICA", options: ["EVEREST", "ACONCÁGUA", "MONTE BRANCO", "PICO DA NEBLINA"], correct: 1 },
    { q: "COMO SE CHAMA O TREMOR DA TERRA", options: ["TSUNAMI", "TERREMOTO", "FURACÃO", "EROSÃO"], correct: 1 },
    { q: "O QUE CAUSA AS MARÉS", options: ["VENTO", "GRAVIDADE DA LUA", "SOL", "PEIXES"], correct: 1 },
    { q: "QUAL O NOME DA MAIOR BARREIRA DE CORAIS", options: ["BRASILEIRA", "GRANDE BARREIRA AUSTRALIANA", "AFRICANA", "MEXICANA"], correct: 1 },
    { q: "O QUE É UM VULCÃO DORMENTE", options: ["MORTO", "NÃO ESTÁ ATIVO MAS PODE ACORDAR", "PEQUENO", "FRIO"], correct: 1 },
    { q: "QUAL O NOME DA CHUVA DE CURTA DURAÇÃO", options: ["TEMPESTADE", "PANCADA/AGUACEIRO", "GAROA", "MONÇÃO"], correct: 1 },
    { q: "O QUE SÃO MONÇÕES", options: ["MONTANHAS", "VENTOS SAZONAIS NA ÁSIA", "RIOS", "FLORESTAS"], correct: 1 },
    { q: "COMO SE CHAMA O GELO QUE FLUTUA NO MAR", options: ["GLACIAR", "ICEBERG", "NEVE", "CALOTA"], correct: 1 },
    { q: "ONDE SE LOCALIZA O ESTREITO DE GIBRALTAR", options: ["AMÉRICA", "ENTRE EUROPA E ÁFRICA", "ÁSIA", "OCEANIA"], correct: 1 },
    { q: "QUAL O NOME DA DISTÂNCIA EM RELAÇÃO AO EQUADOR", options: ["LONGITUDE", "LATITUDE", "ALTITUDE", "ESCALA"], correct: 1 },
    { q: "QUAL O NOME DA DISTÂNCIA EM RELAÇÃO A GREENWICH", options: ["LATITUDE", "LONGITUDE", "FUSO HORÁRIO", "AZIMUTE"], correct: 1 },
    { q: "QUAL O NOME DO CLIMA DAS FLORESTAS", options: ["DESÉRTICO", "EQUATORIAL", "POLAR", "TEMPERADO"], correct: 1 },
    { q: "QUAL O CLIMA CARACTERIZADO POR NEVE", options: ["TROPICAL", "POLAR", "MEDITERRÂNEO", "SECO"], correct: 1 },
    { q: "O QUE É A EROSÃO", options: ["PLANTIO", "DESGASTE DO SOLO", "VULCÃO", "LAGO"], correct: 1 },
    { q: "O QUE É UMA PENÍNSULA", options: ["ILHA", "TERRA CERCADA POR ÁGUA EM 3 LADOS", "MONTANHA", "RIO"], correct: 1 },
    { q: "QUAL O NOME DO ENCONTRO DE DOIS RIOS", options: ["FOZ", "CONFLUÊNCIA", "NASCENTE", "LEITO"], correct: 1 },
    { q: "ONDE FICA O CANAL DE SUEZ", options: ["PANAMÁ", "EGITO", "GRÉCIA", "TURQUIA"], correct: 1 },
    { q: "EM QUAL CONTINENTE FICA A TAILÂNDIA", options: ["ÁFRICA", "ÁSIA", "EUROPA", "OCEANIA"], correct: 1 },
    { q: "QUAL O PAÍS MAIS EXTENSO DA EUROPA", options: ["FRANÇA", "UCRÂNIA", "ALEMANHA", "ESPANHA"], correct: 1 },
    { q: "ONDE FICA A ILHA DE PÁSCOA", options: ["PERU", "CHILE", "EQUADOR", "AUSTRÁLIA"], correct: 1 },
    { q: "QUAL PAÍS TEM MAIS ILHAS NO MUNDO", options: ["JAPÃO", "SUÉCIA", "FILIPINAS", "INDONÉSIA"], correct: 1 },
    { q: "EM QUAL CONTINENTE FICA A ARGÉLIA", options: ["ÁSIA", "ÁFRICA", "EUROPA", "AMÉRICA"], correct: 1 },
    { q: "ONDE FICA O MONTE KILIMANJARO", options: ["ÁSIA", "ÁFRICA", "AMÉRICA", "EUROPA"], correct: 1 },
    { q: "QUAL PAÍS FAZ FRONTEIRA COM O BRASIL AO SUL", options: ["CHILE", "URUGUAI", "PERU", "COLÔMBIA"], correct: 1 },
    { q: "ONDE FICA A TRANSILVÂNIA", options: ["HUNGRIA", "ROMÊNIA", "POLÔNIA", "ALEMANHA"], correct: 1 },
    { q: "QUAL PAÍS É CONHECIDO PELA 'GRANDE MURALHA'", options: ["JAPÃO", "CHINA", "ÍNDIA", "RÚSSIA"], correct: 1 },
    { q: "EM QUAL CONTINENTE FICA A TURQUIA", options: ["ÁSIA E EUROPA", "SÓ ÁSIA", "SÓ EUROPA", "ÁFRICA"], correct: 0 },
    { q: "QUAL O PAÍS MAIS VISITADO DO MUNDO", options: ["EUA", "FRANÇA", "CHINA", "ESPANHA"], correct: 1 },
    { q: "ONDE FICA A PATAGÔNIA", options: ["BRASIL", "ARGENTINA E CHILE", "PERU", "MÉXICO"], correct: 1 },
    { q: "QUAL PAÍS TEM A MAIOR POPULAÇÃO DA EUROPA", options: ["FRANÇA", "ALEMANHA", "INGLATERRA", "ITÁLIA"], correct: 1 },
    { q: "ONDE FICA O DESERTO DE GOBI", options: ["ÁFRICA", "ÁSIA", "AMÉRICA", "AUSTRÁLIA"], correct: 1 },
    { q: "QUAL O ÚNICO PAÍS QUE FICA NOS 4 HEMISFÉRIOS", options: ["BRASIL", "QUIRIBATI", "INDONÉSIA", "EUA"], correct: 1 },
    { q: "QUAL PAÍS TEM A MAIOR LINHA COSTEIRA", options: ["BRASIL", "CANADÁ", "RÚSSIA", "AUSTRÁLIA"], correct: 1 },
    { q: "ONDE FICA A CIDADE DE PETRA", options: ["EGITO", "JORDÂNIA", "IRAQUE", "SÍRIA"], correct: 1 },
    { q: "QUAL PAÍS É FORMADO POR 17 MIL ILHAS", options: ["FILIPINAS", "INDONÉSIA", "JAPÃO", "MALDIVAS"], correct: 1 },
    { q: "ONDE FICA O LAGO TITICACA", options: ["BRASIL", "PERU E BOLÍVIA", "CHILE", "ARGENTINA"], correct: 1 },
    { q: "QUAL O BIOMA EXCLUSIVO DO BRASIL", options: ["AMAZÔNIA", "CAATINGA", "CERRADO", "PANTANAL"], correct: 1 },
    { q: "QUAL O ESTADO MAIS SECO DO BRASIL", options: ["PIAUÍ", "CEARÁ", "RIO GRANDE DO NORTE", "PARAÍBA"], correct: 1 },
    { q: "QUAL A CAPITAL DO ESPÍRITO SANTO", options: ["VITÓRIA", "VILA VELHA", "CARIACICA", "LINHARES"], correct: 0 },
    { q: "EM QUAL ESTADO FICA O JALAPÃO", options: ["GOIÁS", "TOCANTINS", "MATO GROSSO", "BAHIA"], correct: 1 },
    { q: "QUAL O CLIMA PREDOMINANTE NO NORDESTE", options: ["TROPICAL", "SEMIÁRIDO", "EQUATORIAL", "SUBTROPICAL"], correct: 1 },
    { q: "QUAL O ESTADO MAIS POPULOSO DO SUL", options: ["PARANÁ", "SANTA CATARINA", "RIO GRANDE DO SUL", "SÃO PAULO"], correct: 2 },
    { q: "QUAL A CAPITAL DO MATO GROSSO DO SUL", options: ["CUIABÁ", "CAMPO GRANDE", "DOURADOS", "BONITO"], correct: 1 },
    { q: "QUAL O RIO QUE DIVIDE O BRASIL E O PARAGUAI", options: ["RIO AMAZONAS", "RIO PARANÁ", "RIO SÃO FRANCISCO", "RIO DOCE"], correct: 1 },
    { q: "QUAL A CAPITAL DE RORAIMA", options: ["PORTO VELHO", "BOA VISTA", "MACAPÁ", "RIO BRANCO"], correct: 1 },
    { q: "QUAL O ESTADO CONHECIDO COMO 'TERRA DO SOL'", options: ["BAHIA", "CEARÁ", "RIO DE JANEIRO", "PERNAMBUCO"], correct: 1 },
    { q: "ONDE FICA O MONTE RORAIMA", options: ["AMAZONAS", "RORAIMA", "PARÁ", "ACRE"], correct: 1 },
    { q: "QUAL A CAPITAL DO ACRE", options: ["RIO BRANCO", "CRUZEIRO DO SUL", "BOA VISTA", "MANAUS"], correct: 0 },
    { q: "QUAL O NOME DA MAIOR USINA HIDRELÉTRICA DO BRASIL", options: ["BELO MONTE", "ITAIPU", "TUCURUÍ", "FURNAS"], correct: 1 },
    { q: "EM QUAL ESTADO FICA A CHAPADA DIAMANTINA", options: ["MINAS GERAIS", "BAHIA", "GOIÁS", "PIAUÍ"], correct: 1 },
    { q: "QUAL A CAPITAL DE SERGIPE", options: ["MACEIÓ", "ARACAJU", "NATAL", "RECIFE"], correct: 1 },
    { q: "QUAL O ESTADO QUE TEM MAIS MUNICÍPIOS", options: ["SÃO PAULO", "MINAS GERAIS", "BAHIA", "PARANÁ"], correct: 1 },
    { q: "QUAL O NOME DA ILHA DO MARAJÓ FICA EM QUAL ESTADO", options: ["AMAZONAS", "PARÁ", "MARANHÃO", "AMAPÁ"], correct: 1 },
    { q: "QUAL A CAPITAL DO PIAUÍ", options: ["SÃO LUÍS", "TERESINA", "FORTALEZA", "NATAL"], correct: 1 },
    { q: "QUAL O PONTO MAIS SETENTRIONAL DO BRASIL", options: ["MONTE RORAIMA", "CABO ORANGE", "FOZ DO RIO AILÃ", "PONTA DO SEIXAS"], correct: 2 },
    { q: "EM QUAL ESTADO FICA O PORTO DE SANTOS", options: ["RIO DE JANEIRO", "SÃO PAULO", "PARANÁ", "SANTA CATARINA"], correct: 1 },
    { q: "QUAL PAÍS TEM A MAIOR FRONTEIRA COM O BRASIL", options: ["ARGENTINA", "BOLÍVIA", "COLÔMBIA", "PERU"], correct: 1 },
    { q: "QUAL A CAPITAL DO CANADÁ", options: ["TORONTO", "OTTAWA", "VANCOUVER", "QUEBEC"], correct: 1 },
    { q: "QUAL PAÍS NÃO FAZ FRONTEIRA COM O BRASIL", options: ["PARAGUAI", "CHILE", "SURINAME", "PERU"], correct: 1 },
    { q: "QUAL A CAPITAL DA POLÔNIA", options: ["PRAGA", "VARSOVIA", "BUDAPESTE", "CRACOVIA"], correct: 1 },
    { q: "QUAL PAÍS FICA DENTRO DA ÁFRICA DO SUL", options: ["NAMÍBIA", "LESOTO", "ZIMBÁBUE", "BOTSUANA"], correct: 1 },
    { q: "QUAL A CAPITAL DA HUNGRIA", options: ["VIENA", "BUDAPESTE", "BUCARESTE", "SOFIA"], correct: 1 },
    { q: "QUAL O PAÍS MAIS RICO DO MUNDO EM PIB PER CAPITA", options: ["EUA", "LUXEMBURGO", "CHINA", "SUÍÇA"], correct: 1 },
    { q: "QUAL A CAPITAL DA INDONÉSIA", options: ["BALI", "JACARTA", "BANGKOK", "MANILA"], correct: 1 },
    { q: "QUAL O PAÍS COM MAIS FUSOS HORÁRIOS", options: ["RÚSSIA", "FRANÇA", "EUA", "CHINA"], correct: 1 },
    { q: "QUAL A CAPITAL DA UCRÂNIA", options: ["MOSCOU", "KIEV", "VARSOVIA", "MINSK"], correct: 1 },
    { q: "QUAL PAÍS TEM DUAS BANDEIRAS OFICIAIS", options: ["EUA", "FILIPINAS", "BRASIL", "MÉXICO"], correct: 1 },
    { q: "QUAL A CAPITAL DO VIETNÃ", options: ["HO CHI MINH", "HANOI", "BANGKOK", "SEUL"], correct: 1 },
    { q: "QUAL PAÍS É FORMADO POR 5 ILHAS PRINCIPAIS", options: ["INDONÉSIA", "JAPÃO", "FILIPINAS", "REINO UNIDO"], correct: 1 },
    { q: "QUAL A CAPITAL DA FINLÂNDIA", options: ["OSLO", "HELSINQUE", "ESTOCOLMO", "COPENHAGUE"], correct: 1 },
    { q: "QUAL PAÍS TEM O MAIOR NÚMERO DE LAGOS", options: ["BRASIL", "CANADÁ", "RÚSSIA", "EUA"], correct: 1 },
    { q: "QUAL A CAPITAL DO IRÃ", options: ["BAGDÁ", "TEERÃ", "CABUL", "RIADE"], correct: 1 },
    { q: "QUAL O NOME DO PAÍS MAIS NOVO DO MUNDO", options: ["TIMOR LESTE", "SUDÃO DO SUL", "KOSOVO", "MONTENEGRO"], correct: 1 },
    { q: "QUAL A CAPITAL DA DINAMARCA", options: ["OSLO", "COPENHAGUE", "ESTOCOLMO", "BERNA"], correct: 1 },
    { q: "QUAL PAÍS É DIVIDIDO EM CANTONS", options: ["ALEMANHA", "SUÍÇA", "ÁUSTRIA", "BÉLGICA"], correct: 1 },
    { q: "QUAL A CAPITAL DA NIGÉRIA", options: ["LAGOS", "ABUJA", "CAIRO", "NAIROBI"], correct: 1 },
    { q: "QUAL O IDIOMA MAIS FALADO DO MUNDO", options: ["INGLÊS", "MANDARIM", "ESPANHOL", "HINDI"], correct: 1 },
    { q: "QUAL A MAIOR CIDADE DO MUNDO EM POPULAÇÃO", options: ["NEW YORK", "TÓQUIO", "XANGAI", "SÃO PAULO"], correct: 1 },
    { q: "QUAL O BLOCO ECONÔMICO DO BRASIL", options: ["UNIÃO EUROPEIA", "MERCOSUL", "BRICS", "NAFTA"], correct: 1 },
    { q: "O QUE SIGNIFICA PIB", options: ["PLANO INTERNO BRASILEIRO", "PRODUTO INTERNO BRUTO", "PREÇO INTERNACIONAL", "PONTO INTERNO"], correct: 1 },
    { q: "QUAL O PAÍS MAIS VELHO DO MUNDO", options: ["EGITO", "SAN MARINO", "CHINA", "GRÉCIA"], correct: 1 },
    { q: "QUAL O CONTINENTE COM MAIOR TAXA DE NATALIDADE", options: ["ÁFRICA", "ÁSIA", "AMÉRICA", "EUROPA"], correct: 0 },
    { q: "O QUE É O ÊXODO RURAL", options: ["SAÍDA DA CIDADE PARA O CAMPO", "SAÍDA DO CAMPO PARA A CIDADE", "VIAJAR NAS FÉRIAS", "MUDAR DE PAÍS"], correct: 1 },
    { q: "QUAL A MOEDA DO JAPÃO", options: ["DÓLAR", "YEN", "YUAN", "EURO"], correct: 1 },
    { q: "O QUE É A MEGACIDADE", options: ["CIDADE COM MAIS DE 1 MILHÃO", "CIDADE COM MAIS DE 10 MILHÕES", "CIDADE ANTIGA", "CIDADE PEQUENA"], correct: 1 },
    { q: "QUAL O PAÍS QUE MAIS PRODUZ PETRÓLEO", options: ["BRASIL", "ESTADOS UNIDOS", "ARÁBIA SAUDITA", "RÚSSIA"], correct: 1 },
    { q: "QUAL O CONTINENTE MAIS URBANIZADO", options: ["ÁFRICA", "AMÉRICA DO NORTE", "EUROPA", "ÁSIA"], correct: 1 },
    { q: "QUAL O PRINCIPAL GRÃO PRODUZIDO NO BRASIL", options: ["TRIGO", "SOJA", "MILHO", "ARROZ"], correct: 1 },
    { q: "O QUE É O IDH", options: ["ÍNDICE DE DESENVOLVIMENTO HUMANO", "IMPOSTO DE DIREITO HUMANO", "ÍNDICE DE DINHEIRO", "INSTITUTO"], correct: 0 },
    { q: "QUAL O PAÍS QUE MAIS EMITE CO2", options: ["EUA", "CHINA", "ÍNDIA", "RÚSSIA"], correct: 1 },
    { q: "QUAL O SETOR DA ECONOMIA DA AGRICULTURA", options: ["PRIMÁRIO", "SECUNDÁRIO", "TERCIÁRIO", "QUATERNÁRIO"], correct: 0 },
    { q: "QUAL O SETOR DA ECONOMIA DOS SERVIÇOS", options: ["PRIMÁRIO", "SECUNDÁRIO", "TERCIÁRIO", "INDÚSTRIA"], correct: 2 },
    { q: "QUAL O MAIOR EXPORTADOR DE CARNE BOVINA", options: ["EUA", "BRASIL", "ARGENTINA", "AUSTRÁLIA"], correct: 1 },
    { q: "O QUE É A GENTRIFICAÇÃO", options: ["PLANTAR ÁRVORES", "VALORIZAÇÃO DE ÁREAS URBANAS", "LIMPAR RIOS", "CONSTRUIR ESTRADAS"], correct: 1 },
    { q: "QUAL O PAÍS COM O MAIOR NÚMERO DE TURISTAS", options: ["ESPANHA", "FRANÇA", "EUA", "ITÁLIA"], correct: 1 },
    { q: "QUAL O PAÍS TEM A MAIOR MÉDIA DE ALTURA NO MUNDO", options: ["SUÍÇA", "BUTÃO", "NEPAL", "CHILE"], correct: 1 },
    { q: "QUAL PAÍS TEM O MAIOR NÚMERO DE VULCÕES ATIVOS", options: ["JAPÃO", "INDONÉSIA", "ISLÂNDIA", "EUA"], correct: 1 },
    { q: "QUAL A CAPITAL DA COREIA DO NORTE", options: ["SEUL", "PYONGYANG", "PEQUIM", "TÓQUIO"], correct: 1 },
    { q: "EM QUAL PAÍS FICA A CIDADE DE DUBAI", options: ["ARÁBIA SAUDITA", "EMIRADOS ÁRABES UNIDOS", "CATAR", "OMÃ"], correct: 1 },
    { q: "QUAL O MENOR PAÍS DO MUNDO", options: ["MÔNACO", "VATICANO", "MALTA", "SAN MARINO"], correct: 1 },
    { q: "QUAL PAÍS TEM A BANDEIRA COM UM DRAGÃO", options: ["CHINA", "BUTÃO", "VIETNÃ", "JAPÃO"], correct: 1 },
    { q: "QUAL A CAPITAL DA BÉLGICA", options: ["ANTUÉRPIA", "BRUXELAS", "GENT", "BRUGES"], correct: 1 },
    { q: "ONDE SE LOCALIZA O MONTE SAINT-MICHEL", options: ["INGLATERRA", "FRANÇA", "ALEMANHA", "ITÁLIA"], correct: 1 },
    { q: "QUAL PAÍS É DIVIDIDO EM DUAS PARTES PELO MAR", options: ["FILIPINAS", "MALÁSIA", "INDONÉSIA", "JAPÃO"], correct: 1 },
    { q: "QUAL A CAPITAL DA COLÔMBIA", options: ["MEDELLÍN", "BOGOTÁ", "CALI", "CARTAGENA"], correct: 1 },
    { q: "QUAL O ÚNICO PAÍS COM A BANDEIRA NÃO RETANGULAR", options: ["SUIÇA", "NEPAL", "VATICANO", "BÉLGICA"], correct: 1 },
    { q: "EM QUAL PAÍS FICA O DESERTO DO SAARA", options: ["EGITO", "ARGÉLIA", "LÍBIA", "MARROCOS"], correct: 1 },
    { q: "QUAL A CAPITAL DA RÚSSIA", options: ["SÃO PETERSBURGO", "MOSCOU", "KIEV", "MINSK"], correct: 1 },
    { q: "QUAL PAÍS TEM MAIS DE 800 IDIOMAS", options: ["ÍNDIA", "PAPUA-NOVA GUINÉ", "NIGÉRIA", "CHINA"], correct: 1 },
    { q: "QUAL A CAPITAL DA AUSTRÁLIA", options: ["SYDNEY", "CANBERRA", "MELBOURNE", "PERTH"], correct: 1 },
    { q: "QUAL PAÍS É O MAIOR PRODUTOR DE CAFÉ", options: ["COLÔMBIA", "BRASIL", "VIETNÃ", "ETIÓPIA"], correct: 1 },
    { q: "QUAL A CAPITAL DO QUÊNIA", options: ["LAGOS", "NAIROBI", "ADIS ABEBA", "CAIRO"], correct: 1 },
    { q: "EM QUAL PAÍS FICA A GRANDE MURALHA", options: ["JAPÃO", "CHINA", "ÍNDIA", "MONGÓLIA"], correct: 1 },
    { q: "QUAL A CAPITAL DA TAILÂNDIA", options: ["VIETNÃ", "BANGKOK", "PUDONG", "SEUL"], correct: 1 },
    { q: "QUAL PAÍS É CONHECIDO PELA 'TERRA DO FOGO'", options: ["BRASIL", "ARGENTINA/CHILE", "ISLÂNDIA", "AUSTRÁLIA"], correct: 1 },
    { q: "ONDE FICA O MACHU PICCHU", options: ["CHILE", "PERU", "BOLÍVIA", "COLÔMBIA"], correct: 1 },
    { q: "QUAL CIDADE É CONHECIDA COMO 'CIDADE LUZ'", options: ["LONDRES", "PARIS", "NEW YORK", "TÓQUIO"], correct: 1 },
    { q: "ONDE FICA A TORRE DE PISA", options: ["FRANÇA", "ITÁLIA", "ESPANHA", "GRÉCIA"], correct: 1 },
    { q: "ONDE FICA O COLOSSEUM", options: ["ATENAS", "ROMA", "EGITO", "PARIS"], correct: 1 },
    { q: "QUAL A MAIOR CIDADE DO BRASIL", options: ["RIO DE JANEIRO", "SÃO PAULO", "BRASÍLIA", "SALVADOR"], correct: 1 },
    { q: "ONDE FICA A ESTÁTUA DO CRISTO REDENTOR", options: ["SÃO PAULO", "RIO DE JANEIRO", "BELO HORIZONTE", "CURITIBA"], correct: 1 },
    { q: "QUAL CIDADE TEM O APELIDO DE 'BIG APPLE'", options: ["LOS ANGELES", "NEW YORK", "CHICAGO", "MIAMI"], correct: 1 },
    { q: "ONDE FICA O TEMPLO DE ANGKOR WAT", options: ["TAILÂNDIA", "CAMBOJA", "VIETNÃ", "ÍNDIA"], correct: 1 },
    { q: "ONDE FICA O MUSEU DO LOUVRE", options: ["MADRI", "PARIS", "LONDRES", "ROMA"], correct: 1 },
    { q: "ONDE FICA A OPERA HOUSE DE SYDNEY", options: ["EUA", "AUSTRÁLIA", "INGLATERRA", "CANADÁ"], correct: 1 },
    { q: "QUAL CIDADE É FAMOSA PELOS CANAIS", options: ["ROMA", "VENEZA", "MILÃO", "MADRI"], correct: 1 },
    { q: "ONDE FICA O BURJ KHALIFA", options: ["DUBAI", "PEQUIM", "NEW YORK", "RIADE"], correct: 0 },
    { q: "ONDE FICAM AS CATARATAS DO IGUAÇU", options: ["BRASIL/ARGENTINA", "BRASIL/CHILE", "ARGENTINA/PERU", "BRASIL/PARAGUAI"], correct: 0 },
    { q: "ONDE FICA O MONTE EVEREST", options: ["ALPES", "HIMALAIA", "ANDES", "ROCHOSAS"], correct: 1 },
    { q: "ONDE FICA O TAJ MAHAL", options: ["AGRA", "DELI", "PEQUIM", "CAIRO"], correct: 0 },
    { q: "ONDE FICA A ACRÓPOLE", options: ["ROMA", "ATENAS", "ISTAMBUL", "ESPARTA"], correct: 1 },
    { q: "ONDE FICA O BIG BEN", options: ["PARIS", "LONDRES", "DUBLIN", "EDIMBURGO"], correct: 1 },
    { q: "QUAL CIDADE BRASILEIRA É CONHECIDA PELA ARQUITETURA DE NIEMEYER", options: ["RIO", "BRASÍLIA", "CURITIBA", "SÃO PAULO"], correct: 1 },
    { q: "ONDE FICA O GRAND CANYON", options: ["MÉXICO", "ESTADOS UNIDOS", "CANADÁ", "AUSTRÁLIA"], correct: 1 },
    { q: "ONDE FICA O MURO DAS LAMENTAÇÕES", options: ["ROMA", "JERUSALÉM", "CAIRO", "MECA"], correct: 1 },
    { q: "QUAL O MAIOR OCEANO EM EXTENSÃO", options: ["ATLÂNTICO", "PACÍFICO", "ÍNDICO", "ÁRTICO"], correct: 1 },
    { q: "QUAL O MAIOR CONTINENTE", options: ["ÁFRICA", "ÁSIA", "AMÉRICA", "EUROPA"], correct: 1 },
    { q: "ONDE FICA O DESERTO DE ATACAMA", options: ["BRASIL", "CHILE", "MÉXICO", "ÁFRICA DO SUL"], correct: 1 },
    { q: "QUAL RIO ATRAVESSA A CIDADE DO CAIRO", options: ["AMAZONAS", "NILO", "GANGES", "MISSISSIPPI"], correct: 1 },
    { q: "ONDE FICAM AS ILHAS GALÁPAGOS", options: ["PERU", "EQUADOR", "CHILE", "COLÔMBIA"], correct: 1 },
    { q: "QUAL O MAIOR ARQUIPÉLAGO DO MUNDO", options: ["JAPÃO", "INDONÉSIA", "FILIPINAS", "MALDIVAS"], correct: 1 },
    { q: "QUAL O PONTO MAIS BAIXO DA TERRA", options: ["VALE DA MORTE", "MAR MORTO", "FOSSA DAS MARIANAS", "ABISMO"], correct: 1 },
    { q: "ONDE FICA O LAGO BAIKAL", options: ["CANADÁ", "RÚSSIA", "BRASIL", "EUA"], correct: 1 },
    { q: "QUAL O ESTREITO QUE SEPARA A EUROPA DA ÁFRICA", options: ["SUEZ", "GIBRALTAR", "MAGALHÃES", "BERING"], correct: 1 },
    { q: "ONDE FICA A MAIORIA DAS FLORESTAS DE CONÍFERAS", options: ["BRASIL", "RÚSSIA", "ÁFRICA", "AUSTRÁLIA"], correct: 1 },
    { q: "QUAL O MAIOR GOLFO DO MUNDO", options: ["GOLFO PÉRSICO", "GOLFO DO MÉXICO", "GOLFO DE BENGALA", "GOLFO DE ADEN"], correct: 1 },
    { q: "ONDE SE LOCALIZA O CANAL DO PANAMÁ", options: ["AMÉRICA DO SUL", "AMÉRICA CENTRAL", "AMÉRICA DO NORTE", "EUROPA"], correct: 1 },
    { q: "QUAL O NOME DA LINHA QUE DIVIDE OS HEMISFÉRIOS NORTE E SUL", options: ["GREENWICH", "EQUADOR", "TROPICO", "POLAR"], correct: 1 },
    { q: "QUAL O NOME DA LINHA QUE DIVIDE OS HEMISFÉRIOS LESTE E OESTE", options: ["EQUADOR", "MERIDIANO DE GREENWICH", "CAPRICÓRNIO", "CÂNCER"], correct: 1 },
    { q: "QUAL O MAIOR ESTADO DOS EUA EM TERRITÓRIO", options: ["TEXAS", "ALASKA", "CALIFÓRNIA", "FLÓRIDA"], correct: 1 },
    { q: "ONDE FICA O DESERTO DE GOBI", options: ["ÁFRICA", "ÁSIA", "AUSTRÁLIA", "EUA"], correct: 1 },
    { q: "QUAL O MAIOR RIO DA EUROPA", options: ["DANÚBIO", "VOLGA", "RENO", "SENA"], correct: 1 },
    { q: "QUAL A MAIOR ILHA DO MEDITERRÂNEO", options: ["CHIPRE", "SICÍLIA", "SARDENHA", "CRETA"], correct: 1 },
    { q: "ONDE FICA A GROENLÂNDIA", options: ["EUROPA", "AMÉRICA DO NORTE", "ÁRTICO", "ÁSIA"], correct: 1 },
    { q: "QUAL O NOME DO VENTO QUENTE DO DESERTO", options: ["BRISA", "SIROCO", "FURACÃO", "TORNADO"], correct: 1 },
    { q: "ONDE FICA A SEDE DA UNIÃO EUROPEIA", options: ["PARIS", "BRUXELAS", "BERLIM", "ESTRASBURGO"], correct: 1 },
    { q: "QUAL O BLOCO ECONÔMICO DA AMÉRICA DO NORTE", options: ["MERCOSUL", "USMCA", "UE", "APEC"], correct: 1 },
    { q: "QUANTOS PAÍSES FAZEM PARTE DO REINO UNIDO", options: ["2", "3", "4", "5"], correct: 2 },
    { q: "QUAL PAÍS FOI DIVIDIDO EM 1991", options: ["ALEMANHA", "URSS", "IUGOSLÁVIA", "TCHECOSLOVÁQUIA"], correct: 1 },
    { q: "O QUE SIGNIFICA A SIGLA 'BRICS'", options: ["BANCO REAL", "GRUPO DE PAÍSES EMERGENTES", "BLOCO RODOVIÁRIO", "MARCA DE CARRO"], correct: 1 },
    { q: "QUAL O PAÍS MAIS NOVO DA AMÉRICA DO SUL", options: ["SURINAME", "GUIANA", "SUDÃO", "URUGUAI"], correct: 1 },
    { q: "QUAL A MOEDA OFICIAL DO REINO UNIDO", options: ["EURO", "LIBRA ESTERLINA", "DÓLAR", "FRANCO"], correct: 1 },
    { q: "QUAL PAÍS TEM O MAIOR NÚMERO DE VETOS NA ONU", options: ["BRASIL", "RÚSSIA", "CHINA", "EUA"], correct: 1 },
    { q: "ONDE FICA A SEDE DA UNESCO", options: ["NEW YORK", "PARIS", "ROMA", "GENEBRA"], correct: 1 },
    { q: "QUAL PAÍS SAIU DA UNIÃO EUROPEIA RECENTEMENTE", options: ["FRANÇA", "REINO UNIDO", "GRÉCIA", "ITÁLIA"], correct: 1 },
    { q: "O QUE É O ESTADO DO VATICANO", options: ["UMA CIDADE-ESTADO", "UM BAIRRO", "UM PAÍS GIGANTE", "UMA ILHA"], correct: 0 },
    { q: "QUAL PAÍS É CONSIDERADO O MAIS ISOLADO DO MUNDO", options: ["CHINA", "COREIA DO NORTE", "RÚSSIA", "CUBA"], correct: 1 },
    { q: "QUAL O NOME DA ALIANÇA MILITAR DO ATLÂNTICO", options: ["ONU", "OTAN", "BRICS", "MERCOSUL"], correct: 1 },
    { q: "EM QUAL PAÍS FICA A SEDE DA OMS", options: ["FRANÇA", "SUÍÇA", "EUA", "INGLATERRA"], correct: 1 },
    { q: "QUAL O IDIOMA MAIS ESPALHADO PELO MUNDO", options: ["MANDARIM", "INGLÊS", "ESPANHOL", "ÁRABE"], correct: 1 },
    { q: "QUAL PAÍS TEM A MAIOR RESERVA DE PETRÓLEO", options: ["ARÁBIA SAUDITA", "VENEZUELA", "EUA", "RÚSSIA"], correct: 1 },
    { q: "QUAL O NOME DA LINHA QUE DETERMINA A DATA", options: ["EQUADOR", "LINHA INTERNACIONAL DE DATA", "GREENWICH", "CÂNCER"], correct: 1 },
    { q: "O QUE É O EXCLAVE", options: ["PARTE DE UM PAÍS FORA DELE", "ILHA", "MONTANHA", "RIO"], correct: 0 },
    { q: "QUAL PAÍS É CONHECIDO POR SER O MAIS NEUTRO", options: ["ALEMANHA", "SUÍÇA", "SUÉCIA", "ÁUSTRIA"], correct: 1 },
    { q: "ONDE FICA O CANAL DE MANCHA", options: ["ENTRE BRASIL E ARGENTINA", "ENTRE FRANÇA E INGLATERRA", "ENTRE EUA E MÉXICO", "NA CHINA"], correct: 1 },
    { q: "QUAL PAÍS TEM UM CANGURU NA BANDEIRA", options: ["NOVA ZELÂNDIA", "AUSTRÁLIA", "ÁFRICA DO SUL", "ÍNDIA"], correct: 1 },
    { q: "QUAL BANDEIRA É VERMELHA COM UM CÍRCULO BRANCO E LUA", options: ["TURQUIA", "TUNÍSIA", "JAPÃO", "CHINA"], correct: 1 },
    { q: "QUAL PAÍS TEM UMA BANDEIRA COM LISTRAS AZUIS E BRANCAS", options: ["BRASIL", "GRÉCIA", "FRANÇA", "ALEMANHA"], correct: 1 },
    { q: "QUAL A ÚNICA BANDEIRA DO MUNDO COM 3 LADOS", options: ["VATICANO", "NEPAL", "SUIÇA", "MÔNACO"], correct: 1 },
    { q: "CORES DA BANDEIRA DA ALEMANHA", options: ["PRETO, VERMELHO E AMARELO", "AZUL, BRANCO E VERMELHO", "VERDE E AMARELO", "VERMELHO E PRETO"], correct: 0 },
    { q: "QUAL PAÍS TEM UMA ESTRELA DE DAVI NA BANDEIRA", options: ["EGITO", "ISRAEL", "JORDÂNIA", "IRAQUE"], correct: 1 },
    { q: "A BANDEIRA DO JAPÃO É CHAMADA DE...", options: ["ESTRELA", "HINOMARU", "SOL", "PONTO"], correct: 1 },
    { q: "QUAL PAÍS TEM AS CORES DA BANDEIRA IGUAIS À DO BRASIL", options: ["NENHUM", "JAMAICA", "ARGENTINA", "CHILE"], correct: 1 },
    { q: "QUAL BANDEIRA TEM O MAPA DO PRÓPRIO PAÍS", options: ["BRASIL", "CHIPRE", "CANADÁ", "EUA"], correct: 1 },
    { q: "QUAL PAÍS TEM UMA ÁUIA NO MEIO DA BANDEIRA", options: ["EUA", "MÉXICO", "BRASIL", "RÚSSIA"], correct: 1 },
    { q: "CORES DA BANDEIRA DA RÚSSIA", options: ["VERMELHO E AMARELO", "BRANCO, AZUL E VERMELHO", "VERDE E BRANCO", "PRETO E BRANCO"], correct: 1 },
    { q: "QUAL PAÍS TEM UMA ÁRVORE NA BANDEIRA", options: ["CANADÁ", "LÍBANO", "BRASIL", "GRÉCIA"], correct: 1 },
    { q: "QUANTAS ESTRELAS TEM A BANDEIRA DOS EUA", options: ["13", "50", "51", "48"], correct: 1 },
    { q: "QUANTAS ESTRELAS TEM A BANDEIRA DO BRASIL", options: ["21", "27", "26", "28"], correct: 1 },
    { q: "QUAL PAÍS TEM A 'UNION JACK' EM SUA BANDEIRA", options: ["EUA", "AUSTRÁLIA", "ÍNDIA", "ÁFRICA DO SUL"], correct: 1 },
    { q: "CORES DA BANDEIRA DA FRANÇA", options: ["AZUL, BRANCO E VERMELHO", "VERDE, BRANCO E VERMELHO", "AMARELO E AZUL", "PRETO E VERMELHO"], correct: 0 },
    { q: "QUAL PAÍS TEM UM SOL COM ROSTO NA BANDEIRA", options: ["CHILE", "URUGUAI E ARGENTINA", "MÉXICO", "PERU"], correct: 1 },
    { q: "QUAL BANDEIRA TEM AS CORES DO ARCO-ÍRIS", options: ["MÉXICO", "BANDEIRA DE CUSCO/LGBT", "BRASIL", "FRANÇA"], correct: 1 },
    { q: "QUAL PAÍS TEM UMA BANDEIRA TOTALMENTE VERDE", options: ["EGITO", "LÍBIA", "SUDÃO", "OMÃ"], correct: 1 },
    { q: "QUAL O NOME DA BANDEIRA DOS ESTADOS UNIDOS", options: ["UNION JACK", "STARS AND STRIPES", "TRICOLORE", "AURIVERDE"], correct: 1 },
    { q: "QUAL O MENOR PAÍS DA AMÉRICA DO SUL", options: ["URUGUAI", "SURINAME", "GUIANA", "EQUADOR"], correct: 1 },
    { q: "QUAL PAÍS É FAMOSO PELOS SEUS FIORDES", options: ["SUÉCIA", "NORUEGA", "DINAMARCA", "ISLÂNDIA"], correct: 1 },
    { q: "ONDE SE LOCALIZA O MONTE BRANCO", options: ["ALPES DA FRANÇA/ITÁLIA", "HIMALAIA", "ANDES", "PIRINEUS"], correct: 0 },
    { q: "QUAL O MAIOR LAGO DA AMÉRICA DO SUL", options: ["TITICACA", "LAGOA DOS PATOS", "MARACAIBO", "PARANÁ"], correct: 2 },
    { q: "QUAL PAÍS TEM O FORMATO DE UM L", options: ["VIETNÃ", "CHILE", "NORUEGA", "ITÁLIA"], correct: 1 },
    { q: "QUAL O RIO MAIS IMPORTANTE DA ALEMANHA", options: ["SENA", "RENO", "DANÚBIO", "VOLGA"], correct: 1 },
    { q: "QUAL PAÍS É CONHECIDO COMO 'A ILHA ESMERALDA'", options: ["ISLÂNDIA", "IRLANDA", "GRÉCIA", "CUBA"], correct: 1 },
    { q: "EM QUAL PAÍS FICA A REGIÃO DA BAVIERA", options: ["ÁUSTRIA", "ALEMANHA", "SUIÇA", "BÉLGICA"], correct: 1 },
    { q: "QUAL A MAIOR CIDADE DA EUROPA", options: ["PARIS", "LONDRES", "ISTAMBUL", "BERLIM"], correct: 2 },
    { q: "ONDE FICAM AS MONTANHAS ROCHOSAS", options: ["AMÉRICA DO SUL", "AMÉRICA DO NORTE", "ÁSIA", "EUROPA"], correct: 1 },
    { q: "QUAL PAÍS TEM O CANAL QUE LIGA OS OCEANOS", options: ["MÉXICO", "PANAMÁ", "COLÔMBIA", "EGITO"], correct: 1 },
    { q: "QUAL O PONTO MAIS ALTO DA EUROPA", options: ["MONTE BRANCO", "ELBRUS", "ETNA", "OLIMPO"], correct: 1 },
    { q: "ONDE FICA A PENÍNSULA IBÉRICA", options: ["ITÁLIA/GRÉCIA", "ESPANHA/PORTUGAL", "NORUEGA/SUÉCIA", "DINAMARCA"], correct: 1 },
    { q: "QUAL O NOME DO RIO QUE CRUZA 10 PAÍSES EUROPEUS", options: ["RENO", "DANÚBIO", "VOLGA", "TIBRE"], correct: 1 },
    { q: "QUAL O NOME DA MAIOR ILHA DO CARIBE", options: ["JAMAICA", "CUBA", "HAITI", "PORTO RICO"], correct: 1 },
    { q: "ONDE FICA O MONTE ETNA", options: ["GRÉCIA", "ITÁLIA", "ESPANHA", "FRANÇA"], correct: 1 },
    { q: "QUAL A CAPITAL DA REPÚBLICA TCHECA", options: ["BUDAPESTE", "PRAGA", "BRATISLAVA", "VIENA"], correct: 1 },
    { q: "QUAL O NOME DA PARTE DA RÚSSIA QUE FICA NA ÁSIA", options: ["ESTEPE", "SIBÉRIA", "TAIGA", "TUNDRA"], correct: 1 },
    { q: "ONDE SE LOCALIZAM AS CATARATAS DO NIÁGARA", options: ["BRASIL/ARGENTINA", "EUA/CANADÁ", "ÁFRICA", "CHINA"], correct: 1 },
    { q: "QUAL O NOME DO MAR QUE BANHA A GRÉCIA", options: ["CASPIO", "EGUEU", "MORTO", "VERMELHO"], correct: 1 },
    { q: "QUAL A CAPITAL DAS FILIPINAS", options: ["BANGKOK", "MANILA", "JACARTA", "HANOI"], correct: 1 },
    { q: "PEQUIM É A CAPITAL DE QUAL PAÍS", options: ["JAPÃO", "CHINA", "COREIA", "MONGÓLIA"], correct: 1 },
    { q: "QUAL A CAPITAL DA ÍNDIA", options: ["MUMBAI", "NOVA DELI", "CALCUTÁ", "AGRA"], correct: 1 },
    { q: "QUAL A CAPITAL DO QUÊNIA", options: ["LAGOS", "NAIROBI", "DURBAN", "CAIRO"], correct: 1 },
    { q: "QUAL A CAPITAL DO PAQUISTÃO", options: ["CABUL", "ISLAMABAD", "KARACHI", "TEERÃ"], correct: 1 },
    { q: "QUAL A CAPITAL DA MALÁSIA", options: ["CINGAPURA", "KUALA LUMPUR", "BANGKOK", "MANILA"], correct: 1 },
    { q: "QUAL A CAPITAL DO MARROCOS", options: ["CASABLANCA", "RABAT", "MARRAKESH", "TÂNGER"], correct: 1 },
    { q: "QUAL A CAPITAL DA ETIÓPIA", options: ["ADIS ABEBA", "NAIROBI", "ACRA", "LUANDA"], correct: 0 },
    { q: "DOHA É A CAPITAL DE QUAL PAÍS", options: ["EMIRADOS ÁRABES", "CATAR", "OMÃ", "KUWAIT"], correct: 1 },
    { q: "QUAL A CAPITAL DA ANGOLA", options: ["BENGUELA", "LUANDA", "HUAMBO", "MAPUTO"], correct: 1 },
    { q: "QUAL A CAPITAL DE MOÇAMBIQUE", options: ["LUANDA", "MAPUTO", "BEIRA", "NAMPULA"], correct: 1 },
    { q: "QUAL A CAPITAL DA SÍRIA", options: ["BAGDÁ", "DAMASCO", "ALEPPO", "BEIRUTE"], correct: 1 },
    { q: "QUAL A CAPITAL DO LÍBANO", options: ["DAMASCO", "BEIRUTE", "AMAN", "TEL AVIV"], correct: 1 },
    { q: "QUAL A CAPITAL DA JORDÂNIA", options: ["AMAN", "BAGDÁ", "DOHA", "RIADE"], correct: 0 },
    { q: "QUAL A CAPITAL DO IRAQUE", options: ["TEERÃ", "BAGDÁ", "BASRA", "CABUL"], correct: 1 },
    { q: "QUAL A CAPITAL DO AFEGANISTÃO", options: ["ISLAMABAD", "CABUL", "KANDAHAR", "DUSHANBE"], correct: 1 },
    { q: "QUAL A CAPITAL DE ISRAEL", options: ["JERUSALÉM", "TEL AVIV", "HAIFA", "NAZARÉ"], correct: 1 },
    { q: "QUAL A CAPITAL DO SRI LANKA", options: ["COLOMBO", "KANDY", "MALÉ", "DHAKA"], correct: 0 },
    { q: "QUAL A CAPITAL DE TAIWAN", options: ["XANGAI", "TAIPÉ", "HONG KONG", "SEUL"], correct: 1 },
    { q: "QUAL A CAPITAL DA MONGÓLIA", options: ["ASTANA", "ULAN BATOR", "LHAZA", "PEQUIM"], correct: 1 },
    { q: "QUAL A MAIOR ILHA DO ARQUIPÉLAGO JAPONÊS", options: ["HOKKAIDO", "HONSHU", "KYUSHU", "SHIKOKU"], correct: 1 },
    { q: "ONDE SE LOCALIZA A ILHA DE MADAGASCAR", options: ["OCEANO PACÍFICO", "OCEANO ÍNDICO", "OCEANO ATLÂNTICO", "MAR MEDITERRÂNEO"], correct: 1 },
    { q: "QUAL O NOME DA ILHA QUE É UM PAÍS NA EUROPA", options: ["GROENLÂNDIA", "ISLÂNDIA", "SICÍLIA", "CRETA"], correct: 1 },
    { q: "QUAL O NOME DO CONJUNTO DE ILHAS DO HAVAI", options: ["ARQUIPÉLAGO", "ATOL", "CONTINENTE", "PENÍNSULA"], correct: 0 },
    { q: "ONDE FICAM AS ILHAS MALVINAS", options: ["ATLÂNTICO SUL", "PACÍFICO NORTE", "MAR CARIBE", "MAR VERMELHO"], correct: 0 },
    { q: "QUAL O NOME DA MAIOR ILHA DA OCEANIA", options: ["NOVA ZELÂNDIA", "AUSTRÁLIA", "TASMANIA", "FIJI"], correct: 1 },
    { q: "QUAL O NOME DA ILHA ONDE FICA NOVA YORK", options: ["LONG ISLAND", "MANHATTAN", "STATEN ISLAND", "CUBA"], correct: 1 },
    { q: "ONDE SE LOCALIZA A ILHA DE BALI", options: ["FILIPINAS", "INDONÉSIA", "TAILÂNDIA", "MALÁSIA"], correct: 1 },
    { q: "QUAL O NOME DA ILHA QUE É DIVIDIDA ENTRE DOIS PAÍSES", options: ["MADAGASCAR", "HISPANÍOLA", "JAMAICA", "TAIWAN"], correct: 1 },
    { q: "ONDE FICAM AS ILHAS CANÁRIAS", options: ["MAR MEDITERRÂNEO", "OCEANO ATLÂNTICO", "OCEANO PACÍFICO", "MAR MORTO"], correct: 1 },
    { q: "QUAL O NOME DA ILHA MAIS POPULOSA DO MUNDO", options: ["MANHATTAN", "JAVA", "GRAN-BRETANHA", "HONSHU"], correct: 1 },
    { q: "EM QUE OCEANO FICA A ILHA DE PÁSCOA", options: ["OCEANO ATLÂNTICO", "OCEANO PACÍFICO", "OCEANO ÍNDICO", "MAR DO NORTE"], correct: 1 },
    { q: "QUAL O NOME DO ESTREITO ENTRE A RÚSSIA E O ALASKA", options: ["GIBRALTAR", "ESTREITO DE BERING", "MAGALHÃES", "SUEZ"], correct: 1 },
    { q: "QUAL O NOME DO MAR QUE BANHA A ITÁLIA", options: ["MAR VERMELHO", "MAR ADRIÁTICO", "MAR NEGRO", "MAR CÁSPIO"], correct: 1 },
    { q: "QUAL O NOME DO MAR QUE BANHA O NORTE DA ÁFRICA", options: ["ATLÂNTICO", "MEDITERRÂNEO", "PACÍFICO", "ÁRTICO"], correct: 1 },
    { q: "ONDE FICA O GOLFO PÉRSICO", options: ["AMÉRICA CENTRAL", "ORIENTE MÉDIO", "EUROPA", "ÁFRICA"], correct: 1 },
    { q: "QUAL O NOME DO MAR QUE É UM LAGO SALGADO", options: ["MAR NEGRO", "MAR CÁSPIO", "MAR VERMELHO", "MAR DE ARAL"], correct: 1 },
    { q: "QUAL O NOME DO OCEANO QUE BANHA A CALIFÓRNIA", options: ["ATLÂNTICO", "PACÍFICO", "ÍNDICO", "ANTÁRTICO"], correct: 1 },
    { q: "QUAL O NOME DO MAR ENTRE A EUROPA E A TURQUIA", options: ["MEDITERRÂNEO", "MAR NEGRO", "MAR MORTO", "MAR BÁLTICO"], correct: 1 },
    { q: "ONDE FICA A PENÍNSULA DA ESCANDINÁVIA", options: ["SUL DA EUROPA", "NORTE DA EUROPA", "ÁSIA", "AMÉRICA DO NORTE"], correct: 1 },
    { q: "O QUE É O EL NIÑO", options: ["VENTO FRIO", "AQUECIMENTO DAS ÁGUAS DO PACÍFICO", "UM FURACÃO", "UM VULCÃO"], correct: 1 },
    { q: "QUAL O NOME DO VENTO QUE ATINGE VELOCIDADES EXTREMAS", options: ["BRISA", "FURACÃO/TORNADO", "SIROCO", "PASSATOS"], correct: 1 },
    { q: "QUAL O NOME DA CHUVA QUE OCORRE EM MONTANHAS", options: ["CONVECTIVA", "OROGRÁFICA", "FRONTAL", "ÁCIDA"], correct: 1 },
    { q: "O QUE É A AMPLITUDE TÉRMICA", options: ["CALOR MÁXIMO", "DIFERENÇA ENTRE TEMP. MÁXIMA E MÍNIMA", "FRIO MÉDIO", "PRESSÃO"], correct: 1 },
    { q: "QUAL O NOME DO INSTRUMENTO QUE MEDE A CHUVA", options: ["TERMÔMETRO", "PLUVIÔMETRO", "BARÔMETRO", "ANEMÔMETRO"], correct: 1 },
    { q: "QUAL O NOME DO CLIMA DAS REGIÕES DESÉRTICAS", options: ["ÚMIDO", "ÁRIDO", "TROPICAL", "TEMPERADO"], correct: 1 },
    { q: "O QUE É O EFEITO ESTUFA", options: ["RESFRIAMENTO", "AQUECIMENTO DA ATMOSFERA", "VENTO FORTE", "CHUVA"], correct: 1 },
    { q: "QUAL O NOME DA CAMADA QUE PROTEGE DA RADIAÇÃO UV", options: ["MANTO", "CAMADA DE OZÔNIO", "NÚCLEO", "OZÔNIO AZUL"], correct: 1 },
    { q: "QUAL O NOME DO VENTO QUE SOPRA DO MAR PARA A TERRA", options: ["BRISA MARÍTIMA", "BRISA TERRESTRE", "TORNADO", "CIGARRA"], correct: 0 },
    { q: "QUAL O NOME DO CLIMA COM 4 ESTAÇÕES BEM DEFINIDAS", options: ["TROPICAL", "TEMPERADO", "EQUATORIAL", "POLAR"], correct: 1 },
    { q: "QUAL O NOME DO FENÔMENO DE INVERSÃO TÉRMICA", options: ["CALOR NO TOPO", "AR FRIO PRESO PRÓXIMO AO SOLO", "VENTO", "CHUVA"], correct: 1 },
    { q: "O QUE SÃO AS GEADAS", options: ["CHUVA DE GELO", "CONGELAMENTO DO ORVALHO NO SOLO", "NEVE", "NEBLINA"], correct: 1 },
    { q: "QUAL O NOME DA NUVEM DE TEMPESTADE", options: ["ESTRATO", "CUMULONIMBUS", "CIRRUS", "CUMULUS"], correct: 1 },
    { q: "O QUE É O CICLONE", options: ["VENTO PARADO", "SISTEMA DE BAIXA PRESSÃO COM VENTOS GIRATÓRIOS", "LAVA", "TERREMOTO"], correct: 1 },
    { q: "ONDE OCORREM AS MONÇÕES MAIS FORTES", options: ["AMÉRICA DO SUL", "SUL E SUDESTE DA ÁSIA", "EUROPA", "ÁFRICA DO SUL"], correct: 1 },
    { q: "QUAL O NOME DO PONTO ONDE NASCE O SOL", options: ["NORTE", "LESTE", "OESTE", "SUL"], correct: 1 },
    { q: "QUAL O NOME DO PONTO ONDE O SOL SE PÕE", options: ["NORTE", "OESTE", "LESTE", "SUL"], correct: 1 },
    { q: "O QUE É A ALBEDO", options: ["COR DA TERRA", "REFLEXÃO DA LUZ SOLAR PELA SUPERFÍCIE", "CALOR", "SOM"], correct: 1 },
    { q: "QUAL O NOME DO CLIMA COM MUITA CHUVA E CALOR", options: ["SECO", "EQUATORIAL", "POLAR", "MEDITERRÂNEO"], correct: 1 },
    { q: "QUAL O NOME DO DESERTO DE GELO AO NORTE", options: ["ANTÁRTIDA", "ÁRTICO", "SAARA", "GOBI"], correct: 1 },
    { q: "QUAL O NOME DA LINHA QUE SEPARA AS DUAS COREIAS", options: ["LINHA DO EQUADOR", "ZONA DESMILITARIZADA", "MURO DE BERLIM", "FRONTEIRA VERDE"], correct: 1 },
    { q: "QUAL PAÍS TEM O MAIOR NÚMERO DE LÍNGUAS OFICIAIS", options: ["EUA", "ÁFRICA DO SUL", "ÍNDIA", "BRASIL"], correct: 2 },
    { q: "QUAL O ÚNICO PAÍS QUE NÃO TEM BANDEIRA RETANGULAR", options: ["SUIÇA", "NEPAL", "VATICANO", "BÉLGICA"], correct: 1 },
    { q: "EM QUAL PAÍS FICA A REGIÃO DA TASCÂNIA", options: ["NOVA ZELÂNDIA", "AUSTRÁLIA", "INGLATERRA", "ITÁLIA"], correct: 1 },
    { q: "QUAL A CAPITAL DA JORDÂNIA", options: ["AMÃ", "DOHA", "BAGDÁ", "DAMASCO"], correct: 0 },
    { q: "QUAL PAÍS TEM O MAIOR NÚMERO DE PIRÂMIDES", options: ["EGITO", "SUDÃO", "MÉXICO", "PERU"], correct: 1 },
    { q: "ONDE SE LOCALIZA O MONTE KILIMANJARO", options: ["QUÊNIA", "TANZÂNIA", "EGITO", "ETIÓPIA"], correct: 1 },
    { q: "QUAL PAÍS É CONHECIDO COMO O 'CELEIRO DO MUNDO'", options: ["CHINA", "UCRÂNIA", "BRASIL", "EUA"], correct: 1 },
    { q: "QUAL A CAPITAL DA SÉRVIA", options: ["ZAGREB", "BELGRADO", "SARAJEVO", "SOFIA"], correct: 1 },
    { q: "QUAL O NOME DO MAR QUE BANHA A ROMÊNIA", options: ["MAR VERMELHO", "MAR NEGRO", "MAR CASPIO", "MAR ADRIÁTICO"], correct: 1 },
    { q: "EM QUAL PAÍS FICA O LAGO GENEBRA", options: ["FRANÇA", "SUÍÇA", "ALEMANHA", "ÁUSTRIA"], correct: 1 },
    { q: "QUAL A CAPITAL DA CROÁCIA", options: ["LJUBLJANA", "ZAGREB", "SPLIT", "DUBROVNIK"], correct: 1 },
    { q: "QUAL PAÍS É DIVIDIDO PELO ESTREITO DE BÓSFORO", options: ["GRÉCIA", "TURQUIA", "EGITO", "RÚSSIA"], correct: 1 },
    { q: "QUAL A CAPITAL DA ESTÔNIA", options: ["RIGA", "TALLINN", "VILNIUS", "HELSINQUE"], correct: 1 },
    { q: "QUAL O MENOR PAÍS DA UNIÃO EUROPEIA", options: ["MÔNACO", "MALTA", "LUXEMBURGO", "CHIPRE"], correct: 1 },
    { q: "ONDE FICA A SEDE DA INTERPOL", options: ["PARIS", "LYON", "NEW YORK", "LONDRES"], correct: 1 },
    { q: "QUAL PAÍS É CONHECIDO PELA 'TERRA DO DRAGÃO'", options: ["JAPÃO", "BUTÃO", "CHINA", "VIETNÃ"], correct: 1 },
    { q: "QUAL A CAPITAL DA LITUÂNIA", options: ["TALLINN", "VILNIUS", "RIGA", "MINSK"], correct: 1 },
    { q: "QUAL O ÚNICO PAÍS DA AMÉRICA DO SUL QUE TEM O INGLÊS COMO LÍNGUA OFICIAL", options: ["SURINAME", "GUIANA", "TRINIDAD", "EQUADOR"], correct: 1 },
    { q: "ONDE FICA O CANAL DO PANAMÁ", options: ["AMÉRICA DO SUL", "AMÉRICA CENTRAL", "AMÉRICA DO NORTE", "ÁSIA"], correct: 1 },
    { q: "QUAL O PAÍS COM A MAIOR DENSIDADE DEMOGRÁFICA", options: ["CHINA", "MÔNACO", "ÍNDIA", "CINGAPURA"], correct: 1 },
    { q: "QUAL O CONTINENTE COM A MAIOR TAXA DE CRESCIMENTO POPULACIONAL", options: ["ÁSIA", "ÁFRICA", "AMÉRICA", "EUROPA"], correct: 1 },
    { q: "O QUE É O 'BABY BOOM'", options: ["QUEDA DE NATALIDADE", "AUMENTO SÚBITO DE NASCIMENTOS", "NOME DE UM PAÍS", "CRISE ECONÔMICA"], correct: 1 },
    { q: "QUAL O MAIOR PRODUTOR DE OURO DO MUNDO", options: ["BRASIL", "CHINA", "ÁFRICA DO SUL", "AUSTRÁLIA"], correct: 1 },
    { q: "QUAL O MAIOR EXPORTADOR DE PETRÓLEO DO MUNDO", options: ["VENEZUELA", "ARÁBIA SAUDITA", "EUA", "RÚSSIA"], correct: 1 },
    { q: "QUAL O PAÍS COM A MAIOR EXPECTATIVA DE VIDA", options: ["EUA", "JAPÃO", "SUIÇA", "ALEMANHA"], correct: 1 },
    { q: "O QUE É A POPULAÇÃO ECONOMICAMENTE ATIVA", options: ["CRIANÇAS", "PESSOAS QUE TRABALHAM OU BUSCAM TRABALHO", "APOSENTADOS", "ESTUDANTES"], correct: 1 },
    { q: "QUAL O MAIOR PRODUTOR DE SOJA DO MUNDO", options: ["CHINA", "BRASIL", "EUA", "ARGENTINA"], correct: 1 },
    { q: "O QUE É A MIGRAÇÃO PENDULAR", options: ["MUDAR DE PAÍS", "DESLOCAMENTO DIÁRIO", "MUDAR DE CASA", "VIAGEM DE FÉRIAS"], correct: 1 },
    { q: "QUAL O PAÍS COM O MAIOR NÚMERO DE IMIGRANTES", options: ["ALEMANHA", "ESTADOS UNIDOS", "CANADÁ", "FRANÇA"], correct: 1 },
    { q: "O QUE É O CRESCIMENTO VEGETATIVO", options: ["PLANTAR ÁRVORES", "DIFERENÇA ENTRE NATALIDADE E MORTALIDADE", "AUMENTO DE CIDADES", "PRODUÇÃO AGRÍCOLA"], correct: 1 },
    { q: "QUAL O MAIOR PRODUTOR DE DIAMANTES DO MUNDO", options: ["ÁFRICA DO SUL", "RÚSSIA", "BOTSUANA", "CANADÁ"], correct: 1 },
    { q: "COMO É CHAMADO O SETOR 'CEREBRO' DA ECONOMIA", options: ["PRIMÁRIO", "SECUNDÁRIO", "TERCIÁRIO", "QUATERNÁRIO"], correct: 3 },
    { q: "QUAL O MAIOR PRODUTOR DE ENERGIA EÓLICA", options: ["BRASIL", "CHINA", "EUA", "ALEMANHA"], correct: 1 },
    { q: "O QUE É O DESEMPREGO ESTRUTURAL", options: ["FALTA DE VAGAS", "SUBSTITUIÇÃO POR MÁQUINAS/TECNOLOGIA", "CRISE", "FÉRIAS"], correct: 1 },
    { q: "QUAL O PAÍS COM A MAIOR RESERVA DE ÁGUA DOCE", options: ["EUA", "BRASIL", "RÚSSIA", "CANADÁ"], correct: 1 },
    { q: "O QUE É O AGRONEGÓCIO", options: ["SÓ PLANTAR", "CADEIA PRODUTIVA DA AGRICULTURA E PECUÁRIA", "VENDER TERRA", "GOVERNO"], correct: 1 },
    { q: "QUAL O MAIOR PRODUTOR DE CAFÉ DA AMÉRICA CENTRAL", options: ["MÉXICO", "HONDURAS", "COSTA RICA", "PANAMÁ"], correct: 1 },
    { q: "O QUE É O 'LIXO ELETRÔNICO'", options: ["RESTOS DE COMIDA", "RESÍDUOS DE APARELHOS TECNOLÓGICOS", "PAPEL", "PLÁSTICO"], correct: 1 },
    { q: "QUAL O MAIOR PRODUTOR DE CARNE DE FRANGO DO MUNDO", options: ["BRASIL", "EUA", "CHINA", "RÚSSIA"], correct: 1 },
    { q: "QUAL O PONTO MAIS SETENTRIONAL DA TERRA", options: ["POLO SUL", "POLO NORTE", "EQUADOR", "ALASKA"], correct: 1 },
    { q: "QUAL A MAIOR DISTÂNCIA POSSÍVEL EM LINHA RETA NA TERRA", options: ["LONGITUDE", "ANTÍPODA", "LINHA DO EQUADOR", "MERIDIANO"], correct: 1 },
    { q: "QUAL O NOME DO DESERTO NO NORTE DA CHINA", options: ["SAARA", "GOBI", "ATACAMA", "CALAHARI"], correct: 1 },
    { q: "ONDE SE LOCALIZA A PENÍNSULA DO YUCATÁN", options: ["BRASIL", "MÉXICO", "ESPANHA", "ITÁLIA"], correct: 1 },
    { q: "QUAL O NOME DA PASSAGEM AO SUL DA AMÉRICA DO SUL", options: ["CANAL DE SUEZ", "ESTREITO DE MAGALHÃES", "GIBRALTAR", "BERING"], correct: 1 },
    { q: "ONDE FICA O MAR DE ARAL", options: ["EUROPA", "ÁSIA CENTRAL", "ÁFRICA", "AMÉRICA"], correct: 1 },
    { q: "QUAL O MAIOR PAÍS EM EXTENSÃO NA ÁFRICA", options: ["EGITO", "ARGÉLIA", "NIGÉRIA", "SUDÃO"], correct: 1 },
    { q: "QUAL O NOME DO RIO QUE DIVIDE OS EUA E O MÉXICO", options: ["MISSISSIPPI", "RIO GRANDE", "COLORADO", "AMAZONAS"], correct: 1 },
    { q: "QUAL O NOME DA MONTANHA MAIS ALTA DA AMÉRICA DO NORTE", options: ["EVEREST", "DENALI", "ACONCÁGUA", "ALPES"], correct: 1 },
    { q: "ONDE FICA A ILHA DE JAVA", options: ["FILIPINAS", "INDONÉSIA", "JAPÃO", "TAILÂNDIA"], correct: 1 },
    { q: "QUAL O NOME DO MAR QUE FICA NO INTERIOR DA RÚSSIA", options: ["CASPIO", "LAGO BAIKAL", "MAR DE ARAL", "MAR NEGRO"], correct: 1 },
    { q: "QUAL O NOME DO RIO MAIS LONGO DA ÁSIA", options: ["GANGES", "YANGTZÉ", "AMARELO", "MEKONG"], correct: 1 },
    { q: "QUAL O NOME DA MAIOR BAÍA DO MUNDO", options: ["BAÍA DE GUANABARA", "BAÍA DE BENGALA", "HUDSON", "TODOS OS SANTOS"], correct: 1 },
    { q: "ONDE SE LOCALIZA O PAÍS GEÓRGIA", options: ["AMÉRICA", "ÁSIA/EUROPA", "ÁFRICA", "OCEANIA"], correct: 1 },
    { q: "QUAL O NOME DO PONTO MAIS ALTO DA OCEANIA", options: ["MONTE COOK", "PUNCAK JAYA", "EVEREST", "ULURU"], correct: 1 },
    { q: "ONDE FICA O MAR CARIBE", options: ["OCEANO ÍNDICO", "OCEANO ATLÂNTICO CENTRAL", "PACÍFICO", "ÁRTICO"], correct: 1 },
    { q: "QUAL O NOME DA MAIOR CACHOEIRA DO MUNDO EM ALTURA", options: ["IGUAÇU", "ANGEL FALLS", "NIÁGARA", "VICTORIA FALLS"], correct: 1 },
    { q: "QUAL O NOME DO ARQUIPÉLAGO ONDE FICA HONOLULU", options: ["GALAPAGOS", "HAVAÍ", "MALDIVAS", "FILIPINAS"], correct: 1 },
    { q: "QUAL O NOME DO RIO QUE PASSA POR ROMA", options: ["SENA", "TIBRE", "TÂMISA", "PO"], correct: 1 },
    { q: "QUAL A CAPITAL DO PARAGUAI", options: ["MONTEVIDÉU", "ASSUNÇÃO", "LA PAZ", "LIMA"], correct: 1 },
    { q: "QUAL A CAPITAL DA HUNGRIA", options: ["VIENA", "BUDAPESTE", "BUCARESTE", "PRAGA"], correct: 1 },
    { q: "QUAL A CAPITAL DA ROMÊNIA", options: ["SOFIA", "BUCARESTE", "BELGRADO", "TIRANA"], correct: 1 },
    { q: "QUAL A CAPITAL DA BULGÁRIA", options: ["BUCARESTE", "SOFIA", "SKOPJE", "ATENAS"], correct: 1 },
    { q: "QUAL A CAPITAL DA ÁUSTRIA", options: ["BERNA", "VIENA", "ZURIQUE", "MUNIQUE"], correct: 1 },
    { q: "QUAL A CAPITAL DA ESLOVÁQUIA", options: ["PRAGA", "BRATISLAVA", "LJUBLJANA", "ZAGREB"], correct: 1 },
    { q: "QUAL A CAPITAL DA ESLOVÊNIA", options: ["ZAGREB", "LJUBLJANA", "SARAJEVO", "SKOPJE"], correct: 1 },
    { q: "QUAL A CAPITAL DA CROÁCIA", options: ["SPLIT", "ZAGREB", "DUBROVNIK", "BELGRADO"], correct: 1 },
    { q: "QUAL A CAPITAL DA BÓSNIA E HERZEGOVINA", options: ["MOSTAR", "SARAJEVO", "TIRANA", "PRISTINA"], correct: 1 },
    { q: "QUAL A CAPITAL DA ALBÂNIA", options: ["SKOPJE", "TIRANA", "PODGORICA", "ATENAS"], correct: 1 },
    { q: "QUAL A CAPITAL DA MACEDÔNIA DO NORTE", options: ["TIRANA", "SKOPJE", "SOFIA", "BELGRADO"], correct: 1 },
    { q: "QUAL A CAPITAL DE MONTENEGRO", options: ["ZAGREB", "PODGORICA", "SARAJEVO", "TIRANA"], correct: 1 },
    { q: "QUAL A CAPITAL DA BÉLGICA", options: ["ANTUÉRPIA", "BRUXELAS", "GENT", "BRUGES"], correct: 1 },
    { q: "QUAL A CAPITAL DE LUXEMBURGO", options: ["PARIS", "LUXEMBURGO", "BRUXELAS", "ESTOCOLMO"], correct: 1 },
    { q: "QUAL A CAPITAL DE MÔNACO", options: ["NICE", "MÔNACO", "CANNES", "MARSELHA"], correct: 1 },
    { q: "QUAL A CAPITAL DE ANDORRA", options: ["BARCELONA", "ANDORRA A VELHA", "MADRI", "TOULOUSE"], correct: 1 },
    { q: "QUAL A CAPITAL DE MALTA", options: ["VALETA", "MDINA", "SLIEMA", "GOZO"], correct: 0 },
    { q: "QUAL A CAPITAL DE CHIPRE", options: ["ATENAS", "NICÓSIA", "LARNACA", "LIMASSOL"], correct: 1 },
    { q: "QUAL A CAPITAL DA ISLÂNDIA", options: ["OSLO", "REIJKJAVIK", "ESTOCOLMO", "HELSINQUE"], correct: 1 },
    { q: "QUAL A CAPITAL DO PAÍS GEÓRGIA", options: ["BATUMI", "TBILISI", "EREVAN", "BAKU"], correct: 1 },
    { q: "QUAL A CAPITAL DA ARMÊNIA", options: ["TBILISI", "EREVAN", "BAKU", "ASTANA"], correct: 1 },
    { q: "QUAL O PAÍS COM O MAIOR NÚMERO DE ILHAS", options: ["INDONÉSIA", "SUÉCIA", "FILIPINAS", "NORUEGA"], correct: 1 },
    { q: "QUAL O PAÍS COM A MAIOR EXTENSÃO DE LITORAL", options: ["BRASIL", "CANADÁ", "AUSTRÁLIA", "RÚSSIA"], correct: 1 },
    { q: "QUAL O ÚNICO PAÍS QUE FAZ FRONTEIRA COM PORTUGAL", options: ["FRANÇA", "ESPANHA", "MARROCOS", "INGLATERRA"], correct: 1 },
    { q: "QUAL O NOME DO RIO QUE DIVIDE O BRASIL DA ARGENTINA", options: ["RIO PARANÁ", "RIO IGUAÇU", "RIO URUGUAI", "RIO SÃO FRANCISCO"], correct: 1 },
    { q: "QUAL O NOME DO PONTO MAIS ALTO DA ÁFRICA", options: ["MONTE QUÊNIA", "MONTE KILIMANJARO", "MONTE SINAI", "ATLAS"], correct: 1 },
    { q: "QUAL O NOME DO MAR QUE SEPARA A EUROPA DA ÁFRICA", options: ["MAR VERMELHO", "MAR MEDITERRÂNEO", "MAR NEGRO", "MAR MORTO"], correct: 1 },
    { q: "QUAL O NOME DA PASSAGEM NATURAL ENTRE ATLÂNTICO E PACÍFICO", options: ["CANAL DE SUEZ", "ESTREITO DE MAGALHÃES", "GIBRALTAR", "BERING"], correct: 1 },
    { q: "QUAL A CAPITAL DO SURINAME", options: ["CAIENA", "PARAMARIBO", "GEORGETOWN", "QUITO"], correct: 1 },
    { q: "QUAL A CAPITAL DA GUIANA", options: ["PARAMARIBO", "GEORGETOWN", "CAIENA", "BOGOTÁ"], correct: 1 },
    { q: "QUAL A CAPITAL DA GUIANA FRANCESA", options: ["GEORGETOWN", "CAIENA", "PARAMARIBO", "PARIS"], correct: 1 },
    { q: "QUAL O PAÍS MAIS POPULOSO DA AMÉRICA DO NORTE", options: ["CANADÁ", "ESTADOS UNIDOS", "MÉXICO", "CUBA"], correct: 1 },
    { q: "QUAL O NOME DO DESERTO QUE FICA NO SUL DA ÁFRICA", options: ["SAARA", "CALAHARI", "GOBI", "ATACAMA"], correct: 1 },
    { q: "QUAL O NOME DO RIO QUE PASSA POR VIENA E BUDAPESTE", options: ["RENO", "DANÚBIO", "VOLGA", "TIBRE"], correct: 1 },
    { q: "QUAL A CAPITAL DA FILIPINAS", options: ["HANOI", "MANILA", "BANGKOK", "SEUL"], correct: 1 },
    { q: "QUAL A CAPITAL DA INDONÉSIA", options: ["JACARTA", "NUSANTARA", "BALI", "SURABAYA"], correct: 1 },
    { q: "QUAL O NOME DA MAIOR PENÍNSULA DO MUNDO", options: ["IBÉRICA", "ARÁBICA", "ESCANDINAVA", "ITÁLICA"], correct: 1 },
    { q: "QUAL O NOME DO MAR QUE BANHA A TAILÂNDIA", options: ["MAR VERMELHO", "MAR DE ANDAMÃO", "MAR NEGRO", "MAR CASPIO"], correct: 1 },
    { q: "QUAL O NOME DO RIO MAIS LONGO DOS ESTADOS UNIDOS", options: ["AMAZONAS", "MISSISSIPPI-MISSOURI", "COLORADO", "RIO GRANDE"], correct: 1 },
    { q: "QUAL O NOME DO PONTO MAIS ALTO DA ANTÁRTIDA", options: ["MONTE EVEREST", "MONTE VINSON", "PICO DA NEBLINA", "ELBRUS"], correct: 1 },
];