const historiaData = [
    { q: "ONDE FICAM AS PIRÂMIDES", options: ["MÉXICO", "EGITO", "CHINA", "GRÉCIA"], correct: 1 },
    { q: "QUEM FOI O PRIMEIRO IMPERADOR ROMANO", options: ["CÉSAR", "AUGUSTO", "NERO", "CALÍGULA"], correct: 1 },
    { q: "CIVILIZAÇÃO DOS HIERÓGLIFOS", options: ["MAIA", "EGÍPCIA", "ROMANA", "GREGA"], correct: 1 },
    { q: "QUAL CIDADE TINHA UM CAVALO DE MADEIRA", options: ["ROMA", "TROIA", "ATENAS", "ESPARTA"], correct: 1 },
    { q: "ESTRUTURA ONDE OCORRIAM LUTAS EM ROMA", options: ["PARTENON", "COLISEU", "FÓRUM", "CIRCO"], correct: 1 },
    { q: "QUAL O NOME DO RIO DO EGITO", options: ["AMAZONAS", "NILO", "TIBRE", "EUFRATES"], correct: 1 },
    { q: "POVO QUE CRIOU A DEMOCRACIA", options: ["ROMANOS", "GREGOS", "PERSAS", "FENÍCIOS"], correct: 1 },
    { q: "CIVILIZAÇÃO QUE VIVIA NOS ANDES", options: ["MAIA", "INCA", "ASTECA", "OLMECA"], correct: 1 },
    { q: "QUEM FOI O DEUS DO SOL NO EGITO", options: ["ANÚBIS", "RÁ", "OSÍRIS", "HÓRUS"], correct: 1 },
    { q: "QUAL ERA A CAPITAL DO IMPÉRIO ROMANO", options: ["ATENAS", "ROMA", "CARTAGO", "PARIS"], correct: 1 },
    { q: "QUAL POVO INVENTOU A ESCRITA CUNEIFORME", options: ["EGÍPCIOS", "SUMÉRIOS", "CHINESES", "GREGOS"], correct: 1 },
    { q: "ONDE FICAVA O FAROL DE ALEXANDRIA", options: ["GRÉCIA", "EGITO", "ITÁLIA", "TURQUIA"], correct: 1 },
    { q: "QUEM ERA O LÍDER NO EGITO", options: ["REI", "FARAÓ", "PRESIDENTE", "CÉSAR"], correct: 1 },
    { q: "QUAL POVO CONSTRUIU A GRANDE MURALHA", options: ["JAPONESES", "CHINESES", "MONGÓIS", "INDIANOS"], correct: 1 },
    { q: "GUERREIROS FAMOSOS DE ESPARTA", options: ["GLADIADORES", "HOPLITAS", "SAMURAIS", "VIKINGS"], correct: 1 },
    { q: "CIDADE-ESTADO CONHECIDA PELA FILOSOFIA", options: ["ESPARTA", "ATENAS", "TROIA", "TEBAS"], correct: 1 },
    { q: "QUAL ERA O DEUS SUPREMO NA GRÉCIA", options: ["HADES", "ZEUS", "APOLO", "ARES"], correct: 1 },
    { q: "CIVILIZAÇÃO QUE CRIOU O ALFABETO", options: ["FENÍCIOS", "ROMANOS", "SUMÉRIOS", "PERSAS"], correct: 0 },
    { q: "POVO QUE USAVA MÚMIAS", options: ["INCAS", "EGÍPCIOS", "CHINESES", "ROMANOS"], correct: 1 },
    { q: "O QUE SIGNIFICA MESOPOTÂMIA", options: ["TERRA DO SOL", "TERRA ENTRE RIOS", "GRANDE MAR", "MONTANHA"], correct: 1 },
    { q: "QUEM DESCOBRIU O BRASIL", options: ["COLOMBO", "CABRAL", "VESPÚCIO", "MAGALHÃES"], correct: 1 },
    { q: "EM QUE ANO O BRASIL FOI DESCOBERTO", options: ["1492", "1500", "1822", "1889"], correct: 1 },
    { q: "QUAL ERA A PRIMEIRA CAPITAL DO BRASIL", options: ["RIO DE JANEIRO", "SALVADOR", "BRASÍLIA", "SÃO PAULO"], correct: 1 },
    { q: "QUEM GRITOU 'INDEPENDÊNCIA OU MORTE'", options: ["D. PEDRO I", "D. PEDRO II", "TIRADENTES", "DEODORO"], correct: 0 },
    { q: "QUAL FOI O ÚLTIMO IMPERADOR DO BRASIL", options: ["D. PEDRO I", "D. PEDRO II", "D. JOÃO VI", "D. MANUEL"], correct: 1 },
    { q: "QUEM ASSINOU A LEI ÁUREA", options: ["D. PEDRO II", "PRINCESA ISABEL", "ZUMBI", "TIRADENTES"], correct: 1 },
    { q: "QUAL O NOME DA PRIMEIRA RIQUEZA DO BRASIL", options: ["OURO", "PAU-BRASIL", "CAFÉ", "AÇÚCAR"], correct: 1 },
    { q: "QUEM FOI O MÁRTIR DA INCONFIDÊNCIA", options: ["ZUMBI", "TIRADENTES", "BENTO GONÇALVES", "DUQUE DE CAXIAS"], correct: 1 },
    { q: "EM QUE ANO OCORREU A INDEPENDÊNCIA", options: ["1500", "1822", "1889", "1964"], correct: 1 },
    { q: "QUAL ERA A COR DA BANDEIRA IMPERIAL", options: ["AZUL", "VERDE E AMARELA", "VERMELHA", "BRANCA"], correct: 1 },
    { q: "QUEM FOI O LÍDER DO QUILOMBO DOS PALMARES", options: ["ZUMBI", "TIRADENTES", "PEDRO I", "ISABEL"], correct: 0 },
    { q: "QUAL PAÍS COLONIZOU O BRASIL", options: ["ESPANHA", "PORTUGAL", "FRANÇA", "INGLATERRA"], correct: 1 },
    { q: "COMO CHAMAVAM OS FILHOS DE PORTUGUESES NO BRASIL", options: ["MESTIÇOS", "CRIOULOS", "CAIÇARAS", "ÍNDIOS"], correct: 1 },
    { q: "QUAL FOI A SEGUNDA CAPITAL DO BRASIL", options: ["SALVADOR", "RIO DE JANEIRO", "BRASÍLIA", "CURITIBA"], correct: 1 },
    { q: "EM QUE DIA É CELEBRADA A INDEPENDÊNCIA", options: ["21 DE ABRIL", "7 DE SETEMBRO", "15 DE NOVEMBRO", "1 DE MAIO"], correct: 1 },
    { q: "O QUE ERA A SENZALA", options: ["CASA DO SENHOR", "ALOJAMENTO DE ESCRAVOS", "IGREJA", "ESCOLA"], correct: 1 },
    { q: "QUEM ERAM OS BANDEIRANTES", options: ["PADRES", "EXPLORADORES DE TERRITÓRIO", "REIS", "PIRATAS"], correct: 1 },
    { q: "QUAL O NOME DO TRATADO QUE DIVIDIU O MUNDO", options: ["VERSALHES", "TORDESILHAS", "MADRI", "ROMA"], correct: 1 },
    { q: "QUAL RELIGIÃO ERA OFICIAL NO IMPÉRIO", options: ["PROTESTANTE", "CATÓLICA", "ESPÍRITA", "JUDAICA"], correct: 1 },
    { q: "QUEM PROCLAMOU A REPÚBLICA", options: ["DOM PEDRO II", "DEODORO DA FONSECA", "VARGAS", "JK"], correct: 1 },
    { q: "QUEM CHEGOU À AMÉRICA EM 1492", options: ["CABRAL", "COLOMBO", "VASCO DA GAMA", "MAGALHÃES"], correct: 1 },
    { q: "QUAL ERA O SISTEMA ECONÔMICO DA IDADE MÉDIA", options: ["CAPITALISMO", "FEUDALISMO", "SOCIALISMO", "ESCRAVISMO"], correct: 1 },
    { q: "QUAL A DOENÇA QUE MATOU UM TERÇO DA EUROPA", options: ["GRIPE", "PESTE NEGRA", "CÓLERA", "VARÍOLA"], correct: 1 },
    { q: "QUEM ERAM OS GUERREIROS DO NORTE", options: ["ROMANOS", "VIKINGS", "SAMURAIS", "ESPARTANOS"], correct: 1 },
    { q: "COMO SE CHAMAVA A TERRA DO SENHOR FEUDAL", options: ["FAZENDA", "FEUDO", "SÍTIO", "QUINTA"], correct: 1 },
    { q: "QUAL ERA A INSTITUIÇÃO MAIS PODEROSA NA IDADE MÉDIA", options: ["EXÉRCITO", "IGREJA CATÓLICA", "UNIVERSIDADE", "BANCO"], correct: 1 },
    { q: "QUEM ERAM OS CAVALEIROS", options: ["CAMPONESES", "GUERREIROS NOBRES", "PADRES", "REIS"], correct: 1 },
    { q: "QUAL ERA O OBJETIVO DAS CRUZADAS", options: ["COMÉRCIO", "RETOMAR TERRA SANTA", "TURISMO", "EXPLORAR OURO"], correct: 1 },
    { q: "QUEM INVENTOU A PRENSA DE TIPOS MÓVEIS", options: ["DA VINCI", "GUTENBERG", "NEWTON", "GALILEU"], correct: 1 },
    { q: "QUAL NOME SE DAVA AO PACTO ENTRE NOBRES", options: ["CONTRATO", "SUSERANIA E VASSALAGEM", "AMIZADE", "CASAMENTO"], correct: 1 },
    { q: "ONDE VIVIAM OS REIS MEDIEVAIS", options: ["APARTAMENTOS", "CASTELOS", "OCAS", "TENDAS"], correct: 1 },
    { q: "COMO ERAM CHAMADOS OS CAMPONESES PRESOS À TERRA", options: ["ESCRAVOS", "SERVOS", "SUSERANOS", "VILÕES"], correct: 1 },
    { q: "QUAL CIDADE FOI A CAPITAL DO IMPÉRIO BIZANTINO", options: ["ROMA", "CONSTANTINOPLA", "ATENAS", "PARIS"], correct: 1 },
    { q: "QUEM FOI JOANA D'ARC", options: ["RAINHA", "HEROÍNA FRANCESA", "PINTORA", "CIENTISTA"], correct: 1 },
    { q: "O QUE MARCOU O FIM DA IDADE MÉDIA", options: ["QUEDA DE ROMA", "QUEDA DE CONSTANTINOPLA", "DESCOBERTA DO BRASIL", "REVOLUÇÃO FRANCESA"], correct: 1 },
    { q: "QUAL ERA A LÍNGUA OFICIAL DA IGREJA", options: ["GREGO", "LATIM", "FRANCÊS", "INGLÊS"], correct: 1 },
    { q: "QUAL O NOME DA ARQUITETURA COM ARCOS PONTUDOS", options: ["ROMÂNICA", "GÓTICA", "BARROCA", "MODERNA"], correct: 1 },
    { q: "O QUE ERAM AS CORPORAÇÕES DE OFÍCIO", options: ["EXÉRCITOS", "ASSOCIAÇÕES DE ARTESÃOS", "ESCOLAS", "IGREJAS"], correct: 1 },
    { q: "QUEM FOI O EXPLORADOR QUE DEU A VOLTA AO MUNDO", options: ["CABRAL", "FERNÃO DE MAGALHÃES", "COLOMBO", "VASCO DA GAMA"], correct: 1 },
    { q: "QUEM PINTOU A MONA LISA", options: ["MICHELANGELO", "DA VINCI", "RAFAEL", "DONATELLO"], correct: 1 },
    { q: "QUEM PINTOU O TETO DA CAPELA SISTINA", options: ["DA VINCI", "MICHELANGELO", "PICASSO", "DALÍ"], correct: 1 },
    { q: "MOVIMENTO QUE VALORIZAVA A RAZÃO", options: ["BARROCO", "ILUMINISMO", "ROMANTISMO", "GÓTICO"], correct: 1 },
    { q: "PAÍS ONDE COMEÇOU A REVOLUÇÃO INDUSTRIAL", options: ["FRANÇA", "INGLATERRA", "EUA", "ALEMANHA"], correct: 1 },
    { q: "EM QUE PAÍS OCORREU A REVOLUÇÃO DE 1789", options: ["EUA", "FRANÇA", "RÚSSIA", "BRASIL"], correct: 1 },
    { q: "QUEM FOI O LÍDER NA REVOLUÇÃO FRANCESA", options: ["LUIZ XIV", "ROBESPIERRE", "NAPOLEÃO", "DANTON"], correct: 1 },
    { q: "QUAL ERA O LEMA DA REVOLUÇÃO FRANCESA", options: ["ORDEM E PROGRESSO", "LIBERDADE, IGUALDADE, FRATERNIDADE", "PAZ E AMOR", "DEUS E PÁTRIA"], correct: 1 },
    { q: "QUEM FOI O IMPERADOR DOS FRANCESES", options: ["LUIZ XVI", "NAPOLEÃO BONAPARTE", "CARLOS MAGNO", "DE GAULLE"], correct: 1 },
    { q: "MAQUINA QUE MARCOU A REVOLUÇÃO INDUSTRIAL", options: ["AVIÃO", "LOCOMOTIVA A VAPOR", "CARRO", "TELEFONE"], correct: 1 },
    { q: "QUEM ESCREVEU O 'MANIFESTO COMUNISTA'", options: ["ADAM SMITH", "KARL MARX", "NAPOLEÃO", "LOCKE"], correct: 1 },
    { q: "QUAL PAÍS SE TORNOU INDEPENDENTE EM 1776", options: ["BRASIL", "ESTADOS UNIDOS", "MÉXICO", "CANADÁ"], correct: 1 },
    { q: "QUEM FOI O PRIMEIRO PRESIDENTE DOS EUA", options: ["LINCOLN", "GEORGE WASHINGTON", "JEFFERSON", "KENNEDY"], correct: 1 },
    { q: "QUEM DESCOBRIU A LEI DA GRAVIDADE", options: ["EINSTEIN", "ISAAC NEWTON", "GALILEU", "DARWIN"], correct: 1 },
    { q: "QUEM DEFENDEU QUE A TERRA GIRA PRO SOL", options: ["PANTALEÃO", "COPÉRNICO", "ARISTÓTELES", "IGREJA"], correct: 1 },
    { q: "INSTRUMENTO DE EXECUÇÃO NA FRANÇA", options: ["FORCA", "GUILHOTINA", "CADEIRA ELÉTRICA", "FOGO"], correct: 1 },
    { q: "O QUE ERA A BASTILHA", options: ["UM PALÁCIO", "UMA PRISÃO", "UMA IGREJA", "UM RIO"], correct: 1 },
    { q: "QUEM INVENTOU A LÂMPADA ELÉTRICA", options: ["TESLA", "THOMAS EDISON", "BELL", "MARCONI"], correct: 1 },
    { q: "QUEM CRIOU A TEORIA DA RELATIVIDADE", options: ["NEWTON", "ALBERT EINSTEIN", "HAWKING", "CURIE"], correct: 1 },
    { q: "QUAL ERA A CAPITAL DO IMPÉRIO NAPOLEÔNICO", options: ["LONDRES", "PARIS", "ROMA", "BERLIM"], correct: 1 },
    { q: "O QUE SIGNIFICA RENASCIMENTO", options: ["MORTE", "REASCER DA CULTURA CLÁSSICA", "GUERRA", "FIM DO MUNDO"], correct: 1 },
    { q: "QUANDO COMEÇOU A 1ª GUERRA MUNDIAL", options: ["1910", "1914", "1939", "1945"], correct: 1 },
    { q: "QUANDO TERMINOU A 2ª GUERRA MUNDIAL", options: ["1918", "1939", "1945", "1950"], correct: 2 },
    { q: "QUEM FOI O LÍDER DA ALEMANHA NA 2ª GUERRA", options: ["MUSSOLINI", "STALIN", "HITLER", "CHURCHILL"], correct: 2 },
    { q: "QUAL PAÍS SOFREU AS BOMBAS ATÔMICAS", options: ["ALEMANHA", "ITÁLIA", "JAPÃO", "RÚSSIA"], correct: 2 },
    { q: "CONFLITO IDEOLÓGICO ENTRE EUA E URSS", options: ["GUERRA CIVIL", "GUERRA FRIA", "GUERRA DO VIETNÃ", "GUERRA DO GOLFO"], correct: 1 },
    { q: "QUEM FOI O LÍDER DA REVOLUÇÃO RUSSA", options: ["STALIN", "LENIN", "TROTSKY", "CZAR"], correct: 1 },
    { q: "O QUE DIVIDIA A ALEMANHA NA GUERRA FRIA", options: ["UM RIO", "O MURO DE BERLIM", "UMA MONTANHA", "UMA ESTRADA"], correct: 1 },
    { q: "QUEM FOI O LÍDER DA INDEPENDÊNCIA DA ÍNDIA", options: ["MANDELA", "GANDHI", "NEHRU", "MAO"], correct: 1 },
    { q: "QUAL O NOME DO NAVIO QUE AFUNDOU EM 1912", options: ["TITANIC", "LUSITANIA", "OLYMPIC", "BRITANNIC"], correct: 0 },
    { q: "QUEM FOI O PRIMEIRO HOMEM NO ESPAÇO", options: ["ARMSTRONG", "YURI GAGARIN", "ALDRIN", "COLINS"], correct: 1 },
    { q: "QUAL O NOME DO REGIME DE SEGREGAÇÃO NA ÁFRICA", options: ["NAZISMO", "APARTHEID", "FASCISMO", "COMUNISMO"], correct: 1 },
    { q: "QUEM LUTOU PELOS DIREITOS NEGROS NOS EUA", options: ["MALCOLM X", "MARTIN LUTHER KING", "OBAMA", "LINCOLN"], correct: 1 },
    { q: "QUEM FOI O LÍDER DA REVOLUÇÃO CUBANA", options: ["BATISTA", "FIDEL CASTRO", "GUEVARA", "CHAVEZ"], correct: 1 },
    { q: "QUAL O NOME DA ALIANÇA DOS EUA NA GUERRA FRIA", options: ["OTAN", "PACTO DE VARSÓVIA", "ONU", "MERCOSUL"], correct: 0 },
    { q: "EM QUE ANO O MURO DE BERLIM CAIU", options: ["1945", "1989", "1991", "2000"], correct: 1 },
    { q: "QUEM FOI O DITADOR DA ITÁLIA FASCISTA", options: ["HITLER", "MUSSOLINI", "FRANCO", "SALAZAR"], correct: 1 },
    { q: "QUAL PAÍS LANÇOU O SATÉLITE SPUTNIK", options: ["EUA", "UNIÃO SOVIÉTICA", "CHINA", "BRASIL"], correct: 1 },
    { q: "QUEM FOI O PRESIDENTE DO BRASIL NO GOLPE DE 64", options: ["JK", "JOÃO GOULART", "JÂNIO QUADROS", "VARGAS"], correct: 1 },
    { q: "QUAL O NOME DA ORGANIZAÇÃO CRIADA APÓS A 2ª GUERRA", options: ["LIGA DAS NAÇÕES", "ONU", "OTAN", "UNIÃO EUROPEIA"], correct: 1 },
    { q: "QUEM FOI O LÍDER SUL-AFRICANO PRESO POR 27 ANOS", options: ["MANDELA", "GANDHI", "LUTHER KING", "ZUMBI"], correct: 0 },
    { q: "QUEM FOI O DEUS GREGO DO MAR", options: ["ZEUS", "POSEIDON", "HADES", "HERMES"], correct: 1 },
    { q: "POVO QUE CONSTRUIU MACHU PICCHU", options: ["ASTECAS", "INCAS", "MAIAS", "OLMECAS"], correct: 1 },
    { q: "QUAL ERA O NOME DA ESCRITA DO EGITO", options: ["LATIM", "HIERÓGLIFOS", "CUNEIFORME", "ALFABETO"], correct: 1 },
    { q: "QUEM FOI O FILÓSOFO MESTRE DE PLATÃO", options: ["ARISTÓTELES", "SÓCRATES", "DESCARTES", "KANT"], correct: 1 },
    { q: "CIDADE FAMOSA PELO FAROL E BIBLIOTECA", options: ["ROMA", "ALEXANDRIA", "ATENAS", "ESPARTA"], correct: 1 },
    { q: "QUEM FOI O DEUS ROMANO DOS DEUSES", options: ["MARTE", "JÚPITER", "NETUNO", "APOLO"], correct: 1 },
    { q: "QUAL ERA A CAPITAL DO IMPÉRIO ASTECA", options: ["CUZCO", "TENOCHTITLÁN", "PALENQUE", "LIMA"], correct: 1 },
    { q: "QUEM FOI O LÍDER MONGOL QUE CRIOU UM IMPÉRIO", options: ["ATILA", "GENGHIS KHAN", "AKBAR", "SALADINO"], correct: 1 },
    { q: "QUAL ERA A LÍNGUA FALADA EM ROMA", options: ["ITALIANO", "LATIM", "GREGO", "FRANCÊS"], correct: 1 },
    { q: "QUEM FUNDOU O ISLAMISMO", options: ["MOISÉS", "MAOMÉ", "ABRAÃO", "BUDA"], correct: 1 },
    { q: "QUAL LIVRO É SAGRADO PARA OS JUDEUS", options: ["BÍBLIA", "TORÁ", "ALCORÃO", "VEDAS"], correct: 1 },
    { q: "QUAL ERA O DEUS DA GUERRA EM ROMA", options: ["JÚPITER", "MARTE", "VULCANO", "PLUTÃO"], correct: 1 },
    { q: "CIVILIZAÇÃO QUE INVENTOU O PAPEL", options: ["EGÍPCIA", "CHINESA", "GREGA", "ROMANA"], correct: 1 },
    { q: "QUEM FOI O GRANDE RECORDEIRO DE CONQUISTAS", options: ["CÉSAR", "ALEXANDRE O GRANDE", "NAPOLEÃO", "HITLER"], correct: 1 },
    { q: "QUAL ERA O RIO DA MESOPOTÂMIA (UM DELES)", options: ["NILO", "TIGRE", "GANGES", "RENO"], correct: 1 },
    { q: "ONDE SURGIU O BUDISMO", options: ["CHINA", "ÍNDIA", "JAPÃO", "EGITO"], correct: 1 },
    { q: "QUAL CIDADE FOI DESTRUÍDA PELO VESÚVIO", options: ["ROMA", "POMPEIA", "MILÃO", "VENEZA"], correct: 1 },
    { q: "QUEM ERAM OS PATRÍCIOS EM ROMA", options: ["ESCRAVOS", "NOBRES/ELITE", "CAMPONESES", "SOLDADOS"], correct: 1 },
    { q: "QUAL O NOME DA ROTA COMERCIAL ÁSIA-EUROPA", options: ["ROTA DO OURO", "ROTA DA SEDA", "ROTA DO SAL", "ROTA DAS ESPECIARIAS"], correct: 1 },
    { q: "QUEM FOI O ÚLTIMO FARAÓ DO EGITO", options: ["NEFERTITI", "CLEÓPATRA", "TUTANKAMON", "RAMSÉS"], correct: 1 },
    { q: "QUAL O NOME DO PRIMEIRO GOVERNADOR GERAL", options: ["MEM DE SÁ", "TOMÉ DE SOUZA", "DUARTE DA COSTA", "CABRAL"], correct: 1 },
    { q: "QUEM ERAM OS JESUÍTAS", options: ["SOLDADOS", "PADRES CATEQUIZADORES", "PIRATAS", "REIS"], correct: 1 },
    { q: "QUAL CIDADE FOI INVADIDA PELOS HOLANDESES", options: ["SÃO PAULO", "RECIFE", "MANAUS", "BRASÍLIA"], correct: 1 },
    { q: "QUEM LIDEROU A INSURREIÇÃO PERNAMBUCANA", options: ["PEDRO I", "JOÃO FERNANDES VIEIRA", "ZUMBI", "TIRADENTES"], correct: 1 },
    { q: "QUAL O NOME DO TRABALHO FORÇADO INDÍGENA", options: ["FEUDALISMO", "MITA/ENCOMIENDA", "SESMARIA", "SALÁRIO"], correct: 1 },
    { q: "QUEM FOI A ESPOSA DE D. PEDRO I", options: ["CARLOTA JOAQUINA", "MARIA LEOPOLDINA", "PRINCESA ISABEL", "ANITA GARIBALDI"], correct: 1 },
    { q: "QUAL ERA O PRINCIPAL PRODUTO DO CICLO DO OURO", options: ["CAFÉ", "OURO", "AÇÚCAR", "ALGODÃO"], correct: 1 },
    { q: "EM QUE ESTADO OCORREU A INCONFIDÊNCIA", options: ["BAHIA", "MINAS GERAIS", "RIO DE JANEIRO", "SÃO PAULO"], correct: 1 },
    { q: "QUEM FOI O 'PATRIARCA DA INDEPENDÊNCIA'", options: ["DOM PEDRO I", "JOSÉ BONIFÁCIO", "TIRADENTES", "MAUÁ"], correct: 1 },
    { q: "O QUE FOI O 'DIA DO FICO'", options: ["SAÍDA DE PEDRO", "PERMANÊNCIA DE PEDRO", "FIM DA ESCRAVIDÃO", "GUERRA"], correct: 1 },
    { q: "QUAL ERA O NOME DA POLÍCIA DO IMPÉRIO", options: ["GUARDA MUNICIPAL", "GUARDA NACIONAL", "FBI", "EXÉRCITO"], correct: 1 },
    { q: "QUAL O NOME DA GUERRA CONTRA O PARAGUAI", options: ["GUERRA DOS FARRAPOS", "GUERRA DO PARAGUAI", "CISPLATINA", "CANUDOS"], correct: 1 },
    { q: "QUEM LIDEROU A GUERRA DE CANUDOS", options: ["ZUMBI", "ANTÔNIO CONSELHEIRO", "PEDRO II", "VARGAS"], correct: 1 },
    { q: "QUAL O NOME DA REVOLTA NO RIO GRANDE DO SUL", options: ["SABINADA", "FARROUPILHA", "BALAIADA", "CABANAGEM"], correct: 1 },
    { q: "EM QUE ANO A FAMÍLIA REAL CHEGOU AO BRASIL", options: ["1500", "1808", "1822", "1889"], correct: 1 },
    { q: "QUEM ERA O REI DE PORTUGAL EM 1808", options: ["D. PEDRO I", "D. JOÃO VI", "D. MANUEL", "D. DINIS"], correct: 1 },
    { q: "QUAL O NOME DO PORTO ONDE A COROA CHEGOU", options: ["SANTOS", "SALVADOR", "RIO DE JANEIRO", "RECIFE"], correct: 1 },
    { q: "QUAL FOI O ÚLTIMO PAÍS A ABOLIR A ESCRAVIDÃO", options: ["EUA", "BRASIL", "INGLATERRA", "FRANÇA"], correct: 1 },
    { q: "QUEM FOI O DUQUE DE CAXIAS", options: ["POETA", "MILITAR/PATRONO DO EXÉRCITO", "REI", "PADRE"], correct: 1 },
    { q: "O QUE FOI A 'NOITE DAS GARRAFADAS'", options: ["FESTA", "CONFLITO POLÍTICO EM 1831", "GUERRA NO MAR", "DESCOBERTA"], correct: 1 },
    { q: "QUAL O NOME DO NAVIO DO DESCOBRIMENTO DOS EUA", options: ["TITANIC", "MAYFLOWER", "SANTA MARIA", "VICTORY"], correct: 1 },
    { q: "QUEM FOI O LÍDER DA REVOLUÇÃO MEXICANA", options: ["FIDEL", "EMILIANO ZAPATA", "BOLÍVAR", "SAN MARTIN"], correct: 1 },
    { q: "QUAL PAÍS FOI DIVIDIDO PELO PARALELO 38", options: ["ALEMANHA", "COREIA", "VIETNÃ", "BRASIL"], correct: 1 },
    { q: "QUAL ERA O NOME DO ESTADO NAZISTA", options: ["IMPÉRIO", "TERCEIRO REICH", "REPÚBLICA", "COMUNA"], correct: 1 },
    { q: "QUEM FOI O LÍDER DA RÚSSIA NA 2ª GUERRA", options: ["LENIN", "STALIN", "PUTIN", "CZAR"], correct: 1 },
    { q: "QUAL O NOME DO PACTO NAZISTA-SOVIÉTICO", options: ["VERSALHES", "MOLOTOV-RIBBENTROP", "VARSOVIA", "OTAN"], correct: 1 },
    { q: "QUEM FOI O 'REI SOL'", options: ["NAPOLEÃO", "LUIZ XIV", "HENRIQUE VIII", "PEDRO I"], correct: 1 },
    { q: "QUAL O NOME DA PRIMEIRA BOMBA ATÔMICA", options: ["FAT MAN", "LITTLE BOY", "TSAR", "BRAVO"], correct: 1 },
    { q: "ONDE OCORREU O DIA D", options: ["ITÁLIA", "NORMANDIA", "BERLIM", "TÓQUIO"], correct: 1 },
    { q: "QUEM FOI O FUNDADOR DA TURQUIA MODERNA", options: ["SULTÃO", "ATATÜRK", "ERDOGAN", "SALADINO"], correct: 1 },
    { q: "QUAL O NOME DO MURO QUE CAIU EM 1989", options: ["MURALHA DA CHINA", "MURO DE BERLIM", "MURO DE ISRAEL", "MURO DO MÉXICO"], correct: 1 },
    { q: "QUEM FOI O PRESIDENTE DOS EUA NA 2ª GUERRA", options: ["TRUMAN", "ROOSEVELT", "LINCOLN", "KENNEDY"], correct: 1 },
    { q: "QUAL PAÍS INVADIU A POLÔNIA EM 1939", options: ["FRANÇA", "ALEMANHA", "RÚSSIA", "INGLATERRA"], correct: 1 },
    { q: "QUEM FOI O PRIMEIRO-MINISTRO INGLÊS NA GUERRA", options: ["THATCHER", "CHURCHILL", "BLAIR", "JOHNSON"], correct: 1 },
    { q: "QUAL O NOME DA POLÍCIA SECRETA NAZISTA", options: ["KGB", "GESTAPO", "CIA", "FBI"], correct: 1 },
    { q: "QUAL ERA O NOME DA ALIANÇA CONTRA O NAZISMO", options: ["EIXO", "ALIADOS", "TRÍPLICE ENTENTE", "OTAN"], correct: 1 },
    { q: "QUEM FOI O LÍDER CHINÊS DA REVOLUÇÃO DE 1949", options: ["CHIANG KAI-SHEK", "MAO ZEDONG", "DENG XIAOPING", "XI JINPING"], correct: 1 },
    { q: "QUAL CIDADE FOI O ALVO DA 2ª BOMBA ATÔMICA", options: ["HIROSHIMA", "NAGASAKI", "TÓQUIO", "OSAKA"], correct: 1 },
    { q: "QUEM FOI O FILÓSOFO DO 'PENSO, LOGO EXISTO'", options: ["PLATÃO", "DESCARTES", "SARTRE", "NIETZSCHE"], correct: 1 },
    { q: "QUAL O NOME DA GUERRA ENTRE IRÃ E IRAQUE", options: ["GUERRA DO GOLFO", "GUERRA IRÃ-IRAQUE", "GUERRA DOS SEIS DIAS", "GUERRA FRIA"], correct: 1 },
    { q: "QUEM ESCREVEU O LIVRO 'O PRÍNCIPE'", options: ["MAQUIAVEL", "ERASMO", "MORUS", "DANTE"], correct: 0 },
    { q: "QUAL O NOME DA REFORMA DE MARTINHO LUTERO", options: ["CATÓLICA", "PROTESTANTE", "ANGLICANA", "CALVINISTA"], correct: 1 },
    { q: "QUEM FUNDOU A IGREJA ANGLICANA", options: ["LUIZ XIV", "HENRIQUE VIII", "CARLOS I", "ELIZABETH I"], correct: 1 },
    { q: "O QUE FOI A CONTRARREFORMA", options: ["FIM DA IGREJA", "REAÇÃO DA IGREJA CATÓLICA", "NOVA RELIGIÃO", "GUERRA"], correct: 1 },
    { q: "QUAL ERA O NOME DO NAVIO DE DARWIN", options: ["TITANIC", "BEAGLE", "VICTORY", "SANTA MARIA"], correct: 1 },
    { q: "QUEM FOI O LÍDER DA INDEPENDÊNCIA AMERICANA", options: ["LINCOLN", "GEORGE WASHINGTON", "FRANKLIN", "JEFFERSON"], correct: 1 },
    { q: "QUAL O NOME DO REGIME DE LUIZ XIV", options: ["DEMOCRACIA", "ABSOLUTISMO", "REPÚBLICA", "FEUDALISMO"], correct: 1 },
    { q: "O QUE FOI O ILUMINISMO", options: ["ERA DAS TREVAS", "SÉCULO DAS LUZES", "GUERRA RELIGIOSA", "FESTA"], correct: 1 },
    { q: "QUEM ESCREVEU 'O CONTRATO SOCIAL'", options: ["VOLTAIRE", "ROUSSEAU", "MONTESQUIEU", "LOCKE"], correct: 1 },
    { q: "QUEM DIVIDIU OS PODERES EM TRÊS", options: ["ROUSSEAU", "MONTESQUIEU", "VOLTAIRE", "DIDEROT"], correct: 1 },
    { q: "QUAL ERA A CAPITAL DA RÚSSIA DOS CZARES", options: ["MOSCOU", "SÃO PETERSBURGO", "KIEV", "VOLGOGRADO"], correct: 1 },
    { q: "QUEM FOI O 'LIBERTADOR' DA AMÉRICA DO SUL", options: ["CABRAL", "SIMÓN BOLÍVAR", "COLOMBO", "CORTEZ"], correct: 1 },
    { q: "QUAL O NOME DA REVOLUÇÃO INGLESA DE 1688", options: ["INDUSTRIAL", "GLORIOSA", "FRANCESA", "AMERICANA"], correct: 1 },
    { q: "QUEM INVENTOU A MÁQUINA A VAPOR (APERFEIÇOOU)", options: ["NEWTON", "JAMES WATT", "EDISON", "TESLA"], correct: 1 },
    { q: "O QUE ERAM OS LUDISTAS", options: ["POLÍTICOS", "QUEBRADORES DE MÁQUINAS", "REIS", "PADRES"], correct: 1 },
    { q: "QUAL O NOME DA PRIMEIRA CONSTITUIÇÃO DO BRASIL", options: ["1824", "1891", "1934", "1988"], correct: 0 },
    { q: "QUEM FOI O LÍDER DA REVOLUÇÃO HAITIANA", options: ["BOLÍVAR", "TOUSSAINT LOUVERTURE", "ZAPATA", "CASTRO"], correct: 1 },
    { q: "O QUE FOI O CONGRESSO DE VIENA", options: ["FESTA", "REORGANIZAÇÃO DA EUROPA PÓS-NAPOLEÃO", "FIM DA GUERRA", "TRATADO"], correct: 1 },
    { q: "QUEM FOI O PAI DO LIBERALISMO ECONÔMICO", options: ["MARX", "ADAM SMITH", "KEYNES", "DESCARTES"], correct: 1 },
    { q: "QUAL O NOME DA REVOLTA DOS ESCRAVOS NA BAHIA", options: ["MALÊS", "CANUDOS", "SABINADA", "BALAIADA"], correct: 0 },
    { q: "EM QUE ANO FOI PROCLAMADA A REPÚBLICA", options: ["1822", "1889", "1930", "1945"], correct: 1 },
    { q: "QUEM FOI O PRIMEIRO PRESIDENTE CIVIL", options: ["DEODORO", "PRUDENTE DE MORAES", "FLORIANO", "VARGAS"], correct: 1 },
    { q: "QUAL ERA A POLÍTICA DO 'CAFÉ COM LEITE'", options: ["BEBIDA", "ALTERNÂNCIA SP E MG NO PODER", "GUERRA", "PLANTAÇÃO"], correct: 1 },
    { q: "QUEM FOI O 'PAI DOS POBRES'", options: ["JK", "GETÚLIO VARGAS", "LULA", "SARNEY"], correct: 1 },
    { q: "QUAL O NOME DO GOLPE DE VARGAS EM 1937", options: ["ESTADO NOVO", "REPÚBLICA VELHA", "DITADURA", "DIRETAS JÁ"], correct: 0 },
    { q: "QUAL CIDADE JK CONSTRUIU", options: ["RIO", "BRASÍLIA", "GOIÂNIA", "PALMAS"], correct: 1 },
    { q: "QUEM FOI O PRESIDENTE QUE RENUNCIOU EM 7 MESES", options: ["JÂNIO QUADROS", "COLLOR", "VARGAS", "SARNEY"], correct: 0 },
    { q: "O QUE FOI O AI-5", options: ["UM AVIÃO", "DECRETO DE REPRESSÃO DA DITADURA", "UM CARRO", "UM PLANO"], correct: 1 },
    { q: "QUEM FOI O PRIMEIRO PRESIDENTE APÓS A DITADURA", options: ["TANCREDO NEVES", "SARNEY", "COLLOR", "FHC"], correct: 0 },
    { q: "QUAL O NOME DO PLANO QUE ACABOU COM A INFLAÇÃO", options: ["CRUZADO", "REAL", "COLLOR", "VERÃO"], correct: 1 },
    { q: "QUEM SOFREU O PRIMEIRO IMPEACHMENT NO BRASIL", options: ["DILMA", "FERNANDO COLLOR", "VARGAS", "JK"], correct: 1 },
    { q: "QUAL O NOME DO MOVIMENTO PELO VOTO DIRETO", options: ["DIRETAS JÁ", "CARAS PINTADAS", "VOTA BRASIL", "REVOLUÇÃO"], correct: 0 },
    { q: "QUEM FOI O LÍDER DO CANGAÇO", options: ["PADRE CÍCERO", "LAMPIÃO", "CORISCO", "ZAPATA"], correct: 1 },
    { q: "O QUE FOI A COLUNA PRESTES", options: ["UM MONUMENTO", "MOVIMENTO MILITAR REBELDE", "UMA ESTRADA", "UMA IGREJA"], correct: 1 },
    { q: "QUEM FOI A PRIMEIRA MULHER PRESIDENTE", options: ["MARINA", "DILMA ROUSSEFF", "BENEDITA", "SIMONE"], correct: 1 },
    { q: "QUAL ERA O LEMA DE JK", options: ["ORDEM E PROGRESSO", "50 ANOS EM 5", "PAZ E AMOR", "BRASIL ACIMA"], correct: 1 },
    { q: "O QUE FOI A SEMANA DE ARTE MODERNA", options: ["EXPOSIÇÃO EM 1922", "FESTIVAL DE MÚSICA", "FESTA", "REVOLUÇÃO"], correct: 0 },
    { q: "QUEM FOI O PRESIDENTE DA REDEMOCRATIZAÇÃO", options: ["GEISEL", "FIGUEIREDO", "SARNEY", "LULA"], correct: 1 },
    { q: "EM QUE ANO FOI ASSINADA A CONSTITUIÇÃO ATUAL", options: ["1964", "1988", "2000", "1945"], correct: 1 },
    { q: "QUEM FOI O LÍDER DA REVOLTA DA VACINA", options: ["OSWALDO CRUZ", "POPULAÇÃO DO RIO", "EXÉRCITO", "VARGAS"], correct: 1 },
    { q: "QUAL ERA O DEUS DA MORTE NO EGITO", options: ["RÁ", "ANÚBIS", "THOTH", "SET"], correct: 1 },
    { q: "QUEM ESCREVEU 'A ILÍADA'", options: ["SÓCRATES", "HOMERO", "PLATÃO", "VIRGÍLIO"], correct: 1 },
    { q: "QUAL ERA A CAPITAL DO IMPÉRIO PERSA", options: ["ROMA", "PERSÉPOLIS", "BABILÔNIA", "ATENAS"], correct: 1 },
    { q: "QUAL POVO INVENTOU A BÚSSOLA", options: ["GREGOS", "CHINESES", "ÁRABES", "ROMANOS"], correct: 1 },
    { q: "ONDE SURGIRAM OS JOGOS OLÍMPICOS", options: ["ROMA", "GRÉCIA (OLÍMPIA)", "EGITO", "CHINA"], correct: 1 },
    { q: "QUEM FOI O DEUS DA BELEZA NA GRÉCIA", options: ["AFRODITE", "ATENA", "HERA", "ARTEMIS"], correct: 0 },
    { q: "QUAL ERA A CAPITAL DO IMPÉRIO BIZANTINO", options: ["ROMA", "CONSTANTINOPLA", "MILÃO", "PARIS"], correct: 1 },
    { q: "QUEM FOI O AUTOR DE 'DOM QUIXOTE'", options: ["DANTE", "CERVANTES", "SHAKESPEARE", "CAMÕES"], correct: 1 },
    { q: "QUAL ERA A LÍNGUA DOS INCAS", options: ["ESPANHOL", "QUECHUA", "TUPI", "NAHUATL"], correct: 1 },
    { q: "QUEM FOI O GRANDE FILÓSOFO CHINÊS", options: ["BUDA", "CONFÚCIO", "LAO TSÉ", "SUN TZU"], correct: 1 },
    { q: "QUAL ERA O NOME DA FORTALEZA DE ATENAS", options: ["COLISEU", "ACRÓPOLE", "FORUM", "TEATRO"], correct: 1 },
    { q: "QUEM FOI O PAI DA MEDICINA", options: ["SÓCRATES", "HIPÓCRATES", "ARISTÓTELES", "GALENO"], correct: 1 },
    { q: "QUAL ERA O NOME DA ESCRITA DOS MAIAS", options: ["ALFABETO", "GLIFOS", "CUNEIFORME", "LATIM"], correct: 1 },
    { q: "QUEM FOI O DEUS DO SOL DOS ASTECAS", options: ["INTI", "HUITZILOPOCHTLI", "RÁ", "APOLO"], correct: 1 },
    { q: "ONDE FICAVAM OS JARDINS SUSPENSOS", options: ["EGITO", "BABILÔNIA", "ROMA", "CHINA"], correct: 1 },
    { q: "QUEM FOI O AUTOR DE 'A DIVINA COMÉDIA'", options: ["PETRARCA", "DANTE ALIGHIERI", "BOCCACCIO", "DA VINCI"], correct: 1 },
    { q: "QUAL O NOME DA ARTE DE EMBALSAMAR", options: ["PINTURA", "MUMIFICAÇÃO", "ESCULTURA", "DANÇA"], correct: 1 },
    { q: "QUEM FOI O DEUS DA GUERRA NA GRÉCIA", options: ["APOLO", "ARES", "HEFESTO", "HERMES"], correct: 1 },
    { q: "QUAL CIDADE FOI A SEDE DOS PAPAS NA FRANÇA", options: ["PARIS", "AVIGNON", "LYON", "NICE"], correct: 1 },
    { q: "QUEM FOI O DEUS ROMANO DO MAR", options: ["POSEIDON", "NETUNO", "MARTE", "PLUTÃO"], correct: 1 },
    { q: "QUEM ERAM OS TROVADORES", options: ["SOLDADOS", "POETAS E MÚSICOS", "PADRES", "MÉDICOS"], correct: 1 },
    { q: "QUAL ERA O NOME DA ARMADURA DE MALHA", options: ["ESCUDO", "COTA DE MALHA", "ELMO", "GREVA"], correct: 1 },
    { q: "O QUE ERA UM TORNEIO MEDIEVAL", options: ["FEIRA", "COMPETIÇÃO DE CAVALEIROS", "MISSA", "JULGAMENTO"], correct: 1 },
    { q: "QUEM ERAM OS BARÕES", options: ["ESCRAVOS", "NOBRES DE ALTO ESCALÃO", "CAMPONESES", "PIRATAS"], correct: 1 },
    { q: "QUAL O NOME DA PESTE QUE VINHA DAS PULGAS", options: ["GRIPE", "PESTE BUBÔNICA", "CÓLERA", "RAIVA"], correct: 1 },
    { q: "O QUE ERAM AS CATEDRAIS", options: ["CASAS", "GRANDES IGREJAS", "FORTALEZAS", "MERCADOS"], correct: 1 },
    { q: "QUAL ERA A FUNÇÃO DOS MOSTEIROS", options: ["GUERRA", "ORAÇÃO E ESTUDO", "COMÉRCIO", "PRISÃO"], correct: 1 },
    { q: "QUEM FOI RICARDO CORAÇÃO DE LEÃO", options: ["PINTOR", "REI E CRUZADO", "PAPA", "CIENTISTA"], correct: 1 },
    { q: "O QUE FOI A GUERRA DOS CEM ANOS", options: ["INGLATERRA X FRANÇA", "ROMA X GRÉCIA", "EUA X RÚSSIA", "ESPANHA X PORTUGAL"], correct: 0 },
    { q: "QUAL FOI O DESTINO DE JOANA D'ARC", options: ["EXÍLIO", "QUEIMADA NA FOGUEIRA", "COROAÇÃO", "FUGA"], correct: 1 },
    { q: "O QUE ERAM OS VILÕES NA IDADE MÉDIA", options: ["BANDIDOS", "HABITANTES DA VILA (LIVRES)", "ESCRAVOS", "REIS"], correct: 1 },
    { q: "QUAL CIDADE FOI O CENTRO DO ISLAMISMO", options: ["ROMA", "MECA", "PARIS", "ATENAS"], correct: 1 },
    { q: "QUEM FOI SALADINO", options: ["REI EUROPEU", "LÍDER MUÇULMANO", "PAPA", "EXPLORADOR"], correct: 1 },
    { q: "O QUE ERA A EXCOMUNHÃO", options: ["FESTA", "EXPULSÃO DA IGREJA", "PRÊMIO", "CASAMENTO"], correct: 1 },
    { q: "QUAL O NOME DA TÉCNICA DE PINTURA EM PAREDES", options: ["ÓLEO", "AFRESCO", "AQUARELA", "GRAFITE"], correct: 1 },
    { q: "QUEM ERAM OS ESCRIBAS", options: ["SOLDADOS", "PESSOAS QUE ESCREVIAM", "MERCADORES", "REIS"], correct: 1 },
    { q: "O QUE ERAM AS TABERNAS", options: ["IGREJAS", "LOCAIS DE REFEIÇÃO E HOSPEDAGEM", "CASTELOS", "ESCOLAS"], correct: 1 },
    { q: "QUAL ERA O NOME DA MOEDA DE OURO EM FLORENÇA", options: ["REAL", "FLORIM", "DOLAR", "PESO"], correct: 1 },
    { q: "QUAL O NOME DO BARCO RÁPIDO PORTUGUÊS", options: ["TITANIC", "CARAVELA", "GALÉ", "CANOA"], correct: 1 },
    { q: "QUEM CHEGOU À ÍNDIA EM 1498", options: ["CABRAL", "VASCO DA GAMA", "COLOMBO", "CORTÉZ"], correct: 1 },
    { q: "QUAL ERA O NOME DO CABO DAS TORMENTAS", options: ["CABO DA BOA ESPERANÇA", "CABO FRIO", "CABO CANAVERAL", "CABO VERDE"], correct: 0 },
    { q: "QUEM FOI O PRIMEIRO A MAPEAR A AMÉRICA", options: ["COLOMBO", "AMÉRICO VESPÚCIO", "CABRAL", "MAGALHÃES"], correct: 1 },
    { q: "QUAL POVO CONQUISTOU OS ASTECAS", options: ["INGLESES", "ESPANHÓIS", "FRANCESES", "PORTUGUESES"], correct: 1 },
    { q: "QUEM FOI O CONQUISTADOR DO MÉXICO", options: ["PIZARRO", "HERNÁN CORTÉS", "COLOMBO", "CABRAL"], correct: 1 },
    { q: "QUEM CONQUISTOU OS INCAS", options: ["CORTÉS", "FRANCISCO PIZARRO", "VESPÚCIO", "MAGALHÃES"], correct: 1 },
    { q: "O QUE ERA O 'QUINTO'", options: ["FESTA", "IMPOSTO DE 20% DO OURO", "UM NAVIO", "UMA CIDADE"], correct: 1 },
    { q: "O QUE ERAM AS CAPITANIAS HEREDITÁRIAS", options: ["LOTES DE TERRA", "NAVIO", "EXÉRCITOS", "ESCOLAS"], correct: 0 },
    { q: "QUANTAS CAPITANIAS EXISTIAM NO BRASIL", options: ["10", "15", "5", "20"], correct: 1 },
    { q: "QUAL O NOME DA PRIMEIRA VILA DO BRASIL", options: ["SÃO PAULO", "SÃO VICENTE", "SALVADOR", "RIO"], correct: 1 },
    { q: "O QUE ERA A 'CARTA DE SESMARIA'", options: ["MAPA", "CONCESSÃO DE TERRA", "CARTA DE AMOR", "LEI DE ESCRAVOS"], correct: 1 },
    { q: "QUEM ERAM OS CORSÁRIOS", options: ["REIS", "PIRATAS COM AUTORIZAÇÃO REAL", "PADRES", "MERCADORES"], correct: 1 },
    { q: "QUAL O NOME DA COMPANHIA QUE TRAZIA ESCRAVOS", options: ["INDORAMA", "COMPANHIA DAS ÍNDIAS", "CIA DO MAR", "CIA DO CAFÉ"], correct: 1 },
    { q: "O QUE ERA O 'ENGENHO'", options: ["FÁBRICA DE TECIDO", "LOCAL DE PRODUÇÃO DE AÇÚCAR", "MINA", "ESCOLA"], correct: 1 },
    { q: "QUEM ERAM OS CRISTÃOS-NOVOS", options: ["PADRES", "JUDEUS CONVERTIDOS", "REIS", "SOLDADOS"], correct: 1 },
    { q: "QUAL ERA O NOME DA UNIÃO ENTRE ESPANHA E PORTUGAL", options: ["UNIÃO IBÉRICA", "UNIÃO EUROPEIA", "TRATADO DE ROMA", "PACOTO"], correct: 0 },
    { q: "QUEM FOI O LÍDER DOS BANDEIRANTES (CAÇADOR DE ESMERALDAS)", options: ["ANHANGUERA", "FERNÃO DIAS", "RAPOSO TAVARES", "BORBA GATO"], correct: 1 },
    { q: "QUAL O NOME DA ROTA DO OURO NO BRASIL", options: ["ESTRADA REAL", "TRANSAMAZÔNICA", "ROTA DA SEDA", "VIA APPIA"], correct: 0 },
    { q: "O QUE ERAM OS 'MASQUATES'", options: ["SOLDADOS", "COMERCIANTES", "PIRATAS", "REIS"], correct: 1 },
    { q: "QUAL O NOME DA GUERRA CIVIL DOS EUA", options: ["GUERRA FRIA", "GUERRA DE SECESSÃO", "INDEPENDÊNCIA", "VIETNÃ"], correct: 1 },
    { q: "QUEM FOI O PRESIDENTE DOS EUA NA GUERRA CIVIL", options: ["WASHINGTON", "ABRAHAM LINCOLN", "ROOSEVELT", "KENNEDY"], correct: 1 },
    { q: "QUAL O NOME DA REVOLUÇÃO NA RÚSSIA DE 1917", options: ["FRANCESA", "BOLCHEVIQUE", "INDUSTRIAL", "GLORIOSA"], correct: 1 },
    { q: "QUEM FOI O LÍDER DO NAZISMO", options: ["MUSSOLINI", "ADOLF HITLER", "STALIN", "FRANCO"], correct: 1 },
    { q: "QUAL O NOME DA TENTATIVA DE MATAR HITLER", options: ["OPERAÇÃO OVERLORD", "OPERAÇÃO VALQUÍRIA", "DIA D", "BARBAROSSA"], correct: 1 },
    { q: "O QUE FOI O HOLOCAUSTO", options: ["GUERRA NO MAR", "GENOCÍDIO DE JUDEUS", "FESTA", "TRATADO"], correct: 1 },
    { q: "QUAL O NOME DA ALIANÇA ENTRE ALEMANHA, ITÁLIA E JAPÃO", options: ["ALIADOS", "EIXO", "OTAN", "MERCOSUL"], correct: 1 },
    { q: "QUAL CIDADE FOI CERCADA POR 900 DIAS NA 2ª GUERRA", options: ["MOSCOU", "LENINGRADO", "BERLIM", "PARIS"], correct: 1 },
    { q: "QUAL O NOME DA INVASÃO DA RÚSSIA PELA ALEMANHA", options: ["OPERAÇÃO VALQUÍRIA", "OPERAÇÃO BARBAROSSA", "DIA D", "ZEPPELIN"], correct: 1 },
    { q: "QUAL O NOME DO PLANO DE RECONSTRUÇÃO DA EUROPA", options: ["PLANO REAL", "PLANO MARSHALL", "PLANO COLOMBO", "PLANO VERÃO"], correct: 1 },
    { q: "QUAL O NOME DA GUERRA EM QUE OS EUA PERDERAM", options: ["GUERRA DO GOLFO", "GUERRA DO VIETNÃ", "COREIA", "2ª GUERRA"], correct: 1 },
    { q: "QUEM FOI O LÍDER DO VIETNÃ DO NORTE", options: ["MAO", "HO CHI MINH", "KIM IL-SUNG", "POL POT"], correct: 1 },
    { q: "QUAL O NOME DO REGIME NO CAMBOJA", options: ["NAZISMO", "KHMER VERMELHO", "FASCISMO", "DEMOCRACIA"], correct: 1 },
    { q: "QUAL O NOME DA CRISE DOS MÍSSEIS EM 1962", options: ["CRISE DE CUBA", "CRISE DE BERLIM", "CRISE DO CANAL", "CRISE DO PETRÓLEO"], correct: 0 },
    { q: "QUEM FOI O PRESIDENTE DOS EUA ASSASSINADO EM 1963", options: ["LINCOLN", "JOHN F. KENNEDY", "NIXON", "REAGAN"], correct: 1 },
    { q: "QUAL O NOME DA REVOLUÇÃO NO IRÃ EM 1979", options: ["REVOLUÇÃO VERDE", "REVOLUÇÃO ISLÂMICA", "REVOLUÇÃO FRANCESA", "REVOLUÇÃO RUSSA"], correct: 1 },
    { q: "QUEM FOI A 'DAMA DE FERRO'", options: ["PRINCESA ISABEL", "MARGARET THATCHER", "RAINHA VITÓRIA", "ANGELA MERKEL"], correct: 1 },
    { q: "QUAL O NOME DA GUERRA PELAS ILHAS MALVINAS", options: ["GUERRA DO GOLFO", "GUERRA DAS MALVINAS", "GUERRA FRIA", "GUERRA CIVIL"], correct: 1 },
    { q: "QUEM FOI O ÚLTIMO LÍDER DA UNIÃO SOVIÉTICA", options: ["STALIN", "MIKHAIL GORBACHEV", "PUTIN", "IELTSIN"], correct: 1 },
    { q: "QUAL ERA O DEUS SERPENTE DOS ASTECAS", options: ["INTI", "QUETZALCÓATL", "RÁ", "ZEUS"], correct: 1 },
    { q: "SISTEMA DE CONTABILIDADE DOS INCAS", options: ["ESCRITA", "QUIPU (CORDAS)", "ÁBACO", "PAPEL"], correct: 1 },
    { q: "QUAL ERA A CAPITAL DO IMPÉRIO INCA", options: ["LIMA", "CUZCO", "SANTIAGO", "QUITO"], correct: 1 },
    { q: "POVO QUE CRIOU O CALENDÁRIO DE 2012", options: ["INCAS", "MAIAS", "ASTECAS", "TUPIS"], correct: 1 },
    { q: "QUAL ERA A BASE DA ALIMENTAÇÃO MAIA", options: ["TRIGO", "MILHO", "ARROZ", "CARNE"], correct: 1 },
    { q: "CIVILIZAÇÃO QUE CONSTRUIU CHICHÉN ITZÁ", options: ["INCAS", "MAIAS", "ASTECAS", "GREGOS"], correct: 1 },
    { q: "O QUE ERAM AS CHINAMPAS", options: ["ARMAS", "JARDINS FLUTUANTES", "CASAS", "NAVIO"], correct: 1 },
    { q: "QUEM FOI O IMPERADOR ASTECA NA CONQUISTA", options: ["ATAHUALPA", "MONTEZUMA II", "CUAUHTÉMOC", "ITZCOATL"], correct: 1 },
    { q: "QUEM FOI O ÚLTIMO IMPERADOR INCA", options: ["MONTEZUMA", "ATAHUALPA", "MANCO CAPAC", "PACHACUTI"], correct: 1 },
    { q: "QUAL ERA O METAL MAIS SAGRADO PARA OS INCAS", options: ["FERRO", "OURO (SUOR DO SOL)", "PRATA", "COBRE"], correct: 1 },
    { q: "QUEM ERAM OS 'CHASQUIS' NO IMPÉRIO INCA", options: ["REIS", "MENSAGEIROS CORREDORES", "SACERDOTES", "SOLDADOS"], correct: 1 },
    { q: "QUAL ERA O NOME DA LÍNGUA ASTECA", options: ["QUECHUA", "NAHUATL", "ESPANHOL", "MAIA"], correct: 1 },
    { q: "O QUE ERA O 'SACRIFÍCIO HUMANO'", options: ["FESTA", "RITUAL RELIGIOSO", "CASTIGO", "ESPORTE"], correct: 1 },
    { q: "ONDE SE LOCALIZAVA O IMPÉRIO MAIA", options: ["BRASIL", "MÉXICO/AMÉRICA CENTRAL", "PERU", "CHILE"], correct: 1 },
    { q: "QUAL ERA A PRINCIPAL ARMA DOS ASTECAS", options: ["ESPADA DE FERRO", "MACUAHUITL (OBSIDIANA)", "ARCO", "CANHÃO"], correct: 1 },
    { q: "COMO OS INCAS PLANTAVAM EM MONTANHAS", options: ["ESTUFAS", "TERRAÇOS/DEGRAUS", "HIDROPONIA", "NÃO PLANTAVAM"], correct: 1 },
    { q: "QUEM FOI O EXPLORADOR QUE 'DESCOBRIU' MACHU PICCHU", options: ["COLOMBO", "HIRAM BINGHAM", "PIZARRO", "CORTÉS"], correct: 1 },
    { q: "QUAL ERA A FORMA DAS PIRÂMIDES MAIAS", options: ["LISAS", "ESCALONADAS (DEGRAUS)", "REDONDAS", "PONTUDAS"], correct: 1 },
    { q: "O QUE ERAM OS 'CENOTES' PARA OS MAIAS", options: ["CASAS", "POÇOS SAGRADOS", "MONTANHAS", "MERCADOS"], correct: 1 },
    { q: "QUAL O NOME DO JOGO DE BOLA PRÉ-COLOMBIANO", options: ["FUTEBOL", "POK-TA-POK", "TÊNIS", "GOLFE"], correct: 1 },
    { q: "QUAL O NOME DA CLASSE GUERREIRA DO JAPÃO", options: ["NINJA", "SAMURAI", "RONIN", "XOGUM"], correct: 1 },
    { q: "QUEM ERA O LÍDER MILITAR DO JAPÃO ANTIGO", options: ["IMPERADOR", "XOGUM", "SAMURAI", "GEISHA"], correct: 1 },
    { q: "O QUE É O 'BUSHIDO'", options: ["UM PRATO", "CÓDIGO DE HONRA SAMURAI", "UMA LUTA", "UMA CIDADE"], correct: 1 },
    { q: "QUAL ERA A CAPITAL DO JAPÃO ANTES DE TÓQUIO", options: ["OSAKA", "QUIOTO", "NAGASAKI", "HIROSHIMA"], correct: 1 },
    { q: "CIVILIZAÇÃO QUE INVENTOU A PÓLVORA", options: ["INDIANA", "CHINESA", "ÁRABE", "GREGA"], correct: 1 },
    { q: "QUEM FOI O PRIMEIRO IMPERADOR DA CHINA", options: ["MAO", "QIN SHI HUANG", "CONFUCIÓ", "LAO TZU"], correct: 1 },
    { q: "O QUE É A 'CIDADE PROIBIDA'", options: ["UM MITO", "PALÁCIO IMPERIAL CHINÊS", "UMA PRISÃO", "UM TEMPLO"], correct: 1 },
    { q: "QUAL RELIGIÃO NASCEU NO NEPAL/ÍNDIA", options: ["ISLAMISMO", "BUDISMO", "JUDAÍSMO", "XINTOÍSMO"], correct: 1 },
    { q: "O QUE ERA O SISTEMA DE CASTAS", options: ["DIVISÃO SOCIAL NA ÍNDIA", "TIPO DE GOVERNO", "RELIGIÃO", "GUERRA"], correct: 0 },
    { q: "QUAL O NOME DO MONUMENTO AO AMOR NA ÍNDIA", options: ["PIRÂMIDE", "TAJ MAHAL", "ACRÓPOLE", "COLISEU"], correct: 1 },
    { q: "QUEM FOI O LÍDER QUE UNIFICOU OS MONGÓIS", options: ["KUBLAI KHAN", "GENGHIS KHAN", "ATTILA", "TIMUR"], correct: 1 },
    { q: "QUAL ERA A EXTENSÃO DO IMPÉRIO MONGOL", options: ["SÓ A CHINA", "MAIOR IMPÉRIO DE TERRAS CONTÍNUAS", "SÓ A EUROPA", "PEQUENA"], correct: 1 },
    { q: "QUEM ERAM OS NINJAS", options: ["REIS", "ESPIÕES/MERCENÁRIOS", "PADRES", "MERCADORES"], correct: 1 },
    { q: "QUAL PAÍS FOI FECHADO AO MUNDO POR 200 ANOS", options: ["CHINA", "JAPÃO", "COREIA", "ÍNDIA"], correct: 1 },
    { q: "O QUE FOI A 'REVOLUÇÃO MEIJI'", options: ["GUERRA", "MODERNIZAÇÃO DO JAPÃO", "FIM DA CHINA", "INVASÃO"], correct: 1 },
    { q: "QUAL ERA O NOME DA ESCRITA JAPONESA (UM DELES)", options: ["ABC", "KANJI", "HIERÓGLIFOS", "CIRÍLICO"], correct: 1 },
    { q: "QUAL O NOME DA ARTE MARCIAL DOS SAMURAIS", options: ["KARATÉ", "KENJUTSU", "JUDO", "KUNG FU"], correct: 1 },
    { q: "QUEM FOI SIDARTA GAUTAMA", options: ["REI", "BUDA", "GANDHI", "CONFÚCIO"], correct: 1 },
    { q: "O QUE ERAM OS 'GUERREIROS DE TERRACOTA'", options: ["BRINQUEDOS", "EXÉRCITO DE ARGILA FUNERÁRIO", "ESTÁTUAS GREGAS", "MÚMIAS"], correct: 1 },
    { q: "O QUE É O 'TAOISMO'", options: ["UMA LUTA", "FILOSOFIA/RELIGIÃO CHINESA", "UM GOVERNO", "UM PRATO"], correct: 1 },
    { q: "QUEM FOI O PRESIDENTE DO 'MILAGRE ECONÔMICO'", options: ["MÉDICI", "GEISEL", "VARGAS", "SARNEY"], correct: 0 },
    { q: "QUAL O NOME DA REVOLTA CONTRA O RECRUTAMENTO", options: ["VACINA", "CHIBATA", "ARMADA", "CONTestado"], correct: 3 },
    { q: "QUEM FOI O LÍDER DA REVOLTA DA CHIBATA", options: ["ZUMBI", "JOÃO CÂNDIDO", "VARGAS", "DEODORO"], correct: 1 },
    { q: "QUAL ERA O LEMA DA DITADURA MILITAR", options: ["PAZ E AMOR", "BRASIL: AME-O OU DEIXE-O", "ORDEM E PROGRESSO", "50 ANOS EM 5"], correct: 1 },
    { q: "O QUE FOI O 'PLANO METAS'", options: ["PLANO DE JK", "PLANO DE VARGAS", "PLANO REAL", "PLANO COLLOR"], correct: 0 },
    { q: "QUAL ERA A MOEDA ANTES DO REAL", options: ["CRUZEIRO", "CRUZEIRO REAL", "CRUZADO", "TODOS"], correct: 3 },
    { q: "EM QUE ANO BRASÍLIA FOI INAUGURADA", options: ["1950", "1960", "1970", "1945"], correct: 1 },
    { q: "QUEM FOI O ARQUITETO DE BRASÍLIA", options: ["LÚCIO COSTA", "OSCAR NIEMEYER", "MAUÁ", "JK"], correct: 1 },
    { q: "QUEM FEZ O PLANO PILOTO DE BRASÍLIA", options: ["NIEMEYER", "LÚCIO COSTA", "VARGAS", "CASTELLO"], correct: 1 },
    { q: "QUAL FOI O ÚLTIMO PRESIDENTE MILITAR", options: ["MÉDICI", "FIGUEIREDO", "GEISEL", "COSTA E SILVA"], correct: 1 },
    { q: "O QUE FOI A 'CONSTITUIÇÃO CIDADÃ'", options: ["1891", "1988", "1934", "1967"], correct: 1 },
    { q: "QUEM FOI O VICE DE TANCREDO NEVES", options: ["SARNEY", "FHC", "COLLOR", "ITAMAR"], correct: 0 },
    { q: "QUAL PRESIDENTE CONFISCOU A POUPANÇA", options: ["SARNEY", "COLLOR", "DILMA", "LULA"], correct: 1 },
    { q: "O QUE FOI O 'CARAS PINTADAS'", options: ["FESTA", "PROTESTO CONTRA COLLOR", "TEATRO", "REVOLUÇÃO"], correct: 1 },
    { q: "QUAL PRESIDENTE CRIOU A PETROBRAS", options: ["JK", "GETÚLIO VARGAS", "LULA", "SARNEY"], correct: 1 },
    { q: "EM QUE ANO VARGAS SE SUICIDOU", options: ["1930", "1945", "1954", "1964"], correct: 2 },
    { q: "O QUE FOI O 'TENENTISMO'", options: ["MOVIMENTO RELIGIOSO", "MOVIMENTO MILITAR REFORMISTA", "REVOLTA ESCRAVA", "GUERRA"], correct: 1 },
    { q: "QUEM FOI O 'REI DO CAFÉ'", options: ["D. PEDRO II", "BARÃO DE MAUÁ", "CONDE DE IBIABA", "VARGAS"], correct: 2 },
    { q: "O QUE FOI A 'POLÍTICA EXTERNA INDEPENDENTE'", options: ["DE JK", "DE JÂNIO QUADROS", "DA DITADURA", "DO IMPÉRIO"], correct: 1 },
    { q: "QUAL FOI O PRIMEIRO PARTIDO DE VARGAS", options: ["PT", "ALIANÇA LIBERAL", "ARENA", "MDB"], correct: 1 },
    { q: "QUAL O NOME DA GUERRA ENTRE CATÓLICOS E PROTESTANTES", options: ["CEM ANOS", "TRINTA ANOS", "CRUZADAS", "GOLFO"], correct: 1 },
    { q: "O QUE FOI A INQUISIÇÃO", options: ["UMA FESTA", "TRIBUNAL DA IGREJA", "UM MAPA", "UM NAVIO"], correct: 1 },
    { q: "QUEM FOI O LÍDER DA REFORMA NA SUÍÇA", options: ["LUTERO", "CALVINO", "HENRIQUE VIII", "PAPA"], correct: 1 },
    { q: "QUAL ERA O NOME DA CIDADE SAGRADA PARA TRÊS RELIGIÕES", options: ["ROMA", "JERUSALÉM", "MECA", "PARIS"], correct: 1 },
    { q: "O QUE FOI O 'EDITO DE NANTES'", options: ["GUERRA", "TOLERÂNCIA RELIGIOSA NA FRANÇA", "FIM DO MUNDO", "LEI DE ESCRAVOS"], correct: 1 },
    { q: "QUEM FOI O LÍDER DOS 'PURITANOS' NA INGLATERRA", options: ["CARLOS I", "OLIVER CROMWELL", "JAMES II", "VIVIT"], correct: 1 },
    { q: "QUAL O NOME DA RELIGIÃO DOS SAMURAIS", options: ["XINTOÍSMO/ZEN", "ISLÃ", "CATOLICISMO", "HINDUÍSMO"], correct: 0 },
    { q: "QUEM FOI O FUNDADOR DO SIONISMO", options: ["HERZL", "BEN-GURION", "EINSTEIN", "MARX"], correct: 0 },
    { q: "O QUE FOI O 'CONCÍLIO DE TRENTO'", options: ["REFORMA", "CONTRARREFORMA CATÓLICA", "FESTA", "GUERRA"], correct: 1 },
    { q: "QUEM FOI O PAI DA PSICANÁLISE", options: ["JUNG", "FREUD", "NIETZSCHE", "MARX"], correct: 1 },
    { q: "QUAL ERA O LEMA DO ILUMINISMO", options: ["SAPERE AUDE (OUSE SABER)", "PAZ E AMOR", "ORDEM", "PROGRESSO"], correct: 0 },
    { q: "O QUE FOI O 'APARTHEID'", options: ["GUERRA", "SEGREGAÇÃO RACIAL NA ÁFRICA DO SUL", "PANCADA", "TRATADO"], correct: 1 },
    { q: "QUEM FOI O LÍDER DA REVOLUÇÃO LÍBIA", options: ["SADDAM", "GADAFI", "MUBARAK", "ASSAD"], correct: 1 },
    { q: "QUAL O NOME DA GUERRA DOS SEIS DIAS", options: ["CONFLITO ÁRABE-ISRAELENSE", "GUERRA CIVIL", "1ª GUERRA", "FALKIN"], correct: 0 },
    { q: "QUEM FOI O FUNDADOR DA CRUZ VERMELHA", options: ["DUNANT", "NIGHTINGALE", "PASTEUR", "CURIE"], correct: 0 },
    { q: "QUAL O NOME DO MOVIMENTO DE INDEPENDÊNCIA ARGENTINO", options: ["ZAPATA", "SAN MARTÍN", "BOLÍVAR", "PERÓN"], correct: 1 },
    { q: "O QUE FOI A 'PRIMAVERA DOS POVOS'", options: ["FESTA", "REVOLUÇÕES DE 1848", "GUERRA", "PLANTAÇÃO"], correct: 1 },
    { q: "QUEM FOI O LÍDER DA UNIFICAÇÃO ITALIANA", options: ["CÉSAR", "GARIBALDI", "MUSSOLINI", "DANTE"], correct: 1 },
    { q: "QUEM FOI O 'CHANCELER DE FERRO' DA ALEMANHA", options: ["HITLER", "OTTO VON BISMARCK", "KAISER", "KOHL"], correct: 1 },
    { q: "QUAL O NOME DA GUERRA PELO CONTROLE DA CRIMEIA (1853)", options: ["GUERRA FRIA", "GUERRA DA CRIMEIA", "GUERRA RUSSA", "GUERRA CIVIL"], correct: 1 },
    { q: "QUAL O PRIMEIRO SER VIVO NO ESPAÇO", options: ["GATO", "CADELA LAIKA", "MACACO", "HUMANO"], correct: 1 },
    { q: "QUAL O NOME DA MISSÃO QUE LEVOU O HOMEM À LUA", options: ["SPUTNIK", "APOLLO 11", "VOYAGER", "DISCOVERY"], correct: 1 },
    { q: "QUEM FOI O PRIMEIRO HOMEM A PISAR NA LUA", options: ["GAGARIN", "NEIL ARMSTRONG", "BUZZ ALDRIN", "SANTOS DUMONT"], correct: 1 },
    { q: "QUAL PAÍS VENCEU A CORRIDA ESPACIAL (LUA)", options: ["URSS", "EUA", "CHINA", "ALEMANHA"], correct: 1 },
    { q: "QUAL O NOME DO PRIMEIRO SATÉLITE ARTIFICIAL", options: ["EXPLORER", "SPUTNIK 1", "TELSTAR", "LUZ"], correct: 1 },
    { q: "QUEM FOI A PRIMEIRA MULHER NO ESPAÇO", options: ["VALENTINA TERESHKOVA", "MARIA CURIE", "AMELIA EARHART", "SALLY RIDE"], correct: 0 },
    { q: "QUAL O NOME DO ÔNIBUS ESPACIAL QUE EXPLODIU EM 1986", options: ["COLUMBIA", "CHALLENGER", "ATLANTIS", "ENDEAVOUR"], correct: 1 },
    { q: "QUEM INVENTOU O TELEFONE (PATENTE)", options: ["TESLA", "ALEXANDER GRAHAM BELL", "EDISON", "MORSE"], correct: 1 },
    { q: "QUAL O NOME DO CÓDIGO DE PONTOS E TRAÇOS", options: ["BINÁRIO", "CÓDIGO MORSE", "ASCII", "BRAILLE"], correct: 1 },
    { q: "QUEM INVENTOU A VACINA CONTRA A POLIO", options: ["PASTEUR", "JONAS SALK", "SABIN", "FLEMING"], correct: 1 },
    { q: "QUEM DESCOBRIU A PENICILINA", options: ["EINSTEIN", "ALEXANDER FLEMING", "NEWTON", "DARWIN"], correct: 1 },
    { q: "QUAL O NOME DO PRIMEIRO COMPUTADOR", options: ["MAC", "ENIAC", "IBM", "ALTAIR"], correct: 1 },
    { q: "QUEM FOI O PAI DA COMPUTAÇÃO", options: ["BILL GATES", "ALAN TURING", "JOBS", "ZUCKERBERG"], correct: 1 },
    { q: "QUAL O NOME DA MÁQUINA DE CRIPTOGRAFIA NAZISTA", options: ["ENIGMA", "DECIFRA", "CODEX", "MATRIX"], correct: 0 },
    { q: "QUEM INVENTOU O CINEMATÓGRAFO", options: ["IRMÃOS LUMIÈRE", "EDISON", "DA VINCI", "DISNEY"], correct: 0 },
    { q: "QUAL O NOME DO PRIMEIRO CARRO PRODUZIDO EM SÉRIE", options: ["FERRARI", "FORD MODELO T", "FUSCA", "CORVETTE"], correct: 1 },
    { q: "QUEM FOI O PAI DA AVIAÇÃO (MUNDO)", options: ["WRIGHT/SANTOS DUMONT", "DA VINCI", "LINDBERGH", "ARMSTRONG"], correct: 0 },
    { q: "QUAL O NOME DO PROJETO DA BOMBA ATÔMICA", options: ["MANHATTAN", "APOLLO", "VALQUÍRIA", "BARBAROSSA"], correct: 0 },
    { q: "QUEM FOI O PAI DA INTERNET (UM DOS)", options: ["VINT CERF", "BILL GATES", "JOBS", "MUSK"], correct: 0 },
    { q: "QUAL O NOME DO PRIMEIRO NAVEGADOR WEB", options: ["CHROME", "MOSAIC/NETSCAPE", "EXPLORER", "SAFARI"], correct: 1 },
    { q: "QUAL O EVENTO QUE MARCOU O INÍCIO DO SÉCULO XXI", options: ["QUEDA DO MURO", "11 DE SETEMBRO", "GUERRA DO GOLFO", "INTERNET"], correct: 1 },
    { q: "QUAL O NOME DO GRUPO TERRORISTA DO 11/09", options: ["ISIS", "AL-QAEDA", "HAMAS", "TALIBÃ"], correct: 1 },
    { q: "QUEM ERA O PRESIDENTE DOS EUA NO 11/09", options: ["CLINTON", "GEORGE W. BUSH", "OBAMA", "REAGAN"], correct: 1 },
    { q: "QUAL PAÍS OS EUA INVADIRAM EM 2003", options: ["AFEGANISTÃO", "IRAQUE", "IRÃ", "SÍRIA"], correct: 1 },
    { q: "QUEM FOI O PRIMEIRO PRESIDENTE NEGRO DOS EUA", options: ["MARTIN LUTHER KING", "BARACK OBAMA", "NELSON MANDELA", "MALCOLM X"], correct: 1 },
    { q: "QUAL O NOME DA MOEDA ÚNICA EUROPEIA", options: ["LIBRA", "EURO", "DOLAR", "FRANCO"], correct: 1 },
    { q: "QUAL PAÍS SAIU DA UNIÃO EUROPEIA (BREXIT)", options: ["FRANÇA", "REINO UNIDO", "ALEMANHA", "ITÁLIA"], correct: 1 },
    { q: "QUAL O NOME DA CRISE ECONÔMICA DE 2008", options: ["GRANDE DEPRESSÃO", "CRISE DO SUBPRIME", "PLANO REAL", "CRISE DO PETRÓLEO"], correct: 1 },
    { q: "QUEM FOI O LÍDER DA AL-QAEDA", options: ["SADDAM", "OSAMA BIN LADEN", "GADAFI", "KHAMENEI"], correct: 1 },
    { q: "QUAL O NOME DA REVOLTA ÁRABE EM 2011", options: ["PRIMAVERA ÁRABE", "GUERRA SANTA", "REVOLUÇÃO VERDE", "INTIFADA"], correct: 0 },
    { q: "QUEM É O LÍDER DA COREIA DO NORTE", options: ["KIM JONG-UN", "MAO", "XI JINPING", "KIM IL-SUNG"], correct: 0 },
    { q: "QUAL O NOME DO ACORDO PELO CLIMA EM 2015", options: ["KIOTO", "ACORDO DE PARIS", "RIO+20", "ESTOCOLMO"], correct: 1 },
    { q: "QUEM FOI A PRIMEIRA MULHER CHANCELER DA ALEMANHA", options: ["THATCHER", "ANGELA MERKEL", "VON DER LEYEN", "GANDHI"], correct: 1 },
    { q: "QUAL PAÍS SEDIOU A COPA EM 2014", options: ["ALEMANHA", "BRASIL", "RÚSSIA", "QATAR"], correct: 1 },
    { q: "QUAL O NOME DA REDE SOCIAL CRIADA POR ZUCKERBERG", options: ["TWITTER", "FACEBOOK", "INSTAGRAM", "TIKTOK"], correct: 1 },
    { q: "QUEM É O ATUAL PAPA (DESDE 2013)", options: ["BENTO XVI", "FRANCISCO", "JOÃO PAULO II", "PIO XII"], correct: 1 },
    { q: "QUAL O NOME DA DOENÇA QUE CAUSOU PANDEMIA EM 2020", options: ["H1N1", "COVID-19", "EBOLA", "ZIKA"], correct: 1 },
    { q: "QUAL O NOME DO TELESCOPIO QUE SUBSTITUIU O HUBBLE", options: ["KEPLER", "JAMES WEBB", "GALILEO", "SPITZER"], correct: 1 },
    { q: "QUEM É O DONO DA SPACEX E TESLA", options: ["BILL GATES", "ELON MUSK", "JEFF BEZOS", "MARK Z."], correct: 1 },
    { q: "QUAL O NOME DA INTELIGÊNCIA ARTIFICIAL DA OPENAI", options: ["SIRI", "CHATGPT", "ALEXA", "BARD"], correct: 1 },
    { q: "QUEM FOI A RAINHA MAIS LONGEVA DO REINO UNIDO", options: ["VITÓRIA", "ELIZABETH II", "MARY", "ELIZABETH I"], correct: 1 },
    { q: "QUEM FOI A CIENTISTA QUE ESTUDOU A RADIOATIVIDADE", options: ["ANITA GARIBALDI", "MARIE CURIE", "FRIDA KAHLO", "CLEÓPATRA"], correct: 1 },
    { q: "QUEM FOI A HEROÍNA DA INDEPENDÊNCIA DA BAHIA", options: ["PRINCESA ISABEL", "MARIA QUITÉRIA", "ANITA GARIBALDI", "MARINA SILVA"], correct: 1 },
    { q: "QUAL RAINHA GOVERNOU A INGLATERRA NA ERA DE SHAKESPEARE", options: ["MARY I", "ELIZABETH I", "VITÓRIA", "ANNE"], correct: 1 },
    { q: "QUEM FOI A ARTISTA MEXICANA DAS AUTOPINTURAS", options: ["TARSILA", "FRIDA KAHLO", "ANITA MALFATTI", "DALÍ"], correct: 1 },
    { q: "QUEM FOI A PRIMEIRA MULHER A VOAR O ATLÂNTICO", options: ["VALENTINA", "AMELIA EARHART", "SALLY RIDE", "CURIE"], correct: 1 },
    { q: "QUEM FOI A ENFERMEIRA DA GUERRA DA CRIMEIA", options: ["JOANA D'ARC", "FLORENCE NIGHTINGALE", "ANNA NERY", "MARIA"], correct: 1 },
    { q: "QUEM FOI A PRIMEIRA ENFERMEIRA DO BRASIL", options: ["ANNA NERY", "MARIA QUITÉRIA", "ISABEL", "ANITA"], correct: 0 },
    { q: "QUEM FOI A ATIVISTA QUE SE RECUSOU A CEDER LUGAR NO ÔNIBUS", options: ["ROSA PARKS", "MICHELLE OBAMA", "ANGELA DAVIS", "MALALA"], correct: 0 },
    { q: "QUEM É A JOVEM QUE LUTOU PELA EDUCAÇÃO NO PAQUISTÃO", options: ["GRETA", "MALALA YOUSAFZAI", "ANNE FRANK", "INDIRA GANDHI"], correct: 1 },
    { q: "QUEM ESCREVEU O DIÁRIO DURANTE A 2ª GUERRA", options: ["MALALA", "ANNE FRANK", "AGATHA CHRISTIE", "JK ROWLING"], correct: 1 },
    { q: "QUEM FOI A 'DAMA DA LÂMPADA'", options: ["ANNA NERY", "FLORENCE NIGHTINGALE", "ISABEL", "CURIE"], correct: 1 },
    { q: "QUEM FOI A RAINHA DO EGITO QUE SE ALIOU A JULIO CÉSAR", options: ["NEFERTITI", "CLEÓPATRA", "HATSHEPSUT", "ÍSIS"], correct: 1 },
    { q: "QUEM FOI A LÍDER DA INCONFIDÊNCIA MINEIRA (MULHER)", options: ["ANITA GARIBALDI", "BÁRBARA DE ALENCAR", "HIPÓLITA JACINTA", "MARIA QUITÉRIA"], correct: 2 },
    { q: "QUEM FOI A 'ANITA GARIBALDI'", options: ["RAINHA", "HEROÍNA DOS DOIS MUNDOS", "PINTORA", "CANTORA"], correct: 1 },
    { q: "QUEM FOI A IMPERATRIZ QUE AMAVA O BRASIL", options: ["CARLOTA JOAQUINA", "MARIA LEOPOLDINA", "ISABEL", "TEREZA CRISTINA"], correct: 1 },
    { q: "QUEM FOI A ESCRITORA DE 'O QUARTO DE DESPEJO'", options: ["CLARICE LISPECTOR", "CAROLINA MARIA DE JESUS", "CECELIA MEIRELLES", "Lygia Fagundes"], correct: 1 },
    { q: "QUEM FOI A PRIMEIRA MULHER NO PARLAMENTO INGLÊS", options: ["THATCHER", "NANCY ASTOR", "ELIZABETH", "DIANA"], correct: 1 },
    { q: "QUEM FOI A PRINCESA DE GALES QUE MORREU EM 1997", options: ["CAMILLA", "DIANA (LADY DI)", "KATE", "MEGHAN"], correct: 1 },
    { q: "QUEM FOI A PRIMEIRA-MINISTRA DA ÍNDIA", options: ["GANDHI", "INDIRA GANDHI", "TERESA DE CALCUTÁ", "MALALA"], correct: 1 },
    { q: "QUAL ERA O NOME DA MOEDA DO IMPÉRIO ROMANO", options: ["REAL", "DENÁRIO", "DOLAR", "PESO"], correct: 1 },
    { q: "QUAL ERA A BEBIDA SAGRADA DOS ASTECAS", options: ["CAFÉ", "CHOCOLATE (CACAU)", "CHÁ", "VINHO"], correct: 1 },
    { q: "QUAL O NOME DA ESTRADA QUE LIGAVA ROMA AO SUL", options: ["VIA APPIA", "ESTRADA REAL", "ROTA DA SEDA", "VIA SACRA"], correct: 0 },
    { q: "ONDE SURGIU O PRIMEIRO JORNAL DO MUNDO", options: ["LONDRES", "ROMA (ACTA DIURNA)", "PARIS", "PEQUIM"], correct: 1 },
    { q: "COMO OS ROMANOS SE LIMPAVAM NOS BANHOS", options: ["SABONETE", "ÓLEO E ESTRÍGIL", "SÓ ÁGUA", "ESPONJA"], correct: 1 },
    { q: "QUAL O NOME DA CALÇA USADA PELOS ROMANOS (TARDE)", options: ["TOGA", "BRACAE", "TUNICA", "SHORT"], correct: 1 },
    { q: "O QUE ERAM OS 'GLADIADORES'", options: ["REIS", "LUTADORES ESCRAVOS", "PADRES", "MÉDICOS"], correct: 1 },
    { q: "QUAL ERA O NOME DA REFEIÇÃO PRINCIPAL EM ROMA", options: ["BREAKFAST", "CENA", "LUNCH", "DINNER"], correct: 1 },
    { q: "O QUE OS EGÍPCIOS USAVAM COMO TRAVESSEIRO", options: ["ALMOFADA", "SUPORTE DE MADEIRA/PEDRA", "PENAS", "NADA"], correct: 1 },
    { q: "QUAL ERA O ALIMENTO BASE DOS SOLDADOS ROMANOS", options: ["CARNE", "TRIGO (PÃO/PAPA)", "PEIXE", "FRUTAS"], correct: 1 },
    { q: "QUAL O NOME DA BEBIDA DOS VIKINGS", options: ["VINHO", "HIDROMEL", "CERVEJA", "SUCO"], correct: 1 },
    { q: "QUAL ERA O MATERIAL DAS VELAS DOS NAVIOS ANTIGOS", options: ["PLÁSTICO", "LINHO OU CÂNHAMO", "SEDA", "PAPEL"], correct: 1 },
    { q: "O QUE ERAM AS 'CATACUMBAS'", options: ["PALÁCIOS", "CEMITÉRIOS SUBTERRÂNEOS", "MERCADOS", "ESCOLAS"], correct: 1 },
    { q: "QUAL ERA O NOME DO MERCADO PÚBLICO EM ROMA", options: ["SHOPPING", "FÓRUM", "ÁGORA", "BAZAR"], correct: 1 },
    { q: "QUAL ERA O NOME DA PRAÇA PÚBLICA NA GRÉCIA", options: ["FÓRUM", "ÁGORA", "TEATRO", "ESTÁDIO"], correct: 1 },
    { q: "COMO SE CHAMAVA O PROFESSOR EM ROMA", options: ["MAGISTER", "DOCTOR", "COACH", "SENSEI"], correct: 0 },
    { q: "O QUE ERAM OS 'AQUEDUTOS'", options: ["PONTES DE CARROS", "CANAIS DE ÁGUA", "MUROS", "TEMPLOS"], correct: 1 },
    { q: "QUAL ERA O NOME DO RELÓGIO DE SOL", options: ["CRONÔMETRO", "GNÔMON", "AMPULHETA", "DIGITAL"], correct: 1 },
    { q: "O QUE ERAM OS 'PAPIROS'", options: ["LIVROS", "FOLHAS DE PLANTA PARA ESCREVER", "ARMAS", "COMIDA"], correct: 1 },
    { q: "QUAL FOI O PRIMEIRO FILME EXIBIDO NO CINEMA", options: ["O REGADOR REGADO", "SAÍDA DOS OPERÁRIOS", "TITANIC", "STAR WARS"], correct: 1 },
    { q: "QUEM INVENTOU O TELÉGRAFO", options: ["BELL", "SAMUEL MORSE", "EDISON", "TESLA"], correct: 1 },
    { q: "QUAL O NOME DA PRIMEIRA PROGRAMADORA DO MUNDO", options: ["CURIE", "ADA LOVELACE", "ISABEL", "GRACE HOPPER"], correct: 1 },
    { q: "QUAL O NOME DO PRIMEIRO CONSOLE DE VÍDEO GAME", options: ["ATARI", "MAGNAVOX ODYSSEY", "NINTENDO", "PONG"], correct: 1 },
    { q: "QUEM FOI O PAI DO CINEMA DE ANIMAÇÃO", options: ["DISNEY", "ÉMILE COHL", "LUMIÈRE", "EDISON"], correct: 1 },
    { q: "QUAL O NOME DO PRIMEIRO SATÉLITE DE COMUNICAÇÃO", options: ["SPUTNIK", "TELSTAR 1", "APOLLO", "HUBBLE"], correct: 1 },
    { q: "QUAL O NOME DA PRIMEIRA LINGUAGEM DE PROGRAMAÇÃO ALTA", options: ["C", "FORTRAN", "PYTHON", "JAVA"], correct: 1 },
    { q: "QUEM INVENTOU A WORLD WIDE WEB (WWW)", options: ["GATES", "TIM BERNERS-LEE", "JOBS", "MUSK"], correct: 1 },
    { q: "QUAL FOI O PRIMEIRO NOME DA INTERNET", options: ["WWW", "ARPANET", "GOOGLE", "REDE"], correct: 1 },
    { q: "QUAL O NOME DO PRIMEIRO SMARTPHONE", options: ["IPHONE", "IBM SIMON", "NOKIA", "BLACKBERRY"], correct: 1 },
    { q: "QUEM INVENTOU O MOTOR A DIESEL", options: ["FORD", "RUDOLF DIESEL", "BENZ", "FERRARI"], correct: 1 },
    { q: "QUAL O NOME DO PRIMEIRO AVIÃO A JATO", options: ["BOEING", "HEINKEL HE 178", "SPITFIRE", "CONCORDE"], correct: 1 },
    { q: "QUEM INVENTOU A FOTOGRAFIA (UM DOS)", options: ["DA VINCI", "DAGUERRE", "EDISON", "LUMIÈRE"], correct: 1 },
    { q: "QUAL O NOME DO PRIMEIRO DISCO DE ÁUDIO", options: ["CD", "DISCO DE VINIL", "CILINDRO DE FONÓGRAFO", "MP3"], correct: 2 },
    { q: "QUEM INVENTOU A TELEVISÃO (UM DOS)", options: ["BAIRD", "EDISON", "BELL", "TESLA"], correct: 0 },
    { q: "QUAL O NOME DA PRIMEIRA AGÊNCIA ESPACIAL", options: ["NASA", "NACA", "ESA", "ROSCOSMOS"], correct: 1 },
    { q: "QUAL O NOME DO PRIMEIRO ANIMAL CLONADO (MAMÍFERO)", options: ["GATO", "OVELHA DOLLY", "CÃO", "RATO"], correct: 1 },
    { q: "QUEM INVENTOU O ESTETOSCÓPIO", options: ["PASTEUR", "RENE LAENNEC", "SALK", "FLEMING"], correct: 1 },
    { q: "QUAL O NOME DO PRIMEIRO MICROSCOPIO", options: ["GALILEO", "VAN LEEUWENHOEK", "NEWTON", "HOOKE"], correct: 1 },
    { q: "QUEM INVENTOU A DINAMITE", options: ["NOBEL", "EDISON", "TESLA", "EINSTEIN"], correct: 0 },
    { q: "QUAL O NOME DO PLANO QUE CRIOU O REAL", options: ["PLANO VERÃO", "PLANO REAL", "PLANO COLLOR", "PLANO BRESSER"], correct: 1 },
    { q: "QUEM FOI O PRESIDENTE DO 'FOME ZERO'", options: ["FHC", "LULA", "DILMA", "BOLSONARO"], correct: 1 },
    { q: "QUAL CIDADE SEDIOU AS OLIMPÍADAS DE 2016", options: ["SÃO PAULO", "RIO DE JANEIRO", "BRASÍLIA", "CURITIBA"], correct: 1 },
    { q: "QUEM FOI O 'REI DO BAIÃO'", options: ["CAETANO", "LUIZ GONZAGA", "GILBERTO GIL", "CHICO BUARQUE"], correct: 1 },
    { q: "QUAL O NOME DO MOVIMENTO MUSICAL DE 1967", options: ["BOSSA NOVA", "TROPICÁLIA", "JOVEM GUARDA", "PUNK"], correct: 1 },
    { q: "QUEM ESCREVEU 'SÍTIO DO PICAPAU AMARELO'", options: ["MACHADO DE ASSIS", "MONTEIRO LOBATO", "ERICO VERISSIMO", "ZIRALDO"], correct: 1 },
    { q: "QUAL O NOME DA REVOLTA NO PARÁ (1835)", options: ["BALAIADA", "CABANAGEM", "SABINADA", "MALÊS"], correct: 1 },
    { q: "QUEM FOI O 'MARECHAL DE FERRO'", options: ["DEODORO", "FLORIANO PEIXOTO", "VARGAS", "CASTELLO"], correct: 1 },
    { q: "QUAL O NOME DA PRIMEIRA MOEDA DO BRASIL", options: ["REAL", "RÉIS", "CRUZEIRO", "CRUZADO"], correct: 1 },
    { q: "EM QUE ANO FOI EXTINTA A ESCRAVIDÃO", options: ["1822", "1888", "1889", "1900"], correct: 1 },
    { q: "QUEM FOI O FUNDADOR DA ACADEMIA BRASILEIRA DE LETRAS", options: ["ALENCAR", "MACHADO DE ASSIS", "QUINTANA", "BANDEIRA"], correct: 1 },
    { q: "QUAL O NOME DA REVOLTA DOS MARINHEIROS NO RIO", options: ["VACINA", "CHIBATA", "ARMADA", "FORTE"], correct: 1 },
    { q: "QUEM FOI O LÍDER DO MOVIMENTO DOS SEM-TERRA (FUNDADOR)", options: ["LULA", "STÉDILE", "CHICO MENDES", "ZUMBI"], correct: 1 },
    { q: "QUAL O NOME DA PRIMEIRA TRANSMISSÃO DE RÁDIO NO BRASIL", options: ["1900", "1922", "1930", "1950"], correct: 1 },
    { q: "QUEM FOI O PRESIDENTE QUE MORREU ANTES DE ASSUMIR EM 1985", options: ["SARNEY", "TANCREDO NEVES", "COLLOR", "FHC"], correct: 1 },
    { q: "QUAL O NOME DA OPERAÇÃO QUE PRENDEU POLÍTICOS EM 2014", options: ["LAVA JATO", "MENSALÃO", "URAGANO", "ZELOTES"], correct: 0 },
    { q: "QUEM É CONSIDERADA A 'MÃE DO FEMINISMO' NO BRASIL", options: ["DILMA", "BERTHA LUTZ", "MARINA", "TARSILA"], correct: 1 },
    { q: "QUAL O NOME DO PRIMEIRO BANCO DO BRASIL", options: ["ITAÚ", "BANCO DO BRASIL (1808)", "CAIXA", "BRADESCO"], correct: 1 },
    { q: "QUEM FOI O LÍDER SERINGUEIRO ASSASSINADO NO ACRE", options: ["ZUMBI", "CHICO MENDES", "LAMPIÃO", "CONSELHEIRO"], correct: 1 },
    { q: "QUAL O NOME DA CONSTITUIÇÃO DE 1934", options: ["ESTADO NOVO", "CONSTITUIÇÃO DE 34", "CIDADÃ", "IMPERIAL"], correct: 1 },
    { q: "QUAL O NOME DA CIDADE PERDIDA DOS INCAS", options: ["CUZCO", "MACHU PICCHU", "LIMA", "EL DORADO"], correct: 1 },
    { q: "QUEM FOI O AUTOR DE 'A ORIGEM DAS ESPÉCIES'", options: ["LINNEU", "CHARLES DARWIN", "LAMARCK", "MENDEL"], correct: 1 },
    { q: "QUAL O NOME DO EXPLORADOR QUE CHEGOU AO POLO SUL", options: ["SCOTT", "AMUNDSEN", "SHACKLETON", "COOK"], correct: 1 },
    { q: "QUAL O NOME DA PRIMEIRA CIVILIZAÇÃO DO MUNDO", options: ["EGÍPCIA", "SUMÉRIA", "GREGA", "ROMANA"], correct: 1 },
    { q: "QUEM FOI O DEUS DO SOL DOS INCAS", options: ["RA", "INTI", "ZEUS", "APOLO"], correct: 1 },
    { q: "QUAL O NOME DA BIBLIOTECA QUE PEGOU FOGO NA ANTIGUIDADE", options: ["ROMA", "ALEXANDRIA", "ATENAS", "BABILÔNIA"], correct: 1 },
    { q: "QUAL O NOME DA ESPOSA DE NAPOLEÃO", options: ["MARIA", "JOSEFINA", "ISABEL", "VITÓRIA"], correct: 1 },
    { q: "QUEM FOI O PRESIDENTE DOS EUA NA CRISE DE 1929", options: ["ROOSEVELT", "HOOVER", "WILSON", "TAFT"], correct: 1 },
    { q: "QUAL O NOME DO TRATADO QUE TERMINOU A 1ª GUERRA", options: ["MADRI", "VERSALHES", "TORDESILHAS", "ROMA"], correct: 1 },
    { q: "QUEM FOI O LÍDER DA REVOLUÇÃO FRANCESA (TERROR)", options: ["DANTON", "ROBESPIERRE", "LUIZ XVI", "MARAT"], correct: 1 },
    { q: "QUAL O NOME DO IMPERADOR QUE UNIFICOU A ALEMANHA", options: ["GUILHERME I", "BISMARCK", "HITLER", "CARLOS V"], correct: 0 },
    { q: "QUAL O NOME DA GUERRA DOS 7 ANOS", options: ["1756-1763", "1800-1807", "1914-1921", "100-107"], correct: 0 },
    { q: "QUEM FOI O PAI DO COMUNISMO", options: ["STALIN", "KARL MARX", "LENIN", "MAO"], correct: 1 },
    { q: "QUAL O NOME DA MOEDA DA ALEMANHA ANTES DO EURO", options: ["FRANCO", "MARCO ALEMÃO", "LIBRA", "LIRA"], correct: 1 },
    { q: "QUAL O NOME DA PRIMEIRA DINASTIA DA FRANÇA", options: ["BOURBON", "MEROVÍNGIA", "CAROLÍNGIA", "VALOIS"], correct: 1 },
    { q: "QUEM FOI O DEUS DA GUERRA DOS ASTECAS", options: ["INTI", "HUITZILOPOCHTLI", "QUETZALCOATL", "RÁ"], correct: 1 },
    { q: "QUAL O NOME DO ÚLTIMO CZAR DA RÚSSIA", options: ["PEDRO", "NICOLAU II", "ALEXANDRE", "IVAN"], correct: 1 },
    { q: "QUEM FOI A PRIMEIRA MULHER A GANHAR NOBEL", options: ["MADRE TERESA", "MARIE CURIE", "MALALA", "GANDHI"], correct: 1 },
];
