const naturezaData = [
    { q: "MAIOR ANIMAL VIVO", options: ["ELEFANTE", "BALEIA AZUL", "GIRAFA", "TUBARÃO"], correct: 1 },
    { q: "ANIMAL QUE LATE", options: ["GATO", "CAVALO", "CÃO", "LEÃO"], correct: 2 },
    { q: "ANIMAL MAIS RÁPIDO", options: ["GUEPARDO", "CAVALO", "LEÃO", "TIGRE"], correct: 0 },
    { q: "O QUE O PANDA COME", options: ["CARNE", "BAMBU", "FRUTAS", "PEIXE"], correct: 1 },
    { q: "REI DA SELVA", options: ["TIGRE", "ELEFANTE", "LEÃO", "GORILA"], correct: 2 },
    { q: "MAMÍFERO QUE VOA", options: ["PÁSSARO", "MORCEGO", "ESQUILO", "BORBOLETA"], correct: 1 },
    { q: "ONDE VIVE O URSO POLAR", options: ["DESERTO", "ÁRTICO", "SELVA", "SAVANA"], correct: 1 },
    { q: "TEM TROMBA", options: ["RINOCERONTE", "HIPOPÓTAMO", "ELEFANTE", "TAPIR"], correct: 2 },
    { q: "ANIMAL COM BOLSA (MARSÚPIO)", options: ["COALA", "CANGURU", "TIGRE", "URSO"], correct: 1 },
    { q: "PESCOÇO MUITO LONGO", options: ["AVESTRUZ", "GIRAFA", "CEGONHA", "SERPENTE"], correct: 1 },
    { q: "ANIMAL QUE MIA", options: ["CÃO", "GATO", "PASSARINHO", "COELHO"], correct: 1 },
    { q: "ANIMAL QUE PRODUZ LEITE", options: ["GALINHA", "VACA", "PEIXE", "COBRA"], correct: 1 },
    { q: "GATO GRANDE COM LISTRAS", options: ["LEÃO", "TIGRE", "LEOPARDO", "PUMA"], correct: 1 },
    { q: "ANIMAL MAIS ALTO", options: ["ELEFANTE", "GIRAFA", "ALCE", "AVESTRUZ"], correct: 1 },
    { q: "ANIMAL QUE DORME EM PÉ", options: ["GATO", "CAVALO", "PORCO", "CACHORRO"], correct: 1 },
    { q: "ANIMAL COM CASCO DURO", options: ["SAPO", "TARTARUGA", "PEIXE", "COELHO"], correct: 1 },
    { q: "MAIOR PRIMATA", options: ["GORILA", "MACACO", "HUMANO", "LÊMURE"], correct: 0 },
    { q: "ANIMAL QUE MUDA DE COR", options: ["LAGARTO", "CAMALEÃO", "COBRA", "RÃ"], correct: 1 },
    { q: "ANIMAL QUE VIVE NO DESERTO", options: ["PINGUIM", "CAMELO", "URSO", "PEIXE"], correct: 1 },
    { q: "QUANTOS BRAÇOS TEM O POLVO", options: ["6", "8", "10", "12"], correct: 1 },
    { q: "MAIOR PEIXE", options: ["TUBARÃO BALEIA", "ORCA", "ATUM", "BALEIA AZUL"], correct: 0 },
    { q: "PEIXE QUE PARECE UM CAVALO", options: ["SARDINHA", "CAVALO MARINHO", "BALEIA", "CARPA"], correct: 1 },
    { q: "NÃO É UM PEIXE", options: ["TUBARÃO", "SALMÃO", "GOLFINHO", "BACALHAU"], correct: 2 },
    { q: "QUANTOS CORAÇÕES TEM O POLVO", options: ["1", "2", "3", "4"], correct: 2 },
    { q: "ANIMAL QUE VIVE NO CORAL", options: ["PEIXE-PALHAÇO", "TUBARÃO", "BALEIA", "LULA"], correct: 0 },
    { q: "MAMÍFERO MARINHO QUE CANTA", options: ["PEIXE", "BALEIA", "CARANGUEJO", "LULA"], correct: 1 },
    { q: "TEM OITO TENTÁCULOS", options: ["PEIXE", "POLVO", "LULA", "ÁGUA-VIVA"], correct: 1 },
    { q: "PEIXE COM DENTES AFIADOS", options: ["SARDINHA", "TUBARÃO", "GOLFINHO", "TILÁPIA"], correct: 1 },
    { q: "ESTRELA DO MAR TEM QUANTAS PONTAS", options: ["3", "4", "5", "6"], correct: 2 },
    { q: "ANIMAL QUE PARECE UMA GELEIA", options: ["POLVO", "ÁGUA-VIVA", "PEIXE", "LULA"], correct: 1 },
    { q: "ONDE VIVE O TUBARÃO", options: ["RIO", "MAR", "LAGO", "PISCINA"], correct: 1 },
    { q: "O GOLFINHO É UM...", options: ["PEIXE", "MAMÍFERO", "RÉPTIL", "ANFÍBIO"], correct: 1 },
    { q: "ANIMAL QUE FAZ PÉROLAS", options: ["PEIXE", "OSTRA", "CARANGUEJO", "POLVO"], correct: 1 },
    { q: "QUAL PEIXE É LARANJA E BRANCO", options: ["TUBARÃO", "PEIXE-PALHAÇO", "ATUM", "SALMÃO"], correct: 1 },
    { q: "O QUE OS PEIXES USAM PARA RESPIRAR", options: ["PULMÕES", "GUELRAS", "PELE", "NARIZ"], correct: 1 },
    { q: "ANIMAL MARINHO MUITO INTELIGENTE", options: ["TUBARÃO", "GOLFINHO", "SARDINHA", "OSTRA"], correct: 1 },
    { q: "QUANTAS PATAS TEM A ARANHA", options: ["4", "6", "8", "10"], correct: 2 },
    { q: "O QUE A ABELHA PRODUZ", options: ["DOCE", "MEL", "LEITE", "SEDA"], correct: 1 },
    { q: "INSETO QUE BRILHA À NOITE", options: ["MOSCA", "VAGA-LUME", "GRILO", "BARATA"], correct: 1 },
    { q: "LAGARTA VIRA O QUÊ", options: ["BESOURO", "BORBOLETA", "FORMIGA", "MOSCA"], correct: 1 },
    { q: "INSETO QUE VIVE EM COLÔNIAS", options: ["GRILO", "FORMIGA", "MOSCA", "ARANHA"], correct: 1 },
    { q: "QUANTAS ASAS TEM A MOSCA", options: ["2", "4", "6", "0"], correct: 0 },
    { q: "INSETO QUE PULA MUITO", options: ["FORMIGA", "GRILO", "BARATA", "LAGARTA"], correct: 1 },
    { q: "PRODUZ SEDA", options: ["ARANHA", "BICHO-DA-SEDA", "FORMIGA", "ABELHA"], correct: 1 },
    { q: "INSETO COM BOLINHAS PRETAS", options: ["MOSCA", "JOANINHA", "GRILO", "BARATA"], correct: 1 },
    { q: "COMO A ABELHA CARREGA POLEN", options: ["BOCA", "PATAS", "ASAS", "ANTENAS"], correct: 1 },
    { q: "QUANTAS PATAS TEM O FORMIGA", options: ["4", "6", "8", "2"], correct: 1 },
    { q: "INSETO QUE SUCGA SANGUE", options: ["MOSCA", "PERNILONGO", "JOANINHA", "GRILO"], correct: 1 },
    { q: "ONDE VIVE A ABELHA", options: ["FORMIGUEIRO", "COLMEIA", "NINHO", "TEIA"], correct: 1 },
    { q: "QUAL INSETO É VERDE E PULA", options: ["BARATA", "GAFANHOTO", "MOSCA", "JOANINHA"], correct: 1 },
    { q: "O QUE A ARANHA FAZ", options: ["MEL", "TEIA", "SEDA", "NINHO"], correct: 1 },
    { q: "INSETO QUE ATACA PLANTAÇÕES", options: ["JOANINHA", "GAFANHOTO", "ABELHA", "BORBOLETA"], correct: 1 },
    { q: "INSETO QUE CARREGA MUITO PESO", options: ["MOSCA", "FORMIGA", "GRILO", "BORBOLETA"], correct: 1 },
    { q: "INSETO QUE CANTA NO VERÃO", options: ["BARATA", "CIGARRA", "FORMIGA", "MOSCA"], correct: 1 },
    { q: "AVE QUE NÃO VOA", options: ["ÁGUIA", "PARDAL", "AVESTRUZ", "POMBO"], correct: 2 },
    { q: "AVE QUE IMITA A FALA", options: ["CORUJA", "PAPAGAIO", "TUCANO", "FALCÃO"], correct: 1 },
    { q: "MAIOR OVO DO MUNDO", options: ["GALINHA", "AVESTRUZ", "ÁGUIA", "DINOSSAURO"], correct: 1 },
    { q: "AVE QUE ENXERGA À NOITE", options: ["PARDAL", "CORUJA", "CANÁRIO", "POMBO"], correct: 1 },
    { q: "COBRA QUE POSSUI CHOCALHO", options: ["NAJA", "CASCAVEL", "CORAL", "JIBOIA"], correct: 1 },
    { q: "RÉPTIL QUE MUDA DE COR", options: ["JACARÉ", "CAMALEÃO", "TARTARUGA", "IGUANA"], correct: 1 },
    { q: "MAIOR COBRA DO MUNDO", options: ["SUCURI", "NAJA", "CORAL", "PITÃO"], correct: 3 },
    { q: "O JACARÉ É UM...", options: ["MAMÍFERO", "RÉPTIL", "PEIXE", "ANFÍBIO"], correct: 1 },
    { q: "AVE QUE É SÍMBOLO DA PAZ", options: ["ÁGUIA", "POMBA", "FALCÃO", "CISNE"], correct: 1 },
    { q: "AVE QUE CAÇA PEIXES", options: ["MARTIM-PESCADOR", "PARDAL", "BEIJA-FLOR", "AVESTRUZ"], correct: 0 },
    { q: "FILHOTE DE GALINHA", options: ["POTRO", "PINTO", "LEITÃO", "BEZERRO"], correct: 1 },
    { q: "AVE DE LONGAS PERNAS ROSAS", options: ["CEGONHA", "FLAMINGO", "PATO", "CISNE"], correct: 1 },
    { q: "RÉPTIL COM CASCO", options: ["COBRA", "JACARÉ", "CÁGADO", "LAGARTO"], correct: 2 },
    { q: "AVE QUE VOA PARA TRÁS", options: ["ÁGUIA", "BEIJA-FLOR", "TUCANO", "URUBU"], correct: 1 },
    { q: "AVE MAIS RÁPIDA NO MERGULHO", options: ["FALCÃO PEREGRINO", "ÁGUIA", "URUBU", "PATO"], correct: 0 },
    { q: "PINGUIM VIVE ONDE", options: ["ÁRTICO", "ANTÁRTIDA", "DESERTO", "SELVA"], correct: 1 },
    { q: "COBRA QUE NÃO TEM VENENO", options: ["CASCAVEL", "JIBOIA", "NAJA", "CORAL"], correct: 1 },
    { q: "AVE QUE DORME NUMA PERNA SÓ", options: ["POMBO", "FLAMINGO", "ÁGUIA", "PARDAL"], correct: 1 },
    { q: "O QUE O TUCANO USA PARA COMER", options: ["DENTES", "BICO", "PATAS", "LÍNGUA"], correct: 1 },
    { q: "PRODUZ OXIGÊNIO", options: ["PEDRA", "PLANTA", "FOGO", "METAL"], correct: 1 },
    { q: "PARTE QUE FICA DEBAIXO DA TERRA", options: ["FOLHA", "FLOR", "RAIZ", "FRUTO"], correct: 2 },
    { q: "PLANTA QUE VIVE NO DESERTO", options: ["ROSA", "CACTO", "SAMAMBAIA", "PINHEIRO"], correct: 1 },
    { q: "PARTE QUE FAZ A FOTOSSÍNTESE", options: ["RAIZ", "FOLHA", "TRONCO", "SEMENTE"], correct: 1 },
    { q: "ÁRVORE QUE DÁ MAÇÃ", options: ["PEREIRA", "MACIEIRA", "LARANJEIRA", "LIMOEIRO"], correct: 1 },
    { q: "PLANTA QUE COME INSETOS", options: ["ROSA", "CARNÍVORA", "CACTO", "GIRASSOL"], correct: 1 },
    { q: "A MADEIRA VEM DE ONDE", options: ["NUVENS", "ÁRVORES", "MINAS", "MAR"], correct: 1 },
    { q: "COR DA CLOROFILA", options: ["AZUL", "VERDE", "VERMELHO", "AMARELO"], correct: 1 },
    { q: "FLOR QUE SEGUE O SOL", options: ["MARGARIDA", "GIRASSOL", "ROSA", "ORQUÍDEA"], correct: 1 },
    { q: "O QUE NASCE DA SEMENTE", options: ["PEDRA", "PLANTA", "ÁGUA", "TERRA"], correct: 1 },
    { q: "CONJUNTO DE ÁRVORES", options: ["FLORESTA", "REBANHO", "CARDUME", "NINHO"], correct: 0 },
    { q: "FRUTA AMARELA E COMPRIDA", options: ["MAÇÃ", "BANANA", "UVA", "MORANGO"], correct: 1 },
    { q: "ÁRVORE DE NATAL TRADICIONAL", options: ["PALMEIRA", "PINHEIRO", "CARVALHO", "OLIVEIRA"], correct: 1 },
    { q: "FLOR COM ESPINHOS NO CAULE", options: ["LÍRIO", "ROSA", "TULIPA", "VIOLETA"], correct: 1 },
    { q: "ESTAÇÃO DAS FLORES", options: ["VERÃO", "INVERNO", "PRIMAVERA", "OUTONO"], correct: 2 },
    { q: "PLANTA QUE DÁ UVA", options: ["VIDEIRA", "MACIEIRA", "BANANEIRA", "PEREIRA"], correct: 0 },
    { q: "O QUE A PLANTA PRECISA PARA CRESCER", options: ["LEITE", "ÁGUA", "SUCO", "CAFÉ"], correct: 1 },
    { q: "ONDE FICA A SEMENTE", options: ["DENTRO DO FRUTO", "NA FOLHA", "NA RAIZ", "NO AR"], correct: 0 },
    { q: "PRODUZ AZEITONAS", options: ["PINHEIRO", "OLIVEIRA", "SOBREIRO", "MACIEIRA"], correct: 1 },
    { q: "PLANTA QUE NÃO TEM TRONCO", options: ["ERVA", "ÁRVORE", "ARBUSTO", "PALMEIRA"], correct: 0 },
    { q: "ÁGUA QUE CAI DO CÉU", options: ["NEVE", "CHUVA", "RAIO", "NUVEM"], correct: 1 },
    { q: "ESTRELA QUE AQUECE A TERRA", options: ["LUA", "SOL", "MARTE", "VÉNUS"], correct: 1 },
    { q: "FENÔMENO DE SETE CORES", options: ["RAIO", "ARCO-ÍRIS", "TROVÃO", "VENTO"], correct: 1 },
    { q: "GELO QUE CAI DAS NUVENS", options: ["ORVALHO", "GRANIZO", "NEBLINA", "CHUVA"], correct: 1 },
    { q: "BARULHO QUE VEM DEPOIS DO RAIO", options: ["VENTO", "TROVÃO", "CHUVA", "ECO"], correct: 1 },
    { q: "MOVIMENTO DO AR", options: ["CALOR", "VENTO", "FRIO", "LUZ"], correct: 1 },
    { q: "ÁGUA NO ESTADO SÓLIDO", options: ["VAPOR", "GELO", "LÍQUIDO", "QUENTE"], correct: 1 },
    { q: "ESTAÇÃO MAIS QUENTE", options: ["INVERNO", "VERÃO", "OUTONO", "PRIMAVERA"], correct: 1 },
    { q: "ESTAÇÃO QUE AS FOLHAS CAEM", options: ["VERÃO", "PRIMAVERA", "OUTONO", "INVERNO"], correct: 2 },
    { q: "GRANDE MASSA DE ÁGUA SALGADA", options: ["RIO", "OCEANO", "LAGO", "PISCINA"], correct: 1 },
    { q: "MONTANHA QUE SOLTA FOGO", options: ["CAVERNA", "VULCÃO", "VALE", "PICO"], correct: 1 },
    { q: "TREMOR DA TERRA", options: ["VENTANIA", "TERREMOTO", "TSUNAMI", "TORNADO"], correct: 1 },
    { q: "ONDE O SOL NASCE", options: ["NORTE", "LESTE", "OESTE", "SUL"], correct: 1 },
    { q: "LUGAR COM MUITA AREIA E POUCA ÁGUA", options: ["SELVA", "DESERTO", "PANTANAL", "ILHA"], correct: 1 },
    { q: "SATÉLITE NATURAL DA TERRA", options: ["SOL", "LUA", "MARTE", "SATURNO"], correct: 1 },
    { q: "GÁS QUE NÓS RESPIRAMOS", options: ["HIDROGÊNIO", "OXIGÊNIO", "HÉLIO", "NEÔNIO"], correct: 1 },
    { q: "NUVEM QUE TOCA O CHÃO", options: ["CHUVA", "NEBLINA", "FUMAÇA", "RAIO"], correct: 1 },
    { q: "PROTEGE A TERRA DO SOL", options: ["CAMADA DE OZÔNIO", "NUVENS", "LUA", "ESTRELAS"], correct: 0 },
    { q: "ÁGUA QUE NÃO É SALGADA", options: ["MAR", "DOCE", "AMARGA", "AZEDA"], correct: 1 },
    { q: "FENÔMENO QUE GIRA MUITO RÁPIDO", options: ["TERREMOTO", "TORNADO", "ENCENTE", "SECA"], correct: 1 },
    { q: "ANIMAL QUE NÃO POSSUI CÉREBRO", options: ["POLVO", "ÁGUA-VIVA", "TUBARÃO", "TARTARUGA"], correct: 1 },
    { q: "QUANTOS ESTÔMAGOS TEM A VACA", options: ["UM", "DOIS", "TRÊS", "QUATRO"], correct: 3 },
    { q: "ANIMAL QUE TEM A MAIOR LÍNGUA", options: ["CAMALEÃO", "TAMANDUÁ", "GIRAFA", "SAPO"], correct: 1 },
    { q: "QUAL O ÚNICO ANIMAL QUE NÃO PULA", options: ["RINOCERONTE", "ELEFANTE", "HIPOPÓTAMO", "ZEBRA"], correct: 1 },
    { q: "O QUE O MORCEGO USA PARA SE GUIAR", options: ["VISÃO", "OLFATO", "ECO", "TATO"], correct: 2 },
    { q: "ANIMAL QUE PODE DORMIR 3 ANOS", options: ["URSO", "CARACOL", "TARTARUGA", "COBRA"], correct: 1 },
    { q: "O SANGUE DO GAFANHOTO É...", options: ["VERMELHO", "VERDE", "AZUL", "BRANCO"], correct: 1 },
    { q: "QUAL AVE TEM O OLHO MAIOR QUE O CÉREBRO", options: ["ÁGUIA", "AVESTRUZ", "CORUJA", "TUCANO"], correct: 1 },
    { q: "QUANTOS DENTES TEM UM MOSQUITO", options: ["ZERO", "DEZ", "QUARENTA E SETE", "CEM"], correct: 2 },
    { q: "ANIMAL QUE TRANSPIRAR PELAS PATAS", options: ["CACHORRO", "GATO", "COELHO", "PORCO"], correct: 0 },
    { q: "O QUE O ESCORPIÃO É", options: ["INSETO", "ARACNÍDEO", "RÉPTIL", "ANFÍBIO"], correct: 1 },
    { q: "ANIMAL QUE PODE VIVER SEM CABEÇA", options: ["FORMIGA", "BARATA", "GRILO", "MOSCA"], correct: 1 },
    { q: "ANIMAL QUE TEM A MORDIDA MAIS FORTE", options: ["LEÃO", "TUBARÃO", "CROCODILO", "HIPOPÓTAMO"], correct: 2 },
    { q: "QUAL O ANIMAL MAIS BARULHENTO", options: ["LEÃO", "BALEIA AZUL", "MACACO", "ELEFANTE"], correct: 1 },
    { q: "CÃO É DESCENDENTE DE QUAL ANIMAL", options: ["RAPOSA", "LOBO", "COIOTE", "Hiena"], correct: 1 },
    { q: "QUAL ANIMAL É UM PAQUIDERME", options: ["GIRAFA", "ELEFANTE", "ZEBRA", "LEÃO"], correct: 1 },
    { q: "ANIMAL QUE VIVE MAIS TEMPO", options: ["BALEIA", "TARTARUGA GIGANTE", "ELEFANTE", "HUMANO"], correct: 1 },
    { q: "COMO O CANGURU USA A CAUDA", options: ["EQUILÍBRIO", "ATAQUE", "DEFESA", "NADA"], correct: 0 },
    { q: "O QUE O URSO COME NO INVERNO", options: ["PEIXE", "MEL", "NADA (DORME)", "FRUTAS"], correct: 2 },
    { q: "ÁRVORE QUE PRODUZ CORTIÇA", options: ["PINHEIRO", "SOBREIRO", "CARVALHO", "EUCALIPTO"], correct: 1 },
    { q: "PARTE DA PLANTA QUE ATRAI ABELHAS", options: ["RAIZ", "FOLHA", "FLOR", "CAULE"], correct: 2 },
    { q: "PROCESSO DE ALIMENTAÇÃO DA PLANTA", options: ["FOTOSSÍNTESE", "RESPIRAÇÃO", "DIGESTÃO", "ABSORÇÃO"], correct: 0 },
    { q: "MAIOR FLORESTA DO MUNDO", options: ["AFRICANA", "AMAZÔNICA", "EUROPEIA", "ASIÁTICA"], correct: 1 },
    { q: "O QUE É O TOMATE", options: ["LEGUME", "FRUTA", "VERDURA", "RAIZ"], correct: 1 },
    { q: "PLANTA QUE DÁ CACAU", options: ["CACAUEIRO", "COQUEIRO", "PALMEIRA", "VIDEIRA"], correct: 0 },
    { q: "O QUE PROTEGE A SEMENTE", options: ["CASCA", "FRUTO", "FOLHA", "FLOR"], correct: 1 },
    { q: "COR DA SEIVA NA MAIORIA DAS VEZES", options: ["VERMELHA", "BRANCA/TRANSPARENTE", "AZUL", "PRETA"], correct: 1 },
    { q: "ESTRUTURA QUE FIXA A PLANTA", options: ["TRONCO", "RAIZ", "GALHO", "FOLHA"], correct: 1 },
    { q: "PLANTA QUE DÁ ALGODÃO", options: ["ALGODOEIRO", "LINHO", "TRIGO", "SOJA"], correct: 0 },
    { q: "A CEBOLA CRESCE ONDE", options: ["NO GALHO", "NA TERRA", "NA FLOR", "NA ÁGUA"], correct: 1 },
    { q: "O QUE É UM CONJUNTO DE FLORES", options: ["BUQUÊ", "FLORESTA", "POMAR", "HORTA"], correct: 0 },
    { q: "ÁRVORE QUE PRODUZ BORRACHA", options: ["PINHEIRO", "SERINGUEIRA", "CARVALHO", "MOGNO"], correct: 1 },
    { q: "FRUTA QUE TEM A SEMENTE POR FORA", options: ["MAÇÃ", "MORANGO", "UVA", "PERA"], correct: 1 },
    { q: "PARTE QUE ABSORVE LUZ SOLAR", options: ["RAIZ", "FOLHA", "FRUTO", "SEMENTE"], correct: 1 },
    { q: "QUAL PLANTA NÃO PRECISA DE TERRA", options: ["ROSA", "ORQUÍDEA (ALGUMAS)", "SAMAMBAIA", "CACTO"], correct: 1 },
    { q: "FRUTA COM MUITA VITAMINA C", options: ["BANANA", "LARANJA", "MELÃO", "PERA"], correct: 1 },
    { q: "PLANTA TÍPICA DO NATAL", options: ["PINHEIRO", "PALMEIRA", "CACTO", "BAMBU"], correct: 0 },
    { q: "O QUE NASCE NA VIDEIRA", options: ["MAÇÃ", "UVA", "BANANA", "LIMÃO"], correct: 1 },
    { q: "CIÊNCIA QUE ESTUDA AS PLANTAS", options: ["ZOOLOGIA", "BOTÂNICA", "BIOLOGIA", "GEOLOGIA"], correct: 1 },
    { q: "SALINIDADE DO MAR VEM DE ONDE", options: ["PEIXES", "ROCHAS/TERRA", "CHUVAS", "SOL"], correct: 1 },
    { q: "MAIOR OCEANO DO PLANETA", options: ["ATLÂNTICO", "PACÍFICO", "ÍNDICO", "ÁRTICO"], correct: 1 },
    { q: "QUAL A COR DO MAR", options: ["REFLEXO DO CÉU", "AZUL NATURAL", "VERDE", "BRANCO"], correct: 0 },
    { q: "MARÉ É CAUSADA POR QUÊ", options: ["VENTO", "LUA", "PEIXES", "NAVIO"], correct: 1 },
    { q: "ÁGUA QUE NÃO SE MOVE", options: ["RIO", "MAR", "LAGOA", "CASCATA"], correct: 2 },
    { q: "O QUE É O TSUNAMI", options: ["VENTO FORTE", "ONDA GIGANTE", "CHUVA", "NEVE"], correct: 1 },
    { q: "ONDE TERMINA O RIO", options: ["NASCENTE", "FOZ", "MEIO", "MONTANHA"], correct: 1 },
    { q: "GÁS ESSENCIAL NA ÁGUA PARA PEIXES", options: ["HIDROGÊNIO", "OXIGÊNIO", "GÁS CARBÔNICO", "METANO"], correct: 1 },
    { q: "O QUE É UM ICEBERG", options: ["PEDRA", "GELO FLUTUANTE", "ILHA", "NUVEM"], correct: 1 },
    { q: "VENTO MUITO FORTE E CIRCULAR", options: ["BRISA", "FURACÃO", "CHUVA", "NEBLINA"], correct: 1 },
    { q: "QUAL O DESERTO MAIS FRIO", options: ["SAARA", "ANTÁRTIDA", "GOBI", "ATACAMA"], correct: 1 },
    { q: "LUZ QUE RISCA O CÉU NA TEMPESTADE", options: ["TROVÃO", "RAIO", "ESTRELA", "COMETA"], correct: 1 },
    { q: "ESTADO DA ÁGUA NAS NUVENS", options: ["SÓLIDO", "VAPOR", "LÍQUIDO", "TODOS"], correct: 3 },
    { q: "CAMADA QUE NOS PROTEGE DO SOL", options: ["OZÔNIO", "OXIGÊNIO", "NUVEM", "POLUIÇÃO"], correct: 0 },
    { q: "O QUE CAUSA O DIA E A NOITE", options: ["TRANSLAÇÃO", "ROTAÇÃO", "ECLIPSE", "VENTO"], correct: 1 },
    { q: "TEMPO NECESSÁRIO PARA ROTAÇÃO", options: ["12 HORAS", "24 HORAS", "30 DIAS", "1 ANO"], correct: 1 },
    { q: "PLANETA MAIS PRÓXIMO DO SOL", options: ["TERRA", "MERCÚRIO", "MARTE", "VÉNUS"], correct: 1 },
    { q: "PONTO MAIS ALTO DA TERRA", options: ["EVEREST", "ANDES", "ALPES", "PICO DA NEBLINA"], correct: 0 },
    { q: "FENÔMENO DAS LUZES NO NORTE", options: ["ARCO-ÍRIS", "AURORA BOREAL", "ECLIPSE", "COMETA"], correct: 1 },
    { q: "CIÊNCIA QUE ESTUDA O CLIMA", options: ["GEOLOGIA", "METEOROLOGIA", "BIOLOGIA", "FÍSICA"], correct: 1 },
    { q: "QUAL O ANIMAL MAIS PESADO DA TERRA", options: ["ELEFANTE", "RINOCERONTE", "BALEIA AZUL", "HIPOPÓTAMO"], correct: 2 },
    { q: "QUANTOS QUILOS DE COMIDA UM ELEFANTE COME/DIA", options: ["10KG", "50KG", "150KG", "500KG"], correct: 2 },
    { q: "QUAL PÁSSARO CONSEGUE VOAR PARADO", options: ["ÁGUIA", "BEIJA-FLOR", "POMBO", "FALCÃO"], correct: 1 },
    { q: "ANIMAL QUE TEM A LÍNGUA AZUL", options: ["GIRAFA", "LEÃO", "URSO", "LAGARTO SCINCO"], correct: 3 },
    { q: "QUAL ANIMAL NÃO TEM CORDAS VOCAIS", options: ["GIRAFA", "Zebra", "COELHO", "COBRA"], correct: 0 },
    { q: "ANIMAL QUE MAIS DORME NO MUNDO", options: ["PREGUIÇA", "COALA", "GATO", "LEÃO"], correct: 1 },
    { q: "QUANTAS HORAS O COALA DORME POR DIA", options: ["10H", "15H", "22H", "12H"], correct: 2 },
    { q: "QUAL O ÚNICO MAMÍFERO QUE VOA", options: ["MORCEGO", "ESQUILO-VOADOR", "ÁGUIA", "PATO"], correct: 0 },
    { q: "ANIMAL QUE SE REPRODUZ POR CLONAGEM", options: ["ABELHA", "ESTRELA DO MAR", "SAPO", "PEIXE"], correct: 1 },
    { q: "QUANTOS NARIZES TEM UMA LESMA", options: ["UM", "DOIS", "QUATRO", "ZERO"], correct: 2 },
    { q: "QUAL O ANIMAL MAIS FORTE (PROPORCIONAL)", options: ["FORMIGA", "BESOURO ROLIÇO", "GORILA", "ELEFANTE"], correct: 1 },
    { q: "QUAL ANIMAL CONSEGUE VER ATRÁS DE SI", options: ["COELHO", "GATO", "CACHORRO", "LEÃO"], correct: 0 },
    { q: "COR DA PELE DO URSO POLAR", options: ["BRANCA", "PRETA", "ROSA", "CINZA"], correct: 1 },
    { q: "O QUE OS TUBARÕES NÃO TÊM NO CORPO", options: ["SANGUE", "OSSOS", "DENTES", "MÚSCULOS"], correct: 1 },
    { q: "QUAL ANIMAL VIVE NO DESERTO E GUARDA ÁGUA", options: ["COBRA", "CAMELO", "ESCORPIÃO", "LAGARTO"], correct: 1 },
    { q: "QUANTAS PÁLPEBRAS TEM UM CAMELO", options: ["UMA", "DUAS", "TRÊS", "QUATRO"], correct: 2 },
    { q: "ANIMAL QUE TEM IMPRESSÃO DIGITAL IGUAL À HUMANA", options: ["MACACO", "COALA", "CÃO", "PORCO"], correct: 1 },
    { q: "QUAL O ANIMAL MAIS VENENOSO DO MUNDO", options: ["COBRA", "ARANHA", "VESPA-DO-MAR", "ESCORPIÃO"], correct: 2 },
    { q: "ANIMAL QUE PRODUZ PÉROLAS", options: ["OSTRA", "CARANGUEJO", "PEIXE", "POLVO"], correct: 0 },
    { q: "QUAL ANIMAL É UM CANÍDEO", options: ["GATO", "LOBO", "LEÃO", "TIGRE"], correct: 1 },
    { q: "QUAL ÁRVORE É A MAIOR DO MUNDO", options: ["CARVALHO", "SEQUOIA", "PINHEIRO", "EUCALIPTO"], correct: 1 },
    { q: "QUAL O NOME DA FLORESTA DO BRASIL", options: ["SAARA", "AMAZÔNIA", "SAVANA", "TAIGA"], correct: 1 },
    { q: "AS PLANTAS LIBERAM QUAL GÁS À NOITE", options: ["OXIGÊNIO", "GÁS CARBÔNICO", "HIDROGÊNIO", "NITROGÊNIO"], correct: 1 },
    { q: "COMO SE CHAMA O CAULE DA PALMEIRA", options: ["TRONCO", "ESTIPE", "HASTE", "COLMO"], correct: 1 },
    { q: "QUAL PLANTA É USADA PARA FAZER PAPEL", options: ["EUCALIPTO", "ROSA", "MILHO", "FEIJÃO"], correct: 0 },
    { q: "QUAL O NOME DA PARTE MASCULINA DA FLOR", options: ["PÁTALA", "ESTAME", "PISTILO", "SÉPALA"], correct: 1 },
    { q: "PLANTA QUE DÁ FLOR MAS NÃO FRUTO", options: ["GIMNOSPERMA", "ANGIOSPERMA", "BRIÓFITA", "PTERIDÓFITA"], correct: 0 },
    { q: "COMO SE CHAMA O FRUTO DO PINHEIRO", options: ["MAÇÃ", "PINHA", "UVA", "NOZ"], correct: 1 },
    { q: "QUAL A MAIOR FLOR DO MUNDO", options: ["GIRASSOL", "RAFLÉSIA", "ROSA", "LÍRIO"], correct: 1 },
    { q: "QUAL PLANTA DÁ O CAFÉ", options: ["CAFEEIRO", "VIDEIRA", "SOJA", "TRIGO"], correct: 0 },
    { q: "AS PLANTAS SÃO SERES...", options: ["AUTÓTROFOS", "HETERÓTROFOS", "CARNÍVOROS", "FUNGOS"], correct: 0 },
    { q: "QUAL O NOME DO LÍQUIDO DAS PLANTAS", options: ["SANGUE", "SEIVA", "ÁGUA", "MEL"], correct: 1 },
    { q: "QUAL FRUTA TEM MAIS POTÁSSIO", options: ["MAÇÃ", "BANANA", "MELANCIA", "MORANGO"], correct: 1 },
    { q: "A MANDIOCA É O QUE DA PLANTA", options: ["FRUTO", "RAIZ", "FOLHA", "CAULE"], correct: 1 },
    { q: "O QUE AS PLANTAS PRECISAM PARA FOTOSSÍNTESE", options: ["SOL", "LUA", "VENTO", "FOGO"], correct: 0 },
    { q: "QUAL PLANTA DÁ AZEITE", options: ["MACIEIRA", "OLIVEIRA", "LARANJEIRA", "PARREIRA"], correct: 1 },
    { q: "A BATATA NASCE ONDE", options: ["EM CIMA", "EMBAIXO DA TERRA", "NA FLOR", "NO GALHO"], correct: 1 },
    { q: "QUAL O NOME DA CIÊNCIA DAS PLANTAS", options: ["ZOOLOGIA", "BOTÂNICA", "METEOROLOGIA", "FÍSICA"], correct: 1 },
    { q: "AS FOLHAS CAEM EM QUAL ESTAÇÃO", options: ["VERÃO", "INVERNO", "OUTONO", "PRIMAVERA"], correct: 2 },
    { q: "QUAL PLANTA É UM SÍMBOLO DO DESERTO", options: ["ROSA", "CACTO", "PINHEIRO", "ALGA"], correct: 1 },
    { q: "QUANTAS PATAS TEM UMA FORMIGA", options: ["4", "6", "8", "10"], correct: 1 },
    { q: "QUAL INSETO PRODUZ MEL", options: ["FORMIGA", "ABELHA", "VESPA", "MOSCA"], correct: 1 },
    { q: "O QUE O BICHO-DA-SEDA PRODUZ", options: ["LÃ", "SEDA", "ALGODÃO", "LINHO"], correct: 1 },
    { q: "QUAL INSETO VIVE MAIS TEMPO", options: ["MOSCA", "CIGARRA", "CUPIM (RAINHA)", "GRILO"], correct: 2 },
    { q: "QUANTOS OLHOS TEM UMA ABELHA", options: ["2", "3", "5", "10"], correct: 2 },
    { q: "QUANTAS ASAS TEM UMA BORBOLETA", options: ["2", "4", "6", "8"], correct: 1 },
    { q: "QUAL INSETO É CONHECIDO POR PULAR", options: ["BARATA", "GAFANHOTO", "MOSCA", "ABELHA"], correct: 1 },
    { q: "COMO A FORMIGA SE COMUNICA", options: ["SOM", "ANTENAS", "GRITO", "DANÇA"], correct: 1 },
    { q: "QUAL O ALIMENTO DA JOANINHA", options: ["FOLHAS", "PULGÕES", "MEL", "AÇÚCAR"], correct: 1 },
    { q: "O QUE O ESCORPIÃO TEM NA CAUDA", options: ["FERRÃO", "PATA", "BOCA", "OLHO"], correct: 0 },
    { q: "QUANTAS PATAS TEM O CARANGUEJO", options: ["6", "8", "10", "12"], correct: 2 },
    { q: "A LACRAIA É UM...", options: ["INSETO", "QUILÓPODE", "ARACNÍDEO", "MAMÍFERO"], correct: 1 },
    { q: "ONDE AS FORMIGAS VIVEM", options: ["COLMEIA", "FORMIGUEIRO", "NINHO", "TEIA"], correct: 1 },
    { q: "QUAL INSETO BRILHA NO ESCURO", options: ["GRILO", "VAGA-LUME", "MOSCA", "BARATA"], correct: 1 },
    { q: "O QUE A MOSCA GOSTA DE COMER", options: ["SANGUE", "MATÉRIA ORGÂNICA", "MADEIRA", "METAL"], correct: 1 },
    { q: "QUANTAS ANTENAS TEM UMA BORBOLETA", options: ["UMA", "DUAS", "QUATRO", "ZERO"], correct: 1 },
    { q: "O GRILO FAZ O SOM COM O QUÊ", options: ["BOCA", "ASAS", "PATAS", "NARIZ"], correct: 1 },
    { q: "A ARANHA FAZ O QUÊ PARA CAÇAR", options: ["BURACO", "TEIA", "NINHO", "BARULHO"], correct: 1 },
    { q: "QUAL INSETO TRANSMITE MALÁRIA", options: ["MOSCA", "MOSQUITO", "BARATA", "ABELHA"], correct: 1 },
    { q: "COMO SE CHAMA O MAGMA QUE SAI DO VULCÃO", options: ["FOGO", "LAVA", "PEDRA", "CINZA"], correct: 1 },
    { q: "QUAL A ROCHA MAIS DURA DA NATUREZA", options: ["GRANITO", "DIAMANTE", "MÁRMORE", "FERRO"], correct: 1 },
    { q: "CONJUNTO DE MONTANHAS", options: ["VALE", "CORDILLHEIRA", "PLANÍCIE", "ILHA"], correct: 1 },
    { q: "A AREIA VEM DE ONDE", options: ["ÁGUA", "DESGASTE DE ROCHAS", "NUVENS", "TERRA"], correct: 1 },
    { q: "LUGAR ONDE O RIO COMEÇA", options: ["FOZ", "NASCENTE", "LEITO", "MAR"], correct: 1 },
    { q: "PONTO MAIS PROFUNDO DO OCEANO", options: ["FOSSA DAS MARIANAS", "ABISMO", "CANAL", "VALE"], correct: 0 },
    { q: "ILHA FORMADA POR CORAIS", options: ["ARQUIPÉLAGO", "ATOL", "CONTINENTE", "DELTA"], correct: 1 },
    { q: "O QUE CAUSA A EROSÃO", options: ["VENTO E ÁGUA", "SOL", "PEIXES", "FOGO"], correct: 0 },
    { q: "QUAL O METAL LÍQUIDO NA NATUREZA", options: ["OURO", "MERCÚRIO", "PRATA", "COBRE"], correct: 1 },
    { q: "PEDRA QUE VEM DO ESPAÇO", options: ["COMETA", "METEORITO", "ESTRELA", "LUA"], correct: 1 },
    { q: "COMO SE FORMAM OS FÓSSEIS", options: ["FOGO", "SEDIMENTAÇÃO", "VENTO", "CALOR"], correct: 1 },
    { q: "QUAL O MAIOR CONTINENTE", options: ["AMÉRICA", "ÁSIA", "ÁFRICA", "EUROPA"], correct: 1 },
    { q: "CAMADA MAIS INTERNA DA TERRA", options: ["CROSTA", "MANTO", "NÚCLEO", "OZÔNIO"], correct: 2 },
    { q: "O QUE É UMA ESTALACTITE", options: ["PLANTA", "ROCHA NO TETO", "PEIXE", "NUVEM"], correct: 1 },
    { q: "QUAL O NOME DA TERRA FÉRTIL", options: ["AREIA", "HUMUS", "ARGILA", "PEDREGULHO"], correct: 1 },
    { q: "ONDE SE LOCALIZA O EVEREST", options: ["ANDES", "HIMALAIA", "ALPES", "PIRINEUS"], correct: 1 },
    { q: "O QUE É UM ARQUIPÉLAGO", options: ["MONTANHA", "GRUPO DE ILHAS", "RIO", "LAGO"], correct: 1 },
    { q: "ROCHA FORMADA POR VULCÕES", options: ["MAGMÁTICA", "SEDIMENTAR", "METAMÓRFICA", "CALCÁRIA"], correct: 0 },
    { q: "QUAL O MAIOR RIO DO MUNDO", options: ["NILO", "AMAZONAS", "MISSISSIPPI", "CONGO"], correct: 1 },
    { q: "LAGO DE ÁGUA SALGADA", options: ["MAR MORTO", "LAGOA AZUL", "PANTANAL", "RIO DOCE"], correct: 0 },
    { q: "QUAL O MAIOR ÓRGÃO DO CORPO", options: ["FÍGADO", "PELE", "PULMÃO", "CÉREBRO"], correct: 1 },
    { q: "QUANTOS OSSOS TEM UM ADULTO", options: ["106", "206", "306", "50"], correct: 1 },
    { q: "QUAL O OSSO MAIS LONGO", options: ["RÁDIO", "FÊMUR", "COSTELA", "CRÂNIO"], correct: 1 },
    { q: "ÓRGÃO QUE BOMBEIA SANGUE", options: ["PULMÃO", "CORAÇÃO", "ESTÔMAGO", "RINS"], correct: 1 },
    { q: "GÁS QUE EXPULSAMOS AO RESPIRAR", options: ["OXIGÊNIO", "GÁS CARBÔNICO", "NITROGÊNIO", "HÉLIO"], correct: 1 },
    { q: "QUANTOS SENTIDOS NÓS TEMOS", options: ["3", "4", "5", "6"], correct: 2 },
    { q: "QUAL SENTIDO USA O NARIZ", options: ["VISÃO", "OLFATO", "TATO", "PALADAR"], correct: 1 },
    { q: "LÍQUIDO QUE AJUDA A DIGESTÃO", options: ["SANGUE", "SALIVA", "SUCO GÁSTRICO", "ÁGUA"], correct: 2 },
    { q: "ONDE FICA O LABIRINTO", options: ["NARIZ", "OUVIDO", "BOCA", "OLHO"], correct: 1 },
    { q: "QUAL O PRINCIPAL MÚSCULO DA RESPIRAÇÃO", options: ["BÍCEPS", "DIAFRAGMA", "CORAÇÃO", "LÍNGUA"], correct: 1 },
    { q: "QUANTOS DENTES TEM UM ADULTO", options: ["20", "28", "32", "40"], correct: 2 },
    { q: "QUAL A PARTE COLORIDA DO OLHO", options: ["PUPILA", "ÍRIS", "CÓRNEA", "RETINA"], correct: 1 },
    { q: "ONDE SE PRODUZ A INSULINA", options: ["FÍGADO", "PÂNCREAS", "RINS", "BAÇO"], correct: 1 },
    { q: "QUAL O NOME DO 'ESTÔMAGO' DAS AVES", options: ["PAPO", "MOELA", "ESTÔMAGO", "INTESTINO"], correct: 1 },
    { q: "O QUE OS GLÓBULOS VERMELHOS TRANSPORTAM", options: ["COMIDA", "OXIGÊNIO", "GORDURA", "ÁGUA"], correct: 1 },
    { q: "QUAL O ÓRGÃO DA VISÃO", options: ["ORELHA", "OLHO", "MÃO", "NARIZ"], correct: 1 },
    { q: "QUAL O NOME DA UNIÃO DOS OSSOS", options: ["MÚSCULO", "ARTICULAÇÃO", "PELE", "NERVO"], correct: 1 },
    { q: "SISTEMA QUE COMBATE DOENÇAS", options: ["DIGESTIVO", "IMUNE", "NERVOSO", "SOLAR"], correct: 1 },
    { q: "PRINCIPAL ÓRGÃO DO PENSAMENTO", options: ["CORAÇÃO", "CÉREBRO", "PULMÃO", "FÍGADO"], correct: 1 },
    { q: "FLORESTA QUE FICA NA ÁGUA", options: ["SAVANA", "MANGUEZAL", "DESERTO", "TAIGA"], correct: 1 },
    { q: "LUGAR COM GELO O ANO TODO", options: ["SELVA", "CALOTA POLAR", "SAVANA", "PRADARIA"], correct: 1 },
    { q: "O QUE É O DESMATAMENTO", options: ["PLANTAR ÁRVORES", "CORTAR ÁRVORES", "LIMPAR RIOS", "CAÇAR"], correct: 1 },
    { q: "CONJUNTO DE SERES E AMBIENTE", options: ["POVOAÇÃO", "ECOSSISTEMA", "CIDADE", "FLORESTA"], correct: 1 },
    { q: "O QUE CAUSA O AQUECIMENTO GLOBAL", options: ["POLUIÇÃO", "PLANTIO", "CHUVA", "VENTO"], correct: 0 },
    { q: "ENERGA QUE VEM DO SOL", options: ["EÓLICA", "SOLAR", "HIDRÁULICA", "NUCLEAR"], correct: 1 },
    { q: "ENERGIA QUE VEM DO VENTO", options: ["SOLAR", "EÓLICA", "TÉRMICA", "FÓSSIL"], correct: 1 },
    { q: "ANIMAL QUE AJUDA A POLINIZAR", options: ["BARATA", "ABELHA", "MOSCA", "FORMIGA"], correct: 1 },
    { q: "O QUE É RECICLAGEM", options: ["JOGAR FORA", "REUTILIZAR", "QUEIMAR", "ESCONDER"], correct: 1 },
    { q: "QUAL GÁS CAUSA O EFEITO ESTUFA", options: ["OXIGÊNIO", "CO2", "HÉLIO", "ARGÔNIO"], correct: 1 },
    { q: "O QUE É BIODIVERSIDADE", options: ["UMA ESPÉCIE", "VÁRIAS ESPÉCIES", "SOLO", "CLIMA"], correct: 1 },
    { q: "QUAL A FUNÇÃO DA CAMADA DE OZÔNIO", options: ["TRAZER CHUVA", "FILTRAR RAIOS UV", "DAR VENTO", "ILUMINAR"], correct: 1 },
    { q: "O QUE É UMA ESPÉCIE EM EXTINÇÃO", options: ["QUE SOBROU MUITO", "QUE PODE ACABAR", "QUE JÁ ACABOU", "NOVA"], correct: 1 },
    { q: "QUAL A MAIOR AMEAÇA AOS OCEANOS", options: ["PEIXES", "PLÁSTICO", "AREIA", "BARCOS"], correct: 1 },
    { q: "O QUE É REFLORESTAMENTO", options: ["CORTAR", "PLANTAR NOVAS ÁRVORES", "QUEIMAR", "LIMPAR"], correct: 1 },
    { q: "ESTADO DA ÁGUA NO VAPOR", options: ["SÓLIDO", "LÍQUIDO", "GASOSO", "FRIO"], correct: 2 },
    { q: "QUANTAS ASAS TEM UMA LIBÉLULA", options: ["DUAS", "QUATRO", "SEIS", "OITO"], correct: 1 },
    { q: "QUAL O ANIMAL MAIS LENTO DO MUNDO", options: ["TARTARUGA", "PREGUIÇA", "CARACOL", "COALA"], correct: 1 },
    { q: "QUAL ANIMAL CONSEGUE FICAR MAIS TEMPO SEM ÁGUA", options: ["CAMELO", "RATO-CANGURU", "ELEFANTE", "COBRA"], correct: 1 },
    { q: "ANIMAL QUE TEM A LÍNGUA MAIOR QUE O CORPO", options: ["SAPO", "CAMALEÃO", "TAMANDUÁ", "LAGARTO"], correct: 1 },
    { q: "QUANTAS PATAS TEM UMA CENTOPEIA", options: ["10", "100", "PODE VARIAR", "50"], correct: 2 },
    { q: "O QUE O POLVO SOLTA PARA FUGIR", options: ["ÁGUA", "TINTA", "AREIA", "BOLHAS"], correct: 1 },
    { q: "QUAL O MAIOR ANIMAL TERRESTRE", options: ["GIRAFA", "ELEFANTE AFRICANO", "RINOCERONTE", "URSO"], correct: 1 },
    { q: "ANIMAL QUE TEM A PELE TOTALMENTE LISTRADA", options: ["TIGRE", "ZEBRA", "LEOPARDO", "GIRAFA"], correct: 1 },
    { q: "COMO A ZEBRA É", options: ["PRETA COM LISTRAS BRANCAS", "BRANCA COM LISTRAS PRETAS", "MARROM", "CINZA"], correct: 0 },
    { q: "QUAL ANIMAL É UM 'FÓSSIL VIVO'", options: ["TUBARÃO", "CELACANTO", "TARTARUGA", "CROCODILO"], correct: 1 },
    { q: "QUANTAS CAMADAS DE PELE TEM O GOLFINHO", options: ["UMA", "DUAS", "MUITAS", "ZERO"], correct: 1 },
    { q: "QUAL PÁSSARO DORME ENQUANTO VOA", options: ["ÁGUIA", "FRAGATA", "POMBO", "URUBU"], correct: 1 },
    { q: "QUAL O ÚNICO ANIMAL QUE NÃO CONSEGUE RECUAR", options: ["CANGURU", "ELEFANTE", "CACHORRO", "GATO"], correct: 0 },
    { q: "QUANTOS DENTES TEM UM TUBARÃO (VIDA TODA)", options: ["100", "1.000", "30.000", "500"], correct: 2 },
    { q: "O QUE É O 'PLANCTON'", options: ["PEIXE PEQUENO", "ORGANISMOS DERIVANTES", "PEDRA", "ALGA"], correct: 1 },
    { q: "O QUE O CAVALO-MARINHO É", options: ["MAMÍFERO", "PEIXE", "CRUSTÁCEO", "MOLUSCO"], correct: 1 },
    { q: "QUAL ANIMAL TEM O MAIOR CÉREBRO", options: ["HUMANO", "BALEIA CACHALOTE", "ELEFANTE", "GOLFINHO"], correct: 1 },
    { q: "QUANTOS DEDOS TEM O PÉ DE UM AVESTRUZ", options: ["DOIS", "TRÊS", "QUATRO", "CINCO"], correct: 0 },
    { q: "ANIMAL QUE RÓI MADEIRA", options: ["CASTOR", "ESQUILO", "RATO", "COELHO"], correct: 0 },
    { q: "ÚNICO ANIMAL QUE SE VÊ NO ESPELHO", options: ["CÃO", "GATO", "MACACO/DELFIM", "PÁSSARO"], correct: 2 },
    { q: "QUAL PLANTA É CONHECIDA COMO 'OURO VERDE'", options: ["MILHO", "SOJA", "PINHEIRO", "EUCALIPTO"], correct: 1 },
    { q: "PARTE DA PLANTA QUE RESPIRA", options: ["RAIZ", "ESTÔMATO (FOLHA)", "TRONCO", "FLOR"], correct: 1 },
    { q: "O QUE O GIRASSOL BUSCA", options: ["ÁGUA", "LUZ SOLAR", "VENTO", "ADUBO"], correct: 1 },
    { q: "QUAL PLANTA PODE VIVER MILHARES DE ANOS", options: ["ROSA", "PINHEIRO BRISTLECONE", "BAMBU", "CARVALHO"], correct: 1 },
    { q: "O QUE É UM POMAR", options: ["PLANTAÇÃO DE FLORES", "PLANTAÇÃO DE FRUTAS", "MATA", "HORTA"], correct: 1 },
    { q: "QUAL PLANTA É USADA NA TEQUILA", options: ["CANHA", "AGAVE", "UVA", "CEVADA"], correct: 1 },
    { q: "O QUE É A POLINIZAÇÃO", options: ["CORTAR PLANTAS", "TRANSPORTE DE PÓLEN", "DAR ÁGUA", "NASCE FRUTO"], correct: 1 },
    { q: "QUAL PLANTA NÃO TEM FLORES", options: ["SAMAMBAIA", "ROSA", "ORQUÍDEA", "MARGARIDA"], correct: 0 },
    { q: "O QUE A PLANTA SOLTA NA FOTOSSÍNTESE", options: ["CO2", "OXIGÊNIO", "NITROGÊNIO", "VAPOR"], correct: 1 },
    { q: "QUAL O NOME DA CIÊNCIA QUE ESTUDA FRUTOS", options: ["BOTÂNICA", "POMOLOGIA", "BIOLOGIA", "QUÍMICA"], correct: 1 },
    { q: "FRUTA QUE É SÍMBOLO DA TROPICALIDADE", options: ["MAÇÃ", "ABACAXI", "PERA", "UVA"], correct: 1 },
    { q: "COMO AS PLANTAS BEBEM ÁGUA", options: ["PELA FOLHA", "PELA RAIZ", "PELO CAULE", "PELA FLOR"], correct: 1 },
    { q: "QUAL PLANTA DÁ A PIPOCA", options: ["TRIGO", "MILHO", "ARROZ", "FEIJÃO"], correct: 1 },
    { q: "PLANTA QUE CRESCE MAIS RÁPIDO", options: ["CARVALHO", "BAMBU", "PINHEIRO", "ROSA"], correct: 1 },
    { q: "O QUE É O 'CAULE'", options: ["FIXA A PLANTA", "SUSTENTA A PLANTA", "FAZ FRUTO", "RESPIRA"], correct: 1 },
    { q: "PLANTA QUE DÁ O LINHO", options: ["ALGODOEIRO", "LINHAÇA", "TRIGO", "MILHO"], correct: 1 },
    { q: "O QUE É UMA PLANTA PERENE", options: ["MORRE RÁPIDO", "VIVE MUITOS ANOS", "NÃO TEM RAIZ", "SÓ TEM FLOR"], correct: 1 },
    { q: "O QUE ATRAI OS PÁSSAROS NA FLOR", options: ["RAIZ", "NÉCTAR", "FOLHA", "TERRA"], correct: 1 },
    { q: "QUAL ÁRVORE DÁ A CASTANHA-DO-PARÁ", options: ["CASTANHEIRA", "PINHEIRO", "MOGNO", "CEDRO"], correct: 0 },
    { q: "O QUE É A CLOROFILA", options: ["FRUTO", "PIGMENTO VERDE", "RAIZ", "ÁGUA"], correct: 1 },
    { q: "ONDE VIVEM OS CANGURUS", options: ["ÁFRICA", "AUSTRÁLIA", "BRASIL", "ÍNDIA"], correct: 1 },
    { q: "O QUE É A SAVANA", options: ["FLORESTA FECHADA", "CAMPO COM ÁRVORES ESPARSAS", "DESERTO", "GELO"], correct: 1 },
    { q: "QUAL O NOME DA FLORESTA GELADA", options: ["SELVA", "TAIGA", "PANTANAL", "MANGUE"], correct: 1 },
    { q: "O QUE É O PERMAFROST", options: ["TERRA FÉRTIL", "SOLO SEMPRE GELADO", "AREIA", "LAVA"], correct: 1 },
    { q: "PRINCIPAL CAUSA DA EXTINÇÃO ATUAL", options: ["VULCÕES", "AÇÃO HUMANA", "METEOROS", "SOL"], correct: 1 },
    { q: "QUAL O PULMÃO DO MUNDO (BIOLÓGICO)", options: ["AMAZÔNIA", "OCEANOS (ALGAS)", "ÁFRICA", "EUROPA"], correct: 1 },
    { q: "O QUE É O CHORUME", options: ["ADUBO", "LÍQUIDO DO LIXO", "ÁGUA DOCE", "SEIVA"], correct: 1 },
    { q: "QUAL ANIMAL É SÍMBOLO DA CONSERVAÇÃO", options: ["LEÃO", "PANDA", "LOBO", "ÁGUIA"], correct: 1 },
    { q: "O QUE É UM PARQUE NACIONAL", options: ["ZOOLÓGICO", "ÁREA DE PROTEÇÃO", "PARQUE DIVERSÕES", "CIDADE"], correct: 1 },
    { q: "O QUE É O ECOTURISMO", options: ["TURISMO EM CIDADES", "TURISMO NA NATUREZA", "COMPRAS", "TURISMO ESPACIAL"], correct: 1 },
    { q: "O QUE É A COMPOSTAGEM", options: ["QUEIMAR LIXO", "TRANSFORMAR RESTOS EM ADUBO", "RECICLAR PAPEL", "LIMPAR RIO"], correct: 1 },
    { q: "QUAL O GÁS MAIS ABUNDANTE NO AR", options: ["OXIGÊNIO", "NITROGÊNIO", "HIDROGÊNIO", "CO2"], correct: 1 },
    { q: "O QUE É O 'PANTANAL'", options: ["DESERTO", "MAIOR PLANÍCIE ALAGADA", "MONTANHA", "ILHA"], correct: 1 },
    { q: "O QUE SÃO ANIMAIS NOTURNOS", options: ["DORMEM À NOITE", "ATIVOS À NOITE", "NÃO DORMEM", "VIVEM NO SOL"], correct: 1 },
    { q: "O QUE É UM SER HERBÍVORO", options: ["COME CARNE", "COME PLANTAS", "COME TUDO", "COME INSETOS"], correct: 1 },
    { q: "O QUE É UM SER ONÍVORO", options: ["COME CARNE", "COME PLANTAS", "COME TUDO", "SÓ BEBE ÁGUA"], correct: 2 },
    { q: "O QUE É A CADEIA ALIMENTAR", options: ["LOJA DE COMIDA", "RELAÇÃO DE QUEM COME QUEM", "PESO DO ANIMAL", "VELOCIDADE"], correct: 1 },
    { q: "QUAL O NOME DA PROTEÇÃO NATURAL DA TERRA", options: ["CAMADA DE OZÔNIO", "NUVENS", "AR", "ÁGUA"], correct: 0 },// --- 361 a 380: Micro-Natureza e Curiosidades Biológicas ---
    { q: "SER VIVO QUE NÃO É PLANTA NEM ANIMAL", options: ["PEDRA", "FUNGO", "ALGA", "PROTOZOÁRIO"], correct: 1 },
    { q: "O QUE É O MOFO", options: ["POEIRA", "FUNGO", "PLANTA", "INSETO"], correct: 1 },
    { q: "COMO SE CHAMA O ESTUDO DOS FUNGOS", options: ["BOTÂNICA", "MICOLOGIA", "ZOOLOGIA", "QUÍMICA"], correct: 1 },
    { q: "QUAL O ÚNICO MÚSCULO QUE NÃO CANSA", options: ["LÍNGUA", "CORAÇÃO", "BÍCEPS", "PERNA"], correct: 1 },
    { q: "O QUE AS BACTÉRIAS SÃO", options: ["UNICELULARES", "PLURICELULARES", "VÍRUS", "PLANTAS"], correct: 0 },
    { q: "O QUE PROTEGE O CÉREBRO", options: ["COSTELA", "CRÂNIO", "FÊMUR", "PELE"], correct: 1 },
    { q: "QUANTOS PULMÕES NÓS TEMOS", options: ["UM", "DOIS", "TRÊS", "QUATRO"], correct: 1 },
    { q: "PARA QUE SERVE O SANGUE", options: ["DAR COR", "TRANSPORTAR NUTRIENTES", "ESQUENTAR", "NADA"], correct: 1 },
    { q: "QUAL A MAIOR CÉLULA DO MUNDO", options: ["NEURÔNIO", "OVO DE AVESTRUZ", "BACTÉRIA", "SANGUE"], correct: 1 },
    { q: "ONDE FICA O MENOR OSSO DO CORPO", options: ["MÃO", "PÉ", "OUVIDO", "NARIZ"], correct: 2 },
    { q: "O QUE É O DNA", options: ["PROTEÍNA", "CÓDIGO GENÉTICO", "CÉLULA", "ÓRGÃO"], correct: 1 },
    { q: "QUAL O NOME DA PARTE BRANCA DO OLHO", options: ["ÍRIS", "ESCLERA", "PUPILA", "RETINA"], correct: 1 },
    { q: "O QUE AS LÁGRIMAS FAZEM", options: ["LIMPARAM O OLHO", "DAR COR", "AJUDAR A VER", "NADA"], correct: 0 },
    { q: "QUAL A FUNÇÃO DOS RINS", options: ["BOMBEAR SANGUE", "FILTRAR O SANGUE", "RESPIRAR", "DIGERIR"], correct: 1 },
    { q: "O QUE É A BILE", options: ["SANGUE", "LÍQUIDO DIGESTIVO", "SALIVA", "SUOR"], correct: 1 },
    { q: "QUAL ÓRGÃO PODE SE REGENERAR", options: ["CORAÇÃO", "FÍGADO", "CÉREBRO", "PULMÃO"], correct: 1 },
    { q: "QUANTOS CROMOSSOMOS TEM O HUMANO", options: ["23", "46", "50", "12"], correct: 1 },
    { q: "ONDE VIVE O TIGRE DE BENGALA", options: ["ÁFRICA", "ÍNDIA/ÁSIA", "BRASIL", "EUA"], correct: 1 },
    { q: "QUAL O MAIOR FELINO DO MUNDO", options: ["LEÃO", "TIGRE SIBERIANO", "ONÇA", "LEOPARDO"], correct: 1 },
    { q: "QUAL A COR DA LÍNGUA DA GIRAFA", options: ["ROSA", "AZUL/PRETA", "VERMELHA", "BRANCA"], correct: 1 },
    { q: "O QUE É UM ANIMAL ENDÊMICO", options: ["MUITO GRANDE", "SÓ EXISTE NUM LUGAR", "COME TUDO", "ESTÁ MORTO"], correct: 1 },
    { q: "QUAL O NOME DO FILHOTE DE URSO", options: ["POTRO", "CORDEIRO", "LOBINHO", "URSO (MESMO)"], correct: 3 },
    { q: "COMO OS ELEFANTES SE CUMPRIMENTAM", options: ["GRITANDO", "USANDO A TROMBA", "PULANDO", "CORRENDO"], correct: 1 },
    { q: "O QUE É A HIBERNAÇÃO", options: ["COMER MUITO", "SONO PROFUNDO NO FRIO", "MUDAR DE COR", "MIGRAR"], correct: 1 },
    { q: "QUAL ANIMAL É UM RUMINANTE", options: ["GATO", "VACA", "CÃO", "LEÃO"], correct: 1 },
    { q: "O QUE OS PASSARINHOS USAM PARA VOAR", options: ["PELOS", "PENAS", "ESCAMAS", "PELE"], correct: 1 },
    { q: "ONDE OS MACACOS VIVEM", options: ["MAR", "ÁRVORES/SELVA", "DESERTO", "GELO"], correct: 1 },
    { q: "QUAL O ANIMAL MAIS FORTE DO MUNDO", options: ["ELEFANTE", "BESOURO-RINO", "FORMIGA", "LEÃO"], correct: 1 },
    { q: "COMO A COBRA SE MOVE", options: ["PULANDO", "RASTEJANDO", "VOANDO", "CORRENDO"], correct: 1 },
    { q: "O QUE É UM ANIMAL SINANTRÓPICO", options: ["VIVE NA SELVA", "VIVE COM HUMANOS", "VIVE NO MAR", "VIVE NO GELO"], correct: 1 },
    { q: "QUAL O NOME DA CASA DA ABELHA", options: ["NINHO", "COLMEIA", "BURACO", "TEIA"], correct: 1 },
    { q: "O QUE O PICA-PAU BUSCA NO TRONCO", options: ["ÁGUA", "INSETOS", "MADEIRA", "SOL"], correct: 1 },
    { q: "QUAL ANIMAL TEM O COLO COLORIDO", options: ["PANDA", "PAVÃO", "URSO", "LOBO"], correct: 1 },
    { q: "O QUE A ZEBRRA COME", options: ["CARNE", "GRAMA", "PEIXE", "INSETOS"], correct: 1 },
    { q: "ANIMAL QUE TEM CHIFRES", options: ["GATO", "BODE", "CÃO", "PEIXE"], correct: 1 },
    { q: "O QUE É O REBANHO", options: ["GRUPO DE PEIXES", "GRUPO DE OVELHAS", "GRUPO DE LOBOS", "GRUPO DE AVES"], correct: 1 },
    { q: "QUAL ANIMAL É SÍMBOLO DA SABEDORIA", options: ["PAPAGAIO", "CORUJA", "TUCANO", "POMBO"], correct: 1 },
    { q: "O QUE É O ECLIPSE SOLAR", options: ["LUA ENTRE TERRA E SOL", "TERRA ENTRE LUA E SOL", "SOL APAGA", "NUVEM"], correct: 0 },
    { q: "QUAL O PLANETA MAIS QUENTE", options: ["MERCÚRIO", "VÊNUS", "MARTE", "JÚPITER"], correct: 1 },
    { q: "QUANTOS PLANETAS TEM O SISTEMA SOLAR", options: ["7", "8", "9", "10"], correct: 1 },
    { q: "QUAL O ÚNICO PLANETA COM VIDA (CONHECIDA)", options: ["MARTE", "TERRA", "VÊNUS", "SATURNO"], correct: 1 },
    { q: "O QUE É O COMETA", options: ["ESTRELA", "BOLA DE GELO E POEIRA", "PLANETA", "FOGO"], correct: 1 },
    { q: "QUAL A COR DO SOL", options: ["AMARELO", "BRANCO", "VERMELHO", "LARANJA"], correct: 1 },
    { q: "O QUE É A GRAVIDADE", options: ["VENTO", "FORÇA QUE NOS PUXA", "LUZ", "CALOR"], correct: 1 },
    { q: "QUAL A MAIOR ESTRELA DO SISTEMA", options: ["LUA", "SOL", "SÍRIUS", "MARTE"], correct: 1 },
    { q: "O QUE É O ANO-LUZ", options: ["TEMPO", "DISTÂNCIA", "VELOCIDADE", "PESO"], correct: 1 },
    { q: "O QUE É UMA CONSTELAÇÃO", options: ["GRUPO DE PLANETAS", "GRUPO DE ESTRELAS", "NUVEM", "GALÁXIA"], correct: 1 },
    { q: "QUAL O NOME DA NOSSA GALÁXIA", options: ["ANDRÔMEDA", "VIA LÁCTEA", "SOLAR", "ÓRBITA"], correct: 1 },
    { q: "O QUE É UM BURACO NEGRO", options: ["LUGAR SEM LUZ", "REGIÃO COM MUITA MASSA", "ESTRELA MORTA", "TODOS"], correct: 3 },
    { q: "QUAL O PLANETA DOS ANÉIS", options: ["JÚPITER", "SATURNO", "URANO", "NEPTUNO"], correct: 1 },
    { q: "QUAL O ÚLTIMO PLANETA DO SISTEMA", options: ["URANO", "NEPTUNO", "PLUTÃO", "MARTE"], correct: 1 },
    { q: "PLUTÃO É CONSIDERADO O QUÊ HOJE", options: ["PLANETA", "PLANETA ANÃO", "LUA", "ASTEROIDE"], correct: 1 },
    { q: "O QUE É O UNIVERSO", options: ["SÓ A TERRA", "TUDO O QUE EXISTE", "SÓ O SOL", "SÓ A LUA"], correct: 1 },
    { q: "O QUE CAUSA AS ESTAÇÕES", options: ["INCLINAÇÃO DA TERRA", "DISTÂNCIA DO SOL", "VENTO", "LUA"], correct: 0 },
    { q: "O QUE É O VÁCUO", options: ["AR MUITO FRIO", "ESPAÇO SEM MATÉRIA", "LUGAR COM FOGO", "NUVEM"], correct: 1 },
    { q: "QUANTAS LUAS TEM A TERRA", options: ["UMA", "DUAS", "TRÊS", "ZERO"], correct: 0 },
    { q: "O QUE É A VIA LÁCTEA", options: ["UM RIO", "UMA GALÁXIA", "UM PLANETA", "UMA ESTRELA"], correct: 1 },
    { q: "QUAL O NOME DA FLORESTA REPRODUZIDA NA ÁGUA SALGADA", options: ["PANTANAL", "MANGUEZAL", "SELVA", "TAIGA"], correct: 1 },
    { q: "BIOMA CARACTERIZADO POR GRAMÍNEAS E POUCAS ÁRVORES", options: ["FLORESTA", "ESTEPE/PRADARIA", "DESERTO", "TUNDRA"], correct: 1 },
    { q: "O QUE É A TAIGA", options: ["FLORESTA DE CONÍFERAS", "DESERTO QUENTE", "PANTANAL", "ILHA"], correct: 0 },
    { q: "QUAL O NOME DO SOLO CONGELADO DA TUNDRA", options: ["HUMUS", "PERMAFROST", "ARGILA", "LAVA"], correct: 1 },
    { q: "ONDE SE LOCALIZA A SAVANA MAIS FAMOSA", options: ["ÁSIA", "ÁFRICA", "AMÉRICA DO SUL", "EUROPA"], correct: 1 },
    { q: "QUAL O BIOMA MAIS RICO EM BIODIVERSIDADE", options: ["DESERTO", "FLORESTA TROPICAL", "TUNDRA", "TAIGA"], correct: 1 },
    { q: "O QUE É UM DESERTO GELADO", options: ["ANTÁRTIDA", "SAARA", "GOBI", "ATACAMA"], correct: 0 },
    { q: "O QUE É UM OÁSIS", options: ["MONTANHA NO GELO", "ÁREA FÉRTIL NO DESERTO", "ILHA NO MAR", "LAGO SALGADO"], correct: 1 },
    { q: "QUAL A FUNÇÃO DAS ALGAS MARINHAS", options: ["SUJAR O MAR", "PRODUZIR OXIGÊNIO", "ESQUENTAR A ÁGUA", "NADA"], correct: 1 },
    { q: "O QUE É UMA BARREIRA DE CORAIS", options: ["PEDRAS", "COLÔNIAS DE ANIMAIS", "PLANTAS", "LIXO"], correct: 1 },
    { q: "ONDE VIVEM OS ANIMAIS ARBÓREOS", options: ["NO CHÃO", "NAS ÁRVORES", "NA ÁGUA", "NO AR"], correct: 1 },
    { q: "O QUE É UM ANIMAL AQUÁTICO", options: ["VIVE NA TERRA", "VIVE NA ÁGUA", "VIVE NO AR", "VIVE NO FOGO"], correct: 1 },
    { q: "QUAL O NOME DA PASSAGEM DO VERÃO PARA O INVERNO", options: ["PRIMAVERA", "OUTONO", "SOLSTÍCIO", "EQUINÓCIO"], correct: 1 },
    { q: "O QUE É A FOTOSFERA", options: ["CAMADA DA TERRA", "CAMADA DO SOL", "FUNDO DO MAR", "NUVEM"], correct: 1 },
    { q: "COMO SE CHAMA A ÁGUA QUE PODE SER BEBIDA", options: ["SALGADA", "POTÁVEL", "AMARGA", "SUJA"], correct: 1 },
    { q: "O QUE SÃO ANIMAIS MIGRATÓRIOS", options: ["NUNCA SE MOVEM", "VIAJAM NAS ESTAÇÕES", "DORMEM SEMPRE", "SÓ COMEM MELE"], correct: 1 },
    { q: "O QUE É A CADEIA ALIMENTAR", options: ["SUPERMERCADO", "TRANSFERÊNCIA DE ENERGIA", "PESO", "ALTURA"], correct: 1 },
    { q: "QUAL ANIMAL CONSEGUE GIRAR A CABEÇA 270 GRAUS", options: ["ÁGUIA", "CORUJA", "POMBO", "FALCÃO"], correct: 1 },
    { q: "O QUE O ORNITORRINCO NÃO TEM", options: ["BICO", "ESTÔMAGO", "PATAS", "CAUDA"], correct: 1 },
    { q: "QUAL ANIMAL PRODUZ O SOM MAIS ALTO", options: ["LEÃO", "BALEIA AZUL", "ELEFANTE", "MACACO HOWLER"], correct: 1 },
    { q: "QUAL A COR DO LEITE DO HIPOPÓTAMO", options: ["BRANCO", "ROSA", "AZUL", "AMARELO"], correct: 1 },
    { q: "QUAL ANIMAL TEM A MAIOR EXPECTATIVA DE VIDA", options: ["TARTARUGA", "TUBARÃO DA GROENLÂNDIA", "HUMANO", "ELEFANTE"], correct: 1 },
    { q: "QUANTOS CÉREBROS TEM UM POLVO", options: ["UM", "TRÊS", "NOVE", "OITO"], correct: 2 },
    { q: "QUAL ANIMAL NÃO TEM DENTES", options: ["TUBARÃO", "TAMANDUÁ", "LEÃO", "CACHORRO"], correct: 1 },
    { q: "COMO OS CÃES SUAM", options: ["PELA PELE", "PELA LÍNGUA/PATAS", "NÃO SUAM", "PELAS ORELHAS"], correct: 1 },
    { q: "QUAL ANIMAL É CONHECIDO COMO 'PÁSSARO MOSCA'", options: ["POMBO", "BEIJA-FLOR", "PARDAL", "URUBU"], correct: 1 },
    { q: "O QUE AS COBRAS USAM PARA OUVIR", options: ["ORELHAS EXTERNAS", "VIBRAÇÕES NO SOLO", "NARIZ", "OLHOS"], correct: 1 },
    { q: "QUAL A VELOCIDADE DE UM GUEPARDO", options: ["50 KM/H", "110 KM/H", "200 KM/H", "80 KM/H"], correct: 1 },
    { q: "QUAL ANIMAL CONSEGUE REGENERAR O CORAÇÃO", options: ["PEIXE ZEBRA", "SAPO", "LAGARTO", "HUMANO"], correct: 0 },
    { q: "QUAL O ÚNICO ANIMAL QUE NÃO DORME", options: ["MOSQUITO", "TUBARÃO (ALGUNS)", "FORMIGA", "BALEIA"], correct: 1 },
    { q: "ANIMAL QUE USA FERRAMENTAS PARA COMER", options: ["GATO", "MACACO/CORVO", "CÃO", "VACA"], correct: 1 },
    { q: "QUAL ANIMAL TEM A LÍNGUA MAIS PESADA", options: ["ELEFANTE", "BALEIA AZUL", "GIRAFA", "HIPOPÓTAMO"], correct: 1 },
    { q: "O QUE O URSO POLAR COME PRINCIPALMENTE", options: ["PEIXE", "FOCAS", "GELO", "URSO"], correct: 1 },
    { q: "QUAL O PÁSSARO QUE MAIS VIAJA NO MUNDO", options: ["ANDORINHA", "TRINTA-RÉIS-ÁRTICO", "ÁGUIA", "PARDAL"], correct: 1 },
    { q: "QUAL ANIMAL TEM O PERÍODO DE GESTAÇÃO MAIS LONGO", options: ["HUMANO", "ELEFANTE", "BALEIA", "RINOCERONTE"], correct: 1 },
    { q: "QUAL A PRINCIPAL FONTE DE ENERGIA DA TERRA", options: ["LUA", "SOL", "PETRÓLEO", "VENTO"], correct: 1 },
    { q: "O QUE É O CICLO DA ÁGUA", options: ["BEBER ÁGUA", "MOVIMENTO DA ÁGUA NA TERRA", "LAVAR ROUPA", "MARÉ"], correct: 1 },
    { q: "QUAL GÁS AS PLANTAS ABSORVEM", options: ["OXIGÊNIO", "CO2", "HÉLIO", "ARGÔNIO"], correct: 1 },
    { q: "QUAL O NOME DA 'PELE' DAS ÁRVORES", options: ["CASCA", "PELO", "FOLHA", "RAIZ"], correct: 0 },
    { q: "O QUE É UMA PLANTA MEDICINAL", options: ["QUE DÁ FRUTA", "QUE CURA DOENÇAS", "QUE É VENENOSA", "QUE BRILHA"], correct: 1 },
    { q: "QUAL FRUTA TEM O CAROÇO GRANDE", options: ["UVA", "ABACATE", "BANANA", "MORANGO"], correct: 1 },
    { q: "O QUE É O REFLORESTAMENTO", options: ["CORTAR TUDO", "REPLANTAR ÁRVORES", "LIMPAR O RIO", "FUMAR"], correct: 1 },
    { q: "PARA QUE SERVE O CAULE", options: ["RESPIRAR", "TRANSPORTE DE SEIVA", "FAZER FLOR", "NADA"], correct: 1 },
    { q: "QUAL O NOME DA FLOR DA VIDEIRA", options: ["ROSA", "FLOR DA UVA", "LÍRIO", "TULIPA"], correct: 1 },
    { q: "ONDE SE LOCALIZA A MAIORIA DAS PLANTAS", options: ["NO ESPAÇO", "NA TERRA E MAR", "NAS NUVENS", "NO FOGO"], correct: 1 },
    { q: "O QUE É O CLIMA", options: ["TEMPO DE AGORA", "PADRÃO DO TEMPO", "VENTO", "CALOR"], correct: 1 },
    { q: "QUAL O NOME DO VENTO LEVE", options: ["FURACÃO", "BRISA", "TORNADO", "TEMPESTADE"], correct: 1 },
    { q: "O QUE É A UMIDADE", options: ["CALOR", "ÁGUA NO AR", "VENTO", "POEIRA"], correct: 1 },
    { q: "QUAL A COR DA TERRA VISTA DO ESPAÇO", options: ["VERDE", "AZUL", "VERMELHA", "BRANCA"], correct: 1 },
    { q: "O QUE É O HORIZONTE", options: ["LINHA ONDE CÉU E TERRA SE ENCONTRAM", "UMA ESTRELA", "UM RIO", "UM TIPO DE ÁRVORE"], correct: 0 },
    { q: "QUAL O NOME DA CIÊNCIA QUE ESTUDA A TERRA", options: ["BIOLOGIA", "GEOLOGIA", "FÍSICA", "QUÍMICA"], correct: 1 },
    { q: "O QUE É UM FÓSSIL", options: ["PEDRA COMUM", "RESTO DE SER VIVO ANTIGO", "OSSOS NOVOS", "PLANTA VIVA"], correct: 1 },
    { q: "QUANTO TEMPO A TERRA LEVA PARA DAR A VOLTA NO SOL", options: ["UM DIA", "UM MÊS", "UM ANO", "DEZ ANOS"], correct: 2 },
    { q: "QUAL O NOME DO NOSSO SATÉLITE", options: ["SOL", "LUA", "MARTE", "ESTRELA"], correct: 1 },
    { q: "QUANTAS ESTAÇÕES O ANO TEM", options: ["DUAS", "QUATRO", "SEIS", "DOZE"], correct: 1 },
    { q: "QUAL O MÊS QUE COMEÇA O VERÃO NO BRASIL", options: ["JUNHO", "SETEMBRO", "DEZEMBRO", "MARÇO"], correct: 2 },
    { q: "QUAL O MAIOR OCEANO", options: ["ATLÂNTICO", "PACÍFICO", "ÍNDICO", "ÁRTICO"], correct: 1 },
];